### ISSUE TITLE
[Bug] Issue after upgrading AndroidX packages

### ISSUE THREAD

**Issue by matteopiccioni** [xamarin/Xamarin.Forms#10027]
After updating 2 androidx packages as requested from Visual Studio,
my solution doesn't compile

The packages was for sure Xamarin.AndroidX.Browser 1.2.0
and I think: Xamarin.AndroidX.Lifecycle.LiveData 2.2.0

I try to clean,
to clear remove obj and bin folders and to restart visual studio 
but still it doesn't compile
In the screenshot the errors:

![Schermata 2020-03-19 alle 18 38 40](https://user-images.githubusercontent.com/1370434/77097585-4e5e1b80-6a11-11ea-81a8-728b1c8a76ac.png)

Xamarin Forms latest version: 4.5.0.396
Visual Studio for Mac latest version: 8.4.8 (build 2)

Thanks

**Comment by Redth** [comment]
Looks like you're trying to use the old `DX` dexer instead of the newer `D8`.  Here's a [blog post](https://devblogs.microsoft.com/xamarin/androids-d8-dexer-and-r8-shrinker/) which explains these things in more detail.

In any case try setting your project settings to use:
```
<PropertyGroup>
  <!--Other properties here-->
  <AndroidDexTool>d8</AndroidDexTool>
</PropertyGroup>
```

Make sure if you have any other value set in your project for `AndroidDexTool` you remove that.

**Comment by matteopiccioni** [comment]
> Looks like you're trying to use the old `DX` dexer instead of the newer `D8`. Here's a [blog post](https://devblogs.microsoft.com/xamarin/androids-d8-dexer-and-r8-shrinker/) which explains these things in more detail.
> 
> In any case try setting your project settings to use:
> 
> ```
> <PropertyGroup>
>   
>   <AndroidDexTool>d8</AndroidDexTool>
> </PropertyGroup>
> ```
> 
> Make sure if you have any other value set in your project for `AndroidDexTool` you remove that.

hey seems working, thanks!
