### ISSUE TITLE
[Bug] Stepper rounds initial value

### ISSUE THREAD

**Issue by RonnyBansemer** [xamarin/Xamarin.Forms#10032]
### Description
The Stepper (material renderer) changes the initial value of the value property (2-way-binding).
A bound value, lets say 4.99, with stepper increment 0.1 leads to rounding value to 5.00.

### Steps to Reproduce
1. Create a Stepper, bind the value property to it, 2-way-mode
2. Specify Stepper increment value, e.g. 0.1
3. Assign a value to value property in view model, which is more precise than 0.1, e.g. 4.99

### Expected Behavior
Stepper should in-/decrement the initial value by 0.1 (--> 5.09, 5.19,... ) until min-/max-value is reached.

### Actual Behavior
Stepper initial value is rounded after binding from 4.99 to 5.00 (--> 5.10, 5.20, ...).

### Basic Information
- Version with issue: XF 4.5.0.396
- Android: 8.1
- Nuget Packages: Xamarin.Forms, Xamarin.Forms.Visual.Material

**Comment by jfversluis** [comment]
I think this might be introduced by #7383

Just so we can get a clear picture of what you are trying to do. Can I ask you to add a small reproduction sample that shows the issue?

**Comment by RonnyBansemer** [comment]
@jfversluis I did not check it with iOS and a non-material Stepper. I Will check it tomorrow and apply a test project.

**Comment by RonnyBansemer** [comment]
@jfversluis Sorry, I just had time to create the sample project. I did not test it on iOS, the Android default renderer are also affected. There you go: https://github.com/RonnyBansemer/StepperRoundingIssue

![image](https://user-images.githubusercontent.com/45567951/77857154-30a46980-71fc-11ea-86fa-c4e97e6e8c67.png)

**Comment by jfversluis** [comment]
No worries @RonnyBansemer thanks for taking the time to do this!

To verify if it also happens on iOS, I pasted all the bits into a new project. My File > New project came with Forms 4.4 where this bug didn't happen, then upgraded to the latest stable and I suddenly see this on both Android and iOS. Fairly sure it's because of the change I mentioned earlier.

[Repro10032.zip](https://github.com/xamarin/Xamarin.Forms/files/4402488/Repro10032.zip)
