### ISSUE TITLE
[Bug] Button IsEnabled color Android

### ISSUE THREAD

**Issue by NicolaZuc** [xamarin/Xamarin.Forms#10040]
### Description
When setting button IsEnabled to false and BackgroundColor or TextColor properties, colors don't change.
Problem shows up only on Android Platform, on UWP it works like a charm
### Steps to Reproduce

1. Create button
2. Set IsEnabled property to False
3. Set Background color to Green
4. Set TextColor to White

### Expected Behavior
Disabled button
### Actual Behavior
Button looks like enabled button
### Basic Information

- Version with issue: Xamarin Forms 4.5.0.356, Xamarin Forms 4.5.0.396
- Last known good version: Xamarin Forms 4.4.0.991757
- IDE: Visual Studio Professional 2019 16.4.6
- Platform Target Frameworks: 
  - Android: Android 8.0 API 26 and above
  - UWP:  Windows 10, version1809
- Affected Devices:
Honeywell Dolphin CT40, Android  8.1 API 27
Samsung Galaxy S9, Android 10.0 API 29 
### Screenshots

`<Button IsEnabled="False" Text="Submit" BackgroundColor="Green"  TextColor="White"/>`

![with_backgroundcolor](https://user-images.githubusercontent.com/22391760/77178295-2b8e3e80-6ac7-11ea-81b0-716008c57c4a.png)

`<Button IsEnabled="True" Text="Submit" BackgroundColor="Green"  TextColor="White"/>`

![with_backgroundcolor](https://user-images.githubusercontent.com/22391760/77178295-2b8e3e80-6ac7-11ea-81b0-716008c57c4a.png)

`<Button IsEnabled="False" Text="Submit"/>`

![not_active](https://user-images.githubusercontent.com/22391760/77178297-2c26d500-6ac7-11ea-94e0-567163c9a47e.png)

`<Button IsEnabled="True" Text="Submit"/>`

![active](https://user-images.githubusercontent.com/22391760/77178296-2c26d500-6ac7-11ea-8faf-f0752afb7ea2.png)

### Workaround
Going back to Xamarin Forms 4.4.0.991757

**Comment by jfversluis** [comment]
Hey @Nicolazucchelli thanks for the report. I have tried to reproduce it, but I have been unsuccessful unfortunately. You can find my attempt attached. This project runs 4.5 and shows a button with `IsEnabled="False"` which shows me the difference in color that you are expecting. Is there any other code or factors in play?

[Repro10040.zip](https://github.com/xamarin/Xamarin.Forms/files/4361625/Repro10040.zip)

**Comment by Nicolazucchelli** [comment]
Hi, thanks for your response, i've tried your repro and it works, i don't understand in what is different from mine. Here is my repro case https://mega.nz/#!pZpinYhI
![Screenshot_20200320-220843](https://user-images.githubusercontent.com/22391760/77206670-c9016680-6af7-11ea-839e-9ce6c6a8a171.png)

**Comment by jfversluis** [comment]
The download link needs an decryption key. Please add the project here directly by dragging the zip in the comment box. You can attach it to the GitHub issue :)

**Comment by Nicolazucchelli** [comment]
Hi, please retry the mega link  https://mega.nz/#!pZpinYhI!ESTWGt7ipUIV9_jM3kOO5t8rCiKB98Jth7V1J3DhS5U
Repo is too big to be attached here (46mb)

**Comment by ninaada** [comment]
Facing same issue

**Comment by PMarsh-UB** [comment]
Hello,

I ran into this issue also.

To reproduce it, you can download jfversluis' repo and change the **BindingContext**:

`BindingContext = new object();`

This is happening on Android **and iOS** on Xamarin 4.5+ (I've experienced this issue on all version up to **4.6.0.494-pre2**.). There are no issues on Xamarin 4.4. 

To fix this, I added the following to my App.xaml class:

```
<Style TargetType="Button">
    <Style.Triggers>
        <Trigger TargetType="Button" Property="IsEnabled" Value="False">
            <Setter Property="TextColor" Value="#C2C5CC" /> <-- Replace with your style
        </Trigger>
    </Style.Triggers>
</Style>
```

Make sure you call **InitializeComponent();** in the App.xaml.cs constructor, otherwise the triggers are ignored.

**Comment by ninaada** [comment]
Is there any progress on this? Most of the buttons will be used in a BindingContext most of the times. We need some of the latest fixes on collection view and carousel view, but have been holding on from upgrading to 4.5 due to this issue. Or is there any workaround for this ?

**Comment by stesvis** [comment]
I am having this issue too. On android all my buttons look enabled and there is no longer distinction between the enabled and the disabled state.
It used to work with previous XF versions.

**Comment by PMarsh-UB** [comment]
@stesvis @ninaada Have you not tried my solution?

**Comment by ninaada** [comment]
@PMarsh-UB In our case, we have a lot of buttons(with different colors for styles) and not all of them are same color. There is a visual difference between putting a different color against disabling from the native platform itself. We have rolled-back to 4.4 since we found this issue.

Its not just text color, when the control is supposed to be disabled, it usually stays that way showing no change when user taps the button when disabled. In 4.5, what happens is button stays active, i.e; when user taps it, it still gets a ripple effect etc. although nothing happens and that is a really bad/confusing UX for the user. @stesvis

**Comment by PureWeen** [comment]
@jsuarezruiz @hartez 

This regressed as part of this line of code here

https://github.com/xamarin/Xamarin.Forms/pull/9422/files#diff-b2408192f3f7437c9eed488a33f903e8R834

The problem here is that if you specify a `defaultValueCreator` on a bindable property

https://github.com/xamarin/Xamarin.Forms/blob/038a8c612b6fe4e4de8bf8aeb5d5d64ea57e7598/Xamarin.Forms.Core/VisualStateManager.cs#L23

You can't use IsSet like this
https://github.com/xamarin/Xamarin.Forms/blob/038a8c612b6fe4e4de8bf8aeb5d5d64ea57e7598/Xamarin.Forms.Core/VisualStateManager.cs#L101

because the first time the bindable property is retrieved it will cause IsSet to toggle to true..

So you basically have code that works one way and then someone just retrieves your property and then all your IsSet code now acts differently.

AFAIK once IsSet has toggled to true it'll also be set to true forever

So the `HasVisualStateGroups` call needs to be reworked to not use IsSet or the defaultValueCreator should be removed from the property

**Comment by ninaada** [comment]
Any update on this yet ?

**Comment by haavamoa** [comment]
I hope this has a high priority as overriding the `TextColor` of a `Button` is quiet normal. I can confirm that this happens for both Android and iOS if you change the `Button.TextColor`.
