### ISSUE TITLE
[Bug] [iOS] SwipeView items don't support TapGestureRecognizer

### ISSUE THREAD

**Issue by MattGoldmanSSW** [xamarin/Xamarin.Forms#10056]
### Description
When using SwipeView on Android and adding a TapGestureRecognizer to a SwipeView item, swiping and tapping behaves as expected. On iOS the taps are ignored.

### Steps to Reproduce

1. Add a swipeview item to your view
2. Add a TapGestureRecognizer
3. Tap on iOS - nothing happens
4. Tap on Android - event handler is fired

### Expected Behavior
TapGestureRecognizer event handler is fired

### Actual Behavior
Nothing happens

### Basic Information

- Version with issue: 4.5.0.396
- Last known good version: NA
- IDE: Visual Studio for Windows 16.4.5, Visual Studio for Mac 8.4.8 build 2
- Platform Target Frameworks: 
  - iOS:  12.2 and 13.3 both tested
  - Android: 28

### Reproduction Link

Working on this, but sample code:

```
<SwipeView>
         <SwipeView.GestureRecognizers>
                <TapGestureRecognizer NumberOfTapsRequired="1" 
                                                      Tapped="TapGestureRecognizer_Tapped"/>
         </SwipeView.GestureRecognizers>
                <SwipeView.LeftItems>
                    <SwipeItems>
                        <SwipeItem Text="Example swipe item"
                                   BackgroundColor="Pink"
                                   />
                    </SwipeItems>
                </SwipeView.LeftItems>
                <StackLayout>
                       <Label Text="Example"/>
               </StackLayout>
  </SwipeView>
```

### Workaround

None

**Comment by PureWeen** [comment]
@jsuarezruiz this is fixed right?

**Comment by jsuarezruiz** [comment]
Yes, will be fixed by https://github.com/xamarin/Xamarin.Forms/pull/9638
![tapgesture-swipeview](https://user-images.githubusercontent.com/6755973/77737025-764f0f80-700d-11ea-8902-91240ddf635f.gif)
We included a sample using GestureRecognizer in the SwipeView, SwipeView Content and SwipeItemView.
https://github.com/xamarin/Xamarin.Forms/blob/133cfddfa15286c4ae97f1cd9cef7019ec8cf68d/Xamarin.Forms.Controls/GalleryPages/SwipeViewGalleries/SwipeViewGestureRecognizerGallery.xaml#L32
