### ISSUE TITLE
[Bug] OnAppearing called after permission dialog on Android

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#10051]
### Description
On Android the `OnAppearing` method is called after accepting and denying a permission.

### Steps to Reproduce

1. Download this project.
[OnAppearingBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4365882/OnAppearingBug.zip)

2. Put breakpoint in the `OnAppearing` method.
3. Click "Request location permission" button.
4. Grant or deny the permission.
5. The breakpoint is hit.

![OnAppearing_bug](https://user-images.githubusercontent.com/17653648/77257188-0d654180-6c73-11ea-9ccf-abb675b9a44a.gif)

### Expected Behavior
The `OnAppearing` method should not be called when accepting or denying a permission in the permission dialog.

### Actual Behavior
The`OnAppearing` method is called when accepting or denying a permission in the permission dialog.

### Basic Information

- Version with issue: 4.5.0.396
- IDE: Visual Studio for Mac 8.4.8
- Platform Target Frameworks: 
  - Android: 9.0

### Additional info
If `MainPage` is not inside `NavigationPage` the problem does not exists.

**Comment by PureWeen** [comment]
Duplicate

https://github.com/xamarin/Xamarin.Forms/issues/3706#issuecomment-420108673

The main problem here is that OnAppearing is heavily overloaded with what it means to the point that it's hard to really make it mean anything :-/ 

It's vaguely useful but we'll have some newer life cycle methods.

It would also be breaking to change this behavior because some people might want onappearing to fire when a permission dialog opens
