### ISSUE TITLE
[Enhancement] Shell Navigation Route should allow navigation to external web pages

### ISSUE THREAD

**Issue by BenBtg** [xamarin/Xamarin.Forms#10098]
## Summary
Navigation Route currently only supports navigation around the application But often it is useful to be able to navigate to external web pages either via an embedded view or via an external browser. It would be useful if Shell supported this

## API Changes

In order to facilitate this feature the Route property of Flyout Route simply needs to support absolute http urls like below:

`<FlyoutItem Title="Xamarin" `Route="http://github.com/xamarin"/>`

Shell navigation will then treat these route as special case for naviation.

It may be useful to add an addional RouteMode property to determin if the Naviation should use an embedded WebView or external browser.

## Intended Use Case
I have an app with a Flyout where many of the menu items just take you to various web pages. Ideally this would just require setting the Route property of the FlyoutItem to a http:// address. Currently it requires a lot more effort than that and involves either creating dedicated pages for each embedded web page or a more generic solution that uses parameterised navigation. Either way, it's a lot more effort then you would hope to just navigate to a web page.

**Comment by PureWeen** [comment]
@chkn thoughts with this and segues? This feels like something that would map to segues well because users might want to configure more about that Uri route than just the Uri

Either way I think this is a good idea!

The only place we might get into a little trouble is that Shell right now ignores host/scheme when you pass GOTO on it, so in the above case if you have a route called "xamarin" and you clicked the route with the url it'll just try to navigate you to the route called "xamarin" 

Just something to keep in mind...

But I could see this meshing well with segues where you could specify InApp vs ExternalWindow

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
