### ISSUE TITLE
[Bug][iOS] SwipeView.Open() doesn't work on first call in 4.6-pre2

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#10095]
### Description

On iOS, the SwipeView.Open method doesn't open the SwipeView on first call. Instead the SwipeView swipes and it remains closed. On second call to the Open method, the SwipeView remains open.

The Open method works as expected on Android.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the programmatic SwipeView page.
3. Click the Open button.

### Expected Behavior

SwipeView swipes and remains open.

### Actual Behavior

SwipeView swipes and remains closed.

### Basic Information

- Version with issue: 4.6-pre2
- IDE: VSMac 8.5
- Platform Target Frameworks:
  - iOS:  13.2

### Reproduction Link

[SwipeViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/4386924/SwipeViewDemos.zip)

**Comment by SamuelKraus** [comment]
I figured out that this issue is a problem with the animator not working on the first call and really has nothing to do with the swipeview.  I figured this out because on the same page I have a button that rotates 360 degrees when its clicked (looks like a coin flip).  That doesnt work on the first call either.  If I click the rotating button first, then the swipeview, the swipeview works fine.  The animator needs to be initialized for the swipeview to work on click the first time.
