### ISSUE TITLE
[Enhancement] [Android] MainActivity doesn't detect Locale ConfigChanges

### ISSUE THREAD

**Issue by mduchev** [xamarin/Xamarin.Forms#10265]
### Description
If we have multi-language support in our app, everything works fine when we start the app. However, if the app is running, the activity doesn't detect any locale changes. This way, if we have started our app with en-US locale and runtime change the language to de-CH, upon app resume, the activity won't recognize that the locale has changed and CultureInfo.CurrentUiCulture will return en-US.

### Steps to Reproduce

1. Run the project
2. While the app is opened, change device's language
3. When you resume the app, the app should detect the locale change and execute OnConfigurationChanged. (Since we have marked the activity to track locale configuration changes - row 10)

### Expected Behavior
The MainActivity will detect locale changes

### Actual Behavior
The MainActivity doesn't know about any locale changes

### Basic Information

- Version with issue: 4.5.0.530
- Last known good version: N/A
- IDE: VS for mac
- Platform Target Frameworks:
  - Android: Android 10 (Q)
- Nuget Packages: Only Xamarin.Essentials - 1.5.2
- Affected Devices: Android devices

### Reproduction Link
[DemoLocaleChange.zip](https://github.com/xamarin/Xamarin.Forms/files/4451908/DemoLocaleChange.zip)

### Workaround
In the attached sample project you can see a workaround - if we check for configuration changes on app level (in MainApplication.cs), we can easily detect locale changes and update where necessary.

**Comment by rmarinho** [comment]
Hi, we think this more as enhancement to the localization feature than a bug per se. 
But we do think this is a good feature to add.

Thanks

**Comment by mduchev** [comment]
@rmarinho How is this not a bug? The Android documentation explicitly says that an activity can handle locale configuration changes via the OnConfigurationChanged method. This is working if we want to change our app's theme (light/dark) during runtime. If I say to my MainActivity to track theme changes via **ConfigurationChanges = ConfigChanges.UiMode** everything is working fine. However, it doesn't detect the locale changes.

Docs: https://developer.android.com/guide/topics/manifest/activity-element

**Comment by jfversluis** [comment]
Hi @mduchev I think there might've been a misunderstanding. I have looked into the issue for a bit and it seems this is only triggered when you declare `ConfigChanges.LayoutDirection | ConfigChanges.Locale` together. The [assumption](https://stackoverflow.com/questions/18725396/onconfigurationchange-not-called-after-changing-locale/27648645) is that this is because the user might choose a RTL language and you need to update that accordingly. If I updated your repro with this flag the event is triggered.

Unfortunately, this is something within Android and not something we can change. I will close this issue, if you think this is in error, please let us know.
