### ISSUE TITLE
[Bug] Uwp disabled for creating new shell project

### ISSUE THREAD

**Issue by chrisevans9629** [xamarin/Xamarin.Forms#10279]
### Description
UWP option is disabled for a new Xamarin forms shell project, even though UWP shell is supported 
![image](https://user-images.githubusercontent.com/33850520/78916278-d6ed3c00-7a52-11ea-9cc0-4ddde525aa82.png)

UWP supported was added via this issue:
https://github.com/xamarin/Xamarin.Forms/issues/5593

Here is the pull request for that:
https://github.com/xamarin/Xamarin.Forms/pull/6015

### Steps to Reproduce

1. Open dialog to create new xamarin forms project

### Expected Behavior
Allow you to selected UWP
### Actual Behavior
UWP checkbox disabled
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual studio 2019

**Comment by PureWeen** [comment]
@chrisevans9629 we're waiting for some additional enhancements to UWP shell before we expose this on the templates.

I've added this issue to our shell backlog and I'll update the progress here once we're ready to add uwp

**Comment by dgerding** [comment]
Any word? I know Maui is probably causing headaches but if there is any chance we can get a 4.7 service release that enables the UWP shell as a project option that would be great. If not, would someone interested in this and in the know point me to the latest "correct-ish" way to add the UWP project and shell support on an ew 4.7 project?  Thanks!

**Comment by a-einstein** [comment]
Could it be that my UWP application crashes at startup because of this?

I had a Xamarin Forms application with Shell working on Android. Then I wanted to reactivate the UWP part.

-  When I try to debug it from Visual Studio it crashes in the deployment phase, with nothing more than "DEP0700: Registration of the app failed. [0x80073CF0] error 0x80070003: Opening file from location: AppxManifest.xml failed with error: The system cannot find the path specified." That has not give me any usable clue so far.

- When I publish and install first, I get a bit further, seeing my splash screen before it crashes.

I noticed that new Xamarin projects cannot be created for UWP with Shell (just Master-Detail, Tabbed, Blank) so that made me wonder.

If this just silently crashes without any particular error about Shell, or whatever, that is very annoying. Everything builds, including for UWP.

So could Microsoft at least tell me and us what is going on?

**Comment by pwisk** [comment]
On Shell for UWP Xamarin.Forms Shell Navigation dosn't work correctly:

**await Shell.Current.GoToAsync(nameof(SettingsPage)).ConfigureAwait(false);**

The header changes, but the page does not load. The page builder is called. The msdn sample also doesn't work:
https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/userinterface-xaminals/

The alternative call doesn't work either:

**ShellNavigationState state = Shell.Current.CurrentState;
await Shell.Current.GoToAsync($"{state.Location}/{nameof(SettingsPage)}").ConfigureAwait(false);
Shell.Current.FlyoutIsPresented = false;**

**Comment by PureWeen** [comment]
This has been enabled on 16.9
