### ISSUE TITLE
[Bug] Forms previewer crashes if using an IndicatorView

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#10375]
### Description

The forms previewer crashes with the following error if an IndicatorView is used. The experimental flags have been set in the project but the previewer doesn't seem to honor them.

<img width="1170" alt="Screenshot 2020-04-18 at 20 19 44" src="https://user-images.githubusercontent.com/60286968/79644507-1e419e00-81b2-11ea-8b35-0a222469df17.png">

### Basic Information

- Version with issue:
- Xamarin.Forms: 4.6.0.616-pre4
- IDE: VS For Mac 8.6 Preview, build 4243

> VS bug [#1107039](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1107039)

**Comment by jsuarezruiz** [comment]
This issue is because the experimental flag is verified in the context of previewer. Is similar to: https://github.com/xamarin/Xamarin.Forms/pull/10129
This change must fix the issue: https://github.com/xamarin/Xamarin.Forms/pull/10370/files#diff-6229aa671babb7f3fb245864169a986aR30

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**

<span style="color:rgb(23, 78, 134);">**Fixed in version 8.7.0.918 (master)**  
  
The fix will be included in 8.7 Preview 3.  
  
Pull Request #2954 merged by: J??r??mie Laval  
Author: xamarin  
Commit: d7853059d902ebdb916554a2bc7314489fa001ce (xamarin/designer)  
Included in Commit: 03ae2f4d670fc4e891a687938464ea85063fdc38 (xamarin/vsmac)  
  
</span>
