### ISSUE TITLE
[Bug]  NavigationPage.BackButtonTitle doesn't work with MacOS

### ISSUE THREAD

**Issue by linuskirschbaum** [xamarin/Xamarin.Forms#10424]
### Description

The title of the button is not described with "Hello World" -> NavigationPage.BackButtonTitle = "Hello World". The button title takes over the title of the page or remains default to "Back".

### Steps to Reproduce

Into your Xaml:
Title="SalesDashboard"
NavigationPage.BackButtonTitle="Zurück"

- IDE: VS for Mac
- Platform Target Frameworks:  MacOS

**Comment by jsuarezruiz** [comment]
I attached a reproduction sample: [Issue10424.zip](https://github.com/xamarin/Xamarin.Forms/files/4527494/Issue10424.zip)

This is the expected behavior (iOS):
![issue10424-ios](https://user-images.githubusercontent.com/6755973/80189357-d3d97a80-8612-11ea-9bbc-ae54437d073a.gif)

And this is the result on macOS:
![issue10424-macos](https://user-images.githubusercontent.com/6755973/80189358-d4721100-8612-11ea-84aa-0dda550957f7.gif)
