### ISSUE TITLE
[Enhancement] Support circular ActivityIndicator on UWP

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#10485]
## Summary
The [ActivityIndicator](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/activityindicator) on `UWP` is currently rendered with indeterminate [ProgressBar](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.UAP/ActivityIndicatorRenderer.cs).

It would be useful to support the [ProgressRing](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.progressring) type as well. In the [UWP guidelines](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/progress-controls#types-of-progress), both types are proposed to show an activity to the user.

![image](https://user-images.githubusercontent.com/4254116/80456582-21652880-892e-11ea-8c98-30874ad4e4b9.png)

The behavior of the `ProgressRing` type is also more similar to `iOS` and `Android` than the indeterminate `ProgressBar` type.

## API Changes
I propose to add a `UWP` platform specific `AttachedProperty` to define the type of indicator.
````cs
public static readonly BindableProperty IndicatorTypeProperty = 
  BindableProperty.CreateAttached("IndicatorType", typeof(IndicatorType), 
    typeof(ActivityIndicator), IndicatorType.ProgressBar);

public enum IndicatorType
{
    ProgressBar,
    ProgressRing
}
````

## Related
 - [[UWP] Replaced ActivityIndicator renderer with ProgressRing](https://github.com/xamarin/Xamarin.Forms/pull/1417)
- [ActivityIndicator rendered as a ProgressRing in UWP](https://forums.xamarin.com/discussion/100973/activityindicator-rendered-as-a-progressring-in-uwp)
- [Xamarin circular activity indicator for UWP](https://stackoverflow.com/questions/41219938/xamarin-circular-activity-indicator-for-uwp)

**Comment by arivoir** [comment]
I think the UWP implementation can be changed to render as a progress ring directly, no need to add any property. The reason why this was implemented like that is in Windows Phone 8 the performance of the progress ring was really bad, so they used the progress bar. Then in UWP the problem was inherited an nobody realized in this platform the progress ring works ok. 
The activity indicator rendering as a progress bar in UWP was a mistake.

**Comment by YZahringer** [comment]
@arivoir Yes, but to avoid a breaking change, the platform-specific `AttachedProperty` could be a solution. Then you can define it as a global default implicit style for the entire application.

**Comment by arivoir** [comment]
The attached property is ok provided the default behavior is to show the progress ring

**Comment by EmilAlipiev** [comment]
I have a pushed a commit for that. it looks like that it was merged into master https://github.com/xamarin/Xamarin.Forms/pull/10316/commits/cb77488874180e407270fb0da58040e8d9fa5874

**Comment by EmilAlipiev** [comment]
oh there was already a PR for that in 2017 https://github.com/xamarin/Xamarin.Forms/pull/1417
and it was rejected. I dont get why it should be. Because there is ProgressBar which implements exactly same as ActivityIndicator for UWP. it is a duplication already. We can simply change ActivityIndicator to be ProgressRing. If anyone needs ProgressBar of UWP can use Xamarin Progressbar. that simple.

**Comment by EmilAlipiev** [comment]
here is the PR https://github.com/xamarin/Xamarin.Forms/pull/11289

**Comment by YZahringer** [comment]
Fixed on https://github.com/dotnet/maui/issues/5143
