### ISSUE TITLE
CollectionView ItemsLayout Does Not Update in UWP

### ISSUE THREAD

**Issue by scottkuhl** [xamarin/Xamarin.Forms#10482]
I have this code in place to change the number of columns in a CollectionView:

      protected override void OnSizeAllocated(double width, double height)
        {
            base.OnSizeAllocated(width, height);
            var columns = (int)Math.Round((width / 200) / 2, MidpointRounding.AwayFromZero) * 2;
            if (columns < 3) columns = 3;
            CollectionView.ItemsLayout = new GridItemsLayout(columns, ItemsLayoutOrientation.Vertical);
        }

It works fine on Android and iOS and changes the number of columns when the screen is loaded or the orientation changes.  In UWP it does nothing.

**Comment by EmilAlipiev** [comment]
i have been waiting for my PR to be merged 1.5 month for this issue. There is already existing [issue ](https://github.com/xamarin/Xamarin.Forms/issues/5354)for Ios and android was fixed in July 2019 and nobody touched for uwp. I fixed in april and requested several times for review and merge. It is really annoying how xamarin teams is working. You can see they review only 1-2 PRs per day.
#10316
