### ISSUE TITLE
Xamarin Forms ReturnCommand binding NOT working

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10509]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1006441/xamarin-forms-returncommand-binding-not-working.html)._

---
I have a List View containing Entry objects.
I setup a ReturnCommand value on the Entry object pointing to the associated Command in the ViewModel.
When I run the App, no results are shown for the execution of the Command method.

I am attaching screenshots of portions of the xaml file and the ViewModel file.

Why does ReturnCommand not seem to be working?

---
#### Visual Studio Feedback System on 4/25/2020, 07:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment]
Without seeing all the code, I just have to make guesses based on what's in your screenshots. But it looks like your binding for the ReturnCommand is 

`ReturnCommand="{Binding Source=viewModel:EquationLibViewModel, Path=ChooseEquationSet}"`

The screenshot of your application output shows several errors that look like:
`Binding: 'ChooseEquationSet` property not found on 'viewModel:EquationLibViewModel``

So my best guess is that the `Source` you are trying to reference isn't what you think it is. You are probably referencing the `EquationLibViewModel` type, rather than the actual instance of `EquationLibViewModel` that you're binding your ListView to. 

You probably want a relative binding to an ancestor - take a look at the [Relative Binding docs for an example](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/relative-bindings#bind-to-an-ancestor).

**Comment by pfafft33** [comment]
I tried:
ReturnCommand="{Binding Source={RelativeSource Mode=TemplatedParent}, Path=ChooseEquationSet}"
but that doesn't seem to work either.
I have included the xaml and xaml.cs files in a zip format.


[EquationLibPage.zip](https://github.com/xamarin/Xamarin.Forms/files/4569978/EquationLibPage.zip)

**Comment by chowarth** [comment]
You want to only use `Mode=TemplatedParent` when using a `ControlTemplate`, for each cell a `ListView` uses a `DateTemplate` which is something entirely different.

As per @hartez's comment, you probably want to use something that will look for the property `ChooseEquationSet` on the `AncestorType` of `viewModel:EquationLibViewModel`, like this:
```xaml
ReturnCommand="{Binding
    Source={RelativeSource
    AncestorType={x:Type viewModel:EquationLibViewModel}}
    Path=ChooseEquationSet}"
```

On a side note, it's probably not a good idea to pass your entire page through to the command as a parameter as your view model shouldn't deal with anything UI related.

**Comment by pfafft33** [comment]
@chowarth  - Thank you SO much. That syntax worked for me.
This issue may be closed now.
About your side note - Thanks for the pointer. I can use all the help I can get. I'm completely new to MVVM, Xamarin, and C#. I'm an OLD programmer from the days of FORTRAN, C, and PL/SQL.
