### ISSUE TITLE
[Bug][iOS] Custom font not rendered when Label.TextType="Html"

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#10588]
### Description

The following code uses a custom font, registered with the `ExportFont` attribute, and works perfectly:

```
        <Label Text="Hello Forms with XAML"
               FontFamily="Lobster" />
```

![Simulator Screen Shot - iPhone 11 - 2020-05-06 at 10 09 21](https://user-images.githubusercontent.com/8092460/81160720-569ef580-8f82-11ea-8d40-3969ba5ddb7b.png)

However, when the `TextType` property is set to `Html`, the custom font isn't rendered on iOS:

```
        <Label Text="Hello Forms with XAML"
               FontFamily="Lobster"
               TextType="Html"/>
```

![Simulator Screen Shot - iPhone 11 - 2020-05-06 at 10 09 07](https://user-images.githubusercontent.com/8092460/81160736-5d2d6d00-8f82-11ea-919d-0115676b59c9.png)

### Steps to Reproduce

1. Run the attached sample.

### Expected Behavior

"Hello Forms with XAML" is rendered using the custom font.

### Actual Behavior

"Hello Forms with XAML" is rendered using the default (plain) font.

### Basic Information

- Version with issue: 4.6.0.726
- IDE: VSMac 8.5.4
- Platform Target Frameworks: 
  - iOS:  13.4

### Reproduction Link

[WorkingWithFonts.zip](https://github.com/xamarin/Xamarin.Forms/files/4585832/WorkingWithFonts.zip)

**Comment by sandlergiovanni** [comment]
Refering on #2802 bug, my assemblyinfo file is currently using an alias like this: 

[assembly: ExportFont("CircularStd-Bold.ttf", Alias = "FontStdBold")]

**Comment by alexeystrakh** [comment]
We have faced a similar issue (probably the same) on one iOS project and pulled together a sample to reproduce the issue. Basically the issue is reproduced even without using a custom font, even basic attributes are not applied (e.g. `FontSize`, `TextColor`) when `TextType=Html`. And it works for Android as expected, please see below: 

![Simulator Screen Shot - iPhone 11 - 2020-06-05 at 10 22 42](https://user-images.githubusercontent.com/3697084/83932507-d07bf780-a757-11ea-9167-61ca17bbd12e.png)

![Screenshot_1591404632](https://user-images.githubusercontent.com/3697084/83932506-cf4aca80-a757-11ea-8917-81651fb421f7.png)

The sample project is below:
[https://github.com/pchandravadan/AASample](https://github.com/pchandravadan/AASample)

**Comment by nonubitta** [comment]
Waiting for this one to be done. Very important for my project. :(
