### ISSUE TITLE
[Enhancement] Editor MaxLines property

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#10689]
## Summary
Editor can grow by setting AutoSize property. There is no way to set limits on how far it can grow. So the editor should define MaxLines property, if the text reached the max lines the Editor switch to scroll than autosize.

## API Changes
Editor adds MaxLine bindable property

e.g.
```Xaml
<Editor MaxLins = "4" AutoSize="TextChanged" />
```

## Intended Use Case
Limit Editor height when autosize is on.

**Comment by jfversluis** [comment]
Hey everyone! I see there is a good number of upvotes on this one. Unfortunately this won't make it into Xamarin.Forms anymore, but I have labeled it so that it will come up for .NET MAUI consideration. If you have any more detailed ideas around this, feel free to open an issue on the .NET MAUI repo so we can track it even better. Thanks!
