### ISSUE TITLE
[Enhancement] Enable SourceLink support!

### ISSUE THREAD

**Issue by AlleSchonWeg** [xamarin/Xamarin.Forms#10698]
## Summary
Please enable sourcelink support. So we can step into the source code.

## API Changes
No changes

![Anmerkung 2020-05-15 095933](https://user-images.githubusercontent.com/6727366/82026356-efc0c100-9692-11ea-95f8-d54a254cbf80.png)

**Comment by jfversluis** [comment]
I don't know why NuGet explorer thinks otherwise but SourceLink is definitely enabled #6886

Unfortunately, at the time being it only works for Visual Studio for Mac since there is no support for the mono debugger on Windows. Even more unfortunately, that is out of our control. I have found this [feedback ticket](https://developercommunity.visualstudio.com/idea/649946/add-source-link-support-when-debugging-xamarin-app.html) that seems to describe it somewhat. If you feel that is not sufficient, find one that describes your requirements better or open a new one.
