### ISSUE TITLE
[Bug] DarkMode: TextColor of Entry is black on Android when use Entry with EntryValidator Behavior. Setting Entry TextColor doesn't change the actual color

### ISSUE THREAD

**Issue by SunshineSpring666** [xamarin/Xamarin.Forms#10722]
### Description

In dark mode (dark theme specified in XAML)，Text color of Entry shows as black on Android while using Entry with EntryValidator Behavior. Setting the Entry's TextColor doesn't change the actual color.

### Steps to Reproduce

1. Add an Entry in a XAML page.
2. Add Nuget Package (https://www.nuget.org/packages/EntryValidator/)  to projects. (Install-Package EntryValidator -Version 1.0.1)
3. Set the Behavior of the Entry using the EntryValidator.
4. Build and Run it on an Android device or emulator.

### Expected Behavior

In DarkMode, the text color should be shown as light color such as WhiteSmoke, LightGray and so on by default.

### Actual Behavior

The text color of the Entry is shown as Black on a dark background. Setting the TextColor explicitly won't help.

### Basic Information

- Version with issue: All recent versions I tried, including Xamarin.Forms 4.5.0~4.6.0 release and 4.7.0 pre-release.
- Last known good version: Not known.
- IDE: Visual Studio 2019 (16.5.5).
- Platform Target Frameworks: 
  - Android: Android 10.0 (API 29)
- Nuget Packages: Xamarin.Forms 4.7.0 pre-release and EntryValidator 1.0.1 [https://www.nuget.org/packages/EntryValidator/]  (Install-Package EntryValidator -Version 1.0.1)
- Affected Devices: Android devices.

### Screenshots
![image](https://user-images.githubusercontent.com/42401603/82113442-b79baa00-9788-11ea-8f7a-9b46d22973cf.png)

### Reproduction Code
`<Entry Text="{Binding Quantity}" IsVisible="{Binding InEdit, Source={x:Reference this}}"  Placeholder="Qty" Keyboard="Numeric">
        <Entry.Behaviors>
                <ev:EntryValidatorBehavior x:Name="QtyEV" IsRange="True" RangeMin="0" RangeMax="100000"/>
        </Entry.Behaviors>
</Entry>
`

### Workaround
No workaround found for this issue on Android. Setting the TextColor on Entry or Validator doesn't change anything.

**Comment by jfversluis** [comment]
In the plugin that you are using the color is set to `Color.Default` [here](https://github.com/AhmedAglan/EntryValidator/blob/master/EntryValidator/Behaviors/EntryValidatorBehavior.cs#L262). I guess this plugin needs to be updated to either account for the Dark Theme possibility or you need to get this code in your own codebase and do that yourself.

I see that you can set `ChangeTextColor` to false to prevent the text color from being changed when there is an invalid value. So that could be a workaround. Or you should change both the text color _and_ the background color into something that stays readable on both dark theme and light theme.

**Comment by samhouts** [comment]
Closing as this is an issue with EntryValidator, not Xamarin.Forms. Thanks!

**Comment by SunshineSpring666** [comment]
It works. Thanks a lot.
