### ISSUE TITLE
[Bug] WebView causes NullReferenceException

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#10738]
### Description

Since the latest Update of Xamarin.Forms, the WebView causes a NullReferenceException when it is used with a Html String through a HtmlWebViewSource. 

Exception in Log: 
```
2020-05-17 23:24:12.822169+0200 MyApp.iOS[1386:6561715] Unhandled managed exception: Object reference not set to an instance of an object (System.NullReferenceException)
  at Xamarin.Forms.Platform.iOS.WebViewRenderer+CustomWebViewDelegate.ShouldStartLoad (UIKit.UIWebView webView, Foundation.NSUrlRequest request, UIKit.UIWebViewNavigationType navigationType) [0x00072] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\WebViewRenderer.cs:277 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at MyApp.iOS.Application.Main (System.String[] args) [0x00001] in /Users/sebastian/WorkingCopy/git/MyApp/MyApp/MyApp/MyApp.iOS/Main.cs:12

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x1070faa65 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/86960A04-1815-4A23-BD18-EEB5669F2C1D/MyApp.iOS.app/Frameworks/Mono.framework/Mono : mono_dump_native_crash_info
	0x10709a0f5 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/86960A04-1815-4A23-BD18-EEB5669F2C1D/MyApp.iOS.app/Frameworks/Mono.framework/Mono : mono_handle_native_crash
	0x1070fa08b - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/86960A04-1815-4A23-BD18-EEB5669F2C1D/MyApp.iOS.app/Frameworks/Mono.framework/Mono : sigabrt_signal_handler
	0x7fff51b2f5fd - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x7ffee982e5f8 - Unknown
	0x7fff51a1fb7c - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_c.dylib : abort
	0x10677e2ef - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/86960A04-1815-4A23-BD18-EEB5669F2C1D/MyApp.iOS.app/MyApp.iOS : xamarin_unhandled_exception_handler
	0x1071884f5 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/86960A04-1815-4A23-BD18-EEB5669F2C1D/MyApp.iOS.app/Frameworks/Mono.framework/Mono : mono_invoke_unhandled_exception_hook
	0x107099a99 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/86960A04-1815-4A23-BD18-EEB5669F2C1D/MyApp.iOS.app/Frameworks/Mono.framework/Mono : mono_handle_exception_internal
	0x107097f89 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/86960A04-1815-4A23-BD18-EEB5669F2C1D/MyApp.iOS.app/Frameworks/Mono.framework/Mono : mono_handle_exception
	0x1070f52d9 - /Users/sebastian/Library/Developer/CoreSimulator/Devices/8F57A017-3FC1-4D08-B03A-ACA4A4AC2FAB/data/Containers/Bundle/Application/86960A04-1815-4A23-BD18-EEB5669F2C1D/MyApp.iOS.app/Frameworks/Mono.framework/Mono : handle_signal_exception
	0x7ffee982e2f8 - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fff51a9033a):0x7fff51a9032a  ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....
0x7fff51a9033a  73 08 48 89 c7 e9 e5 a2 ff ff c3 90 90 90 b8 53  s.H............S
0x7fff51a9034a  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 cd a2  ...I....s.H.....
0x7fff51a9035a  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  ...........I....

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
```

### Steps to Reproduce

1. Using a WebView with HtmlWebViewSource

### Expected Behavior

Should not cause the exception as it was before.

### Actual Behavior

Causes NRE. 

### Basic Information

- Version with issue: 4.6.0.772
- Last known good version: 4.6.0.726

VS for Mac Info: 
```
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.2
	1.0.5

Xamarin.Profiler
Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 11.4.1 (16137)
Build 11E503a

Xamarin.Mac
Version: 6.16.0.13 (Visual Studio Enterprise)
Hash: b75deaf82
Branch: d16-5-xcode11.4
Build date: 2020-04-01 21:33:18-0400

Xamarin.iOS
Version: 13.16.0.13 (Visual Studio Enterprise)
Hash: b75deaf82
Branch: d16-5-xcode11.4
Build date: 2020-04-01 21:33:19-0400

Xamarin Designer
Version: 16.5.0.471
Hash: 35aa4889d
Branch: remotes/origin/d16-5
Build date: 2020-02-25 00:52:08 UTC

Xamarin.Android
Version: 10.2.0.100 (Visual Studio Enterprise)
Commit: xamarin-android/d16-5/988c811
Android SDK: /Users/sebastian/Library/Android/sdk
	Supported Android versions:
		4.4 (API level 19)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.6
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: c0c5c78
Java.Interop: xamarin/java.interop/d16-5@fc18c54
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

Microsoft Mobile OpenJDK
Java SDK: /Users/sebastian/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.5.0.39
Hash: 6fb4c79
Branch: remotes/origin/d16-5
Build date: 2020-04-29 20:09:00 UTC

Android Device Manager
Version: 16.5.0.73
Hash: dff2f03
Branch: remotes/origin/d16-5
Build date: 2020-04-29 20:09:20 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 805060011
Git revision: b31ce1cc7c62479ddaa387af4b7a1a6cb1e72443
Build date: 2020-05-13 14:55:07-04
Build branch: release-8.5
Xamarin extensions: b31ce1cc7c62479ddaa387af4b7a1a6cb1e72443

Operating System
Mac OS X 10.15.4
```

**Comment by jsuarezruiz** [comment]
@Sebastian1989101 Could you attach a reproduction sample?. 

I have tried to replicate the issue but without success.
[Issue10738.zip](https://github.com/xamarin/Xamarin.Forms/files/4642909/Issue10738.zip)

**Comment by Sebastian1989101** [comment]
@jsuarezruiz I think the issue can be closed. It seems like for some reason the WebView was forced to use the old WebViewRenderer instead of WkWebViewRenderer. After updating deleting obj and bin folders and update every library to the latest stable available beside Xamarin.Forms, this issue seems to be solved.

**Comment by Stensan** [comment]
I have the same problem on iOS. Deleting obj and bin folders does not fix the problem for me.

**Steps to Reproduce**
Using a WebView with HtmlWebViewSource inside a CarouselViewControl.

**Expected Behavior**
Should not cause the exception as it was before.

**Actual Behavior**
Causes NRE.

**Basic Information**
Versions with issue: 4.6.0.772 and 4.6.0.800
Last known good version: 4.6.0.726

**VS for Mac Info:**
Microsoft Visual Studio Enterprise 2019 (2)
Version 16.6.0
VisualStudio.16.Release/16.6.0+30114.105
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Azure App Service Tools v3.0.0   16.6.936.3669
Azure App Service Tools v3.0.0

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2019.3.4   Build 193.0.20200226.112949
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2020 JetBrains, Inc.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.6.17 (9692114)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.6.000.1055 (d16-6@2873694)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.1.0 (d16-6/3fe860a)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

Xamarin.iOS and Xamarin.Mac SDK   13.18.1.31 (b3eedfe)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Exception in Log:**
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Forms.Platform.iOS.WebViewRenderer+CustomWebViewDelegate.ShouldStartLoad (UIKit.UIWebView webView, Foundation.NSUrlRequest request, UIKit.UIWebViewNavigationType navigationType) [0x00072] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\WebViewRenderer.cs:277 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.18.1.31/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.18.1.31/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at UIKit.UIApplic
ation.Main (System.String[] args, System.Type principalClass, System.Type delegateClass) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.18.1.31/src/Xamarin.iOS/UIKit/UIApplication.cs:75 
  at Forms.iOS.AppStoreCloudInventory.Application.Main (System.String[] args) [0x0000d] in C:\VS\Projects\BaseSolutionsCPD\Forms.iOS.AppStoreCloudInventory\Main.cs:17 
2020-05-25 14:15:32.895 Forms.iOS.AppStoreCloudInventory[343:44941] Unhandled managed exception: Object reference not set to an instance of an object (System.NullReferenceException)
  at Xamarin.Forms.Platform.iOS.WebViewRenderer+CustomWebViewDelegate.ShouldStartLoad (UIKit.UIWebView webView, Foundation.NSUrlRequest request, UIKit.UIWebViewNavigationType navigationType) [0x00072] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\WebViewRenderer.cs:277 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.18.1.31/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.18.1.31/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at UIKit.
UIApplication.Main (System.String[] args, System.Type principalClass, System.Type delegateClass) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.18.1.31/src/Xamarin.iOS/UIKit/UIApplication.cs:75 
  at Forms.iOS.AppStoreCloudInventory.Application.Main (System.String[] args) [0x0000d] in C:\VS\Projects\BaseSolutionsCPD\Forms.iOS.AppStoreCloudInventory\Main.cs:17 

=================================================================
	Native Crash Reporting
=================================================================
Got a abrt while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10b299fe8 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x10b290260 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x10b299534 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x1902d2894 - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x1902db74c - /usr/lib/system/libsystem_pthread.dylib : <redacted>
The app has been terminated.	0x19022a644 - /usr/lib/system/libsystem_c.dylib : abort
	0x10b458a78 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : xamarin_get_block_descriptor
	0x10b2fac1c - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : mono_pmip
	0x10b28fc54 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x10b28e63c - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x10b284940 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x1080c52dc - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56

192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x103b45100 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x10b2a1854 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : mono_pmip
	0x10b35cd30 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : mono_pmip
	0x10b360594 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : mono_pmip
	0x1032819d0 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x1032a2940 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A3
The app has been terminated.
79-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x194bb0e74 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x1905cf760 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1904a0b40 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1904a1718 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x19c693c64 - /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy : <redacted>
	0x1905cd414 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1905cf5bc - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : _CF_forwarding_prep_0
	0x1905cf760 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1904a0b40 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x198abbd6c - /System/Library/PrivateFrameworks/WebCore.framework/WebCore : <redacted>
	0x190547b64 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x190547abc - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x190547244 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x190542274 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x190541c34 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x19a68b38c - /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x19467422c - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x104c73108 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x1043aa990 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x1043aa814 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x1043aa910 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x1032d6aa0 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x103b45100 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x10b2a1854 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : mono_pmip
	0x10b35cd30 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : mono_pmip
	0x10b362f88 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : mono_pmip
	0x10b27fe0c - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudIn
ventory : 
	0x10b46b738 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : xamarin_localized_string_format_9
	0x1032d6954 - /private/var/containers/Bundle/Application/F215FF53-827F-49B7-A379-1E1F9E56192E/Forms.iOS.AppStoreCloudInventory.app/Forms.iOS.AppStoreCloudInventory : 
	0x1903c9800 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1903bed88):0x1903bed78  c0 03 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .._..._..)......
0x1903bed88  e3 00 00 54 fd 7b bf a9 fd 03 00 91 4f 7b ff 97  ...T.{......O{..
0x1903bed98  bf 03 00 91 fd 7b c1 a8 c0 03 5f d6 c0 03 5f d6  .....{...._..._.
0x1903beda8  90 29 80 d2 01 
10 00 d4 e3 00 00 54 fd 7b bf a9  .).........T.{..

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================

**Comment by Stensan** [comment]
@Sebastian1989101 Could you please reopen this issue?

**Comment by Sebastian1989101** [comment]
@Stensan You should make sure you use `WkWebViewRenderer` not the old `WebViewRenderer` for the base class of custom renderers. Two of my friends got the very same exception by this mistake. After that you need to make sure you did a clean recompile which was my issue.

**Comment by Stensan** [comment]
@Sebastian1989101 Thank you, that worked! I wasn't aware that I used the old WebViewRenderer.
