### ISSUE TITLE
Bottom Navigation Tab Bar With 5 Tab Items Issue

### ISSUE THREAD

**Issue by jaigupta91** [xamarin/Xamarin.Forms#10783]
### Description
Created a tabbed page with 5 tab items. When we switch from between 1-4 tab items it works fine. When we click on 5 tab item and then click on any of tab from 1-4 it reload the view everytime. It calls OnSizeAllocated() method everytime. It happens in android.

### Steps to Reproduce

1. Run the uploaded project.

### Expected Behavior
It should not refresh/reload the view.

### Actual Behavior
It's reloading every time.

### Basic Information

- Version with issue: Xamarin.forms 4.3.0.947036 and afterwords
- Last known good version: Xamarin.forms 3.4.0.1009999
- IDE: Visual Studio 2019
- Platform Target Frameworks:
   - Android: 9.0 

### Reproduction Link

[TabBar.zip](https://github.com/xamarin/Xamarin.Forms/files/4654859/TabBar.zip)

**Comment by samhouts** [comment]
The Android ViewPager, which is backing the TabbedPage, keeps a minimum number of pages loaded in memory to keep the UI fast and responsive. If you go beyond the initial offscreen limit, it will start disposing pages and recreating them as needed. If you want to prevent this, you can increase the offscreen limit using the `TabbedPage.OffscreenPageLimit` platform specific (see https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/tabbedpage-page-swiping). However, keep in mind that this will slow down your startup time and inflate your app's memory usage. In any event, this is expected behavior.
