### ISSUE TITLE
[Bug] Image sizing problem with CarouselView inside an Expander 

### ISSUE THREAD

**Issue by Softtinn** [xamarin/Xamarin.Forms#10835]
### Description

The Expander control behaves strangely when a CarouselView is set as its content. The images are being shown as thumbnails instead of their acutal size after the content is collapsed. See the included .GIF-file.

### Steps to Reproduce

1. Setup the Expander control according to the official documentation.
2. Inside the Expander, add a CarouselView as the Content.
3. Feed the CarouselView with a few images (web-source).

See the code below:
`<Expander.Header>
                // Some labels
                ...
            </Expander.Header>
            <StackLayout>
                <CarouselView
                    HeightRequest="240"
                    IndicatorView="indicatorView"
                    ItemsSource="{Binding Images}">
                    <CarouselView.ItemTemplate>
                        <DataTemplate>
                            <Image
                                Aspect="AspectFit"
                                IsOpaque="True"
                                Source="{Binding Value}" />
                        </DataTemplate>
                    </CarouselView.ItemTemplate>
                </CarouselView>
                <IndicatorView
                    x:Name="indicatorView"
                    HorizontalOptions="Center"
                    IndicatorColor="LightGray"
                    SelectedIndicatorColor="DarkGray" />
            </StackLayout>
        </Expander>`

### Expected Behavior

You should be able to hide/show the CarouselView inside the Expander without the images being shown as thumbnails. 

### Actual Behavior

The images inside the CarouselView are shown as thumbnails when the content is collapsed/shown. Please see the included .GIF file.

### Basic Information

- Version with issue: Xamarin.Forms version: 4.6.0.726
- Last known good version: Unknown
- IDE: Visual Studio 2019 Pro, v. 16.5.4
- Platform Target Frameworks:
  - Android: Android 9.0 (API Level 28)
- Android Support Library Version: v28.0.0.3
- Affected Devices:
  - Samsung S10+ (physical device)
  - Pixel 2 (emulator)

### Screenshots

![expander_buggy](https://user-images.githubusercontent.com/7129814/82756351-088b4e00-9dda-11ea-914e-5ba19f9e40e9.gif)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by jpacov** [comment]
I'm having the same problem. Is it possible to re-open the issue? I can provide more info if needed.

The problem is:
I have a CarouselView inside an Expander content.
When Expander control is expanded, the contents only a part of the items in Carousel is viewed (items are cut). When you swipe the carousel elements, then they are displayed correctly.

As a workaround, How could I force a "Refresh" for the CarouselView when the Expander control is expanded?
@Softtinn : did you manage to solve somehow the problem?

**Comment by Softtinn** [comment]
@jpacov No, we didn't manage to find a workaround for this issue.

@samhouts I will try to upload an example project asap!

**Comment by Softtinn** [comment]
Hi again,

@samhouts I've uploaded a small example project for this issue.
See: https://github.com/Softtinn/ExpanderSample.git

**Comment by jpacov** [comment]
Hi @Softtinn 

I guess this issue will not be followed up anymore since it was previously closed.

As you already uploaded a sample project, Could you please create a new issue and paste here the reference? So that I can also follow the new one and try to support the investigation as much as possible.

Thanks a lot :)

**Comment by Softtinn** [comment]
I've submitted a new bug report as this issue hasn't been reopened.
See: [11678](https://github.com/xamarin/Xamarin.Forms/issues/11678)
