### ISSUE TITLE
[Bug] SwipeView.LeftItems in CollectionView stop Scrolling

### ISSUE THREAD

**Issue by ThaerM** [xamarin/Xamarin.Forms#10875]
**Using SwipeView in CollectionView**:  
Like this sample [FavFighters](https://github.com/jfversluis/FavFighters  ) @jfversluis  you can scroll vertical if you use SwipeView.RightItems but if you used the SwipeView.LeftItems you can't scroll 

Steps to Reproduce
Put SwipeView (with some SwipeItems) in CollectionView
Set SwipeView.LeftItems to swipeView
You can't scroll 

** This work fine **
`  <SwipeView >
                    <SwipeView.RightItems>
                        <SwipeItems Mode="Reveal">
                     
                            <SwipeItemView   >
                                <Grid >
                                    <Label   Text="Favourite" />
                                </Grid>
                            </SwipeItemView>
                        </SwipeItems>
                    </SwipeView.RightItems>
                    <SwipeView.Content>...  `

** This not work **
`   <SwipeView >
                    <SwipeView.LeftItems>
                        <SwipeItems Mode="Reveal">
                     
                            <SwipeItemView   >
                                <Grid >
                                    <Label   Text="Favourite" />
                                </Grid>
                            </SwipeItemView>
                        </SwipeItems>
                    </SwipeView.LeftItems>
                    <SwipeView.Content>...  `

**Basic Information**
Version with issue: 4.6.0.800
IDE: VS 2019  16.6.0
Platform Target Frameworks:
Android: Not working  @(SDK Android 9.0)

**Comment by jsuarezruiz** [comment]
@ThaerM Thanks for the description. Reading the description I thought that it could be the same issue as https://github.com/xamarin/Xamarin.Forms/issues/10313 that will be fixed with the PR https://github.com/xamarin/Xamarin.Forms/pull/ 10614
To validate this specific case I added in the PR a test using FavFighters.

<img width="478" alt="issue10875" src="https://user-images.githubusercontent.com/6755973/83256724-3e9e4880-a1b3-11ea-83eb-775aad68f0e0.png">

I have tested on different emulators and devices.
