### ISSUE TITLE
[Bug] Binding to Listview fails when AndroidLinkMode is Full

### ISSUE THREAD

**Issue by Soushi-Atsumi** [xamarin/Xamarin.Forms#10896]
### Description

When AndroidLinkMode is Full, binding a property (such as Group) to ListView fails.
Binding to cells in the listview fails also.

### Steps to Reproduce

1. Create a Page and place a ListView which contains TextCell.
2. In ListView, Binding a property to GroupDisplayBinding and set IsGroupingEnabled True.
3. In TextCell, Binding properties to Text and Detail.

### Expected Behavior
Rows are generated as it has been added and Group, Text and Detail are displayed which it have been bound.

### Actual Behavior
Rows are generated as it has been added. However, Group, Text and Detail are not displayed.

### Basic Information

- Version with issue: 4.5.0.495 to 4.6.0.800
- Last known good version: I don't know.
- IDE: Microsoft Visual Studio Community 2019 Version 16.6.0
- Platform Target Frameworks:
  - Android: 10.0 (Q)

### Screenshots

SdkOnly | Full
------- | ----
![9036](https://user-images.githubusercontent.com/38220617/83317494-158bbf80-a268-11ea-9863-aeccfe372e8c.png) | ![3700](https://user-images.githubusercontent.com/38220617/83317583-c2663c80-a268-11ea-8079-b5cd793122f8.png)

### Reproduction Link

Don't forget change AndroidLinkMode to Full at Android Project -> Properties -> Android Options to reproduce this issue.
https://gist.github.com/Soushi-Atsumi/ffb6b4bf99397ceec899fd9e7647b845

### Workaround

Nothing. Even if a property which is bound returns a constant value it is not displayed.

**Comment by jsuarezruiz** [comment]
Could you add the **preserve** attribute to the class bound to the ListView?

**Comment by Soushi-Atsumi** [comment]
> Could you add the **preserve** attribute to the class bound to the ListView?

Adding Preserve attribute to the class does not solve this problem but adding to properties of the class solve it.
We have to add this attribute to a property when it is bound to ListView.

**Comment by jsuarezruiz** [comment]
@Soushi-Atsumi Are you using compiled bindings?. It should not happen using it.

**Comment by Soushi-Atsumi** [comment]
> 
> 
> @Soushi-Atsumi Are you using compiled bindings?. It should not happen using it.

No. I'm not using.
Surely compiled bindings solve this problem too.

**Comment by hartez** [comment]
@Soushi-Atsumi This is how the linker works. It is working as expected - removing code which is never directly referenced. 

You can [tell the linker to preserve your classes in several ways](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker#preserving-code), including using Preserve attributes.

 > Adding Preserve attribute to the class does not solve this problem but adding to properties of the class solve it.

Specify in the attribute that you wish to preserve all members of the class:

```
[Preserve(AllMembers = true)]
public class TextCellData
{
	public string Text { get; } = "Text";
	public string Detail { get; } = "Detail";
}
```

The`AllMembers` parameter allows you to specify that you want to preserve all of the properties. 

Using [compiled bindings](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/compiled-bindings) may also solve your issues, because the compiled bindings will provide a direct references to the properties which will prevent the linker from removing them.

**Comment by Soushi-Atsumi** [comment]
@hartez Thank you for your polite reply.
I completely understood.
