### ISSUE TITLE
Xamarin - Binding a DateTime gives "InvalidProgramException - Invalid IL Code"

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11061]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1077549/xamarin-binding-a-datetime-gives-invalidprogramexc.html)._

---
This is my code:

MyChildControl.cs
```
public class MyChildControl : NControlView
{
    public DateTime MyDateTime { get; set; }
}
```

MyParentControlModel.cs
```
public class MyParentControlModel : INotifyPropertyChanged
{
    private DateTime _myDateTime;
    public DateTime MyDateTime
    {
        get => _myDateTime;
        set
        {
            _myDateTime= value;
            OnPropertyChanged();
        }
    }
    ....
}
```

MyParentControl.xaml
```
...
<myNamespace:MyChildControl MyDateTime="{Binding MyDateTime}"/>
...
```

Doing this results in an InvalidProgramException "Invalid IL Code".  Removing the binding makes the issue disappear

---
#### Visual Studio Feedback System on 6/15/2020, 00:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
The problem seems to be that the Xaml parser is getting confused when the property is a DateTime and is attempting to compile something to IL instead of throwing the expected exception that MyDateTime is not a BindableProperty. If you change MyDateTime to be a string instead of a DateTime, you get the proper compile exception.

Repro without NControl:
[FT1141376.zip](https://github.com/xamarin/Xamarin.Forms/files/4781750/FT1141376.zip)

**Comment by StephaneDelcroix** [comment]
the Xaml compiler is confused because DateTime supports `Add()` 🤦
