### ISSUE TITLE
Java.Lang.NoClassDefFoundError at FrameRenderers.cs:39

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11112]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1068687/javalangnoclassdeffounderror-at-framerendererscs39.html)._

---
The Preview don't work with Xamarin.Forms 4.5.x,4.6.x and 4.7.x.

I use this repo: https://github.com/devcrux/WeatherApp

After activate the preview I get an error at FrameRenderers.cs:39

---
#### Visual Studio Feedback System on 6/8/2020, 11:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

> VS bug [#1144405](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1144405)

**Comment by paymicro** [comment]
Are there any more detailed steps? In my case, the Android preview works on latest stable build of Xamain.Forms
| VS2019 | VS4M |
|-|-|
| ![Screenshot_4](https://user-images.githubusercontent.com/27482193/85643801-e406e800-b69d-11ea-89d4-274cf7e0afbd.png) | ![image](https://user-images.githubusercontent.com/27482193/85644205-fcc3cd80-b69e-11ea-838c-c18393b6dc96.png) |

Maybe the bug is already fixed
