### ISSUE TITLE
[Bug] Xamarin.Forms Shell - contextual navigation from global routes is not working

### ISSUE THREAD

**Issue by MaxFmi** [xamarin/Xamarin.Forms#11237]
### Description
Having two pages registered as global routes (see "Register page routes" under [Shell navigation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation#routes)) and navigating in a contextual way won't work (nothing happens, no exception, no return value or anything else).

### Steps to Reproduce

1. Open the provided example -> [Xaminals global routes contextual navigation.zip](https://github.com/xamarin/Xamarin.Forms/files/5802296/Xaminals.global.routes.contextual.navigation.zip)
2. Open it in your IDE.
3. Open the file Xaminals.ViewModels.MonkeyDetailViewModel.cs.
4. Add a breakpoint at line 49.
5. Start the app and navigate to 
5.1 Monkeys (tab)
5.2 Select any monkey
5.3 Click the button "Navigate to MonkeyGenomePage"

### Expected Behavior

App should navigate to the page MonkeyGenomePage.

### Actual Behavior

Nothing happens.

### Basic Information

- Version with issue: Xamarin.Forms 4.7.0.968
- Last known good version: -
- IDE: Visual Studio for Mac 8.5
- Platform Target Frameworks: 
  - iOS:  Simulator 13.5
  - Android: 9.0
- Android Support Library Version: 28.0.03

### Workaround

Not using contextual routes on global routes + using a prefix to make routes unique.

**Comment by tcerdaj** [comment]
I got the same issue in Xamarin forms 4.8.

**Comment by RidhwanDev** [comment]
Yes same here, any work around for this? I need to keep state of 3 pages intact. I'm also not using the tabs because I'm rendering my own tabs.

**Comment by PureWeen** [comment]
@MaxFmi @tcerdaj @RidhwanDev 

Can you test with the nuget here?
https://dev.azure.com/xamarin/public/_build/results?buildId=33278&view=results


@MaxFmi a couple notes about the sample you attached

1) On monkey view model where you have the code that goes to monkeyDetails absolutely your casing on monkeydetails is wrong and should be monkeyDetails
2) The better way to go back twice here is to use `await Shell.Current.GoToAsync("../..");`. the problem with using RemovePage is that it now makes the uri invalid since the monkeygenome page depends on the monkeyDetails page to be there in order to for a valid uri.  I'm not too sure the best way to handle this case. I'm thinking throwing an exception would probably be the best bet so that users aren't met with weird behavior.

**Comment by MaxFmi** [comment]
@PureWeen Thanks for the answer.

I haven't worked with Azure DevOps and not sure where to download the nuget. Artifacts is only showing an old Android version.
![Screenshot 2021-01-12 at 14 17 06](https://user-images.githubusercontent.com/61872738/104319253-e79a7900-54e0-11eb-8c60-903dc4b4a6c6.png)
![Screenshot 2021-01-12 at 14 17 51](https://user-images.githubusercontent.com/61872738/104319321-fe40d000-54e0-11eb-86eb-8ca348de7f63.png)
![Screenshot 2021-01-12 at 14 14 26](https://user-images.githubusercontent.com/61872738/104319144-c174d900-54e0-11eb-881c-3ab6c814220f.png)


Addressing 1. Corrected spelling and uploaded example in this issue.
Addressing 2. Prior to version 5 await Shell.Current.GoToAsync("../.."); had no animation so we couldn't use it in our app. Which seems still to be the case. At least I haven't seen an animation while navigating back twice using the command above.

**Comment by PureWeen** [comment]
@MaxFmi on the page above you would click on where it says "4 published"

Here's a direct link you can use
https://dev.azure.com/xamarin/public/_build/results?buildId=33354&view=artifacts&pathAsName=false&type=publishedArtifacts

When you hover over the "nuget"  option you'll see three dots to the right. Click those to download the packages

**Comment by MaxFmi** [comment]
It works. Thank you @PureWeen
