### ISSUE TITLE
First index page is coming for a second in CarouselView with Xamarin Forms 4.7.0.1080 

### ISSUE THREAD

**Issue by MridulMalviya** [xamarin/Xamarin.Forms#11377]
### Steps to Reproduce

1. Add carousel view 
2. pass more than 2 data in item source 
3. set position =1 in code behind 

### Expected Behavior
it should be open to target element, which is in position 1

### Actual Behavior
first element is visible for a second, when set position =1( in code behind)

### Basic Information

- Version with issue: Xamarin Forms 4.7
- Last known good version:4.3
- IDE:Visual Studio Community 
- Platform Target Frameworks: 
  - iOS:  ](url
![xf](https://user-images.githubusercontent.com/21024649/87002318-f4a77a00-c1d6-11ea-973e-265b7b88f4cd.gif)

)
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin Forms 4.7
- Affected Devices: ipad and android 

### Screenshots
![xf](https://user-images.githubusercontent.com/21024649/87003279-f83c0080-c1d8-11ea-8e2b-ead613364e96.gif)

**Comment by PureWeen** [comment]
@rmarinho ?

Not sure the desired behavior here. It seems like on initial load it should just start at the position indicated opposed to animating to it

**Comment by poliahrameshkumar** [comment]
I also face this issue and it is not only in Android but iOS also. Suppose if we have 10 elements in carousel view and we set position 5 directly, then instead of loading the 5th element directly, It shows first element for a second and then it animates to 5th element which doesn't look good. This exists in latest Xamarin.Forms version also and it should be fixed on high priority.

**Comment by rmarinho** [comment]
this should be fixed on 5.0.0.1931 you can set the position and it will start in that position
