### ISSUE TITLE
[Bug] [UWP, iOS] Can't set transparent color on selected template item in CollectionView

### ISSUE THREAD

**Issue by themronion** [xamarin/Xamarin.Forms#11421]
### Description
Can't set transparent color on selected template item in CollectionView on iOS. Other colors work. As i found the issue with "selected" state in UWP is being resolved so maybe this is only an iOS issue
### Steps to Reproduce

1. Try the code from official sample docs: [*click*](https://docs.microsoft.com/ru-ru/xamarin/xamarin-forms/user-interface/collectionview/selection#change-selected-item-color) 
2. Set background color to Transparent 
3. See that the color is not being changed to transparent on iOS (uwp).

### Expected Behavior
Color is being set to Transparent on all platforms

### Actual Behavior
Color is not being set to Transparent on iOs (uwp)

### Workaround
Set background color as property of binded observablecollection item

**Comment by jsuarezruiz** [comment]
@themronion Do you mean modify the background color using the Selected VisualState?

**Comment by themronion** [comment]
@jsuarezruiz yeap

**Comment by themronion** [comment]
Any progress here?

**Comment by jsuarezruiz** [comment]
I have done some tests on Android, iOS and UWP. The behavior seems the same on all platforms:
- If a background color is set using the Selected state, the selection color is modified.
- If the Selected state is not used, by default, a selection color is applied.
- If a transparent color is applied in the Selected state, the behavior is the same as in the previous point.

**Android**

Using:  
```
<VisualState x:Name="Selected">
     <VisualState.Setters>
          <Setter Property="BackgroundColor" 
               Value="Transparent" />
     </VisualState.Setters>
</VisualState>
```
<img width="515" alt="Captura de pantalla 2020-07-17 a las 12 53 15" src="https://user-images.githubusercontent.com/6755973/87779698-8180b200-c82d-11ea-9c54-5b8aa177145b.png">

Using transparent:

<img width="520" alt="Captura de pantalla 2020-07-17 a las 12 53 27" src="https://user-images.githubusercontent.com/6755973/87779686-7ded2b00-c82d-11ea-9736-f002c865f320.png">

**UWP**
<img width="1199" alt="Captura de pantalla 2020-07-17 a las 12 57 22" src="https://user-images.githubusercontent.com/6755973/87779680-7c236780-c82d-11ea-84ad-32221fe61bf3.png">
<img width="1200" alt="Captura de pantalla 2020-07-17 a las 12 54 07" src="https://user-images.githubusercontent.com/6755973/87779693-7fb6ee80-c82d-11ea-8cb4-ad1eb9440d4c.png">


The expected behavior would be not to apply any selected color (avoid the native selection color)?

**Comment by themronion** [comment]
Yes, on android i managed somehow to avoid the selection color in a selected collection view item. As i now realized this wasn't because i was setting a transparent color in the vsm. But how then to acheive not a gray background (on ios) on a selected collection view item, but a transparent one? Using custom renderers i did the trick with a listview, but how to write a renderer to remove the selection color im a collection view in ios a have no idea. I thought i would acheive that with VSM, but no... maybe you can give me a tip?

**Comment by bpaquin** [comment]
Is there a fix for the transparent color on ios? I'm still seeing the grey background when a set the "selected" color to transparent.

**Comment by jthun** [comment]
@samhouts, @hartez, can you please provide on update? Is this being worked on?
