### ISSUE TITLE
[Bug] NavigableElement.Navigation Has an Empty Navigation Stack When Displayed as a Modal Page

### ISSUE THREAD

**Issue by Lonswaya** [xamarin/Xamarin.Forms#11461]
### Description
The Navigation property of a content page claims that the current Navigation stack is always empty, only if the content page in question is pushed as a modal page.

### Steps to Reproduce

1.  Push a content page using Navigation.PushModalAsync
2.  Inspect the Navigation property of the content page
3.  The modal stack will contain the content page, but the navigation stack will be empty, regardless of any other existing pages

### Expected Behavior
Navigation stack contains pages in the flow
### Actual Behavior
Navigation stack is empty 
### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: Unknown
- IDE: Visual Studio

### Reproduction Link

https://github.com/Lonswaya/XamarinModalNavigationBug

### Workaround

Application.Current.MainPage.Navigation is a substantial workaround, if your main page is a NavigationPage

**Comment by hartez** [comment]
This is as designed. You've pushed a ContentPage (which has no navigation stack) onto the modal stack. So the modal stack has 1 page (the ContentPage) and the current Navigation stack (the one referred to by the `Navigation` property) does not exist (because the context is the ContentPage, which does not provide navigation). 

To get a better sense of what's happening, in your App.xaml.cs, try setting your MainPage to an instance of your `NavigationAwareContentPage` class:

```
MainPage = new NavigationAwareContentPage();
```

You'll see that all the stacks have a count of zero, because they essentially don't exist - you don't have any NavigationPages in your app at all.

Alternatively,  in your MainPage.xaml.cs, change the modal button handler to 

```
        private async void ModalOpenButton_OnClicked(object sender, EventArgs e)
        {
            var navPage = new NavigationPage(new NavigationAwareContentPage());
            await Navigation.PushModalAsync(navPage);
        }
```

Then you will see a navigation stack count on the modal page, because navigation is now available in the modal page's context.
