### ISSUE TITLE
[Bug] Shell.GotoAsync does not pass any parameter data after a "#" is encountered 

### ISSUE THREAD

**Issue by horizondave** [xamarin/Xamarin.Forms#11525]
If your data contains a "#", the hash and everything after it is lost by the receiving field.

1. Shell.Current.GoToAsync("dest?param1=data#123")
2. Declare receiver:
[QueryProperty("Param1","param1")]

public string Param1 {
   set { _value here only contains "data", not "data#123"_ }

### Expected Behavior
param1's entire value should be passed to the receiving property.

### Actual Behavior
Only the value before "#" is passed to the receiving property.

Forms 4.7

**Comment by hartez** [comment]
The `#` character in a URI indicates the start of a [fragment identifier](https://tools.ietf.org/html/rfc3986#section-3.5). So the "query" portion of your URI ends at the `#`; that's why the value for `param1` only includes `data`. 

If you want `param1` to have a value of `data#123`, you can escape the `#` character with percent encoding (using the value `%23`). Something like this should work:

```
Shell.Current.GoToAsync("dest?param1=data%23123")
```
