### ISSUE TITLE
AppResources translations not loaded/included in final app on iOS and Android

### ISSUE THREAD

**Issue by Gerome90** [xamarin/Xamarin.Forms#11585]
*Release status update*

A new Release version of Xamarin.Android has now been published on macOS that includes the fix for this item to match [yesterday's new version on Windows](https://github.com/xamarin/Xamarin.Forms/issues/10821#issuecomment-637146722). Thanks again for submitting this issue that has helped improve the product!

Fix included in Xamarin.Android SDK version 10.3.1.4.

Fix included on macOS in Visual Studio 2019 for Mac version 8.6.2. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.6.1. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.)

Fix not yet available in the Visual Studio 2019 Preview versions. I will add a few final comments on this item when Visual Studio 2019 Preview versions are available that include the fix.

_Originally posted by @brendanzagaeski in https://github.com/xamarin/Xamarin.Forms/issues/10821#issuecomment-637856339_

**Comment by Gerome90** [comment]
My VS version is 16.6.5 and Xamarin.Android SDK is 10.3.1.4 According to the comment of @brendanzagaeski this should be fixed in this constellation. But it is not. Only with the workraound the Android app is functional again.

I added this code at the end of my .csproj file:


  <Target Name="_ResolveSatellitePaths"
    DependsOnTargets="_ResolveAssemblies">
    <ResolveAssemblyReference
        AllowedAssemblyExtensions="$(AllowedReferenceAssemblyFileExtensions)"
        AssemblyFiles="@(ResolvedUserAssemblies)"
        AutoUnify="$(AutoUnifyAssemblyReferences)"
        FindDependencies="True"
        FindRelatedFiles="False"
        FindSatellites="True"
        SearchPaths="$(AssemblySearchPaths)"
        TargetFrameworkMoniker="$(TargetFrameworkMoniker)"
        TargetFrameworkMonikerDisplayName="$(TargetFrameworkMonikerDisplayName)"
        TargetFrameworkDirectories="$(TargetFrameworkDirectory)">
      <Output TaskParameter="SatelliteFiles" ItemName="_AndroidResolvedSatellitePaths"/>
    </ResolveAssemblyReference>
  </Target>

**Comment by Gerome90** [comment]
My VS version is 16.6.5 and Xamarin.Android SDK is 10.3.1.4 According to the comment of @brendanzagaeski this should be fixed in this constellation. But it is not. Only with the workraound the Android app is functional again.

I added this code at the end of my .csproj file:

`   <Target Name="_ResolveSatellitePaths"
    DependsOnTargets="_ResolveAssemblies">
    <ResolveAssemblyReference
        AllowedAssemblyExtensions="$(AllowedReferenceAssemblyFileExtensions)"
        AssemblyFiles="@(ResolvedUserAssemblies)"
        AutoUnify="$(AutoUnifyAssemblyReferences)"
        FindDependencies="True"
        FindRelatedFiles="False"
        FindSatellites="True"
        SearchPaths="$(AssemblySearchPaths)"
        TargetFrameworkMoniker="$(TargetFrameworkMoniker)"
        TargetFrameworkMonikerDisplayName="$(TargetFrameworkMonikerDisplayName)"
        TargetFrameworkDirectories="$(TargetFrameworkDirectory)">
      <Output TaskParameter="SatelliteFiles" ItemName="_AndroidResolvedSatellitePaths"/>
    </ResolveAssemblyReference>
  </Target>`

**Comment by brendanzagaeski** [comment]
Thanks for the report. One possibility is if the _.resx_ resource files for your solution are located directly in the Android application project and not in a library project, then you would be seeing <https://github.com/xamarin/xamarin-android/issues/4805>. The fix for that scenario is not included in Visual Studio 2019 version 16.6, but it is available in Visual Studio 2019 version 16.7 Preview, which is getting close to being promoted from Preview to Release.

For the other possibility, if the _.resx_ resource files for your solution are located in a library project, then the next best step would be to collect the diagnostic build output for your project to help the team investigate further:

1. Set **Tools > Options > Project and Solutions \[section\] > Build and Run \[subsection\] > MSBuild project build output verbosity** to **Diagnostic**.
2. Run **Build > Clean Solution** and then use **Debug > Start Debugging** or **Debug > Start Without Debugging** to build and deploy your project to your Android device.
3. After the project is deployed, open the **View > Output** window in Visual Studio and set **Show output from** to **Build**.
4. Make sure the **Output** window is selected and then choose **File > Save Output As** to save the contents to a text file. Or copy and paste the build output into a text file.
5. Attach back the text file in a new comment on this item. You can optionally zip the file before attaching it to make the upload size smaller. Note that by default the file will contain some details about your environment and project. If the build output contains information you need to keep private, you can remove the private information before attaching it or create a new Visual Studio Developer Community feedback item via **Help > Send Feedback > Report a Problem** in Visual Studio and attach the build output there instead (attachments on new Developer Community items are only visible to the Microsoft team).

After you complete these steps, you can set **Tools > Options > Project and Solutions \[section\] > Build and Run \[subsection\] > MSBuild project build output verbosity** back to **Minimal** to avoid adding extra time to your future builds. Thanks in advance for the additional info!

Alternatively, if it is easy to trim down your full project to a small sample that demonstrates the problem, and you can attach that, that would be excellent too.

Thanks in advance!

**Comment by Gerome90** [comment]
Thank you for your answer. The affected .resx resource files are located directly in the Android application. 

The hint that it is fixed in Visual Studio version 16.6.7 is very good. Then I have misunderstood your comment (xamarin/xamarin-android#4805).

Thank you and best regards!
