### ISSUE TITLE
[Spec]  Remove Experimental Flag from Drag and Drop Recognizers

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#11663]
# Considerations before letting drag and drop leave experimental

The API is largely a copy paste from UWP

- Does AllowDrag/CanDrop make sense as property names? Would Enabled make more sense? Should these be true by default? [x]
- CollectionView implementation
- Can users extend the drag and drop handlers at the platform level so provide customization. For example on iOS/uwp you can provide custom animations
- Does the DataPackage make sense?
- Drag Leave [x]
- Fix accepted Operations [x]

**Comment by squinn7** [comment]
Just took a look at it and it works great. Especially cool because I worked on a previous project where we hand spun this with renderers and it took a lot of effort.

 As a suggestion, we used drag and drop to implement a planner app with calendars and timelines. Something that I can't figure out is if you can get the position of the drop on the screen from the event.

If this isn't in here I might suggest this as an important feature because it lays the ground work for easy implementation of an end user view manipulation feature.
