### ISSUE TITLE
[Bug] Bindings: ResourceDictionary requires usage of BindingContext and x:Reference

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11672]
Binding to the binding source inside a content page's resource dictionary (and possibly other places outside of the content section) requires to prefix all bindings with 'BindingContext.' and fetching it from the page's root.

```xaml
    <ContentPage
        ...
        x:Name="myRoot" />

        <ContentPage.Resources>
            <ResourceDictionary>
                <converters:IsInCollectionConverter
                    x:Key="MyConverter"
                    Collection="{Binding BindingContext.SomeIds, Source={x:Reference myRoot}}" /> <!-- this is required! -->
            </ResourceDictionary>
        </ContentPage.Resources>
```

Just writing the following wouldn't work:

```xaml
                <converters:IsInCollectionConverter
                    x:Key="MyConverter"
                    Collection="{Binding SomeIds}" />
```

This is of course not required within the Content section.

Any kinds of special cases where bindings don't work for whatever reason are extreme time sinks as things just don't work and there's no good debugging tools available other than starting to disable stuff until you figure out what's wrong. Given that a lot of this is auto-generated and there's no state visualising tools etc I'd really love it if bindings always worked **consistently** no matter the case.

Thanks!

**Comment by PureWeen** [comment]
- If there are binding errors you can look in the debug output for specifics
- try this tool out https://marketplace.visualstudio.com/items?itemName=PeterSpa.XamlBinding


That's the expected behavior of `x:Reference` 

The purpose of x:Reference is to enable view-to-view bindings

If you look at the example here you'll see they are binding a label to a slider
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-binding-basics#view-to-view-bindings

The `Source` by default on a binding is the BindingContext of that element once you define a different source it's no longer the BindingContext of the element it's whatever you've specified

In the case of `x:reference` you've indicating you want a particular control to act as the source

**Comment by Tommigun1980** [comment]
Hi @PureWeen and thanks for the explanation!

The things that *always* gets me, which I probably did not explain well enough, is the following:
* Say you have a custom View component, that has a VM assigned as the BindingContext
* Say you also declare some bindable properties in the view itself (some purely UI specific things)
* When you want to bind against them in your XAML;
    * If you want to access said bindings inside the ContentDictionary section (say bindings for a converter) you have to write it as such: `{Binding BindingContext.ActivityTypeIdFilter, Source={x:Reference tabRoot}}"`
    * If you want to access said bindings inside the Content section, you have to write it as such: `{Binding ActivityTypeIdFilter, Source={x:Reference tabRoot}}"`.

It won't work if you inside the ContentDictionary omit BindingContext, or use BindingContext inside the Content object. Is this also by design as it's extremely easy to get this wrong, to remember exactly how these have to be written, and if you move stuff around it's extremely easy to forget adding 'BindingContext.', or removing it.

If the problem is that the context, inside ResourceDictionary, is not set by Xamarin, could this be changed so that the ResourceDictionary's context object would be the same as the Content object's, as this is something that gets me every time.

Thanks!
