### ISSUE TITLE
[Bug] Custom controls don't always render on iOS

### ISSUE THREAD

**Issue by claytonone** [xamarin/Xamarin.Forms#11702]
### Description

Custom controls don't always render on iOS, the same control will render correctly on Android

### Steps to Reproduce

1. Create a custom control
2. Include it in a ContentPage
3. Notice that when running on Android it is visible, whilst it is probably not on iOS

### Expected Behavior

The control is visible

### Actual Behavior

The control is not visible

### Basic Information

- Version with issue: XF 4.7 & 4.8 but may have existed before
- Last known good version: Unknown
- IDE: Visual Studio 2019
- Platform Target Frameworks:
  - iOS:  13.6
  - Android: 9

### Screenshots

Android

<img width="337" alt="Screenshot 2020-08-08 at 12 45 52" src="https://user-images.githubusercontent.com/25326306/89709163-547b7700-d975-11ea-9a42-b345aee85082.png">

iOS

<img width="481" alt="Screenshot 2020-08-08 at 12 46 44" src="https://user-images.githubusercontent.com/25326306/89709159-4b8aa580-d975-11ea-858e-08690095e6e0.png">

### Reproduction Link

Run the below project on Android and then on iOS. Notice that a control appears on Android but not on iOS

[CustomControlDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/5045177/CustomControlDemo.zip)

**Comment by rmarinho** [comment]
Seems this is related with the  Font.SystemFontOfSize(NamedSize.Medium).FontSize 

If you use it like this it should work: 
` Font = Font.SystemFontOfSize(NamedSize.Medium),`

![image](https://user-images.githubusercontent.com/1235097/89895338-8e49b900-dbd3-11ea-91e1-fe731fdd2a16.png)

But since Font is deprecated what you want is to use:

`FontSize = Device.GetNamedSize(NamedSize.Small, typeof(Label))`
