### ISSUE TITLE
[Bug] xamarin forms 4.8 Uwp shell excepion on navigation ArgumentException: An item with the same key has already been added. Key: background

### ISSUE THREAD

**Issue by filipoff2** [xamarin/Xamarin.Forms#11768]
After update to "Xamarin.Forms" Version="4.8.0.1269"

Getting other exception on
ArgumentException: An item with the same key has already been added. Key: background

line 71:
rootFrame.Navigate(typeof(MainPage), e.Arguments);
In
https://github.com/filipoff2/MagicGradients/blob/issues/Add-UWP-Playground-Project-45/Playground/Playground.UWP/App.xaml.cs

Result:
On 4.8 App is crashing on start
On 4.5 navigation was not done.

**Comment by filipoff2** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/8498#issuecomment-672929538

**Comment by filipoff2** [comment]
Tomorrow will deliver branch with 4.8

**Comment by PureWeen** [comment]
@filipoff2  i don't think this is a shell bug

I ran your code and the exception is happening here

```C#
            styleList.Add(styleAttributeInstance);
            dictionaryAdd.Invoke(styleProperties, new object[] { name, styleList });
        }
```

in your StyleSheet.cs class

I'm not sure what's all going on in there but if you could break that out into a smaller repro. Maybe this is an issue on your side? I see reflection so maybe it's triggering an unsupported scenario?

For fun I changed "add" to "tryadd" and then it loads

**Comment by mgierlasinski** [comment]
@filipoff2 @PureWeen This is not an issue with Shell but with Magic Gradients and Brushes working together. In Forms 4.8 there was new `background` css property introduced, we use exact same property in Magic Gradients. We are working on fix, registering css properties outside Forms assembly is a reflection pain 😞  As @PureWeen pointed this is registration issue, if there is an existing `background` key, we should modify value instead of adding new entry.

See [Bug report](https://github.com/mgierlasinski/MagicGradients/issues/107) for details.

**Comment by filipoff2** [comment]
Ok well I did update something was working after update not so conclusion was fast.

**Registering css properties outside Forms assembly** should be more formalized in such case.

@PureWeen  @mgierlasinski  is there an new feature request for formalize **Registering css properties outside Forms**?

**Comment by filipoff2** [comment]
ok I'm closing issue.
This one is hobby for me.
For commercial projects: Less 3rd party are nuggets used in xamarin client solution that Is more chance it won't be hit by xamarin update.
