### ISSUE TITLE
[Spec]  Major Breaking Changes Proposed for Xamarin.Forms 5.0

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#11857]
### WHAT??

Xamarin.Forms 5.0 is the last major version of Xamarin.Forms. New major features and development will now be in .NET MAUI and the Xamarin Community Toolkit. We will continue to fix critical and high impact bugs in Xamarin.Forms in regular patch releases.

To ensure that Xamarin.Forms is in a maintainable and stable state, we propose to make the following breaking changes.

### Move MediaElement to Xamarin Community Toolkit

This is currently experimental. As it was a fantastic contribution by the community (thank you, @peterfoot!), we hope that it can continue to be maintained and improved during this transition period in the Xamarin Community Toolkit. 

### Move C# Markup Extensions to Xamarin Community Toolkit

This is another amazing community contribution (thanks @VincentH-Net). As I mentioned [here](https://github.com/xamarin/Xamarin.Forms/pull/11428#issuecomment-676555719), we want this to continue to be worked on and innovated--and right now, the best place for that is in the toolkit! 

### [Move Expander to Xamarin Community Toolkit](https://github.com/xamarin/XamarinCommunityToolkit/issues/214)

Thank you, @AndreiMisiukevich, for contributing this awesome control! We love it, and we want to see it improved. As such, we'd like to see it in the Xamarin Community Toolkit, too.

### Remove support for Visual Studio 2017

We've kept support for Visual Studio 2017 for as long as possible to allow our loyal customers to continue to work in their favorite version of the IDE. However, the world moves on, and sooner or later, it will be necessary to update Visual Studio to take advantage of modern mobile bits, including critical security fixes in the native platforms. Rather than introduce a breaking change later in the maintenance cycle when that point occurs, we'd like to make this change now.

### Cease publishing DataPages, remove from solution

[DataPages](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/datapages/) was released in preview quite some time ago, and we've continued to publish updated packages since. However, it is no longer on our roadmap, so to make the solution leaner, we'll remove it and all associated projects.

### Rename MasterDetailPage

The name MasterDetailPage is not descriptive and does not map to any modern mobile concepts. 

We're open to ideas on what to call this. Current working list:

- SplitPage
- SplitView
- ListDetailPage
- CollectionDetailPage
- ParentDetailPage
- OverviewDetailPage
- HierarchicalView

### Remove UIWebView

iOS apps cannot be published if they reference UIWebView

### Remove XFCorePostProcessor.Tasks

This projects injects IL to maintain XF 2.5 compatibility. We're far enough away from XF 2.5 now that this weaving should no longer be necessary

https://github.com/xamarin/Xamarin.Forms/pull/2880

**Comment by mackayn** [comment]
Never used data pages, few have so makes sense to remove, seems like a pragmatic list. SplitPage or ParentDetailPage gets my votes. Moving the other great contributions into the toolkit means they can evolve faster as 5.0 is the last major release before MAUI hopefully appears sometime.

**Comment by AndreiMisiukevich** [comment]
MasterDetailPage -> DrawerPage (?)

**Comment by grimorde** [comment]
My vote for ParentDetailPage.. although I do like @AndreiMisiukevich 's suggestion of DrawerPage too

**Comment by VincentH-Net** [comment]
## Push C# Markup back out of Forms!?

To all 250+ community members who [voted to integrate the community CSharpForMarkup in Forms](https://github.com/xamarin/Xamarin.Forms/pull/8342), making it the most wanted PR in the history of Xamarin Forms by far:
![image](https://user-images.githubusercontent.com/1872271/90757552-0f910200-e2de-11ea-9c1c-9db210b14424.png)

If you are surprised, worried and/or confused by what seems to be a plan to undo all this (**what!?** indeed) - so am I.

As @davidortinau [mentioned on Twitter](https://twitter.com/davidortinau/status/1291048597308477441), the intention was that @Clancey and I work together during the MAUI design phase to shape an optimal, unified C# Markup for MVVM and MVU - see [the MAUI Spec](https://github.com/dotnet/maui/discussions/119).

I do see serious technical and commitment problems with this move, esp for MAUI.

But before I get into that, as per the invite by @samhouts I am first [discussing this with the team on discord](https://discord.com/channels/732297728826277939/738043671575920700), to understand why they would even want this, and what their intention/commitment is for the future of [C# Markup in Forms and MAUI - for MVU _and_ MVVM](https://github.com/dotnet/maui/discussions/119).

I hope to address any concerns in the team that may have lead to this idea, or possibly propose a less damaging alternative.

After that discussion I intend to update here and involve the community.
In the mean time do chime in and let the team know how you feel about this. Thanks!

**Comment by mattleibow** [comment]
What does the MasterDetailPage actually do on all the platforms? Is it basically a Flyout container?

Maybe Flyout is better as we have been using that word instead of master or split?

**Comment by almirvuk** [comment]
I would also use Flyout term for MasterDetailPage

**Comment by mattleibow** [comment]
What does the MasterDetailPage actually do on all the platforms? Is it basically a Flyout container?

Maybe Flyout is better as we have been using that word instead of master or split?

**Comment by jcmanke** [comment]
May I propose the breaking change of removing the UIWebView renderer for iOS?

**Comment by MagicAndre1981** [comment]
> ### Remove support for Visual Studio 2017

NO, VS2017 is rock stable, VS2019 only has bugs in each new update. DON'T DO THIS!

**Comment by DeerSteak** [comment]
Since the current MasterDetailPage is really just the flyout and the menu, I'd prefer to call it FlyoutPage, or maybe MenuParentPage. 

The timing doesn't bother me. We use a few here and there and changing the inherited class wouldn't be time consuming.

**Comment by johnshardman** [comment]
Overall, seems like a pragmatic approach. However, whilst I understand the plan to rename MasterDetailPage in XF 5, I would be tempted to leave it as is in XF and only do the rename in MAUI.

**Comment by nbevans** [comment]
Is it just me that thinks none of these seem particularly "major breaking"? Probably the rename of MasterDetailPage is the only one and that's a trivial fixup for any codebase. Easier than some "minor breaking changes" in XF history for sure.

**Comment by hartez** [comment]
While we're here, I might as well add some visibility to another breaking change proposal: https://github.com/xamarin/Xamarin.Forms/discussions/11823

**Comment by balbarak** [comment]
MasterDetail -> HierarchyPage

Also, SplitPage looks good

**Comment by MelbourneDeveloper** [comment]
Rule of thumb for any framework: if the feature can be moved up a level and doesn't need to be in the core to work, it shouldn't be there. 

Everything that isn't core XF should be in the community toolkit. We're mostly talking about phones. The less bloat, the better.

**Comment by dotMorten** [comment]
@MelbourneDeveloper Second rule of thumb: If the feature is already there, moving it somewhere else is incredibly disruptive and keeps people from moving to newer versions. Also 3rd party libraries that rely on these would suddenly be broken, so you risk breaking the entire ecosystem. Breaking an ecosystem while XF is drawing closer to it's ultimate demise makes it a tougher sell for 3rd parties to continue supporting it.

**Comment by samhouts** [comment]
@dotMorten Which of those features, if moved, would be disruptive to you? They're all experimental, with the exception of MasterDetailPage.

**Comment by dotMorten** [comment]
I think that's fine for experimental features - when you chose to use those, you took on that risk.

I'm more against the entire notion of even considering introducing breaking changes at this point.

**Comment by knocte** [comment]
I’m going to be playing a bit of devil’s advocate here.

What’s worse? An unexpected regression or an announced breaking-change? The latter is not only warned in the release notes, it's also brought up to you by your compiler before you try to deploy your application! And what causes the former? Too much churn, too much functionality to maintain, new features that break existing features when landing on new versions.

Granted, moving from Xamarin.Forms to Maui may require a bit of overhead by the community already, but that’s an step that you should already take as a necessary evil. If you think this is too much work, then just do a migration to XF5 first, and then postpone the migration to Maui to 2 years later (or more) when/if Xamarin.Forms stops receiving updates. It’s a small price to pay to get a bit more stability.

I, for one, prefer breaking changes that increase stability of newer versions down the line, than no breaking changes and discovering unexpected regressions (or having my users, and not my developers, discover those regressions) when upgrading.

**Comment by KPixel** [comment]
The issue with bugs has already been discussed at length here: https://github.com/dotnet/maui/issues/109
The Xamarin team's response was that they have started focusing on fixing bugs, and that will continue for the next year.

You can see their planning here: https://github.com/xamarin/Xamarin.Forms/projects

**Comment by acuntex** [comment]
@KPixel 
I'll believe it when the team finally starts to fix controls that should work in a stable cross platform library. There are bugs that have an incredible high impact on stability, yet these bugs are open for months or even years.

But this doesn't seem to be their priority, it seems much more important to rename the MasterDetailPage.

**Comment by alexrainman** [comment]
@acuntex thats the reason i stopped using XF and supporting my open source libraries.

**Comment by PureWeen** [comment]
> To ensure that Xamarin.Forms is in a maintainable and stable state, we propose to make the following breaking changes.

The point of these breaking changes is to make maintenance of 5.0 easier so we can address and focus on more critical bugs. 

For example, VS 2017 support has been a major drain on resources in a number of areas across a number of teams. We have to rewrite a bunch of IL so that dlls are backwards compatible and we have a bunch of extra build lanes setup for the specific purpose of testing VS 2017 support. This is also stopping us from adopting C# 8.0

Renaming MDP will probably just be done through inheritance magic and hiding the base type.  The MDP concept is going to change across all of Microsoft. Also, the MDP in XF is fundamentally not an MDP it's a page with a Flyout.

Moving expander, MediaElement, markup, and DataPages out of forms gives us a lot more time to focus on CollectionView, Editor, and fundamental aspects of Forms

**Comment by mattleibow** [comment]
If the MDP is just going to be an inheritance tweak, then I think moving all the experimental feature out into the toolkit is a good idea.

Not only is this a good idea for the ones here now, but also allows the actual control to be iterated faster in the toolkit. Instead of having to wait for forms to release, the toolkit can release when a feature is going well. Also, this will reduce churn and change in parts that are new. We could have had a v1 of media element already if it wasn't in the main repo. In addition to this, once the media element is stable, the merge into forms will be simple and we know it is good to go from day one.

And, if we start moving the old things out now, then we can also keep the forms codebase cleaner. If there is minimal/no usage of data pages, then it probably wouldn't have reached the main repo at all if it wasn't a feature people wanted.

Finally, the VS2017 support is great and all, but that IDE is getting old and the general fixes have been low and no real updates to support the new things of the frameworks. Just looking at .NET Core 3.1, that is not even supported in VS2017. If we want to have better support for new things, then we have to drop off the older IDEs. VS2019 can still build for the same old devices and platforms. Using newer IDEs encourage better/modern code in the framework. And, we can better add things like nullable for all the consumers.

**Comment by acuntex** [comment]
@PureWeen Thanks for this explanation.

Your work bears a lot of responsibility. Individuals and companies and their whole existance rely on a working library. It's like .NET.

I know changes and fixes don't come overnight. But we're at the point of discussing **on a sunday** with the team whether we should drop 6 months of work and start over with react-native because we don't see the commitment of Microsoft. And it breaks my heart because Xamarin is doing so much things the right way compared to other cross platform libraries. (imho)

It's extremely risky to release an App where bugs in basic controls occur, where you can't even workaround the issues and no fix occurs in the library itself. What do you tell the customer/user?

Third party community libraries are sometimes abandoned for years, as @alexrainman stated. The community is dying.

Can we, the developers, get at least one official commitment by Microsoft that

1. Basic controls in Xamarin will be fixed with the highest priority so that they work as currently documented/intended.
2. No more internal classes, more exchangeability and all methods in some classes like Renderers **protected virtual** so we can override them, either because of a non existing feature or so we can react to issues and don't have to wait for official fixes.

The latter would btw. also make it possible for developers to give you code snippets of fixes way faster, without knowing all the inner workings of Xamarin.
I can only speak for myself: Just the thought of cloning the xamarin.forms repository, make it compile, create an App thats using this code base, fix it, test the fix etc. it's probably so time consuming that I wouldn't do it. Not everyone is working at a company so big that you can take a few days to fix bugs in a external library. But fixing it as workaround in a derived Renderer and submitting the code snippet, even if it is just a small hint for the Xamarin team, would probably help everyone.

Thanks!

**Comment by DeerSteak** [comment]
We've had similar discussions, and our Xamarin Forms apps started life in 2017, so there's a boatload of code that would have to be rewritten. I'm currently rewriting my own self-published apps in React Native just to see what it's like. 

Xamarin Forms feels like Windows 10 - new feature after new feature without much regard for getting what was released last time sorted out. We're writing full-on custom renderers, duplicating work that was already done, because we can't just override it. At this point there's double-digit work-years invested in the platform so it's not like starting over is all that attractive, but we need the apps to work and Xamarin control quirks (as outlined previously by several people) cause stumbles.

**Comment by PureWeen** [comment]
> renderers

This is one of the huge shifts with .net MAUI. I realize this doesn't directly help XF 5 but it's very much about collapsing the separation of the renderers and the xplat so if you change into an `Android` context while at xplat you just have full access to the android apis. We're also standardizing all of the property/native mapping access points so that we don't accidentally not provide a hook. I'm curious during this work @samhouts if as we convert properties to "Mapped Properties" in MAUI that we ensure the XF 5 version of that is also `protected virtual` as it should have been anyway.

> Basic controls in Xamarin will be fixed with the highest priority so that they work as currently documented/intended.

This is the plan for XF 5.0 and why we're cutting down to the core components as much as possible

> No more internal classes, more exchangeability and all methods in some classes like Renderers protected virtual so we can override them, 

All methods that map to a Forms property should be overridable which we're focusing on doing better with Maui but I'm wondering here if we can spread that love to XF 5 :-)  The risk here, from an API surface standpoint, is if something is part of the API it's really hard to change anything about it. Everything that becomes part of the API has maintenance burden and has the potential to hamper future development. We don't usually (pretty much never?) have the liberty of semantic versions where major version can make breaking API changes.

> I can only speak for myself: Just the thought of cloning the xamarin.forms repository, make it compile, create an App thats using this code base, fix it, test the fix etc.

This is another area we're focusing on improving. If you look here

https://github.com/Pureween/Xamarin.Forms.Sandbox

I have a very basic project that's compiled against source. I use this for 95 percent of my own development if you ever want to use that to articulate an issue.  It unfortunately doesn't work with VSMac :-/ the story there will hopefully improve as multi targeting stories improve. 

 > we don't see the commitment of Microsoft

Microsoft is moving XF into the `System` namespace because of how committed they are to the future success of .NET MAUI. MAUI very much represents that commitment 

@acuntex @DeerSteak If you want to email me the issues that are your main blocker and/or renderer apis giving you the most headache that would be helpful!! shneuvil at microsoft.com just so we can keep this particular issue on track about how these breaking changes might be show stoppers for people :-)

**Comment by PureWeen** [comment]
> As long as we can build apps that will be accepted by the Apple and Google app stores, we'll let MAUI mature a bit.

Another thing I'd like to highlight. MAUI isn't a "file => new project => MAUI" framework

CollectionView, Editor, Entry, etc... will all fundamentally work the same way in MAUI as they do in XF 5 so it's in our best interest to make XF 5 as solid as possible. The code that makes a LabelRenderer in XF 5 work will be a lot of the same platform level code that's used in MAUI. 

Which is another reason why we're trimming down to the most important bits. In 2 or 3 years will Expander/markup/converters/etc.. all become part of MAUI and not the Xamarin Community Toolkit? Possibly.

But they aren't the best things to focus on right now as we make sure to address this `Basic controls in Xamarin will be fixed with the highest priority so that they work as currently documented/intended.`

**Comment by themronion** [comment]
Voting for SplitPage!

**Comment by YZahringer** [comment]
+1 for `SplitPage` too.

`SplitView` should be used for a control, not for a `Page`. 

Maybe be consistent/inspired with `UWP` [Master/details](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/master-details) & [SplitView](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/split-view)?

**Comment by VincentH-Net** [comment]
## C# Markup, Forms, MAUI, Flutter, UNO
For those interested; I am giving damage control one more shot. In the mean time, just to clarify the stakes:

The whole idea to move C# Markup out, unless a less damaging course can be agreed on, would more than undo what has been won for Forms by including C# Markup in Forms in the first place. That was a big win that took a lot of effort.

The "blessing" of Microsoft is required by many enterprises / devs before they adopt a new approach.
Moving a feature out after it was integrated is even worse than never integrating it. It destroys any built up trust.

-> Enterprises will react: do not adopt C# Markup. Wait for MAUI and then maybe. After a few releases. 2+ years delay?

You are saying: Microsoft does not want to support this
You really cannot send a more clear discouragement than that.

This is why I am putting so much effort into preventing this. It sets the competition with Flutter back 2 or more years.

In the mean time, Flutter grows like crazy and UNO actually has big customers asking if they can add C# Markup!

If this goes south with Forms/MAUI, I seriously consider switching to UNO. They want it - now.

**Comment by mackayn** [comment]
> ## C# Markup, Forms, MAUI, Flutter, UNO
> For those interested; I am giving damage control one more shot. In the mean time, just to clarify the stakes:
> 
> The whole idea to move C# Markup out, unless a less damaging course can be agreed on, would more than undo what has been won for Forms by including C# Markup in Forms in the first place. That was a big win that took a lot of effort.
> 
> The "blessing" of Microsoft is required by many enterprises / devs before they adopt a new approach.
> Moving a feature out after it was integrated is even worse than never integrating it. It destroys any built up trust.
> 
> -> Enterprises will react: do not adopt C# Markup. Wait for MAUI and then maybe. After a few releases. 2+ years delay?
> 
> You are saying: Microsoft does not want to support this
> You really cannot send a more clear discouragement than that.
> 
> This is why I am putting so much effort into preventing this. It sets the competition with Flutter back 2 or more years.
> 
> In the mean time, Flutter grows like crazy and UNO actually has big customers asking if they can add C# Markup!
> 
> If this goes south with Forms/MAUI, I seriously consider switching to UNO. They want it - now.

I thought C# markup was of more appeal to indy devs, not enterprise dev. Just curious as been doing XForms enterprise dev since 2014 and everywhere I been used XAML for UI description and C# for custom controls and other scenarios.

Not saying it's not wanted, just curious. Uno very much promotes XAML usage.

**Comment by VincentH-Net** [comment]
> I thought C# markup was of more appeal to indy devs, not enterprise dev. 
@mackayn nope; enterprises ask for this in the framework (whether UNO or Forms) because they care. Indy devs don't mind using community open source. I have been using and improving C# Markup for the enterprise apps that I build in my day job.

**Comment by VincentH-Net** [comment]
> Uno very much promotes XAML usage.
@mackayn Yes; just like Forms did. At first ... 

Until the Forms team took their cue from Google and Apple who gave the global developer community  something new that devs really liked: MVU + same language logic & markup + hot reload for that.

It proved to be a recipe to win a lot of developers

If you want to keep up with the big players, better innovate fast and don't go back. Or be content with a stagnant user base, of course

**Comment by KSemenenko** [comment]
@mackayn I know many enterprise projects that use templates to build pages.
I mean when the configuration of the page send comes from the server in the settings.
And the solution from @VincentH-Net  controls the creation of such pages at times.

I do not know why we have to feel pain and limitations.
And I also agree that adding another open-source library to the project requires a lot of effort to check for vulnerabilities, bugs and licenses.

**Comment by KSemenenko** [comment]
By the way, about HotReload - I did not use this option at once.
So for me and my company this is the most useless feature.

But the slow CollectionView is a problem and shadows, and shapes. And other basic controls.

**Comment by francoistanguay** [comment]
> > Uno very much promotes XAML usage.
> 
> @mackayn Yes; just like Forms did. 
> 

For clarification, not only did Uno start as C#-first, but today, the XAML is still parsed at compile time to emit C# code behind the scenes.

**Comment by mackayn** [comment]
> By the way, about HotReload - I did not use this option at once.
> So for me and my company this is the most useless feature.
> 
> But the slow CollectionView is a problem and shadows, and shapes. And other basic controls.

Found Hotreload really useful, obviously for code 1st approach it's not. Regarding other issues, the comments from the team above suggest they want to address these stability issues, that includes reducing the core footprint of Forms...but for C# markup, I can totally understand the concern and they must have known the noise this decision would generate and I think the people who pushed for this deserve an official response from the team.

**Comment by VincentH-Net** [comment]
> By the way, about HotReload - I did not use this option at once.
> So for me and my company this is the most useless feature.

@KSemenenko 
Give [LiveSharp](https://www.livesharp.net/) a shot - I am partly to blame that @ionoy built that, but it works great in C# Markup, also does Blazor (and XAML as well) and should also work with any .NET based UI framework.

The C# Hot Restart tooling is not a real alternative; the team did not take their queue from LiveSharp even though it worked better before they started than their own approach works today. I did talk to the MS people involved, both before and during when the team was formed. Can't say I did not try ;-)

**Comment by mackayn** [comment]
> > > Uno very much promotes XAML usage.
> > 
> > 
> > @mackayn Yes; just like Forms did.
> 
> For clarification, not only did Uno start as C#-first, but today, the XAML is still parsed at compile time to emit C# code behind the scenes.

It would be far to slow otherwise, before XamlG came alone (was using Forms back then), anything but basic UI loading was slow.

**Comment by mackayn** [comment]
> > By the way, about HotReload - I did not use this option at once.
> > So for me and my company this is the most useless feature.
> 
> @KSemenenko
> Give [LiveSharp](https://www.livesharp.net/) a shot - I am partly to blame that @ionoy built that, but it works great in C# Markup, also does Blazor (and XAML as well) and should also work with any .NET based UI framework.
> 
> The C# Hot Restart tooling is not a real alternative; the team did not take their queue from LiveSharp even though it worked better before they started than their own approach works today. I did talk to the MS people involved, both before and during when the team was formed. Can't say I did not try ;-)

No doubt Livesharp is the best tool out there for reload scenarios, have a licence as well.

**Comment by prashant-gupta-dev** [comment]
> I am now waiting for the team response on discord, to see if we can come to a commitment (also for me).
> I will update here with the proposal and substantiation why this will work, once we agree and details are OK to publish

Hi @VincentH-Net  - are there any updates here or when do you expect to hear back? 

Thanks! 
Prashant

**Comment by VincentH-Net** [comment]
Hi @prashant-gupta-dev, thx for asking. I will be talking to key people next week; some were are on holiday this week. Will update after that!

**Comment by softlion** [comment]
@VincentH-Net I hope this markup style will be the exception, not the default. Creating markup in code is not maintainable
 and not a good practice. It's good for school projects and small custom controls.
I had a developer 4 years ago who created all its views in code. 2 month after he left, changing anything in his code means rewriting everything in xaml as it was much faster in addition to have a working preview.
Spaghetti code ...

**Comment by ionoy** [comment]
@softlion Can you provide any reasons why markup in code is less maintainable than XAML? It's my understanding that the opposite is true. C# provides a better separation of concerns, expressivity, refactoring tools. Everything you need to write clean and maintainable code. 

I guess XAML can save you from accidentally mixing logic and the UI. But this restrictiveness can also be harmful if you need to create a complex UI interaction.

**Comment by softlion** [comment]
@ionoy  Open a poll and see the results :)

**Comment by Feroks** [comment]
@softlion Have you seen the syntax for C# markup? It is not what WinForms used to be. It has great separation between View and logic stored in ViewModel.

**Comment by VincentH-Net** [comment]
@Feroks wrote:
> @softlion Have you seen the syntax for C# markup? It is not what WinForms used to be. It has great separation between View and logic stored in ViewModel.

FYI I currently have framework quality code and patterns to implement C# Markup like below across Forms / MAUI, even within the limitations of C# 8, with close to zero allocation (no GC pressure) and a fully focused Intellisense experience in each location of the Fluent call chain:

![image](https://user-images.githubusercontent.com/1872271/92227080-04290380-eea6-11ea-859f-3bd83a7083e9.png)
[more info](https://github.com/dotnet/maui/discussions/119#discussioncomment-54250)

This breaking change move triggered me to implement MAUI features now instead of waiting for .NET 5 + C# 9 ga.
Btw this is also applicable to other .NET UI frameworks.

**Comment by VincentH-Net** [comment]
> > I am now waiting for the team response on discord, to see if we can come to a commitment (also for me).
> > I will update here with the proposal and substantiation why this will work, once we agree and details are OK to publish
> 
> Hi @VincentH-Net - are there any updates here or when do you expect to hear back?
> 
> Thanks!

As promised, here I am with a summary and the outcome, which is positive. 

Last Tuesday I had a call with the Forms team. I am quite honored by who attended (most of the Forms team but also e.g. @jamesmontemagno); key in this meeting for me were @davidortinau and @Clancey :-)

I demoed my approach for the final MAUI C# Markup pattern and how a stable subset could be taken from that to include in Forms 5 (since that demo improved even further, now with practically zero extra allocations).

My two concerns were addressed by feedback from @davidortinau and @Clancey:

1. Concern: By moving C# Markup out of Forms to the Xamarin Community Toolkit, adoption of C# Markup in enterprises would not progress until after MAUI is released, because it would not be "blessed" by Microsoft.

This was addressed by the explanation that the Toolkit is just another Microsoft .NET library like many other Xamarin libraries. This was a misunderstanding by me based on the communication here and the GitHub repo name [XamarinCommunityToolkit](https://github.com/xamarin/XamarinCommunityToolkit).

The library is published on NuGet as [Microsoft.Toolkit.Xamarin.Forms](https://www.nuget.org/packages/Microsoft.Toolkit.Xamarin.Forms)

To my question how we could prevent companies making the same wrong assumption I did, David offered to talk internally about updating the [Xamarin Support Policy](https://dotnet.microsoft.com/platform/support/policy/xamarin) to make clear what libraries are included for paid support. Tbc.

2. Concern: how are we going to ensure that [MAUI C# Markup for MVU and MVVM is well aligned](https://github.com/dotnet/maui/discussions/119) if we move the MVVM code out first? Wont we run the risk that they diverge and MVVM C# Markup would have to be bolted on after the fact in MAUI creating unnecessary differences between the two  models?

This was addressed by James, who after my demo said the are already almost completely aligned, with the exception of two elements I use to simulate C# language support for markup: eliminating the `new` keyword and eliminating repeated enum type names in property values. Those two things are under discussion with the C# language team, although outcome tbd and eta unknown at this time. But that makes it understandable that the team prefers not to include those workarounds under the strict new .NET system namespace guidelines, since deprecating them later on if and when C# language support for markup arrives would be frowned upon inside Microsoft.

**Comment by spouliot** [comment]
Please consider removing all references to `UIKit.UIWebView` inside 5.0 - so that even a un-linked XF app can't trigger Apple's warnings (or errors).

c.c. @PureWeen

**Comment by PureWeen** [comment]
@spouliot 

https://github.com/xamarin/Xamarin.Forms/pull/12095

**Comment by lassana** [comment]
> Rename MasterDetailPage

Wouldn't this break other frameworks like MvvmCross? If so, the change is not acceptable.

**Comment by Dmbandit** [comment]
> > By the way, about HotReload - I did not use this option at once.
> > So for me and my company this is the most useless feature.
> > But the slow CollectionView is a problem and shadows, and shapes. And other basic controls.
> 
> Found Hotreload really useful, obviously for code 1st approach it's not. Regarding other issues, the comments from the team above suggest they want to address these stability issues, that includes reducing the core footprint of Forms...but for C# markup, I can totally understand the concern and they must have known the noise this decision would generate and I think the people who pushed for this deserve an official response from the team.

Same, HotReload is amazing and saves a ton of time for me and my team!

**Comment by Tommigun1980** [comment]
> > Rename MasterDetailPage
> 
> Wouldn't this break other frameworks like MvvmCross? If so, the change is not acceptable.

Why yes it did, https://github.com/xamarin/Xamarin.Forms/issues/12224. I had to revert back to Xamarin.Forms 4 as the plugins in my project broke, and I don't fancy sitting with a broken project for a few months until the plugins are updated (if ever).
