### ISSUE TITLE
[Bug] TabBarIsVisible = True/False doesn't work on Back navigation

### ISSUE THREAD

**Issue by jm-parent** [xamarin/Xamarin.Forms#12126]
### Description

I have an App with Shell Navigation.
Page A is the "Tab". 
I navigate to Page B with  await Shell.Current.GoToAsync(RouteNames.WorkOrderDetailPage);
This page have Shell.TabBarIsVisible="False"

TabBar is hiding. :muscle: 

When a tap "back" , Page A doesn't show Bottom Tabs :frowning: Even if i foce Shell.TabBarIsVisible="True" on this ContentPage. 

### Steps to Reproduce

Page A ( a Tab ) with TabbarVisible = true //  Tab is => Visible :white_check_mark:
Nav to Page B with TabbarVisible = false //  Tab is => Hide :white_check_mark:

And now 2 things , if you :

Nav Back to Page A TabbarVisible = true //  Tab is => Still hide :no_entry_sign: 
or
Nav to Page C : TabbarVisible = true //  Tab is => Visible  :white_check_mark: but :thinking:

### Expected Behavior

TabBar is visible when TabBarIsVisible = True 👍 

### Actual Behavior

TabBar is not visible even if TabBarIsVisible = True 🙅 

### Basic Information

I'm currently using XF 4.8.0.1364.

### Screenshots

Page A : Tab with TabbarVisible = true 
Page C : Common ContentPage with TabbarVisible = false
Page A : Common ContentPage Tab with TabbarVisible = true 

https://streamable.com/0nkdb5
In this video you can see :
Page A => Page B => Page C => Page B => Page A
Tab : visible => not visible => visible ✅ => visible 🙅 => visible ✅ 
Page A => Page B => Page A 
Tab : visible => not visible => not visible 🙅

**Comment by josephlbailey** [comment]
Can confirm this issue persists in 4.8.0.1451

**Comment by jm-parent** [comment]
🤔It seems SharedTransitionShell was the mistake.

I replace it by Shell , and TabBar show and hide correctly .

@josephlbailey did you use SharedTransition too ? 

![20-09-29-10-23-06](https://user-images.githubusercontent.com/39386863/94532667-75a66880-023e-11eb-893c-597f603bb0d4.gif)

**Comment by josephlbailey** [comment]
@jm-parent I believe mine is related to #8969 or #12144 as it is an issue only on iOS.

**Comment by Cr15Denis** [comment]
That's right, friend, when they break a bug, provide a video or gif of the problem so the engineering team can solve it as soon as possible.
![TabbarProblem](https://user-images.githubusercontent.com/70722700/94713168-b0c09e80-0307-11eb-80cd-0b4d3fd449be.gif)

**Comment by PureWeen** [comment]
Hmm so this is an odd one :-/ 

Similar issue here
https://github.com/xamarin/Xamarin.Forms/issues/12144

For some reason these exports are no longer executing....

https://github.com/xamarin/Xamarin.Forms/blob/f35ae07a0a8471d255f7a1ebdd51499e10e0a4cb/Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs#L80

It's annoying because they execute fine when I'm building against source but not from the nuget package...

Haven't traced back to why those have stopped executing yet

**Comment by PureWeen** [comment]
I've only seen one repro so far so that's what I've been able to fix :-) 

I'm that's everyones issue.

There's a nuget here
https://dev.azure.com/xamarin/public/_build/results?buildId=27801&view=artifacts&type=publishedArtifacts

If you can all test that nuget and let me know if that resolves the issue for you that would be great!!! If it doesn't can you try to include a repro?

**Comment by josephlbailey** [comment]
@PureWeen So I tested the new nuget with no luck. 

So here's a repro using the standard boilerplate project that is created when doing a new Shell app: 
[TabBarVisibilityRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/5313280/TabBarVisibilityRepro.zip)



 I used the LoginPage as my third level of navigation to illustrate that when using `Shell.GoToAsync("../")` on a page with `Shell.TabBarIsVisible="False"`, it breaks the visibility on the previous page as illustrated here: 

![tabbarvisiblilitybugrepro](https://user-images.githubusercontent.com/46647444/94832041-6f99be80-03db-11eb-8eb1-a10aaab3073f.gif)

**Comment by PureWeen** [comment]
Thank you @josephlbailey !! 

That helped me locate what looks to be the most problematic part of code.

New set of nugets here brewing
https://dev.azure.com/xamarin/public/_build/results?buildId=27842

Let me know if that works for you
