### ISSUE TITLE
IMarkupExtension no longer compile since version 4.8

### ISSUE THREAD

**Issue by michelevirgilio** [xamarin/Xamarin.Forms#12393]
### Description
I've this `IMarkupExtension` class:

```cs   
public class DefineConditionalXamlExtension : IMarkupExtension
    {
        public object Ob1 { get; set; }
        public object Ob2 { get; set; }
        public object ProvideValue(IServiceProvider serviceProvider)
        {
#if OB1
            return Ob1;
#elif OB2
            return Ob2;
#else
            return null;
#endif
        }
}
```
XAML (for example inside a StackLayout, or inside App.xaml):
```xml
      <ext:DefineConditionalXaml> 
        <ext:DefineConditionalXaml.Ob1>
          <!-- something -->
        </ext:DefineConditionalXaml.Ob1>
        <ext:DefineConditionalXaml.Ob2>
          <!-- something -->
        </ext:DefineConditionalXaml.Ob2>
      </ext:DefineConditionalXaml>
```
and it has compiled perfectly until Xamarin.Forms 4.7.0.1351.
After upgrade to XF 4.8.x i get this compile error:

Error	XFC0009	No property, BindableProperty, or event found for "xxxx", or mismatching type between value and property.	

### Expected Behavior
Compile

### Actual Behavior
Won't compile

### Basic Information

- Version with issue: 4.8.x
- Last known good version: 4.7.0.1351
- IDE: VS 2019
- Platform Target Frameworks: 
  - Android: 9.0

**Comment by jsuarezruiz** [comment]
I have created a sample and tried to reproduce the issue without success.
[Issue12393.zip](https://github.com/xamarin/Xamarin.Forms/files/5340127/Issue12393.zip)

@michelevirgilio Could you attach a sample where reproduce the issue?.

**Comment by michelevirgilio** [comment]
I've updated your sample with my actual code, and the problem is the same: until XF 4.7 everything works fine, when i upgrade to 4.8.0.x does not compile anymore. Thanks
[Issue12393.zip](https://github.com/xamarin/Xamarin.Forms/files/5345803/Issue12393.zip)

**Comment by StephaneDelcroix** [comment]
your markup extension returns an `object`, and you're adding to a collection of `Views, hence the message. We changed the checks to catch more potentials errors at compilation time (like this one) vs crashes at runtime in 4.8

the solution for you is to be clear on what your markup extension returns, and implements `IMarkupExtension<View>` instead of `IMarkupExtension`

as a side note, what looks like a nice trick is actually a major performance hit. all the Xaml, from all the conditional branches, is compiled and inflated, then discarded. you're better off having multiple xaml files and switch them at compile time with some msbuild directives

**Comment by michelevirgilio** [comment]
Thank you StephaneDelcroix for your info. And for the side note too.
You suggest to use multiple xaml files to be switched at compile time.
So if i have, for example, a big xaml, with just a few, little parts to be conditional, do i need to duplicate the entire xaml (multiple times), then having worst maintenance, or can i use another pattern?
Thanks
