### ISSUE TITLE
[Bug] RefreshView vs. ListView: Command invoked when setting IsRefreshing property

### ISSUE THREAD

**Issue by PieterjanDeClippel** [xamarin/Xamarin.Forms#12506]
### Description
There seems to be a difference in behavior between the `ListView` and `RefreshView`.

### Steps to Reproduce

1. `git clone https://github.com/PieterjanDeClippel/XamarinForms.RefreshViewVSListView`
2. Run the project
3. Go to the ListViewPage
    1. On navigating to the ListViewPage, the `Appearing` hook invokes the `RefreshCommand` manually
    2. `IsLoading = false`
    3. This sets the `IsLoading` property to `true`, **in order to activate the loading spinner**.
4. Pull-refresh the View.
    1. The ListView sets the `IsLoading` property internally, and invokes the command-handler
    2. Inside the command handler the `IsLoading` property is set to `true` once again.
    3. The method is **not** being invoked again
5. Go to the RefresViewPage
    1. On navigating to the RefresViewPage, the  `Appearing` hook invokes the `RefreshCommand` manually
    2. `IsLoading = false`
    3. This sets the `IsLoading` property to `true`, **in order to activate the loading spinner**.
    4. Setting the `IsLoading` binding once again invokes the Command, and the OnRefresh method is being called again.

### Expected Behavior

The behavior for `RefreshView` should be the same as the `ListView`.

### Basic Information

- Version with issue: 4.8.0.1560
- IDE: VS 16.7.6
- Platform Target Frameworks:
  - Android: 9.0
- Affected Devices: Virtual Pixel 2 Pie 9.0 - API 28

### Reproduction Link

https://github.com/PieterjanDeClippel/XamarinForms.RefreshViewVSListView

### Workaround

Setting the `IsLoading` property, instead of invoking the Command

**Comment by rachelkang** [comment]
Hi, @PieterjanDeClippel - thanks for submitting this issue!

In your code, you're executing the `RefreshCommand` yourself:
```
private void RefreshViewPage_Appearing(object sender, EventArgs e)
{
     viewModel.RefreshCommand.Execute(null);
}
```
There's no way for RefreshView to know that you're doing this, and so you have to communicate that by changing the code in this `RefreshViewPage_Appearing` method to `viewModel.IsLoading = true` in order to trigger the actual refresh.

The RefreshView API can be confusing, and it took a while for me to fully understand it myself; [here are our docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/refreshview) on RefreshView and [here's a related conversation](https://github.com/xamarin/Xamarin.Forms/issues/11470) you can take a look at if you wish to understand a bit more about why it is this way

If you have any more questions about this or if I misunderstood something, just let us know! :)

**Comment by PieterjanDeClippel** [comment]
Hi,

I just thought it's a little weird that the ListView can deal with this case.

But anyhow, is setting the `IsRefreshing` binding the recommended approach to trigger a reload of the `RefreshView`, instead of invoking the command?

**Comment by rachelkang** [comment]
@PieterjanDeClippel it can definitely seem weird! But since ListView and RefreshView are two different controls, they're backed by different APIs that dictate these things differently.

and yes, so `IsRefreshing` is what (1) triggers the refresh visualization, and (2) puts the control in the "Refreshing" state and executes the command. So when you invoke the command separately, none of the other things happen automatically. Hope that makes sense!

**Comment by PieterjanDeClippel** [comment]
Yup. It's clear now
