### ISSUE TITLE
[Bug] UWP - FontIcons not showing in Latest Xamarin Form release

### ISSUE THREAD

**Issue by KarthikRaja26** [xamarin/Xamarin.Forms#12635]
### Description

FontIcons not showing in Latest Xamarin Forms Release in UWP platform

### Steps to Reproduce

1. Run the attached sample
2. Note the icon is not rendering properly and it's like a rectangle shape.

### Expected Behavior

Font Icons should show.

### Actual Behavior

Font Icons showing like a rectangle and broken

### Basic Information

- Version with issue: 4.8.0.1560
- Last known good version: 4.8.0.1269
- IDE: Visual Studio 2019

### Screenshots

![image](https://user-images.githubusercontent.com/46777511/97415263-ff734f80-192a-11eb-936f-e0a93d333e97.png)

### Reproduction Link

[SfChat.zip](https://github.com/xamarin/Xamarin.Forms/files/5450780/SfChat.zip)

### Workaround
No

**Comment by KarthikRaja26** [comment]
Hi @samhouts , 

Any update on this?

**Comment by MagicAndre1981** [comment]
> Hi @samhouts ,
> 
> Any update on this?

The issue is fixed in code. Browser to https://github.com/xamarin/Xamarin.Forms/tree/4.8.0, click on the green checkmark

![image](https://user-images.githubusercontent.com/8274816/98656818-65a39d80-2341-11eb-955a-97f25e9a8ab5.png)

click on details in the xamarin.forms-ci entry, now click on artifacts:

![image](https://user-images.githubusercontent.com/8274816/98657029-b3b8a100-2341-11eb-9f0b-283e2d6f3bd2.png)

and here on nuget->download artifact

![image](https://user-images.githubusercontent.com/8274816/98657208-e5316c80-2341-11eb-8161-a5461c9c3688.png)

Extract the zip and this local path to nuget, and in the VS package UI in VS, select the local folder and update the Xamarin.Forms packages.

When official 4.8 SR5 is out, update to latest official version.

I had the same with [SfDataPager](https://help.syncfusion.com/xamarin/datagrid/paging#normal-paging) not showing the First/Last entry with official versions, but this is now fixed

![image](https://user-images.githubusercontent.com/8274816/98657599-540ec580-2342-11eb-847f-5226fda1c122.png)

**Comment by KarthikRaja26** [comment]
Hi @samhouts ,

Can you please tell the issue fixed or not in the latest version ?

**Comment by MagicAndre1981** [comment]
> Can you please tell the issue fixed or not in the latest version ?

it is fixed in latest SR5.

You can compare the tags and see this is included:

https://github.com/xamarin/Xamarin.Forms/compare/release-4.8.0-sr4...release-4.8.0-sr5s
