### ISSUE TITLE
[Enhancement] Add events related to Shell Flyout status being changed OnFlyoutOpened OnFlyoutClosed

### ISSUE THREAD

**Issue by Cfun1** [xamarin/Xamarin.Forms#12682]
## Summary
In order to execute some code upon Flyout being opened/closed, an event which is triggered once the Flyout is opened/closed and could be helpful.

## API Changes
```
Shell.OnFlyoutOpened="Flyout_Opened"
Shell.OnFlyoutClosed="Flyout_Closed"
```

**Comment by PureWeen** [comment]
@Cfun1 there's a property on shell "FlyoutIsPresented"  that you can watch for

https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.shell.flyoutispresented?view=xamarin-forms

So, I'd subscribe to PropertyChanged events on Shell and then change with that property changes

**Comment by Cfun1** [comment]
@PureWeen 
```
public static readonly BindableProperty FlyoutIsPresentedProperty =
			BindableProperty.Create(nameof(FlyoutIsPresented), typeof(bool), typeof(Shell), false, BindingMode.TwoWay);
```
I don't know how to listen to an inherited `BindableProperty` which is not exposing a `propertyChanged ` delegate?
Isn't an overkill to listen to changes on my whole class ?

**Comment by PureWeen** [comment]
@Cfun1 you just have to subscribe to property changes on shell

> Isn't an overkill to listen to changes on my whole class ?

No, all of these property changed events already get fired. It wouldn't make sense for us to add a specific event for every single Bindable Property that exists on a control. It's more performant overall to just have one otherwise users would have to subscribe to multiple events (which would be slower)
