### ISSUE TITLE
[Bug][Android] Problem while navigating between pages after httpclient.PostAsync(...)

### ISSUE THREAD

**Issue by feduss** [xamarin/Xamarin.Forms#12739]
### Description
I have a page (DocumentList ) with a list of document (folders) and, when i click in one of them, i open a new page (DocumentEditor), in which i have a button to add some photos (file into the document folder) and another one to send them to an url. 
So, the execution flow is the follow:

DocumentList -> DocumentEditor -> AddPhotos

In DocumentEditor i have, as said before, the possibility to send the document (and related photos) to an url through a client.postAsync(String Url, MultipartFormDataContent). I haven't any problem during this operation, but only when i press the back button in the navigation bar or if i execute a Navigation.PopAsync/PopToRootAsync.

I can come back in the prev page (DocumentList), but the title is cutted and, if i want to select another document, it opens a black DocumentEditor Page.

If i don't send the document, i haven't any problem with back button, so, it's definitely a problem with client.postAsync.

This bug is only on Android. Everything is working well on IOS.

### Steps to Reproduce

1. From the mainpage, open a new page with Navigation.PushAsync
2. Do an httpClient.PostAsync()
3. Do a Navigation.PopAsync()

### Expected Behavior
A normal working page

### Actual Behavior
Bugged page

### Basic Information

- Version with issue: i've tested from 4.8.0.1451 to 4.8.0.1560
- Last known good version: idk
- IDE: vs 2019
- Platform Target Frameworks:
  - iOS:  n/a
  - Android: 10 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
DocumentList before postAsync:
https://i.stack.imgur.com/ipkgH.jpg

DocumentEditor before postAsync:
https://i.stack.imgur.com/SeAT2.jpg

DocumentList after postAsync and back button pressed (notice the title):
https://i.stack.imgur.com/aBmV7.jpg

DocumentEditor after selected a document in prev image: 
https://i.stack.imgur.com/HlpTx.jpg

**Comment by rmarinho** [comment]
Hello @fedus, this seems a complicated issue and we really need a reproduction to understand what's going on.  Can you please upload a small sample ?

Thanks

**Comment by feduss** [comment]
Hi @rmarinho , sorry for the delay...

here's the sample...ios project is not implemented (or it's partially implemented because i've used shared codes) because i didn't have the bug there:

[https://github.com/feduss/SampleProblem12739_](url)

**Comment by feduss** [comment]
There's some kind of problem with the url. Copy and paste manually:

https://github.com/feduss/SampleProblem12739_

**Comment by feduss** [comment]
Any news? :)

**Comment by feduss** [comment]
Nobody? have you succeeded to verify my bug?

**Comment by jsuarezruiz** [comment]
Can reproduce the issue but I'm going to review everything in more detail to understand what happens.

**Comment by feduss** [comment]
@jsuarezruiz Great! Let me know, even if i can help with testing :)

**Comment by feduss** [comment]
Hi @jsuarezruiz , have you found the reason of this bug?

**Comment by feduss** [comment]
Hi! Any news???

**Comment by feduss** [comment]
???

**Comment by feduss** [comment]
Well...any valid workaround?

**Comment by feduss** [comment]
@rmarinho any possible workaround? The bug is still here after almost 5 months

**Comment by mattleibow** [comment]
I managed to find the error. It is a combination of things that together broke UI.

In short, it is because UI updates are being done on a background thread, and then all exceptions being swallowed.

First part is this line: https://github.com/feduss/SampleProblem12739_/blob/main/SampleProblem12739/ProgressableStreamContent.cs#L24
You are passing in a new Task, but not awaiting it. If you change it to `Func<long, long, Task>`, then you can await in the progress loop.

However, once you do that you see the hidden error: https://github.com/feduss/SampleProblem12739_/blob/main/SampleProblem12739/DocumentEditor.xaml.cs#L81
It is basically something that is not supported because all UI updates _must_ be done on the UI thread. Replace that `Task.Run` with `Dispatcher.BeginInvokeOnMainThread`. Once you do this, you no longer need to await in the loop either and can go back to `Action<long, long>` that I mentioned above. (It was more to demonstrate the real error.)

Finally, once you are back on the UI thread and the code is actually running, you see a third exception: A null ref on `ProgressBar`: https://github.com/feduss/SampleProblem12739_/blob/main/SampleProblem12739/DocumentEditor.xaml.cs#L83
This is because the find code is using the wrong name: https://github.com/feduss/SampleProblem12739_/blob/main/SampleProblem12739/DocumentEditor.xaml.cs#L34 But in the XAML, it is `ProgressBar2_`

**Comment by feduss** [comment]
@mattleibow you are a life saver! In my real code, i don't have the line 24 because i'm handling the progress with a different class, but the other two errors (Task.Run e ProgressBar reference) yes! So, at the end, it was my mistake, sorry for the caos generated by this post :P. Thanks all, issue fixed!

**Comment by mattleibow** [comment]
No prob at all. Glad you could get it fixed and move on!
