### ISSUE TITLE
Whether it will appear .NET 5 in Xamarin Forms?

### ISSUE THREAD

**Issue by TopSkillDeveloper** [xamarin/Xamarin.Forms#12854]
It is known that Xamarin will be converted to Maui with .Net 6 in November 2021. What is the situation with Net-5? Will it appear in Xamarin forms, or will it immediately switch from standard 2.1 to volume 6? Sorry for the bad English

**Comment by acuntex** [comment]
.NET 5 is the successor of .NET Core.

Since Xamarin.Forms runs on Mono, i doubt it will run with .NET 5.0.

As far as I understood correctly, .NET 6 will be be the "One .NET Framework" that will ultimately succeed the existing frameworks completely. (Previously this was planned for .NET 5 but was changed to .NET 6.)

**Comment by jsuarezruiz** [comment]
.NET MAUI will target .NET 6. Why?
- Continue shipping Xamarin.Forms at the current cadence of every 6 weeks.
- Continue shipping Android and iOS SDK updates in a timely fashion (imagine shipping iOS 14 for 2 different versions of .NET, double the work, yikes!).
- Allow the .NET/Mono engineering teams the time and focus to enable AOT, linker, crypto, and other very necessary things for mobile platforms.
- Allow the Xamarin teams to focus on the vNext work that promises to have huge impact, specifically in the architecture of the renderers (yes, existing apps will continue to work).
