### ISSUE TITLE
[Bug] Label TextTransform settings ignored if LineHeight is set

### ISSUE THREAD

**Issue by jacoch** [xamarin/Xamarin.Forms#12887]
### Description
On a label, if LineHeight is set to a value different than -1, TextTransform value is ignored.

### Steps to Reproduce
1. Create a label with for example TextTransform set to Uppercase.
2. Test the app. Label should be displayed in upper case.
3. Now add property LineHeight and set it to 2 for example.
4. Run app again. Label is not in upper case anymore.

### Expected Behavior
TextTransform should be applied even if LineHeight is set.

### Actual Behavior
TextTransform is ignored.

### Basic Information

- Version with issue: Xamarin.Forms 4.8.0.1687
- Last known good version: None
- Affected Devices: All

**Comment by jsuarezruiz** [comment]
@jacoch On what platform does it happen? All, Android, iOS, etc?

**Comment by jacoch** [comment]
@jsuarezruiz Sorry. Didn't mention. The problem above only appears on iOS. On Android, as LineHeight seems to be ignored (at least on the versions I tried), the problem does not occur.

**Comment by cabal95** [comment]
I believe the issue is right here:

https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs#L443

This should be applying the standard text transforms in this case. From what I could tell Android at least does handle this correctly when I was looking into this on our application.

I can submit a PR to fix this on iOS. Is there anything I need to do to "claim" this issue or should I just submit a PR and reference this issue?
