### ISSUE TITLE
Allow specification of accessibility order

### ISSUE THREAD

**Issue by johnshardman** [xamarin/Xamarin.Forms#13006]
## Summary
A mechanism is required to allow the accessibility order of controls on a page to be specified. Assuming that TabIndex provides the correct sequence is over-simplistic and prevents some inaccessible apps being made accessible without pages being re-designed.

## API Changes
At the very least, I suggest adding a method such as the following to ContentPage:
public void SetAccessibilityReadingOrder(VisualElement[] xfVisualElements)

That is likely to want to make use of a more generic static helper, that may be in another class:
public static void SetAccessibilityReadingOrder(VisualElement xfContainingElement, VisualElement[] xfVisualElements)

As part of doing this, or as a stop-gap so that people can implement accessibility order themselves whilst waiting for the full solution to be implemented, make GetAccessibilityElements() in PageRenderer (on iOS) virtual, so that it can be overridden in a custom page renderer.

I see the API being used as follows:

            View[] accessibilityOrder =
            {
                explanationLabel,
                entry,
                entryValidationLabel,
                workingDaysSlider,
                workingHoursSlider,
                productivitySlider,
                resultsExplanatoryTextLabel,
                resultsValueEntryView
            };

            page.SetAccessibilityReadingOrder(accessibilityOrder);

## Intended Use Case
This is required for those cases where TabIndex does not provide the same sequence of controls as is required when using accessibility options (which is often the case).

**Comment by johnshardman** [comment]
Similarly, on Android, a stepping stone would be to make 
void IOrderedTraversalController.UpdateTraversalOrder()
in PageRenderer virtual so that its behavior can be overridden.

**Comment by rachelkang** [comment]
Hi, @johnshardman - thank you for your feedback.

We've since introduced [SemanticOrderView](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/samples/XCT.Sample/Pages/Views/SemanticOrderViewPage.xaml.cs) in XamarinCommunityToolkit. If you aren't familiar with it, you can learn more about it [from this blog post](https://devblogs.microsoft.com/xamarin/the-journey-to-accessible-apps-meaningful-content-ordering/#semantic-order-view). We're open to hearing any feedback you have and hope you find this API helpful!
