### ISSUE TITLE
[Bug] ResourceDictionary.Source does not include assembly name

### ISSUE THREAD

**Issue by etvorun** [xamarin/Xamarin.Forms#13187]
### Steps to Reproduce

1.  Open attached solution in VS 2019
[XamarinApp9.zip](https://github.com/xamarin/Xamarin.Forms/files/5712375/XamarinApp9.zip).
2. Set Debug x86.
3. Build and Run.
4. Click on Click Me button

### Actual Behavior
Appears text "ResourceDictionary.Source is 'CustomRD.xaml'"

### Expected Behavior
ResourceDictionary.Source is 'fx://XamarinApp9/CustomRD.xaml' or similar. With assembly name.

**Comment by BretJohnson** [comment]
This is needed to fix: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1259031

**Comment by StephaneDelcroix** [comment]
(related #2660)

**Comment by BretJohnson** [comment]
We're still seeing Source with the old value here, `CustomRD.xaml`, not including the assembly name.
Interestingly, it seems like there are two issues here currently with Resources.Source is SR2:
1. Sometimes Source includes the assembly name, but it's in a format we don't expect. We expected the "XF mutation" format below, but it's currently in the "XF RD.Source" format below. One of both of us will have to update our code. We'll discuss tomorrow (Wednesday) in our XET tactics call.
```
WPF:  pack://application:,,,/MyApp;component/foo.xaml
XF mutation:  xf://MyApp/foo.xaml
XF RD.Source: rd.xaml;assembly=MyXFLib
```

2. Sometimes Source (like for this project) doesn't include the assembly name. It's still just `CustomRD.xaml`. We're not quite sure why Source includes the assembly sometimes but not others, but that's the current case.

This bug will continue to track both issues, which hopefully we can get fixed in SR3.

**Comment by etvorun** [comment]
We need some docs on RD.Source URI. One aspect which is still not clear from Brett's example is meaning of relative path, e.g. "rd.xaml" in "rd.xaml;assembly=MyXFLib". Is it relative to owner document? Or is it relative to package/project root. Hot Reload needs project relative root.

**Comment by StephaneDelcroix** [comment]
@etvorun source Uris are relative to the object loading the resource

**Comment by StephaneDelcroix** [comment]
@BretJohnson we don't, and won't, do pack Uris. To specify assembly, we use the same attributes as, e.g., xmlns, or XamlSourceInfo

**Comment by StephaneDelcroix** [comment]
![image](https://user-images.githubusercontent.com/313003/106764588-36e34d80-6638-11eb-9942-7f40522ed380.png)

**Comment by etvorun** [comment]
![image](https://user-images.githubusercontent.com/48451158/106765675-e941f300-65ed-11eb-85b8-209d56b12d73.png)

**Comment by StephaneDelcroix** [comment]
@etvorun what are you trying to say here ? that there's a mismatch between the assembly version, and the version actually loaded ? are you _sure_ you updated the Nuget in BOTH projects, you cleaned and eventually restarted the IDE ?
