### ISSUE TITLE
Question: NuGet packages for service releases

### ISSUE THREAD

**Issue by agouriou** [xamarin/Xamarin.Forms#1318]
Hi,
From this page https://github.com/xamarin/Xamarin.Forms/releases I can see several service releases, eg 2.4.0-sr6, 2.5.0-sr1, 2.5.0-sr2....

No NuGet is available for those service release. Could you explain why please?

Thanks

**Comment by davidortinau** [comment]
Those service releases are available on GitHub. The version numbers match up.

2.5.0-SR1 is 2.5.0.91635
2.5.0-SR2 is 2.5.0.121934
2.4.0-SR6 is 2.4.0.91020

However, not everything we build is promised to end up on NuGet. Sometimes they are web previews or hotfixes. When we publish to NuGet it triggers all the IDEs to update packages, and in some cases we don't want that to happen.

**Comment by agouriou** [comment]
Thanks for the explanation 👍

**Comment by mattclarkie** [comment]
@davidortinau Why are the release notes for SR2 and SR3 missing from the release notes page? Only shows SR1... https://developer.xamarin.com/releases/xamarin-forms/xamarin-forms-2.5/

**Comment by jalbertSyncroTech** [comment]
Can you document on the github releases page whether or not a package is planned on being published to NuGet?

I've had our team waiting to upgrade because of a blocking bug that's been fixed in 2.5.0.122203.  Had I known it wasn't going to ever go to NuGet I would have published it to our local feed.
