### ISSUE TITLE
[Bug] Shell Navigation URI encoding issue

### ISSUE THREAD

**Issue by AmSmart** [xamarin/Xamarin.Forms#13266]
### Description
The **+** (Plus) sign gets truncated from my query property string during shell navigation
### Steps to Reproduce

```
string phoneNo = "+2222222222";
await Shell.Current.GoToAsync($"{nameof(VerifyPage)}?phoneNumber={Uri.EscapeDataString(phoneNo)});
```

Inside VerifyViewModel

```
public string PhoneNumer
{
    get => _phoneNumber;
    set => _phoneNumer = Uri.UnescapeDataString(value);
}
```

### Expected Behavior
PhoneNumber is supposed to be set to "+2222222222" because 'value' in setter should be "%2B2222222222"
### Actual Behavior
Instead, PhoneNumber is set to "2222222222" and 'value' in setter is "2222222222"

**(NB: EDIT)**
The behaviour is actually: PhoneNumber is set to "2222222222" and 'value' in setter is " 2222222222" 
### Basic Information
This is some issue with the URI encoding automatically done by Shell while navigating with query properties

### Reproduction Link

I don't think this is needed

### Workaround
This issue can be avoided by first manually encoding the URI (phone number in my case) before passing it as a query property. This can be easily achieved with the HttpUtility or Uri class. Nevertheless, the inconsistency is infuriating.

**Comment by hartez** [comment]
> ### Reproduction Link
> I don't think this is needed

It's very much needed, because I can't reproduce the behavior you're describing.

I'm attaching my repro attempt, maybe you can tell me what I'm missing. In my repro, the "Test Querystring" button on the About page passes the parameter "+1234567890" twice - once with no escaping, and once with Uri.EscapeDataString(). On the other end (the ItemsViewModel class), the escaped version is unescaped using Uri.UnescapeDataString(); the raw version is left as-is. Both versions come across intact - you can see them in the console output.

Is there a step or detail I'm missing?

**Comment by hartez** [comment]
[_13266 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/5765719/_13266.Repro.zip)

**Comment by AmSmart** [comment]
> [_13266 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/5765719/_13266.Repro.zip)

So I downloaded this and it worked well and fine.

Well, it did until I upgraded to the latest stable version of Xamarin.Forms (5.0.0.1874) which is what I'm working with. Looks like we have a regression.

**Comment by PureWeen** [comment]
So, @AmSmart the "+" character is an unfortunate casualty of how UriDecode/Encode works.  Usually this all works fine but unfortunately "UriDecode" replaces all "+"'s with a space.

With 5.0 we made it so query strings automatically get decoded once they reach the destination so if you encode the phone number first then it'll come out correctly on the other end.

**Comment by PureWeen** [comment]
@AmSmart can you elaborate on this?

> Nevertheless, the inconsistency is infuriating.

If you encode the query string on the uri then it will come out decoded on the other side so you don't have to do any decoding in your VMs that receive the parameters

**Comment by AmSmart** [comment]
> So, @AmSmart the "+" character is an unfortunate casualty of how UriDecode/Encode works. Usually this all works fine but unfortunately "UriDecode" replaces all "+"'s with a space.
> 
> With 5.0 we made it so query strings automatically get decoded once they reach the destination so if you encode the phone number first then it'll come out correctly on the other end.



> @AmSmart can you elaborate on this?
> 
> > Nevertheless, the inconsistency is infuriating.
> 
> If you encode the query string on the uri then it will come out decoded on the other side so you don't have to do any decoding in your VMs that receive the parameters.
> 
> Shell doesn't automatically encode your parameters it'll just automatically decode it if it's a string

@PureWeen 

This is clearer to me now! I believed ``Shell`` automatically encoded URI strings and that caused the confusion. Perhaps you could also clarify me with why this same process yielded correct results worked in the earlier versions.

Also, wouldn't it be better if ``Shell`` did both encoding and decoding and we never have to worry about it? This could potentially prevent bugs in a case where the query property depends on some ``string`` input from the user.

**Comment by PureWeen** [comment]
> This is clearer to me now! I believed Shell automatically encoded URI strings and that caused the confusion. Perhaps you could also clarify me with why this same process yielded correct results worked in the earlier versions.

We only started automatically decoded strings in XF 5.0
Unfortunately the '+' symbol is kind of a unique case. So, prior to 5.0 the data would just come through unscathed

> Also, wouldn't it be better if Shell did both encoding and decoding and we never have to worry about it? This could potentially prevent bugs in a case where the query property depends on some string input from the user.

It's not really possible to accurately encode the parameters. What happens if the data has an "&" as part of the data? if we auto encoded then we would interpret that "&" as a separate piece of data

> Edit: Turns out that my assumption that Shell encoded wasn't self-originated. I probably read it from MS Docs here. Kindly clarify on which is false

The docs should now be updated to reflect proper behavior

**Comment by AmSmart** [comment]
Stumbled on this again and I realised I didn't say "Thanks" for the help. Better late than never.

**Comment by acaliaro** [comment]
I have the same problem with a json object like this


This is the Query

%7B%22id%22:%22f97de73a-e8dc-4c0d-a7fa-334c35253a13%22,%22idNegozio%22:%22d380779a-15e9-4dc9-81be-760dc01b02ee%22,%22dataCreazione%22:%222022-07-19T14:47:02.9553826+02:00%22,%22idCliente%22:%22169922f4-79b5-4971-af4c-627470366718%22,%22numeroTessera%22:%2229995451844362773467%22,%22articoli%22:[],%22pagamenti%22:[],%22numeroArticoli%22:0,%22prezzoTotale%22:0.0%7D

this is the result with HttpUtility.UrlDecode

{"id":"f97de73a-e8dc-4c0d-a7fa-334c35253a13","idNegozio":"d380779a-15e9-4dc9-81be-760dc01b02ee","dataCreazione":"2022-07-19T14:47:02.9553826 02:00","idCliente":"169922f4-79b5-4971-af4c-627470366718","numeroTessera":"29995451844362773467","articoli":[],"pagamenti":[],"numeroArticoli":0,"prezzoTotale":0.0}

in "dataCreazione" the "+" is lost.

@PureWeen do you have a solution / workatround for this?

**Comment by acaliaro** [comment]
> 

you are right

**Comment by AndyDentFree** [comment]
>If you encode the query string on the uri then it will come out decoded on the other side so you don't have to do any decoding in your VMs that receive the parameters.

This is unclear because it fails to adequately specify circumstances.

The linked [help on passing data](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation#pass-data) lists **two** techniques.

### Approach One - using QueryPropertyAttribute
The [example for using QueryPropertyAttribute](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation#process-navigation-data-using-query-property-attributes) shows a property setter being called without a need to decode.

### Approach Two - using a "Single Method"
The [single method approach](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation#process-navigation-data-using-a-single-method) still seems to require manual decoding, according to the documentation.
