### ISSUE TITLE
[Bug] RadioButton. Different rendering Content in Android and iOS.

### ISSUE THREAD

**Issue by Nelo-cool** [xamarin/Xamarin.Forms#13309]
### Description
Hello my dear friends :) I try new Xamarin release version - 5.0 and a little upset by different behavior for RadioButton.Content.
Please, see in my code, this is selector for themes:
![image](https://user-images.githubusercontent.com/902820/103771866-99492e00-5039-11eb-916c-adff12a1bedf.png)

After build and run on iOS (14.3):

![image](https://user-images.githubusercontent.com/902820/103771955-be3da100-5039-11eb-86f6-36635b0f192a.png)

Good! Works fine, very goods! But Android (7.1, 8, 9.0 pie and other...) make my cry :'( :

![image](https://user-images.githubusercontent.com/902820/103772182-22f8fb80-503a-11eb-83cf-853b302f9127.png)

Cry! Very bad:)

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue: 5.0 pre 6 and release
- Last known good version: no good version
- Platform Target Frameworks: 
  - iOS:  14.3
  - Android: 7.1 and above
  - UWP:  none
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by hartez** [comment]
@Nelo-cool Check the console when you run your application - you should see a message that says something like "Warning - Android does not support Label as the Content property of RadioButton; the return value of the ToString() method will be displayed instead." [More info here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/radiobutton#display-arbitrary-content).

If you want to use a View (e.g., a Label) for RadioButton content on Android, you'll need to tell the RadioButton to use a ControlTemplate. Change your RadioButton XAML to look something like this:

```
<RadioButton ControlTemplate="{x:Static RadioButton.DefaultTemplate}">
    <RadioButton.Content>
        <Label Text="some text" LineBreakMode="TailTruncation"/>
    </RadioButton.Content>
</RadioButton>
```

That will tell the RadioButton to use the built-in template, which allows arbitrary content. 

This won't affect how the RadioButton looks on iOS, because iOS already uses the ControlTemplate by default (because there is no native RadioButton on iOS).
