### ISSUE TITLE
[Forms] Label inside ViewCell is cut off vertically when LineBreakMode is WrapWords (default)

### ISSUE THREAD

**Issue by bruzkovsky** [xamarin/Xamarin.Forms#1343]
### Description

We have a pretty complex layout for our ViewCells, consisting of Grids and StackLayouts inside ContentViews. The whole thing looks as follows:

```
+-+-----------------------+---+---+---+-+
| |      <title>          |<i>|<i>|<i>| | (a)
| +-----------------------+---+---+---+ |
| |                       |   |   |   | |
| |                                   | |
| |   <actual content (colspan=4)>    | | (*)
| |                                   | |
| |                       |   |   |   | |
+-+-----------------------+---+---+---+-+
(a)         (*)            (a) (a) (a) (a)
```
(a) ..... auto-sizing
(*) ..... star-sizing

### Steps to Reproduce

1. Start the repro UWP project
2. The silly long text will be cut off at the end, so you cannot see the grumpy ._. smiley
3. Resize the window and it will show

### Expected Behavior

The cell should resize and show the full text

### Actual Behavior

The text is cut off

#### Workaround

1. Go to MainPage.xaml (in the PCL) and uncomment the RowDefinitions
2. Start again
3. The cell is resizing correctly

### Basic Information

- Version with issue: 2.3.5.256-pre6, 2.5.0.121934
- Last known good version: N/A
- IDE: VS15 Windows

### Reproduction Link

[FormsLabelInListViewCutOff.zip](https://github.com/xamarin/Xamarin.Forms/files/1538547/FormsLabelInListViewCutOff.zip)

The solution is called UWPLabelInListViewCutOff, but this issue is occurring on all platforms. UWP is just the simplest and fastest (for me) to test.

**Comment by samhouts** [comment]
Last tested with 4.0.0.62955-pre2. Still an issue.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
