### ISSUE TITLE
Android status bar isn't set on start of the application

### ISSUE THREAD

**Issue by ychergui** [xamarin/Xamarin.Forms#1348]
### Description

I have set the color of my status bar into a color.xml file and a style in the style.xml but the application make some seconds to update the status bar color.

I have made a sample with 2 activity separated to see the effect.

Thanks

### Steps to Reproduce

1. Launch the app
2. The status bar will be black and the mainActivity will be launch
3. Press back when the MainActivity has been loaded to return on splashScreen Activity
4. The status bar as changed to blue

### Expected Behavior

The status bar is blue on the start of the app and not after some seconds

### Actual Behavior

The status bar change is color after some time

### Basic Information

- Version with issue: 2.4.0.280
- IDE: VS2017
- Platform Target Frameworks: 
  - Android: Android 6 and 7

### Reproduction Link

https://github.com/Ychergui/AndroidStatusBar

**Comment by toussam** [comment]
Hi Jason,

Could you tell me if this debug will be process in a near future ? I know you guys are quite busy, but it's just to have an estimation.

Thank you in advance for your response and wish you a great day !
Best regards,
Mathias

**Comment by toussam** [comment]
Hi @pauldipietro  and @samhouts ,

I noticed this issue was not included into the recent sprints. Is it possible to fix it into the next one ?

Thank you in advance for your response and wish you a great week !

**Comment by Romain1Lambert** [comment]
I am also currently facing this issue with android 8  the bar is grey too for a short while during launch.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
