### ISSUE TITLE
Xamarin Live Player wont' work with Prism

### ISSUE THREAD

**Issue by ninaada** [xamarin/Xamarin.Forms#1351]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
https://twitter.com/brianlagunas/status/933006012415598592

Xamarin Live Player wont' work with Prism

### Steps to Reproduce

1. Create a basic Xamarin Forms with Prism template
2. Try opening it in Live Player
3.  It shows blank screen

### Expected Behavior

Should work seamlessly

### Actual Behavior

It does not support

### Basic Information

- Version with issue: 2.5 
- Last known good version:
- IDE: VS 2017
- Platform Target Frameworks: 
  - iOS:  latest
  - Android: latest

**Comment by jassmith** [comment]
The live player can't deploy dependencies like that. Its out of the scope of what the Live Player is capable of doing. Basically the live player can only use dll's it already shipped with.

**Comment by ninaada** [comment]
So, Live player works with only default Xamarin.Forms and not if it uses any additional frameworks?

**Comment by ninaada** [comment]
@brianlagunas how can we make it work?

**Comment by brianlagunas** [comment]
You can't make it work. @jassmith just told you why. If you try to use any dependency like SkiaSharp for example, it won't work.

**Comment by ninaada** [comment]
@jassmith Any future plans to make it work?

**Comment by opcodewriter** [comment]
I don't get it, what's the point of Xamarin Live Player if it can't handle dependencies? Many applications use dependencies like frameworks and libraries.
This is yet another feature half baked by Xamarin, sad.

**Comment by pleb** [comment]
@jassmith 

> The live player can't deploy dependencies like that. Its out of the scope of what the Live Player is capable of doing. Basically the live player can only use dll's it already shipped with.

What is the purpose of Live player? I assumed it was a development tool, which is obviously not correct.

**Comment by TMagnum1974** [comment]
I am pretty new to Xamarin and had a simple App for iOS and Android in mind to get done.

With all the quickstarts and everything a Visual Studio MSDN Subscription offers it is just frustrating to see that the hardest thing to do is to get to a productive speed. I spent days to just set up the environment to create a xaml page, edit and preview it for iOS and/or Android.

Then, equipped with Visual Studio, Xamarin Live Player Testflight version and Reflector3 I was able to get a Xamarin.Forms project up and could edit and indeed easily create a tabbed app. I found NuGet packages to create a circle image and charts.

Now I wanted to get everything set up to create a Azure Mobile App Backend, implemented everything ... just to realize that now I can no longer use the Xamarin Live Player.

I could live with the fact it does not properly use custom renderers and sometimes displays the custom fonts and sometimes it does not ... but now since I added the Azure Mobile App Backend (which works as I see from the iOS Simulator run) Xamarin Live Player just breaks.

This is so frustrating - Maybe I do have to buy a Mac and do everything from there but I don't think this is Microsoft's intention - but with the sloooooow performance of iOS debugging via iOS Simulator (don't get me started on the Android one ...) and now a broken Live Player (which as it sounds will be no issue that can be fixed the way the Live Player is built) I don't think it makes any more sense to use this toolset on Windows. Will see if I can try the Visual Studio for Mac and if I can make any progress on there ...
