### ISSUE TITLE
[Bug] Material UI Editor with placeholder displays duplicated placeholder value

### ISSUE THREAD

**Issue by danielMd2805** [xamarin/Xamarin.Forms#13693]
If you display a Xamarin.Forms Editor on the UI with material design the placeholder is displayed twice.

Steps to Reproduce:
1.  Create an editor on xaml with design material
2.  Add a individually placeholder text
3.  display the ui 

In Xamarin.Forms 4.8 the placeholder doesn't display twice.

In Xamarin.Forms 5.0 the placeholde is displayed twice.

This issue was detected on android API 29.  iOS is unknown to me.

![Screenshot_1612777782](https://user-images.githubusercontent.com/54937170/107203208-707ed480-69fb-11eb-9781-4c7182175c09.png)

**Comment by jsuarezruiz** [comment]
Attach a sample where reproduce the issue:
[Issue13693.zip](https://github.com/xamarin/Xamarin.Forms/files/5943876/Issue13693.zip)

![issue13693](https://user-images.githubusercontent.com/6755973/107224704-12acb580-6a18-11eb-92c1-eed0b9085d5c.gif)

@PureWeen Could this issue be fixed by: https://github.com/xamarin/Xamarin.Forms/pull/13666

**Comment by PureWeen** [comment]
Fixed by the following PR

https://github.com/xamarin/Xamarin.Forms/pull/13647

**Comment by sattasundar** [comment]
Still this issue exist.
