### ISSUE TITLE
No way to pass an argument value to XAML BindingContext ViewModel Argument.

### ISSUE THREAD

**Issue by xshiiiidev** [xamarin/Xamarin.Forms#13751]
Was searching for this for quite some time now.

I encountered this post stating all the problems I encountered he has the same problem as me.

https://forums.xamarin.com/discussion/182839/how-to-pass-initialization-argument-to-view-in-mvvm

Is there a way for this to work ? Or as stated to the above link there is no way ?

**Comment by hartez** [comment]
If your constructor argument needs to be determined at runtime, then passing it in via XAML is going to be difficult. There might be some really awkward way to make it work, but I wouldn't recommend it.

Is there a reason you want to do it via XAML rather than constructing your view model in code and setting the BindingContext?

**Comment by xshiiiidev** [comment]
@hartez 

This is related to my previous [code bug encountered](https://github.com/xamarin/Xamarin.Forms/issues/13752) I though it was the constructor whose in fault here.

I re-implemented my requirement here using the Code Behind constructor instead of the XAML.

Code behind is really more simple than the XAML.

Will be closing this now.

Thank you.
