### ISSUE TITLE
[Bug] Debugging with a Listview results in insane memory increase with CachingStrategy Recycle*

### ISSUE THREAD

**Issue by jtorvald** [xamarin/Xamarin.Forms#14010]
### Description
Since somewhere around last week I noticed that my app was going nuts in debug mode; memory was increasing, threads were increasing, while nothing really happened. I didn't get clear at first what was causing this. On the same day I updated Visual Studio and start using Enterprise for the profiler. After seeing similar messages on Slack I decided to make some time free and look into it. I managed to reproduce the issue with an out of the box new Xamarin Forms Shell project where I replaced the CollectionView in the items list to a standard ListView, with (**IMPORTANT**):

CachingStrategy="RecycleElementAndDataTemplate|RecycleElement". When I don't set the CachingStrategy to recycle I don't see this behavior.

### Steps to Reproduce

1. Run the attached sample app with **debugging** in Visual Studio for Mac
2. Wait 10 seconds to see the memory usage of the app: 6MB
3. Go to tab: Browse to open the listview.
4. Wait and see memory increasing and threads being created.

When I start the same App without the debugger connected I don't experience this issue.

### Expected Behavior

I expect memory stays the same.

### Actual Behavior

Memory keeps increasing until the whole app becomes unresponsive.

### Basic Information

- Version with issue: 5.0.0.2012
- Last known good version: I believe probably until 5.0.0.2012
I'm not 100% sure that Xamarin Forms 5.0.0.2012 is the problem. Maybe it is Visual Studio update?

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Visual Studio Enterprise 2019 for Mac
Version 8.9.1 (build 34)
Installation UUID: ba5a8ba5-332e-470e-a7b0-3ad1be7d4adf
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000122

Mono Framework MDK
Runtime:
	Mono 6.12.0.122 (2020-02/c621c35ffa0) (64-bit)
	Package version: 612000122

Roslyn (Language Service)
3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

NuGet
Version: 5.8.0.6860

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/5.0.201/Sdks
SDK Versions:
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	3.0.100-rc1-014190
	2.2.402
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.302
	2.1.4
	2.0.0
	1.0.4
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	3.0.0-rc1-19456-20
	2.2.7
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.2
	2.0.5
	2.0.0
	1.1.2
	1.0.5

.NET Core 3.1 SDK
SDK: 3.1.407

Xamarin.Profiler
Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 12.4 (17801)
Build 12D4e

Xamarin.Mac
Version: 7.8.2.5 (Visual Studio Enterprise)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:43-0500

Xamarin.iOS
Version: 14.14.2.5 (Visual Studio Enterprise)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:44-0500

Xamarin Designer
Version: 16.9.0.316
Hash: bd2705417
Branch: remotes/origin/d16-9
Build date: 2021-02-24 00:16:08 UTC

Xamarin.Android
Version: 11.2.0.21 (Visual Studio Enterprise)
Commit: xamarin-android/d16-9/93eab59
Android SDK: /Users/developer/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@d6d86b2
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.34.1@daff8f4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@9d8924d

Microsoft OpenJDK for Mobile
Java SDK: /Users/developer/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/d16-9
Build date: 2021-02-18 03:14:56 UTC

Android Device Manager
Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/d16-9
Build date: 2021-02-18 03:15:18 UTC

Build Information
Release ID: 809010034
Git revision: 33bce2b7f3d45d05865cd3282f1c2cdc3a112aa0
Build date: 2021-03-04 11:21:38-05
Build branch: release-8.9
Xamarin extensions: 33bce2b7f3d45d05865cd3282f1c2cdc3a112aa0

Operating System
Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Thu Jan 21 00:07:06 PST 2021
    root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
DeepClean 1.2.5
FileNesting 0.1.2

```

</details>

### Screenshots

https://user-images.githubusercontent.com/1808131/111076298-11294e00-84ec-11eb-9d42-dc2204ea0d9e.mp4

### Reproduction Link

[listview-debug.zip](https://github.com/xamarin/Xamarin.Forms/files/6137091/listview-debug.zip)

edit: happens with both caching reclycle strategies.

> VS bug [#1314753](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1314753)

**Comment by jtorvald** [comment]
This seems to be a duplicate of #13992 only with a sample solution for iOS

**Comment by john-dalsgaard** [comment]
I think I see the same issue when using AiForms.Dialogs....

**Comment by jsuarezruiz** [comment]
Need to investigate more, but, could be related with: https://github.com/xamarin/Xamarin.Forms/issues/14020?

**Comment by jtorvald** [comment]
@jsuarezruiz Yes, that described behavior looks the same and I can add some more details:
This only happens if you have Hot Reload **_Changes Only_**.  With Hot Reload set to **_Full Page_** it works fine.

**Comment by Redth** [comment]
@BretJohnson this looks similar to #14034 and may be related to what I experienced myself with LVT and loading all the items or the caching strategy.  Could you take a look and see if you can make sense of what's happening in this scenario?

**Comment by dirivero** [comment]
Any update on this one? It quite impossible to use the hot reload under Changes Only mode. 

Below is the iOS call stack that ends up creating thousands of templates inside any recycling ListView (Android's call stack is exactly the same except for the initial calls).

```
Xamarin.Forms.ElementTemplate.CreateContent() 
Xamarin.Forms.Internals.DataTemplateExtensions.CreateContent(Xamarin.Forms.DataTemplate self, string item, Xamarin.Forms.ListView container) 
Xamarin.Forms.Internals.TemplatedItemsList<Xamarin.Forms.ItemsView<Xamarin.Forms.Cell>,Xamarin.Forms.Cell>.ActivateContent(int index, string item) 
Xamarin.Forms.Internals.TemplatedItemsList<Xamarin.Forms.ItemsView<Xamarin.Forms.Cell>,Xamarin.Forms.Cell>.CreateContent(int index, string item, bool insert) 
Xamarin.Forms.Internals.TemplatedItemsList<Xamarin.Forms.ItemsView<Xamarin.Forms.Cell>,Xamarin.Forms.Cell>.GetOrCreateContent(int index, string item) 
Xamarin.Forms.Internals.TemplatedItemsList<Xamarin.Forms.ItemsView<Xamarin.Forms.Cell>,Xamarin.Forms.Cell>.get_Item(int index) 
Xamarin.HotReload.Xaml.VisualTreeService.VisualTree.FormsItemsViewEnumerator<Xamarin.Forms.Cell>.get_Item(int index) 
Xamarin.HotReload.Xaml.VisualTreeService.VisualTree.DispatcherVisualTreeContext.ProcessPendingInitialize(Xamarin.Forms.ListView parent) 
Xamarin.HotReload.Xaml.VisualTreeService.VisualTree.DispatcherVisualTreeContext.ProcessPendingObjects(int processingTime) 
Xamarin.HotReload.Xaml.VisualTreeService.VisualTree.DispatcherVisualTreeContext.<ScheduleAsyncProcessing>b__78_0() 
Xamarin.HotReload.Xaml.Utility.DispatcherExtensions.() 
Xamarin.HotReload.Xaml.Utility.DispatcherExtensions.<bool>() 
Foundation.NSAsyncActionDispatcher.Apply() 
UIKit.UIApplication.UIApplicationMain() 
UIKit.UIApplication.Main(string[] args, string principalClassName, string delegateClassName)
```

**Comment by drasticactions** [comment]
@dirivero 

There is a bug in Forms Hot Reload that breaks virtualization by invoking every element inside of a listview. You can see this in the Live Visual Tree by the number of items that are added. The number reflects the in-memory objects, so when it increases, that's in memory.

The problem we have now is that there is no way to support Hot Reload in List View otherwise unless the Forms team introduces some kind of API to get the visual elements contained within the list. So our choices are:

- Remove Hot Reload support for ListView, which will fix the memory/performance issues you're seeing, but break it for those who don't have auto-populating lists with set values.
- Keep it and have a known issue where it's broken for this mode, but then it'll stay working for those that don't have large virtualized lists.

We debated this within the team, and decided on option 2 unless we have more support to show that more people are being hit by this. 

We'll talk about it again and see about servicing this, IMO I don't think it's worth having ListView be totally broken in debug in this state.

(MAUI is not affected by this. For MAUI, we use `IVisualTreeElement` for creating the live visual tree to get elements for Hot Reload, so anything that implements it will work with Hot Reload. ListView doesn't, so it won't appear. If they do implement it, it should then work.)

**Comment by dirivero** [comment]
Hi @drasticactions, thanks for getting back on this one.

I understand why you picked option 2 if it behaved like that, but the problem is that even if the list has **one element**, thousands of cells are created (I included the sample code that breaks below). 

Would it be possible to make it work as you describe? Like it only instantiate the actual number of cells required by the `ItemsSource`?

```
<ListView CachingStrategy="RecycleElement">
    <ListView.ItemsSource>
        <x:Array Type="{x:Type x:String}">
            <x:String>single element</x:String>
        </x:Array>
    </ListView.ItemsSource>
    <ListView.ItemTemplate>
        <DataTemplate>
            <ViewCell>
                <Label Text="{Binding .}" />
            </ViewCell>
        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
```

The result:
![image](https://user-images.githubusercontent.com/7670773/148250441-d41a9d0e-feaa-4741-bd41-a239dec76769.png)

With `CachingStrategy="RetainElement"` it works as expected:
![image](https://user-images.githubusercontent.com/7670773/148250826-0f2edbe2-5ae8-4fe6-9562-f7372de76cb0.png)

**Comment by drasticactions** [comment]
Could you try turning off XAML Hot Reload and see if you hit the same behavior? If it still does, then it's unrelated to XAML Hot Reload. If it doesn't and it works, I'm pretty sure it's the issue I described. If that's the case, you don't have a way to work around it beyond turning off XAML Hot Reload or using "Full Page". IMO, I would file a VS Feedback issue for it so we can talk about it again among our team.

At this point, we're probably never going to have ListView support for Forms working (That requires significant refactoring in Forms, and at this point the focus is on MAUI), so we need to decide if we want it in this "half-working, half-broken" state, or remove it so you don't have to turn off Hot Reload all together.

**Comment by dirivero** [comment]
In Full Page mode or w/o Hot Reload it works fine. 

I've submitted the problem to VS so you can have the follow up conversation with your team. I believe that considering the current state it would be better to ignore ListViews completely when Changes Only mode is turned on. If possible, they could be ignored only when virtualized by checking the CachingStrategy attribute. Otherwise the App becomes unresponsive due to heavy memory usage.

Thanks again.
