### ISSUE TITLE
[Question] iOS RadioButton Renderer

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/Xamarin.Forms#14131]
is there any RadioButtonRenderer in Xamarin.Forms 5 for iOS? ican't find any :( 
maybe does have different name that i don't know?

**Comment by rachelkang** [comment]
Hi, @mhrastegary77 - thanks for asking! The short answer is no, there is no RadioButtonRenderer for iOS, and this is because iOS has no native equivalent of RadioButton. You can check out the original PR for more context https://github.com/xamarin/Xamarin.Forms/pull/11628, and if you have more questions, @hartez is your guy :)
