### ISSUE TITLE
[Enhancement] [macOS] Add ImageButton to macOS

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/Xamarin.Forms#14133]
## Summary
I'm trying to port my little project to macOS. The ImageButton doesn't work.
Could we have it in Xamarin Forms 5? it's one of the Primary controls!!! :(

**it's been reported since 2018 btw -> #4792**

**Comment by rachelkang** [comment]
Hi, @mhrastegary77 - thanks for submitting this proposal. I'll be closing this issue since it's a duplicate, and will make sure the original issue gets on our Enhancements board.

For now, I suggest checking out alternative solutions - for example, [Button w/ ImageSource](https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/button#using-bitmaps-with-buttons)
