### ISSUE TITLE
[Enhancement] FlyoutPage should work on Android NonAppCompat

### ISSUE THREAD

**Issue by nbevans** [xamarin/Xamarin.Forms#14157]
On Forms 5.0+

A non-AppCompat model Android app must register the FlyoutPageRenderer manually in order to avoid a runtime exception:

```csharp
Xamarin.Forms.Internals.Registrar.Registered.Register(typeof(FlyoutPage), typeof(FlyoutPageRenderer));
```

There appears to be no functional reason for this limitation on non-AppCompat apps. The obsolete MDP renderer appears to be a functionally very similar implementation and relies on the same AndroidX DrawerLayout component.

**Comment by PureWeen** [comment]
@nbevans 

The MDP still exists and you can use it in the obsolete form on non-AppCompat

We're not going to be iterating on the FlyoutPageRenderer/MDPRenderer at all inside XF with MAUI on the horizon so you don't lose out on anything by just using the deprecated MDP. Very few (if any) new changes will get pushed to the Flyout Page Renderer

The purpose of doing this was to shape the stable supported story for MAUI so that users can update to the latest 5.0 and update deprecated things, like this, which will then allow users to migrate to MAUI more easily

**Comment by nbevans** [comment]
Okay - so MAUI will be AppCompat only. Whilst annoying (it creates re-work) that is good to know _now_ so that I can start thinking about how to refactor our Android app toward the AppCompat model.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
