### ISSUE TITLE
[Android] HorizontalTextAlignment="Center" loses alignment when scrolled

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#1415]
Moved from https://bugzilla.xamarin.com/show_bug.cgi?id=49311

### Description
I've confirmed this issue. I also confirmed the Label is sized full width, and this issue is still present with Fast Renderers.

From original Bugzilla description:

It's a bit odd, but sometimes the alignment of a Label inside a StackLayout inside a Frame (inside a ViewCell) is messed up.

If you scroll, then sometimes the Label is not centered and sometimes it's centered.

### Expected Behavior
Text should be always centered on the screen

### Actual Behavior
Text occasionally appears left aligned when scrolled.

### Basic Information
- Version with issue: 2.3.3.175, 2.5.0.121934
- Last known good version: ?
- IDE:
- Platform Target Frameworks: 
  - Android: 8.0
- Android Support Library Version: 25.4.0.2

### Screenshots

https://github.com/lhaussknecht/CenterBug/blob/master/assets/centerBug.gif

https://www.dropbox.com/s/z4hzr7rl9o2lvqb/Screenshot%202017-12-18%2009.04.09.png?dl=0

https://www.dropbox.com/s/evk3zhdu0ivfi5p/Screenshot%202017-12-18%2009.23.53.png?dl=0

### Reproduction Link

https://github.com/lhaussknecht/CenterBug

**Comment by rmarinho** [comment]
Maybe related with #1396

**Comment by numb3r** [comment]
This issue is still happening with v2.5.0.280555. Is this has been resolved ? What is the work around ?

**Comment by tlhintoq** [comment]
This has been touched on many times in Xamarin.Forums.  And was reported 2 years ago in Bugzilla. And ignored every time.

##Workaround:##
So this sort of shows the approach you have to take.  You can't try to color or the expand the labels themselves because they always want to shift to the left.  You have to nest the `Label` in a `Grid` then manipulate the `Label` as an object.
Instead you colorize the grid they are sitting in.  An then center the `label` _inside_ the grid

Here we see the `Label` as fushcia for ease of understanding.  Imagine it transparent and you can see what happens.  The `Label` gets centered instead of being expanded and then trying to center the text.
![image](https://user-images.githubusercontent.com/11351506/37412695-cb7aab18-277b-11e8-87e3-acd3167e0c43.png)

**Comment by LarsNymand** [comment]
This issue also applies for the VerticalTextAlignment

**Comment by davidortinau** [comment]
Another instance of this issue. When I exit the app on android and come back, it resets left.

https://www.screencast.com/t/SDvfVjjaMXD8

This is on 3.0.0.446417

iOS is fine.

**Comment by rboyette** [comment]
@numb3r  Someone posted a workaround on StackOverflow that works for me [here](https://stackoverflow.com/questions/43147929/xamarin-label-losing-text-alignment-when-page-returned-to)

**Comment by StephexIron** [comment]
tlhintoq, your solution works for me
