### ISSUE TITLE
Inconsistent behavior of Push/PopModalAsync

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#1427]
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=31542

### Steps to Reproduce
Scenario:

Page1 pushes Page2 using Navigation.PushModalAsync (from Page1). Page2 then calls Navigation.PopModalAsync (from within Page2). That pop is using Page2's Navigation property, which should have its own modal stack. I believe this should throw, but instead it pops Page2. Next, Page2 pushes Page2 using Navigation.PushModalAsync (still from within Page2, using Page2's Navigation property). This page is never shown.

### Expected Behavior
There are two possibly consistent results:

1. Page2's call to PopModalAsync should throw.
Or
2. Page3 should be shown.

### Actual Behavior
This behavior is inconsistent.

### Basic Information

- Version with issue: 1.4.2 through June 2017

### Reproduction Link

[Nudge_PopModalAsync_Demo.zip](https://github.com/xamarin/Xamarin.Forms/files/1573704/Nudge_PopModalAsync_Demo.zip)

**Comment by samhouts** [comment]
Last tested with 4.0.0.94569-pre3. Still an issue.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by TheRealAdamKemp** [comment]
I don’t currently use Xamarin products so I can’t test this myself. It looks like I attached a sample project so you could hopefully just run it and see if this behavior still exists.
