### ISSUE TITLE
[Bug] Unable to bind CollectionView FooterTemplate

### ISSUE THREAD

**Issue by nielscup** [xamarin/Xamarin.Forms#14360]
**Xamarin.forms 5.0.0.2012:**

`{Binding IsLoadingMore}` in the footer below does not do anything. 
```
<CollectionView.FooterTemplate>
    <DataTemplate>
        <StackLayout HeightRequest="100">
            <ActivityIndicator **IsRunning="{Binding IsLoadingMore}"** >
        </StackLayout>
    </DataTemplate>
</CollectionView.FooterTemplate>
```

I even tried binding a label in the FooterTemplate like this:
`<Label Text="{Binding TestText, Source={x:Reference MyPage1}}"/>`
Not a chance.

I can move the ActivityIndicator outside the CollectionView and it works as expected.

https://github.com/xamarin/Xamarin.Forms/issues/14359 2 bugs in 1 hour. unbelievable how buggy the collectionView is...

**Comment by GalaxiaGuy** [comment]
Both of those issues seem to be caused by misunderstanding how the footer works.

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/layout#display-a-templated-header-and-footer

Looking at the docs it seems the binding context of `FooterTemplate` is the value of `Footer` to be. Adding `Footer="{Binding .}"` should make it do what you want.

**Comment by nielscup** [comment]
Ah thanks, I don't see the logic in that, but it works now.
