### ISSUE TITLE
Please solve important bugs before MAUI

### ISSUE THREAD

**Issue by kerberosargos** [xamarin/Xamarin.Forms#14409]
Hello,  We are waiting serious bugs resolution before MAUI. So many active Xamarin Forms's apps in production As you know. Also some people may not migrate their projects to MAUI quickly.

List of bugs is as follows. Thank you in advance for your efforts.

[White Screen in Android when using NavigationPage #11993](https://github.com/xamarin/Xamarin.Forms/issues/11993)

[FlexLayout height not rendered correctly when placed inside Grid #5265](https://github.com/xamarin/Xamarin.Forms/issues/5265) 

[FlexLayout height's is not rendered correctly when its child visibilty false #14363](https://github.com/xamarin/Xamarin.Forms/issues/14363)

**Comment by IgorKravchenko10** [comment]
It seems one part of team working on MAUI, the rest is on vacation =)
Any replies on bug reports

**Comment by jsuarezruiz** [comment]
We are here, we read your feedback and we want to have regular releases improving. It is impossible to attend to everything at once, I hope it was possible!, but we will try to create boards with the issues, status, explain the priorities established etc. We will also update with progress status. Take a look to: https://github.com/xamarin/Xamarin.Forms/projects/87

Improving Xamarin.Forms is very important, not only because we want Xamarin.Forms devs to have the best possible experience but because it also impacts .NET MAUI.

Again, thank you all for your feedback and help to improve Xamarin.Forms!.

**Comment by AndyDentFree** [comment]
> Improving Xamarin.Forms is very important, not only because we want Xamarin.Forms devs to have the best possible experience but because it also impacts .NET MAUI.

That's good but not the only reason.

Here's a perspective from 40 years of development, in case you are too new to the industry to realise how Microsoft triggers those of us with long memories.

When Microsoft appear to be shifting their focus to a _shiny new thing_ and abandoning old users, we get chilling echoes of when you did it before.

Yes I get that MAUI is supposedly close enough to Forms that it will be an easy migration.

That's a promise, not a proven reality.

It doesn't take into account the entire ecosystem of 3rd party code needing conversion, on which major projects rely.

So, when we get asked which direction to pick in the future, we start recommending at a corporate level to _avoid all MS UI frameworks until a few years of stabilisation._

People replan around alternatives like Flutter or straight web technologies.

I haven't seen anything clearcut enough that, if I was advising a major org today, I could take to them, like:

1. We commit to supporting Xamarin Forms for five years
2. Here is the major sample project you can download and build to confirm things are working.
3. Our team size is X and here is the team blog so you can see they are still working on Forms.


Note that throughout my years of working on forms, I've never seen anything like 2 maintained consistently.

**Comment by jfversluis** [comment]
Thanks for sharing your view @AndyDentFree! As mentioned in the other issue (#14205) I think a lot already has been said, in fact, you posted largely the same message in that very issue. You're free to use and advice anyway you want, in fact, I would encourage that!

I'd rather not go into these kinds of discussions and instead focus on actually doing the work and unblocking people and regain confidence that way instead of through words :) 

In fact, I'll add the issues mentioned here to the other issue and close this one so we can have a more centralized place for updates.

Thanks!
