### ISSUE TITLE
[Solved] [Bug] FlyoutPage have a space between Flyout and Details pages

### ISSUE THREAD

**Issue by DellaMoraWalter** [xamarin/Xamarin.Forms#14466]
### Description
After upgrade to Xamarin.Forms 5 the FlyoutPage present a space between the Flyout page and the Details page.
Following screenshot come from UWP version of the app.
![Flyout issue 1](https://user-images.githubusercontent.com/53078750/127219450-7e0285e2-3c2c-46f1-a89a-da6d3c30d941.PNG)

I haven't find any property in the FlyoutPage that can produce this effect.
Playing with live visual tree, I've finded that this space is created by the underneath UWP FlyoutPageControl.
For test I've forced his Canvas container with a red background, the result is this.
![Flyout issue 1B](https://user-images.githubusercontent.com/53078750/127218021-d85a603a-1c5e-4bd3-8ede-41e33bf704b5.PNG)
![Flyout issue 2](https://user-images.githubusercontent.com/53078750/127218028-a8da9813-6bf4-4ed9-86a0-c459cb8ab7f1.PNG)
So this is only an empty transparent space and I've not finded a property for set that in some way.

I've created a new sample project for reproduce the issue but inadspettately the problem doesn't happend.
I've spent many hours removing parts of the application and at the end was almost the same as the sample but I haven't discovered wich configuration or property can produce this effect.

Have someone an idea of what's wrong?
Unfortunately I can't attach the project with the issue.

### Versions
xamarin forms 5.0.0.2012
Microsoft.NETCore.UniversalPlatform 6.2.12
Microsoft.UI.Xaml 2.6.1
Prism.DryIoc.Forms 8.1.97

**Comment by DellaMoraWalter** [comment]
My UWP project specify a dependency to the Microsoft.UI.Xaml nuget package that recently I've upgraded to versione 2.6.1.
Is not clear why there is that inclusion because xamarin.forms import automatically this dependency, but actually at the version 2.4.3, and the problem is here.
Removing the explicit dependency the UI problem disappear.

This let me think that if in the future xamarin team decide to upgrade the version of the required Microsoft.UI.Xaml can occour to this problem.
For test, I've tried to progressively downgrade the Microsoft.UI.xaml and finded that this issue appear only with >= 2.6.0 versions

**Comment by azeemchaudhrry** [comment]
**Description**
After NuGet packages upgrade the FlyoutPage sample app
https://github.com/xamarin/xamarin-forms-samples/tree/main/Navigation/FlyoutPage
to "Xamarin.Forms" 5.0.0.2196, "Microsoft.UI.Xaml" upgrade to 2.7.0.0.

**Steps to Reproduce**
Run the UWP application attached.

**Expected Behavior**
There should be no space between Flyout and Details pages

**Actual Behavior**
A space between Flyout and Details pages

**Basic Information**
Platform Target Frameworks:
UWP: 19041

**Screenshots**
![image](https://user-images.githubusercontent.com/20266299/140957077-3adbbe86-b6e8-4958-82ad-b28b9a58837c.png)

**Reproduction Link**
[FlyoutPageNavigation.zip](https://github.com/xamarin/Xamarin.Forms/files/7506127/FlyoutPageNavigation.zip)


**Workaround**
Downgrade the "Microsoft.UI.Xaml" to 2.5.0.0. package

**Comment by jfversluis** [comment]
Seems fixed then! Thank you!
