### ISSUE TITLE
Disabled button passes user tap to control behind it

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#1454]
### Description
Repro: (re-purposed sample, ignore the name) - https://www.dropbox.com/s/ig5szzjmhyluxxl/PullToRefreshSample.zip?dl=0

Load the app in debug mode.
The button in the listview's cell is disabled. Tap it.
In the output window, you will see "List View Tapped" instead of "Button Hit"

If you set the button to enabled, hitting the button will show "Button Hit" instead of "List View Tapped"

### Expected Behavior
Even though the button is disabled, the user tapped the button, and the tap should go to the button (and do nothing since it is disabled).

### Actual Behavior
The tap goes to the control under the button, and the listview tapped function is called

### Basic Information
Tested with Xamarin forms 2.5.0.121934

**Comment by PureWeen** [comment]
I feel like this one isn't a bug 
I tested this behavior on ios/uwp and they all act the same as Android

So either it's a bug for all or a bug for none it seems

@hartez  thoughts?

**Comment by hartez** [comment]
It's undefined behavior - I don't think we've ever specifically determined any rules for it. 

We should probably determine what the least surprising behavior would be and enforce it.

**Comment by PureWeen** [comment]
I feel like since 
> Disabled button passes user tap to control behind it

Is how it works on all the platforms currently that that would constitute 
> the least surprising behavior

Any variation of that would now cause any apps based on this expectation to act differently

**Comment by Paul-Brenner-Tangoe** [comment]
I don't think any apps work based on that expectation though. I posted it as a bug because that doesn't make sense as the expected behavior IMO. If you tap a button, the touch should go to it, not what is behind it. Anyone have any idea what native iOS and Android does?

**Comment by PureWeen** [comment]
I tested a basic sample and native implementations

### Xamarin Forms
```C#
ContentView contentView = new ContentView()
{
	Content = new Button()
	{
		Text = "CLICK ME",
		Command = new Command(() =>
		{

		},
		canExecute: () => false)
	}
};

contentView.GestureRecognizers.Add(new TapGestureRecognizer()
{
	Command = new Command(() =>
	{

	})
});
```
-iOS/Android pass the event through to the GestureRecognizer whereas 
-UWP does not :-/ 

### Native Android
With a button on top of a linear layout. If the button is disabled the linear layout will not receive the click event

### Native iOS
https://stackoverflow.com/questions/3211790/uibutton-passes-touches-to-superview-when-disabled-how-can-i-avoid-this

When the button is disabled. The Tap Gesture passes through the disabled button and fires on the TapGestureRecognizer

```C#
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			SomeButton.TouchUpInside += SomeButton_TouchUpInside;
			SomeButton.BackgroundColor = UIColor.Green;
			UITapGestureRecognizer uITapGestureRecognizer = new UITapGestureRecognizer(() =>
			{
				SomeButton.Enabled = !SomeButton.Enabled;
			});

			View.AddGestureRecognizer(uITapGestureRecognizer);
		}

		private void SomeButton_TouchUpInside(object sender, EventArgs e)
		{
			SomeButton.Enabled = !SomeButton.Enabled;
		}
```

### UWP
Natively UWP looks to act more like iOS which is funny considering Forms it does not work like that. The difference with UWP is that the tap event passes all the way through. So clicking the Button (even when enabled) causes the Tapped event on the Grid to fire

```XAML
 <Grid Tapped="Grid_Tapped" Background="Yellow" Width="1000" Height="1000">
		<Button IsEnabled="False" Background="Pink" Content="Button Press" Click="Button_Click"></Button>
    </Grid>
```

So all three platforms are subtly different natively but Android is really the only one where the disabled button blocks the event from passing through.  

### Recommendations
I realize it's a bit annoying because there's not a great way to have that disabled button block the touch. So you currently have to account for that on the underlying view.  There's currently work being done to allow the user to articulate this better though via XAML which would let one ensure that the event doesn't pass through

As far as a fix. I still stand by saying the way it works now is intentional in order to create consistency between iOS/Android. If we change how Android works then we have to change how iOS works which now causes this behavior to be counter intuitive to an iOS developer and counts as a breaking change.

The fix here seems more to make sure that UWP is consistent with iOS/Android

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by ChaseFlorell** [comment]
I too ran into this today, I ended up stacking buttons to make it work

```xaml
<Grid>
    <!-- This is awful, never ever do this... 
    unless your disabled button starts passing 
    touch events through to the base TapGestureRecognizer -->
    <Button Text="{Binding CheckInOutText}"
            Style="{StaticResource PrimaryPillButton}" />

    <Button Text="{Binding CheckInOutText}"
            Style="{StaticResource PrimaryPillButton}"
            d:Text="CHECK OUT"
            Command="{Binding MoveNextStateCommand, Mode=OneTime}"
            CommandParameter="{Binding .}" />
</Grid>
```

My preference would be that `InputTransparent` actually override the thing.

```xaml
<Button Command="{Binding SomeCommandThatMightNotExecute}"
        InputTransparent="False" />
```
