### ISSUE TITLE
[Enhancement] Please bring back xamarin forms previewer

### ISSUE THREAD

**Issue by xdamithx** [xamarin/Xamarin.Forms#14636]
hello xamarin, 

xamarin forms previewer was a grate tool for developers. u dont hve to run the app or even dont hve to connect a debug device to preview changes. hot reload is good but its a huge time waste. most of the devs including me will be much appreciated if u guys add that feature again. xamarin 5 is grate but i can benefit from it cause i simply cant develop without previewer, please re - consider your decision and make both previewer and hot reload options available at the same time! thank you

**Comment by ShinichiHezemansCortegs** [comment]
yes! 
Is there a technical limitation or something?

**Comment by IoTFier** [comment]
Previewer never worked if you were to use third party plugin or renderers provided thru their nuget packages. 
I didn't see it working out for anything beyond primitive "hello world" screens.

I like the Live visual tree connected with the Hot Reload. But it is broken since XF 5.0.0.2125 release yesterday.
We need Hot Reload in the design / development phase.

https://developercommunity.visualstudio.com/t/VS-16113---Xamarin-Forms-upgrade-to-5/1534554?entry=myfeedback

**Comment by ShinichiHezemansCortegs** [comment]
Yes that is true. But I used the previewer for creating the simple layouts and in the beginning of a project. Seeing if the screen looked okay with the margins and paddings I set on different devices. The preview is so much faster than using hot reload and saves al lot of time. 
But later in development the preview is no longer that usefull and hot reload takes over.
It would be great if developers had both options.

**Comment by jfversluis** [comment]
There is a new previewer now available in the latest VS2022 preview that works with .NET MAUI. This is not something that is going to happen for Xamarin.Forms. If you have any ideas around it, I think the best place to propose something is on https://developercommunity.visualstudio.com/home as this has to do with the tooling and not so much with the SDK :)

Thanks for your enthusiasm about out products!
