### ISSUE TITLE
[Enhancement] FULLY pre-calc a page ahead of time.

### ISSUE THREAD

**Issue by ToolmakerSteve** [xamarin/Xamarin.Forms#14826]
## Summary
Its well-known that Xamarin Forms on Android takes significantly longer the first time you open a page, than corresponding Android code. While this has improved greatly over the years, to me this is still the largest "downside" of XF for mobile development.

IDEA: Be able to do EVERYTHING needed to display a page, BEFORE the page is needed. In my experience, the performance bottleneck is in "measure and layout", and the internal prepping of the java objects. While its not hard to pre-call a page's constructor, that is only a fraction of the time. I'd like to get the "most likely next page" ready ahead of time - before user asks for it.

## API Changes

    // Do this on a background thread.
    var page = new MyPage();
    var vm = new MyPageViewModel();
    // ...set vm properties as needed...
    page.BindingContext = vm;
    // **NEW API** This does whatever it can do ahead of time.
    // I presume there is significant work that could be done, given how much slower first-load is than later loads, and than a corresponding Xamarin.Android layout.
    page.PreLoad();

    // Do this later on MainThread.
    // ...push "page" on to nav stack...

## Intended Use Case
Any time you need to show a complicated page on Android.

NOTE: I experience this, on complicated pages, even when using VS Enterprise 2019's advanced Android pre-compilation options. (OTOH, those options do help a lot.)

NOTE: I am well-versed in designing XF pages to minimize layout complexity. Avoiding nested layouts where possible (Including making custom layouts.) But eventually some pages with complicated dynamic list items hit a point where the only solution I've found is to re-write the item layout in a custom Android renderer. I'd like to avoid doing so.)

**Comment by jfversluis** [comment]
Hey @ToolmakerSteve ! This is a very well-through thought feature. I love it!

You're right, this has been a pain point and therefore something we are very focussed on with .NET MAUI.

Now for the bad news. I'm pretty sure we're not going to do this for Xamarin.Forms anymore. It is probably pretty impactful for the whole product. And as you might know, we're maintaining this and making sure that everything keeps working while we introduce .NET MAUI, but we're not going to add big new features. I think this is one of those. However, I love the idea and I would encourage you to open a discussion for this on the [.NET MAUI repo](https://github.com/dotnet/maui). A discussion so that some other people can chime in on this idea and the potential implementation, but also there can be discussed how this hooks into the improvements that are already in .NET MAUI today.

Again, thanks for taking the time to think this up and sharing it with us.

Closing this for now on Xamarin.Forms, but hoping to see it popup on .NET MAUI :)

**Comment by ToolmakerSteve** [comment]
@jfversluis - I suspected as much. I won't raise an issue on MAUI until I've been able to spend time with it. I plan to spend significant time with MAUI on Android this month. Including diving into the source code. My point in raising this issue on XF, was to "put a stake in the ground" that this is THE BIGGEST hesitation I have in recommending XF to other developers. It must be solved in MAUI. No matter what breaking changes that causes in migrating from XF.
