### ISSUE TITLE
What's the current state of Xamarin.Forms on macOS

### ISSUE THREAD

**Issue by mnxamdev** [xamarin/Xamarin.Forms#14834]
We have an app that runs well using Xamarin.Forms on iOS, Android, and UWP. Our macOS app is written using Xamarin.Mac and we want to update that app with code shared from our Xamarin.Forms apps so that we can give our customers the latest features. We're trying to decide if we should move towards MAUI but given the delays we're revisiting Xamarin.Forms for macOS. The following page states it's in "Preview" (updated 7/2021) but the Wiki was last updated in 2018:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/mac

https://github.com/xamarin/Xamarin.Forms/wiki/Platform-Support-macOS-Status

The repo shows a different story:
![image](https://user-images.githubusercontent.com/46384868/140577624-b16ed1e4-4319-4ad0-b884-a6d0a408fdb9.png)

Can someone tell me if the Wiki is current or needs to be updated? Also, does anyone know if there will be work done to further Xamarin.Forms for macOS given the MAUI delays?  I know everyone is excited for the M1 Macs and iOS apps running on them. Our app runs well on M1 Macs but we have lots of customers on Intel Macs and those will still be around for quite some time. Thanks.

**Comment by jfversluis** [comment]
Hey there! Thanks for your question.

macOS has never been an officially supported platform for Xamarin.Forms. Or maybe I should state it different: it never has been a primary target. Something that is luckily changing with the transition to .NET MAUI. So the "preview" in this case is still valid. 

While a lot has been implemented to work on macOS, there are still things missing. Unfortunately, I can't give you an exact list of what that is. Also, because the usage is a lot less than the other platforms, there definitely might be some bugs that haven't been discovered yet.

> Also, does anyone know if there will be work done to further Xamarin.Forms for macOS given the MAUI delays? 

We're actively releasing service releases for Xamarin.Forms on a monthly basis until .NET MAUI goes GA and even a year after that. Bugs will still be solved and stability fixes will still be added. However, as you might have gotten from above, macOS never has been a priority and given the other work that is still there in other areas there is no guarantee your bugs will be fixed in the time you want them to be fixed. To be fair; that is, per license, of course also true for the rest of the Xamarin.Forms product, but still :)

If this is a path you want to go down you'll have to determine if our macOS support is in a state that you can use it. If you do run into anything and you feel you're blocked, I'm happy to look at any PR that you might submit to make that process go faster. I'd even offer some help to get you started with that if time allows for it.

Hope this answers your question!
