### ISSUE TITLE
[Bug] ToolbarItem IsEnabled Error

### ISSUE THREAD

**Issue by pulmuone** [xamarin/Xamarin.Forms#14832]
### Description
    <ContentPage.ToolbarItems>
        <ToolbarItem x:Name="ToolbarItemPrimary0" 
					 Order="Primary" 
					 Priority="0" 
                                        Text="ADD"
					 IsEnabled="False"
					 Command="{Binding AddNewCommand}"/>
    </ContentPage.ToolbarItems>

**If you set IsEnabled="False" of ToolbarItem, an error occurs as shown below.**

Error Message : 
System.InvalidOperationException: 'The BindableProperty "IsEnabled" is readonly.'

Visual Studio 2019 Pro : Version 16.11.5
Xamarin.Forms : 5.0.0.2196
Android : API Level 30 - R

**Comment by lee-m** [comment]
The IsEnabled property is documented as being "For internal use by the Xamarin.Forms platform." so that's probably why. 

Have you tried using the CanExecute functionality of the command bound to the toolbar item instead and simply having it return false?

Something like 

`
AddNewCommand = new Command(() => { ... }, () => false);
`

**Comment by pulmuone** [comment]
I have to use IsEnabled="False" and IsEnabled="True" depending on certain conditions.
Previously, this function worked.

> The IsEnabled property is documented as being "For internal use by the Xamarin.Forms platform." so that's probably why.
> 
> Have you tried using the CanExecute functionality of the command bound to the toolbar item instead and simply having it return false?
> 
> Something like
> 
> `AddNewCommand = new Command(() => { ... }, () => false);`

**Comment by jfversluis** [comment]
> Previously, this function worked.

Do you know when? Because I see this behavior changed back in 2018 so it has been a while :)
Unfortunately, this error is correct, it's readonly. I think that has been changed because the toolbar items differ per platform and not all platforms allows them to be disabled.

In light of .NET MAUI we're not going to change this behavior anymore. If it's something you would like to see changed, please open an issue on the .NET MAUI repository so we can consider it.

Thanks!
