### ISSUE TITLE
XAML Compilation does not identify and report missing tags

### ISSUE THREAD

**Issue by stevechadbourne** [xamarin/Xamarin.Forms#1486]
### Description
Missing a group of parent tags is not caught and no error message is displayed. When the app is run an vague error message is displayed.

### Steps to Reproduce
Here is an example where ViewCell tags are missing

```
<ListView.ItemTemplate>
    <DataTemplate>
        <Grid HeightRequest="{Binding GridHeight}">
            <Label Text="{Binding DisplayName}" />
        </Grid>
    </DataTemplate>
</ListView.ItemTemplate>
```
Here is another example where ResourceDictionary tags are missing

```
<ContentView.Resources>
    <local:MyConverter1 x:Key="MyConverter1"/>
</ContentView.Resources>

```
### Expected Behavior
I would like to see an error message identifying the missing tags.

### Actual Behavior
No error is displayed at compilation time. When the app is run a message is displayed:

Unhandled Exception:
System.InvalidCastException: Specified cast is not valid.

### Basic Information

- Version with issue:
- Last known good version: None
- IDE: VS 2017 15.5.0
- Platform Target Frameworks: iOS/Android
  - iOS:  11.1
  - Android: 7.1 
  - UWP:  None 
- Android Support Library Version:
- Nuget Packages: Xamarin.Forms
- Affected Devices:

**Comment by StephaneDelcroix** [comment]
hey @stevechadbourne, thanks for the report.

Unfortunately, these kind of constructs are valid Xaml and can not be caught without a `lint` tool that we do not have yet.

### the `DataTemplate` example
The `DataTemplate` takes any `object` and turns is into a `Func<object>`. As `Grid` is an object, the syntax is valid. The same issue can be triggered in `C#` by doing `listView.ItemTemplate = new DataTemplate(typeof(MyGrid));`, and there's no way (without a `lint` tool) to catch the fact the `MyGrid` isn't deriving from `Cell` at compilation time either.

### the `ResourceDictionary` example
Again, this is a valid Xaml syntax, as it tries to add a `MyConverter1` to the `ResourceDictionary` the issue is that the `ResourceDictionary` does not exists. Catching the fact that it doesn't exists require knowing the default value for the property, and also make sure that it wasn't already set previously (in code behind, or in parent constructor, or ...). The `C#` equivalent would be `myPage.Resources.Add(new MyConverter1());` and would compile just fine.

That being said, the `ResourceDictionary` problem won't happen in the next version of XF, as the dictionary is lazily created on `get` https://github.com/xamarin/Xamarin.Forms/pull/1295.
