### ISSUE TITLE
i complained about splashscreen loading and then exiting app and was waiting for reply and they closed the issue. Can you  people see how annoying xamarin form staffs are.. bunch of idiots. everybody cant be perfect. is it wrong to admit you are lost?

### ISSUE THREAD

**Issue by sergeibystrov** [xamarin/Xamarin.Forms#15016]
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jfversluis** [comment]
The reason I closed your first issue _and_ this one is because you're coming in with insults straight away which is not appreciated and actually even a violation of our code of conduct. But beyond that, you provide 0 details. I am no mind reader, I don't know your project or what code is involved. Without any info from your side it's impossible to get to the root cause and see what might be going on.

Consider this your last warning, I definitely do want to help you, but not if you keep being rude, in that case I will see no other option than to restrict your access from this repository.

**Comment by sergeibystrov** [comment]
zzz
