### ISSUE TITLE
#Spinner 

### ISSUE THREAD

**Issue by rsultan2021** [xamarin/Xamarin.Forms#15041]
###I'm beginner in Xamarin android , I want to fill spinner  from  database (such as fill Combox ###in Csharp  from data table). 
###Can please help me?
![searchLayout](https://user-images.githubusercontent.com/95768290/148774006-d019352d-3adb-40c5-8f8b-00c843e03507.JPG)

**Comment by jfversluis** [comment]
Hey @rsultan2021 welcome to Xamarin.Forms! I'm happy you found your way to our product and started working with it. However, the issues is not the right place to ask. Issues are meant to be about (potential) bugs in our product, not as a Q&A or how-to. You probably want to try the Discussions tab, Microsoft Tech Community forums or Stack Overflow.

I do think that most people would appreciate some more effort on your side though, like: what have you tried already and where have you failed instead of just a one-line question on how to do something. There are a good number of tutorials and resources out there that should help you learn. Please also have a look at our Microsoft Docs and Microsoft Learn modules.

Closing this here, I hope you will figure it out soon!
