### ISSUE TITLE
Android AOT Compile Fails in System.Drawing.Common

### ISSUE THREAD

**Issue by dgerding** [xamarin/Xamarin.Forms#15154]
**Anyone else getting AOT compile error from System.Drawing.Common in Android all of the sudden?**

It seems since the last XF Nuget release channel update that I am getting a build error in my Xamarin.Forms Android project:

- XA3001: Could not AOT the assembly: System.Drawing.Common.dll		 	0	

When I started poking around I found this article:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

Does anyone have experience using the System.Drawing.EnableUnixSupport setting runtimeconfig.json as part of a work-around/fix with Android (part of Xamarin Forms solution)? 

To be clear, I don't need System.Drawing.  I can't seem to get rid of it as it seems, if I'm reading the error correctly, that the reference is in the Android SDK or related bindings.

So, it seems like we're supposed to migrate away from System.Drawing dependencies and choose from:

-SkiaSharp
-ImageSharp
-Microsoft.MauiGraphics

Any ideas or help appreciated. 

Dave G

**Comment by queequac** [comment]
I have the same error with regular Xamarin.Android project when archiving or deploying an release build to the device.
Not yet sure if this is caused by the latest VS 17.1 update or through the AndroidX nuget packages I am referencing...

**Comment by queequac** [comment]
I can compile with AOT+LLVM enabled if I turn off startup tracking. But I don't want to deploy such a build to the store, since it's slower and double size now. :(

@jonathanpeppers Maybe something broke with VS 17.1? Even the last successful release of my app cannot be built anymore...
I can even create a new Xamarin.Android app and get the same error. It successfully compiles as long as I do not turn on startup tracing. In case of the blank Xamarin.Android app it fails due to `XA3001: Could not AOT the assembly: System.Numerics.dll`
Did 17.1 maybe mess up between traditional Xamarin and .NET 6? (Even though I am wondering this would not have hit anyone in the previews.)

**Comment by dgerding** [comment]
@kristofmaar Thanks for the info. I'm on VS 2022 latest (17.1.2) and am still getting the error. Fingers crossed on https://github.com/xamarin/xamarin-android/issues/6792#issuecomment-1055700500
