### ISSUE TITLE
Can't scroll to end of ViewCell inside a ListView after its content changed!

### ISSUE THREAD

**Issue by RsZoli** [xamarin/Xamarin.Forms#1519]
### Description

I have a ListView with many elements, each of them has some text and a hidden StackLayout. On tapped event i make the StackLayouts visible so the ViewCell's height changes, and i want to make the whole content visible, so i try calling: listView.ScrollTo(viewCell, ScrollToPosition.End, false); but it does nothing. I assume it's because the new end position of the layout is unknown and it prevents the function to work as i expect it.

### Expected Behavior

Somehow get the new end position to supply it to the ScrollTo() method.

### Actual Behavior

see above...

### Basic Information

- Version with issue: ALL
- Last known good version: n/a
- IDE: VS2017 Professional 15.5.2
- Platform Target Frameworks:
  - Android: 7.1 
- Android Support Library Version: 26.1.0.1
- Nuget Packages: Xamarin.Forms 2.5.0.121934
- Affected Devices: ALL

**Comment by pauldipietro** [comment]
@207713 Can you please upload a zipped reproduction that exhibits the issue?

**Comment by 207713** [comment]
@pauldipietro here you go: [https://drive.google.com/open?id=1m7EhkEY5RM4151HqFdAUSNQIPG3m6a-F](https://drive.google.com/open?id=1m7EhkEY5RM4151HqFdAUSNQIPG3m6a-F)

thank you very much!

**Comment by 207713** [comment]
@hartez any word on this? it has almost been 3 months :/

**Comment by samhouts** [comment]
@z07713 Are you still experiencing this issue? Thanks!

**Comment by TingtingAn** [comment]
Any plan to fix it?  it has almost been 2 years

**Comment by jfversluis** [comment]
@TingtingAn can I assume that you are still experiencing this behavior with the most recent versions of Xamarin.Forms then?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
