### ISSUE TITLE
Implicit Styles in Resources do not override Styles in MergedDictionaries

### ISSUE THREAD

**Issue by dstefanov** [xamarin/Xamarin.Forms#1523]
### Description
**Implicit** styles defined in Resource.MergedDictionaries resources could not be overridden with implicit styles defined in the Resource. It does work for explicit styles.
### Steps to Reproduce
1. In ResourceDictionary (A) create style 
```  
<Style TargetType="Button">
    <Setter Property="Background" Value="Red" />
</Style>
```
2. In ResourceDictionary (B) create style
```
<Style TargetType="Button">
    <Setter Property="Background" Value="Blue" />
</Style>
```
3. In ResourceDictionary (B) in MergedDictionaries add ResourceDictionary (A)
4. Create new Page and assign page.Resources = ResourceDictionary (B)
5. Add a button on the page
<Grid><Button/></Grid>
### Expected Behavior
Button Background color should be Blue.
### Actual Behavior
Button Background color is Red.
### Basic Information
- Version with issue: Xamarin.Forms 2.5.0.121934

**Comment by pauldipietro** [comment]
It seems as if I can reproduce the behavior in question, Will assign to Stephane to look at more closely.

**Comment by samhouts** [comment]
@dstefanov Are you still experiencing this issue? Thanks!

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
