### ISSUE TITLE
[Bug] [Android] CarouselView stops displaying content when source changes.

### ISSUE THREAD

**Issue by GalaxiaGuy** [xamarin/Xamarin.Forms#15231]
### Description

Updating the `ItemsSource` on a `CarouselView` makes the content disappear on Android. I found this issue while investigating #15082. On 5.0.0.2012, updating the `ItemsSource` causes the `Position` to stop updating. When I updated to 5.0.0.2337, it also stopped displaying content.

### Steps to Reproduce

1. Create a `CarouselView` with an `ItemsSource` set to something.
2. Update the `ItemsSource` to a new value.

### Expected Behavior

The carousel shows the new content.

### Actual Behavior

The carousel is blank

### Basic Information

- Version with issue: 5.0.0.2337
- Last known good version: 5.0.0.2012

https://github.com/GalaxiaGuy/xf-bugs/tree/bug/broken-carouselview

**Comment by GalaxiaGuy** [comment]
After a bit of investigation, this may only happen if you update the items source by changing the binding context.

**Comment by RicolabRico** [comment]
Hi, 
I have same kind of behavior depending on Xamarin form version.
With old Xamarin forms 5.0.0.224 everithing works fine (changing entire itemsource, refresh perfectly view).Since Xamarin forms 5.0.0.2291, strange behavior like described here.

I have made a simple project and i have same behavior.

In the view a simple carousel with label:

 <ContentPage.Resources>
     <ResourceDictionary>
          <DataTemplate x:Key="PostItemTemplate">
     <Grid  x:Name="GridGlob" BackgroundColor="Green" Margin="5">
                  <Label Grid.Row="1" Text="{Binding .}" />
             </Grid>
 </DataTemplate>
     </ResourceDictionary>
 </ContentPage.Resources>




<CarouselView BackgroundColor="Pink" ItemTemplate="{DynamicResource PostItemTemplate}"
x:Name="carou" Loop="False" ItemsSource="{Binding LesItems}" PeekAreaInsets="50">


in the viewmodel

     private ObservableCollection<string> _LesItems;
     public ObservableCollection<string> LesItems
     {
         get { return _LesItems; }
         set { _LesItems = value;
             OnPropertyChanged();
         }
     }

Now just add a button in the view with command binding viewmodel doing this:

       ObservableCollection<string> obsCol = new ObservableCollection<string>();
         obsCol.Add("ble");
         obsCol.Add("sdf");
         obsCol.Add("erz");
         obsCol.Add("grz");
         obsCol.Add("efs");
         obsCol.Add("new");
         LesItems = obsCol;


since Xamarin forms 5.0.0.2291:
First time, everything is good, 6 items are drawn . If you clic again , You will see only 4 items and most of time only 1 item (debug show that "LesItems" contains 6 items but only 1 is drawn)


With old Xamarin forms 5.0.0.224:
It always works fine. No matter number of clic. all items are drawn that should be normal behaviour because each time you clic it must replace collection by next one and drawing all items.

**Comment by jfversluis** [comment]
Should be fixed by #15266 closing under this assumption, let me know if that's not the case

**Comment by stoff99** [comment]
I have to say thank you! THANK YOU!
I stuck in this bug for a week now and didn't realize that i'm using an older XF package version >.<
I also was not able to find this bug here in git. Maybe my wording ...
Thanks again for this fix! :) 👍
