### ISSUE TITLE
Custom BoxViewRenderer in UWP doesn't fire from external lib.

### ISSUE THREAD

**Issue by MarcosCobena** [xamarin/Xamarin.Forms#1530]
### Description

Having a Custom Renderer for a custom BoxView does nothing if such is placed in a library. However, just moving it to the Forms UWP app works fine. Passing the container assembly at Forms.Init(e, rendererAssemblies) neither works.

### Steps to Reproduce

1. Download GradientBoxView sol. from https://github.com/DevsDNA/GradientBoxView/tree/features/UWP
2. Run UWP Example

### Expected Behavior

To show a gradient at the center of the screen.

### Actual Behavior

You see the screen empty. However, adding a link to UWP GradientBoxViewRenderer.cs at UWP Example app it just works.

### Basic Information

- Version with issue: 2.5.0.121934
- Last known good version: N/A
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - UWP:  10.0.16299.0 (min.: 10.0.10586.0)
- Nuget Packages: N/A
- Affected Devices: N/A

**Comment by samhouts** [comment]
@MarcosCobena  Are you still experiencing this issue? Thanks!

**Comment by MarcosCobena** [comment]
Hey @samhouts I've not tried anymore since then, let me write this down and I'll look for a moment this week to try again. Thanks!

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by MarcosCobena** [comment]
Sorry @samhouts, I couldn't spend time on this. It's OK for me to close this issue for now, I guess no one else has showed interest on it.

Thanks for your time!

**Comment by samhouts** [comment]
@MarcosCobena Thank you for the quick response! We'll close this, but do let us know if you have any other issues!
