### ISSUE TITLE
Xamarin Forms ,master page and navigation page rendering jerk issue on Samsung devices 

### ISSUE THREAD

**Issue by vijaypalve** [xamarin/Xamarin.Forms#1536]
### I am using Xamarin.Forms master page for my application. Where I have bindings for the menu in the master page. But when I deployed on devices such as Samsung J5 or other, rendering of pages is jerky.
It is just very slow.
### Steps to Reproduce

1. Click on Humbergur Menu
2. See rendering of Menu's Its very slow and Jerky
3. Same jerkiness for other navigation pages

### Expected Behavior
It should not be jerky
### Basic Information
  - Android:  7.1.1
 - Xamarin.Forms 2.3.4.247
 - Xamarin.Android.Support.v4 23.3.0

**Comment by hartez** [comment]
@vijaypalve If you update to Xamarin.Forms 2.4 or 2.5, do you still have these issues?

**Comment by jassmith** [comment]
Closed due to inactivity

**Comment by JR-Fire** [comment]
Same problems, again with J5. We're currently unable to upgrade to Xamarin.Forms 2.5 because of building problems with another plugin.

**Comment by jassmith** [comment]
I would need a lot more detail that what you are providing. You need to open a new bug and provide detail, ideally provide a reproduction case too.

**Comment by JR-Fire** [comment]
Ok, what do you want me to provide? I\ll open a new bug but I'd rather give you all the info you need in advance.

**Comment by jassmith** [comment]
Bugs with minimal reproduction cases and clear definitions get resolved far quicker than any other type of bug.

Good bug reports have:

- A clear *specific* issue
- A reproduction case (this is usually a small project)
- A good explanation of what the expected behavior is

So in this case I think "every user action in our app takes forever and is glitchy, even typing on the keyboard and opening the Hamburger menu." is not helpful. You need to call out specific interactions with reproductions so we can dig into them. Otherwise we just kind of look at it and go "well we have plenty of apps that don't have that problem, so one has to wonder what is different."
