### ISSUE TITLE
[UWP] ExportImageSourceHandler doesn't work for Toolbar.Icon

### ISSUE THREAD

**Issue by pauldipietro** [xamarin/Xamarin.Forms#1541]
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=59719

### Description

Images being used as a toolbar icon do not display when using ExportImageSourceHandler, while a regular image does. Reported on UWP.

### Steps to Reproduce

1. Run referred to reproduction on the original report (update to 2.5.0 as needed; should still show the error)
2. Note the visibility of the image on the page
3. Open the toolbar at the top

### Expected Behavior

Toolbar item shows the same image

### Actual Behavior

Image does not show

### Basic Information

- Version with issue: 2.5.0
- Platform Target Frameworks:
  - UWP:  17063

### Reproduction Link

[Attachment from original report](https://bugzilla.xamarin.com/attachment.cgi?id=24912)

**Comment by craigwi** [comment]
My experience with this issue is that it works in Debug, but not when compiling with .NET Native tool chain (as required for UWP store submission).  I am using Xamarin Forms 2.5.

Would love to know a workaround.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by craigwi** [comment]
I reverted the workaround I described above and initial tests indicate no issues (images display in release build of UWP).

I am using Xamarin 4.5.0.725.

**Comment by samhouts** [comment]
Thanks @craigwi !! I'll go ahead and close this now.
