### ISSUE TITLE
Text Alignment on TextView begin reset to Gravity if parent view hidden then shown

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#1557]
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=55243

If a view contains a TextView (lives inside a Grid, if that matters) and the parent view is hidden and then reshown, the TextAlignment of the TextView is being reset back to "Gravity", when it was previously set to End.

I've confirmed this happens by adding a check in a custom render.

Odd behavior: if you change the text in the view, the alignment is restored to "End".  If you do not change the text, it is reset back to Gravity, instead of retaining the right alignment (End) originally set.

### Basic Information

- Version with issue: 2.3.4.231, 2.5.0

### Reproduction Link

[b55243.zip](https://github.com/xamarin/Xamarin.Forms/files/1622872/b55243.zip)

**Comment by jerone** [comment]
Possible duplicate: https://github.com/xamarin/Xamarin.Forms/issues/1396.

**Comment by jassmith** [comment]
This should be fixed in the Shell branch at the very least, can you please confirm?

**Comment by jassmith** [comment]
In fact I think this should be fixed in 3.1.0

**Comment by davidortinau** [comment]
I have confirmed this is NOT fixed in 3.1.0.

**Comment by BlueFire-LLC** [comment]
I have a similar issue but it only occurs if I set Android Target Version to 19 (4.4) or above. Is this the case with others? My app has always supported Android 4.3 (minimum version) so I haven't needed to change the target version until now since Google is forcing us to target 25+.

**Comment by louis030195** [comment]
Same here, with Xamarin.Forms 3.1.0.
StackLayout having child Grid, HorizontalTextAlignment of items in the grid is broken when parent view is set to visible / invisible.

**Comment by scottkdavis** [comment]
It is disheartening that this bug is still open.  I first reported this bug in April 2017 with an accompanying repo solution (the Bugzilla report above).  

In Xamarin Forms 3.1, some alignment issues were resolved, but not all. We are now seeing some gravity issues in locations we never saw before, resulting in even more work after Xam Forms 3 upgrade.

It looks like the issue is related to all locations where a label lives inside an autosized container.  A column definition that has an "auto" or "star" grid length, or an Absolute Layout with a AutoSize specified on the child add method.  My best guess is that rendering performance improvements that were added to Xamarin Forms removed the extra measure/draw events that once existed, and in turn took care of these auto-layout needs.

The only work around I have found is to avoid auto sizing.  Do all the math yourself to position your controls within the detected screen width to accommodate all screen sizes and set a WidthRequest on your controls.

**Comment by samhouts** [comment]
@scottkdavis We spent quite a bit of time working on this issue, and unfortunately, it requires a larger effort than we anticipated. It is an important issue, and it is not forgotten. As @jassmith mentioned, the issue is resolved in a feature branch, and we had hoped to be able to incorporate that fix into a service release; however, it depends on other changes made in that branch, so we won't see it land until the shell branch is merged in. Thank you for reporting this issue, and thank you for your patience!

**Comment by adrianknight89** [comment]
@samhouts I just ran into this issue. When do you expect to merge in the shell branch?

**Comment by adrianknight89** [comment]
@samhouts I have a similar issue with regards to `HorizontalTextAlignment` being lost as I scroll a `ListView` up and down. It's said that the issue is fixed in the shell branch, but I'm testing the code against 4.0 pre-10. :(

**Comment by aharwood2** [comment]
I have a `Button` inside a `Grid` and when hiding then showing the buttons, the text alignment is reset to its default value. Effect is seen on Android device and emulators of all API levels. Using XF 4.0.0.482894.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
