### ISSUE TITLE
Android - ButtonRenderer not using TextFormatted.

### ISSUE THREAD

**Issue by nieweglowski** [xamarin/Xamarin.Forms#1565]
It has been described in #972 but no fix has been added and issue has been closed. Are you going to do anything about it in nearest future?

https://bugzilla.xamarin.com/show_bug.cgi?id=47430

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
