### ISSUE TITLE
[Bug] [Android] [Regression] [Maps] Map.IsShowingUser stops working

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#15815]
### Description

I don't have a repro for this, but I'm seeing it in the wild with my app running on an Android 13 phone. In a nutshell, the blue circle on the map that appears when Map.IsShowingUser is true often (a) takes a while to appear, and (b) stops updating when I put my phone in my pocket and then pull it out later. The former may simply be GPS latency, but the latter is likely a bug. I've started seeing it recently with the Android 13 update, so it's possible this is a regression in that work.

More context: the same app that's displaying the map with the stuck blue circle also has a background service that uses the FusedLocationProviderClient on Android to get the user's location and draw a track on the map. When the bug occurs, the track continues to render correctly, but the blue circle stays in the same place.

### Steps to Reproduce

1. Presumably build an app the displays a map and sets Map.IsShowingUser is true
2. Run the app, then turn off your phone and pocket it. Then walk around
3. Open your phone later, see whether the circle will update or whether it stays in an earlier location

### Expected Behavior

Blue circle updates continuously

### Actual Behavior

It does not

### Basic Information

- Version with issue: 5.0.0.2612
- Last known good version: Earlier versions of Xamarin.Forms.Maps didn't exhibit this problem. I think.
- Platform Target Frameworks: 
  - Android: 13

### Workaround

Setting IsShowingUser to false, and then back to true seems to work.

**Comment by jfversluis** [comment]
Thanks for the report! Unfortunately without any relevant code or reproduction I think the chances of this being fixed are almost 0. If you have any additional information please let us know, thanks.

**Comment by mfeingol** [comment]
Thanks for looking, @jfversluis. If I go to the trouble of putting a repro together, will someone actually take a look and maybe fix it? I've spent a lot of time putting repros together for Xamarin and Maui issues over the years and they're almost never used.

**Comment by jfversluis** [comment]
I'm sorry you feel that way! I think we might look at it more often than you realize, however in the prioritization of issues there are a lot of factors at play. While a reproduction might not be looked at immediately, it will still be very helpful also later on to see if an issue can still be reproduced and if yes, will give us a hint on where to look for a cause when we do get to it.

Since Xamarin.Forms is nearing end-of-life there is not much I can say unfortunately about if and when this will be picked up. However, I hope you see that the information you put in here is very little to go on. Even you yourself put some presumables and "I think"s in there, which makes if very hard on our side, people who do not have a sample project to show this behavior at our disposal, to figure out what might be the cause of this. Let alone if this is a bug.

While you might find that it's going through trouble when putting a repro together, I on the other hand, need to go through a lot of trouble trying to read your mind and reconstruct what your code might look like 😄  Additionally, creating a reproduction is not only helpful for us, but might also help you understand what is going on and often people discover that it's not a bug and/or something they can fix themselves.

Having all that said, a full reproduction might not be needed if you feel it's a lot of effort to put it together, but then some code snippets and relevant information would be really helpful at the very least. Thanks for understanding!

**Comment by mfeingol** [comment]
@jfversluis: understood. It's just that when we do the work to put together a repro and then hear nothing back beyond a "placed in backlog" tag... well, it can be a little frustrating. Especially if the issue is a showstopper for us, e.g. in terms of porting an app to MAUI in anticipation of end of support for XF.

For this issue, ironically, the time I spent working on a repro yesterday helped me track down the issue. Oddly, calling SetMaxUpdateDelayMillis(5000) on a LocationRequest.Builder results in delays up to 15 seconds receiving a location, whereas without it the callbacks come fast and furious. This was not the behavior before my app supported Android 13. This isn't your fault, of course. But hey, at least I can fix the problem and close this issue.
