### ISSUE TITLE
[Android] Incorrect warning about a missing file when using SVG in the Android app

### ISSUE THREAD

**Issue by ddobrev** [xamarin/Xamarin.Forms#1582]
### Description
When an SVG is used on a component, it displays fine but the output gets a warning "FileImageSourceHandler: Could not find image or image file was invalid:". This warning is obviously incorrect since it works.

### Steps to Reproduce

1. Create a Xamarin.Forms application;
2. Get an SVG;
3. Create a drawable vector from it;
4. Use the SVG on a component, such as a button or image;
5. Run the application.

### Expected Behavior
No warning in the output.

### Actual Behavior
The following warning in the output - "FileImageSourceHandler: Could not find image or image file was invalid:".

### Basic Information

- Version with issue: Latest
- Last known good version: None
- IDE: Visual Studio 2017 15.5.3

**Comment by PureWeen** [comment]
[App4.zip](https://github.com/xamarin/Xamarin.Forms/files/1692527/App4.zip)

**Comment by MegaMileyCode** [comment]
I just converted our app to use only Drawable Vector Graphics and I'm experiencing the same issue. The images are shown as expected but the log is filled with these warnings

**Comment by AndreiMisiukevich** [comment]
@samhouts tested. it works fine now, without warnings

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
