### ISSUE TITLE
iOS Picker, DatePicker & TimePicker hide InputAccessoryView when changing from Portrait to Landscape

### ISSUE THREAD

**Issue by erdennis13** [xamarin/Xamarin.Forms#1614]
### Description

iOS 11 introduced a change to the way the InputView and InputAccessoryView content is displayed. When a Toolbar is used as a InputAccessoryView, the Toolbar (and button) gets hidden in landscape mode. 

### Steps to Reproduce

1. Add a Picker, DatePicker or TimePicker to a ContentPage
2. Click the Picker and wait for the keyboard to become visible.
3. Change device orientation from Portrait to landscape. The Picker will hide the Toolbar and Done button.

### Expected Behavior

The Toolbar should be visible above the picker for all device orientations.

### Actual Behavior

The Toolbar is hidden behind the picker in landscape mode.

### Basic Information

- Last known good version: iOS 10
- Platform Target Frameworks:
  - iOS:  11
- Nuget Packages: Xamarin.Forms 2.5.0.122203

### Screenshots

<img width="1118" alt="screen shot 2018-01-18 at 4 11 47 pm" src="https://user-images.githubusercontent.com/8703324/35124061-5238f1ce-fc6a-11e7-9e1c-0f814413baad.png">

### Reproduction Link

[inputview.zip](https://github.com/xamarin/Xamarin.Forms/files/1644641/inputview.zip)

**Comment by bahrman** [comment]
The description of this bug only tells half the story.  If the page is initially rendered in landscape mode, then the picker is displayed, then the device is rotated to portrait mode, the toolbar will be displayed above the picker with a gap between the picker and the toolbar.  An easy way to reproduce this is to create an app with a start page containing a button that navigates to a second page that contains the picker.  This way, you don't have to restart the app in order to reproduce the problem with different starting orientations.
