### ISSUE TITLE
Desktop support: MenuItem.Command CanExecute delegate not visually respected (macOS)

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#1638]
### Description

On macOS, when directly setting MenuItem.Command to an ICommand implementation (i.e. without a binding), that has both Execute and CanExecute delegates, while the CanExecute delegate always executes, it's returned value is not *visually* respected by the MenuItem. Therefore, when a CanExecute delegate returns false, the MenuItem's Execute delegate won't be invoked but the MenuItem won't be disabled.

### Steps to Reproduce

1. Run the attached sample and navigate to the context menu page. 
2. Right click on the BoxView and select a color from the context menu.

### Expected Behavior

The BoxView color changes to the chosen color, the Execute delegate for the Command can't be invoked, and the chosen color is disabled on the context menu.

### Actual Behavior

The BoxView color changes to the chosen color, the Execute delegate for the Command can't be invoked, and the chosen color remains enabled on the context menu.

### Basic Information

- Version with issue: 2.5.0.122203
- IDE: VSMac
- Platform Target Frameworks: macOS (10.12.6)

### Reproduction Link

[DesktopSupportIssues-MenuItemNotDisabledByDelegate.zip](https://github.com/xamarin/Xamarin.Forms/files/1655831/DesktopSupportIssues-MenuItemNotDisabledByDelegate.zip)

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by jfversluis** [comment]
There is a workaround for this available and macOS has not been a priority (or even officially supported platform) for Forms. Considering all the other priorities we have I don't think this will be fixed, unless someone provides a PR for it. Thanks!
