### ISSUE TITLE
Desktop support: Can't set MenuItem.Icon with an image from an asset catalog (macOS)

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#1641]
### Description

On macOS, attempting to set MenuItem.Icon from an image stored in an asset catalog results in an Exception (System.Exception) being thrown.

### Steps to Reproduce

1. Run the attached sample.

### Expected Behavior

The sample runs and you are able to browse to the context menu page (XAML) where color icons appear on the context menu.

### Actual Behavior

A System.Exception is thrown in AppDelegate.DidFinishLaunching.

### Basic Information

- Version with issue: 2.5.0.122203
- IDE: VSMac
- Platform Target Frameworks: macOS (10.12.6)

### Reproduction Link

[DesktopSupportIssues-AssetCatalog.zip](https://github.com/xamarin/Xamarin.Forms/files/1656262/DesktopSupportIssues-AssetCatalog.zip)

**Comment by chucker** [comment]
The exception in Xamarin Forms 2.5.0 is:

>Could not initialize an instance of the type 'AppKit.NSImage': the native 'initWithContentsOfFile:' method returned nil.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.

Upgrading to 4.5.0 makes that exception go away.

However, no icon actually appears:

<img width="302" alt="image" src="https://user-images.githubusercontent.com/20194/76805155-6568f780-67de-11ea-9844-267e2fdf38c5.png">

It seems this is supposed to happen [here](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.MacOS/Extensions/NSMenuExtensions.cs#L58).

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
