### ISSUE TITLE
[Enhancement] UWP: Button: AccessKey support

### ISSUE THREAD

**Issue by kingces95** [xamarin/Xamarin.Forms#1672]
![image](https://user-images.githubusercontent.com/4120386/35463298-0af5e77e-0294-11e8-82d1-22c8f5e1b241.png)

## Rationale

Disabled and/or power users find the keyboard easier/faster to use than the mouse. 

## Implementation

A UAP platform specific subset of https://docs.microsoft.com/en-us/windows/uwp/design/input/access-keys as can be exposed via the following:

```csharp
public class View {
	public static readonly BindableProperty AccessKey; // string
	public static readonly BindableProperty AccessKeyPlacement; // AccessKeyPlacement
}

public enum AccessKeyPlacement {
	Auto = 0,
	Top, 
	Bottom, 
	Right, 
	Left, 
	Center, 
}
```

## Expected Result

 https://docs.microsoft.com/en-us/windows/uwp/design/input/access-keys

## Implications for CSS

None.

## Backward Compatibility

None.

## Difficulty : Easy

The test matrix should include all derivations of View typically clicked or tapped.

**Comment by henricm** [comment]
Should implementation be UWP only? If so, should the Bindable properties be added to a WindowsSpecific View class or shared View class?

**Comment by henricm** [comment]
I have started implemented this and I've got the basics to work.
So far I've put the bindable properties in the shared `VisualElement` class and updated the Windows `VisualElementRenderer`. I've tried it on Label and Button classes and it seems to work as expected. I have a few questions:

1. In which class do we want these properties - is `VisualElement` the right way to go?
2. Should we place them in a Windows specific `VisualElement` rather than the view class shared between platforms. I thought maybe it would be easier to use if we do it this way, instead of having to use the `button.On<Windows>()...` approach. But I'm not sure we want to add this to more platforms in the future?
