### ISSUE TITLE
[F100] Allow overriding theme capitalization settings in Android

### ISSUE THREAD

**Issue by jassmith** [xamarin/Xamarin.Forms#1676]
## Rationale

Sometimes changing the theme on an android app can be a bit difficult. It may be useful for people to be able to override theme capitalization settings without modifying the theme or using an effect.

## Implementation

```csharp
button.On<Android>().SetAllCaps (true/false);
```

### Android
When set to false, the button should not auto-cap letters. When set to true it should.

Should directly pass ABP value to `Control.SetAllCaps (value);`

### iOS
No change

### UWP
No change

## Implications for CSS
Not relevant to CSS

## Backward Compatibility

Third party renderers may need to be updated to ensure that this functionality is supported through the new official mechanism. Further we will need to be careful to code the changes to the renderers in a careful manner to ensure that if someone is already using an effect support this feature that the effect is as best as possible not broken by our changes.

## Difficulty : Trivial

Yeah, straightforward and easy.

**Comment by alanag13** [comment]
I can take this!

**Comment by jassmith** [comment]
Moving to InProgress :)

As a matter of practice (and nothing personal) we will probably move this back to an unclaimed pool if we dont get just a ping or something that work is still going on every 2 weeks or so.

**Comment by alanag13** [comment]
So `SetAllCaps` is a property of `TextView` (from which `Button` inherits) rather than `Button`. Should the platform-specific be added at the `TextView` level, or is this item only relevant to `Button`? Are there any other controls that inherit from `TextView` besides `Button`, `Label`, `Switch`, and `Entry`?  That seems to be the complete list best I can tell based on this: https://developer.android.com/reference/android/widget/TextView.html

**Comment by alanag13** [comment]
@jassmith can you let me know your thoughts on the above? Otherwise I'll just assume that for completion's sake it's best to apply this to all the `TextView` controls I mentioned.

**Comment by jassmith** [comment]
Yes, sorry for the delay. I was in boston all last week. Still catching up.

It would be ideal to add this to each of those controls yes. Unfortunately as its a platform specific and we wouldn't want to add this to each base class you will likely need to do a fair amount of copy/paste work here.

**Comment by alanag13** [comment]
no problem at all, hope you enjoyed Boston.
I don't have a problem with some extra copy/paste if it produces something considered more ideal 😄 . Thanks.

**Comment by PureWeen** [comment]
I'm not setting SetAllCaps for this issue
https://github.com/xamarin/Xamarin.Forms/issues/1683

But just wanted to reference other Caps efforts happening right now

**Comment by alanag13** [comment]
@jassmith hit a bit of snag here -- since Android doesn't provide a getter for `IsAllCaps`, and the default value of the control could vary based on the theme, how do I determine what the default should be?

I could just pick an arbitrary default and not change the renderer until `SetAllCaps` is explicitly called, but then calls to `GetIsAllCaps` could return a potentially misleading (incorrect) value at any time before that happens. Should this perhaps be implemented in a way that doesn't use Bindable properties (an event)?

**Comment by alanag13** [comment]
I got some inspiration after I saw what @rmarinho did here: https://github.com/xamarin/Xamarin.Forms/pull/1829/files

Basically I'll just use an enum of default, true, false rather than a bool and that should take care of this.

**Comment by jassmith** [comment]
@alanag13 sounds great, sorry I didn't see your response! Looking forward to the PR.

**Comment by alanag13** [comment]
Despite what I said above I struggled a little bit because when the user chooses `Default`, I need to be able to check to see what `IsAllCaps` is/was by default for the Android theme, but no such property exists. I found a (somewhat unconventional) way to determine this...

When you use `SetAllCaps` and set `true`, `TextView.TransformationMethod` becomes an instance of `AllCapsTransformationMethod`... which is an internal Android class, so unfortunately we can't just do an `is` or something... however, we can use `Java.Lang.Object` to get the same of that class. Would comparing the name of that class to its known value if `SetAllCaps` is set to `true` here be acceptable?

**Comment by davidortinau** [comment]
@jassmith ^

**Comment by samhouts** [comment]
@alanag13 Are we ready to create the PR in the main repo?

**Comment by samhouts** [comment]
@alanag13 ping! Let us know if you'd like us to return this to the backlog. Thanks!

**Comment by alanag13** [comment]
Hey @samhouts, same here, sorry for the delay but I'll try to get this to you really soon. If I can't then we can go ahead and return this but I'd like to get it out to you in the next week or so.

**Comment by davidortinau** [comment]
I suspect @alanag13 will be a little too busy to continue on this. 

![image](https://user-images.githubusercontent.com/41873/44231762-d2309180-a164-11e8-9f45-44dd1f366af3.png)

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">I have a son. His name is Ivan Thomas Grgic and he is cooler than you. <a href="https://twitter.com/hashtag/dadmode?src=hash&amp;ref_src=twsrc%5Etfw">#dadmode</a> <a href="https://t.co/HsZoTwA9VH">pic.twitter.com/HsZoTwA9VH</a></p>&mdash; Alan Grgic (@spellgrgicright) <a href="https://twitter.com/spellgrgicright/status/1029758412131852288?ref_src=twsrc%5Etfw">August 15, 2018</a></blockquote>

Back to the pile

**Comment by alanag13** [comment]
@davidortonau @samhouts sorry to be such a tease for so long about getting this one done! Fatherhood is definitely a blocker for now but I'll make my ( hopefully more predictable ) return to OSS in time.

**Comment by ravero** [comment]
@alanag13 this is very useful but addition, but what if we expand the allCaps as an abstraction in Xamarin.Forms itself? What I mean is, sometimes is useful if we could just set `Label.IsAllCaps = true` and it works not just in Android, but also in iOS. I think this feature itself is useful enough to not be a platform specific.

What you think about it @davidortinau? I know that this would change the structure of this whole spec, since It would need to add a BindableProperty to the label and implement specific logic in iOS to handle capitalising its contents, but I think it's worth!

**Comment by ravero** [comment]
@jassmith this is very useful but addition, but what if we expand the allCaps as an abstraction in Xamarin.Forms itself? What I mean is, sometimes is useful if we could just set Label.IsAllCaps = true and it works not just in Android, but also in iOS. I think this feature itself is useful enough to not be a platform specific.

What you think about it @davidortinau? I know that this would change the structure of this whole spec, since It would need to add a BindableProperty to the label and implement specific logic in iOS to handle capitalising its contents, but I think it's worth!

**Comment by jfversluis** [comment]
This won't be happening for Forms anymore. If this is still of interest to anyone, please make sure to express it for .NET MAUI. Thanks!
