### ISSUE TITLE
[Enhancement] Add EvaluateJavaScript method to WebView

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#1699]
## Rationale

Forms does not currently have a simple cross-platform way to call JavaScript methods in a WebView and return the results.

## Implementation

Add a method to WebView, something like:

`public async Task<string> EvaluateJavaScript(string script);`

The renderers should map this to InvokeScriptAsync on UWP, EvaluateJavascript on iOS, and EvaluateJavascript on Android.

## Backward Compatibility

This is a brand new method, so there should not be any backward compatibility issues.

## Difficulty: Moderate

**Comment by alanag13** [comment]
I can take this!

**Comment by alanag13** [comment]
@hartez I noticed that this is mostly already implemented as `WebView.Eval(script)`, with the only missing piece being that that method is void rather than returning `string` as this suggests. 

It doesn't look like it would be safe to simply change this implementation to return a string instead, namely because on GTK and Tizen the native methods this is mapped to in the renderers return void (Android does too, but we can use `EvaluateJavascript` there as you proposed), unless

Perhaps the new method should be named something like `GetEvaluateJavascriptResult` for platforms where it's supported? It seems odd/confusing to me to have both `Eval` and `EvaluateJavascript`, and we can't just remove `Eval`.

**Comment by alanag13** [comment]
@adamped, @davidortinau looking for opinions here -- given what we said about the support matrix, would it be safe to implement this by having `WebView.Eval` return `string`  and just having it operate as usual but return `null` on GTK and Tizen?

**Comment by jassmith** [comment]
We should deprecate Eval once EvaluateJavaScript is supported and works everywhere.

It is not safe to re-use the Eval method as this will break backwards compat.

**Comment by alanag13** [comment]
That makes much more sense and I figured we shouldn't re-use Eval, but I was stuck on the fact that both `Eval` and `EvaluateJavascript` would exist side-by-side. For some reason deprecating didn't occur to me :-), thanks for your input.

**Comment by jassmith** [comment]
@alanag13 hows it going? :) You sure got a lot of these. Still planning on this one?

**Comment by alanag13** [comment]
You might notice a pattern: I've done a lot of webview customizations :-).

Yup, though I do have a question on this one -- how should I handle platforms where this feature cannot be implemented (API for running JavaScript returns void?) Just do nothing? NotImplementedException?

**Comment by jassmith** [comment]
return null

**Comment by alanag13** [comment]
I have a branch for this here and will have a PR soon (probably later this week):
https://github.com/XamarinFormsCommunity/Xamarin.Forms/tree/feature/1699-webview-evaluate-js

I have a few small changes left around handling how platforms handle js script errors differently.
