### ISSUE TITLE
[Enhancement] Allow DetectReadingOrderFromContent on UWP

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#1717]
## Rationale

Currently there is no way to utilize TextReadingOrder="DetectFromContent" in UWP from a Forms application without creating a custom renderer.

## Implementation

BindableProperties to enable this behavior will have to be added to the Windows PlatformSpecifics for the relevant controls:

InputView (Entry/Editor):
```
public static readonly BindableProperty DetectReadingOrderFromContentProperty = 
BindableProperty.Create("DetectReadingOrderFromContent", typeof(bool), typeof(InputView), false);
```

Label:
```
public static readonly BindableProperty DetectReadingOrderFromContentProperty = 
BindableProperty.Create("DetectReadingOrderFromContent", typeof(bool), typeof(Label), false);
```

When this PS is enabled, the UWP renderers should set the `TextReadingOrder` property of the native controls to `DetectFromContent`. Otherwise, `TextReadingOrder` should remain in its default value of `UseFlowDirection`.

## Backward Compatibility

This property will default to `false`, which will map to the current default value. So adding this PS should not cause any backward compatibility issues. 

## Difficulty: Easy

**Comment by henricm** [comment]
Started working on this and think I got the property added to `InputView` and I updated the `EntryRenderer` is so `TextReadingOrder` is updated as described above. I'm now testing with some Arabic and English texts set in the Entry control. However, it looks like we may also need to also update the `TextAlignment` property when updating `TextReadingOrder` for it to have any effect.  For example the 
[EntryRenderer.UpdateAlignment](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.UAP/EntryRenderer.cs#L122)
causes the direction to flip back again even though `TextReadingOrder` is set to `DetectFromContent`. So, I'm not sure how we want to update the [TextAlignment](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.textalignment) (if we want to do that) since it has slightly different possible values.

**Comment by henricm** [comment]
Realize I'm not sure how we should verify that this actually works. Is there anyone that could provide some more details? 
For example, if we set an Arabic text and set FlowDirection to LeftToRight and then set the TextReadingOrder to DetectFromContent (which should cause some kind of direction switch to RightToLeft). What would be the expected behaviour? Should the text align right/left? Should special characters switch places, as described here: 
https://docs.microsoft.com/en-us/previous-versions/windows/apps/jj712703(v%3dwin.10)
etc.

Example code that sets an Arabic text and adds buttons for toggling between TextReadingOrder property.

```
                private void DetectFromContent (bool detect) 
		{
			_entryLeftToRight.On<Windows> ().SetDetectReadingOrderFromContent (detect);
		}

		protected override void Init()
		{
			_entryLeftToRight= new Entry 
			{
				Text = "قطت بخطوط وايرلندا أن على, وصل والكوري الواقعة الساحلية قد. شيء الشتوية الإمتعاض ٣٠, وكسبت بأيدي ا الى هو, أم‬",
				FlowDirection = FlowDirection.LeftToRight
			};
			var buttonDetectFromContent = new Button 
			{
				Text = "Detect from content",
			};
			buttonDetectFromContent.Clicked += (x, o) => DetectFromContent (true);

			var buttonUseDefault = new Button 
			{
				Text = "Use FlowDirection"
			};
			buttonUseDefault.Clicked += (x, o) => DetectFromContent (false);

			var stack = new StackLayout 
			{
				Children = {
					_entryLeftToRight,
					buttonDetectFromContent,
					buttonUseDefault,
				}
			};

			Content = stack;
		}

```

**Comment by hartez** [comment]
As I understand it, [DetectFromContent for TextReadingOrder should not affect alignment](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.textreadingorder#Remarks).

**Comment by henricm** [comment]
Ah - I see now. Makes sense I guess. Will try to wrap up and create a PR.
