### ISSUE TITLE
Wrap Veldrid? (A high performance cross platform graphics library for .NET)

### ISSUE THREAD

**Issue by jarlestabell** [xamarin/Xamarin.Forms#1720]
## Summary
Make a Veldrid wrapper component?

I just want to make sure you guys are aware of this library:
https://github.com/mellinoe/veldrid

"A cross-platform, graphics API-agnostic rendering library for .NET. "

To me it looks like a great way to do portable high performance (low level) 2D and 3D graphics programming in .NET and which could(?) be used in Xamarin Forms apps.

## Intended Use Case
HIgh performance cross platform 2D and 3D graphics. And perhaps a foundation to build complex cross platform graphical components upon.

**Comment by StephaneDelcroix** [comment]
> I just want to make sure you guys are aware of this library: https://github.com/mellinoe/veldrid

thanks, we're aware

**Comment by tzachshabtay** [comment]
@StephaneDelcroix not sure why this was closed?

Currently, as far as I can tell, xamarin forms only offers an opengl widget but opengl is on the way out (already deprecated on mac).
Instead of creating Vulkan widget, Metal widget, DirectX widget and OpenGLES widget, just having a Veldrid widget seems like the most reasonable way forward to me.

**Comment by Kemsekov** [comment]
Veldrid is really good. If xamarin will use it as backend then it will simplify life for xamarin devs as well as give veldrid more attentions and improvement. This is win - win situation.
