### ISSUE TITLE
Expand/Collapse issue for inner grid within Listview.

### ISSUE THREAD

**Issue by ojasteredesai** [xamarin/Xamarin.Forms#1745]
Hi,
This is regarding expand/collapse issue for inner grid within listview.

**Platform - IOS**
**Issue#1- Expand/Collapse function gradually becomes time consuming after performing** expand/collapse several times.

PFA video - IOS Expand-Collapse issue 1.mp4

**Platform - IOS/Android**
**Issue#2- When the expandable grid is not visible (Collapsed) bydefault and we perform expand/collapse functions, instead of OnImageTapped event of toggle button the itemselected of listview is fired.**

PFA video - IOS Expand-Collapse issue 2.mp4

PFA code - ExpandableSectionIssue.ZIP
[ExpandableSectionIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/1677538/ExpandableSectionIssue.zip)

PFA Videos for issues -
[IOS Expand-Collapse issues.zip](https://github.com/xamarin/Xamarin.Forms/files/1677534/IOS.Expand-Collapse.issues.zip)

**Comment by ojasteredesai** [comment]
Hi,
Any updates on this issue...

**Comment by PureWeen** [comment]
[ExpandableSectionIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/1691261/ExpandableSectionIssue.zip)

I modified your sample slightly

A few things
1) the performance is improved if you set the caching strategy to recycle. https://developer.xamarin.com/guides/xamarin-forms/user-interface/listview/performance/
Since you have a lot of items in that list the performance gets pretty slow using retain

2) I wouldn't search the visual tree to interact with the items. With how templating works that's going to give you some odd behavior and it'll be hard to do that right.  I modified the sample a bit to use commanding which makes it go a lot smoother

3) You can't disable selection of items in a ListView so you have to kind of hack the behavior of disabling selection
https://stackoverflow.com/questions/46271416/how-can-i-disable-the-click-in-a-list-view-xamarin-form
