### ISSUE TITLE
Desktop support: can't set a single modifier on an accelerator (macOS)

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#1749]
### Description

On macOS, you can't set a single modifier on an `Accelerator`. However, multiple modifiers can be set.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the ContextMenuPage.
3. Right-click on the `BoxView` and examine the context menu accelerators for each `MenuItem`.

### Expected Behavior

On the context menu you should see CTRL + R for Red, CMD + G for Green, and Shift + B for Blue.

### Actual Behavior

On the context menu you see SHIFT + CMD + R for Red, SHIFT + CMD + G for Green, and SHIFT + CMD + B for Blue.

I suspect the problem is that modifiers are only processed if there's more than 1 (https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.MacOS/Extensions/NSMenuExtensions.cs#L74), which is why multiple modifiers work.

### Basic Information

- Version with issue: 2.5.0.122203
- IDE: VSMac
- Platform Target Frameworks: macOS (10.12.6)

### Reproduction Link

[DesktopSupport-Modifier.zip](https://github.com/xamarin/Xamarin.Forms/files/1678611/DesktopSupport-Modifier.zip)

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!
