### ISSUE TITLE
Regression Issue - Content set after an await is not visible

### ISSUE THREAD

**Issue by ceblanda** [xamarin/Xamarin.Forms#1760]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Android only, Master/Detail window opened from master, Content is blank if set after an await

### Steps to Reproduce

1. Run the attached app.  Label on the detail screen reads "Before the await", then changes to "After the await"
2. Open the Master menu and choose the TestPage option.  This opens the same page as step 1.  The "Before the await" label is visible, then the view is blank.

### Expected Behavior
The window should behave the same in both steps.

### Actual Behavior
The second label is not displayed in the second step

### Basic Information

- Version with issue: 2.5.0 (and 2.4)
- Last known good version: 2.3.4.270
- IDE: VS2017
- Affected Devices: Android

### Reproduction Link
[HeaderTest.zip](https://github.com/xamarin/Xamarin.Forms/files/1682920/HeaderTest.zip)

**Comment by PureWeen** [comment]
Might be related to
https://github.com/xamarin/Xamarin.Forms/issues/1736

It seems the issue here is with the ScrollView control.  The label is inside a scrollview and when it's set after the await it doesn't render the new label. If you change the container to a StackLayout then it does render the label after the await 

I've attached a slim down version of the reproduction.  In HeaderPage.cs you'll notice 

```
     // works
            /*Content = new StackLayout
            {
                Children = { _headerPageContent }
            };*/

            // doesn't work
           Content = new ScrollView
            {
                Content = _headerPageContent
            };
```

The steps to reproduce listed are still the same
[HeaderTest.zip](https://github.com/xamarin/Xamarin.Forms/files/1687697/HeaderTest.zip)

iOS works fine

**Comment by ceblanda** [comment]
This is still not working with 3.1.0.583944

**Comment by hartez** [comment]
@ceblanda Can you expand on that? I've tried @PureWeen's repro with 3.1.0.583944 and it's working.

**Comment by ceblanda** [comment]
@PureWeen's repo does work, but original repo does not.  It appears @PureWeen removed code that is relevant to the original issue.
