### ISSUE TITLE
[Proposal] Conditional XAML

### ISSUE THREAD

**Issue by workgroupengineering** [xamarin/Xamarin.Forms#1782]
### Description
Allow [Conditonal XAML](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/conditional-xaml) 
### Steps to Reproduce
none

### Expected Behavior
like [this](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/conditional-xaml)
### Actual Behavior
none
### Basic Information

- Version with issue: All
- Last known good version: none
- IDE: All
- Platform Target Frameworks: All
- Nuget Packages:
- Affected Devices:

### Screenshots

none

### Reproduction Link

none

**Comment by StephaneDelcroix** [comment]
what's the rationale for this ?

**Comment by workgroupengineering** [comment]
hi,
in my case i would using for debugging purpose,but there are endless use cases.
very very stupid example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ContentView
	xmlns="http://xamarin.com/schemas/2014/forms"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:debug="http://xamarin.com/schemas/2014/forms?DEBUG">
       <ContentView.Content>
            <StackLayout>
                   <debug:StackLayout>
                       <Label Text="Debuging"/>
                       <Label Text="{Binding ItemsClicking}"/>
                   </debug:StackLayout>
                   .....
            </StackLayout>
       </ContentView.Content>
</ContentView>
```
DEBUG is codintional compiling symbol.

**Comment by StephaneDelcroix** [comment]
how does

> DEBUG is codintional compiling symbol.

fits with

> Conditional statements are evaluated at runtime (https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/conditional-xaml)

?

**Comment by dansiegel** [comment]
@workgroupengineering while I can certainly understand the desire for tying into compilation symbols, as that would open up the ability to have elements added to the UI to display debug info, but only for the Debug build, I really have to agree with @StephaneDelcroix. I don't see how your example fits with the original issue.

I would also add here, Xamarin Forms has long since provided mechanisms for conditionally setting properties or adding Views at runtime through [OnPlatform](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/OnPlatform.cs) or [OnIdiom](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/OnIdiom.cs). While those are basic (and very common) conditions, the implementations really are very straight forward and very easy to replicate for your own more complex conditions.

**Comment by programmation** [comment]
I have done this kind of thing by binding to `StaticResource`s from the app's `ResourceDictionary`. If you have a key in the dictionary that's set at runtime you can switch `IsVisible` as needed on your debug element. Because it's in the app's `ResourceDictionary` it also works with the forms previewer.

**Comment by dansiegel** [comment]
@programmation that certainly works... though you do end up with a View that is created when it doesn't need to be

**Comment by programmation** [comment]
@dansiegel for debug I don't care as much as I might for runtime. However there are so many other inefficiencies in the Xamarin.Forms system as a whole that I'm willing to tolerate this little inefficiency, until I'm happy it's working as advertised, then comment out the XML in the source before final testing - but only if I can prove that leaving it in is creating too much of an overhead. Otherwise I just leave it in and accept it as part of the inherent overhead of using Forms in the first place.

**Comment by workgroupengineering** [comment]
Hi, I would suggest that it works like a precompiler without compromising performance in runtime.

**Comment by StephaneDelcroix** [comment]
@dansiegel and @programmation: you're a bit out of context here.

@workgroupengineering 
> [...]I would suggest that it works like a precompiler[...]

that's definitely not the intent of conditional xaml.

XF already supports conditional xmlns, depending on platform (`targetPlatform` argument of the `cir-namespace`)

**Comment by workgroupengineering** [comment]
Hi @StephaneDelcroix ,
thank you for explaining.
I have found [this](https://github.com/firstfloorsoftware/xcc/wiki) project that comes close to what I want.
