### ISSUE TITLE
UWP - OnShareTargetActivated Init Error

### ISSUE THREAD

**Issue by AlexF12004Roma** [xamarin/Xamarin.Forms#1783]
### Description

When a Forms App starts after a onShareTarget invocation,  Xamarin.Forms.Forms.Init(e) throws an Exception.

### Steps to Reproduce

1.  Add Share Target declaration in UWP (any kind)
2.  Share with the APP
3.  Try to Init Forms

### Expected Behavior
Frame rootFrame initialized

### Actual Behavior
Exception

### Basic Information

- Version with issue: 2.5.0
- IDE: VS2017
- Platform Target Frameworks: 
  - UWP:  Win10 November Update

**Comment by PureWeen** [comment]
This is an interesting (annoying?) one. 

The issue here is that on UWP Xamarin Forms only really works single windowed so you can't re-init the new window opened by OnShareTargetActivated  if you already have a window opened.

To handle a case where the app is opened from OnShareTargetActivated you essentially just have to call the same code in OnLaunched. Both of those args just inherit from *IActivatedEventArgs* so you can pretty much just copy and paste the code from OnLaunched or just move it to a common method

As far as cases where the app is already running you can still control the open window so in this case you can close the new window and use the already running one.

Usually I'll just add logic in and inspect the passed in args to determine if the app is opening new or if it's already running

Not a perfect solution but that's currently how the interactions with UWP work

**Comment by AlexF12004Roma** [comment]
Mmmm.

I  put Forms init in a common method, when the app is already running rootFrame is not null but 
rootFrame.Content is null and if i call "rootFrame.Navigate(typeof(MainPage), files);" i got Exception

````
protected async override void OnShareTargetActivated(ShareTargetActivatedEventArgs args)
        {
            base.OnShareTargetActivated(args);
            Frame rootFrame = InitForms(args);
            //rootFrame.Navigate(typeof(MainPage), files);
            Window.Current.Activate();
            //Chiude L'app
            op.ReportSubmittedBackgroundTask();
        }



`private Frame InitForms(IActivatedEventArgs e)
        {
            Frame rootFrame = Window.Current.Content as Frame;

            // Do not repeat app initialization when the Window already has content,
            // just ensure that the window is active
            if (rootFrame == null)
            {
                // Create a Frame to act as the navigation context and navigate to the first page
                rootFrame = new Frame();

                rootFrame.NavigationFailed += OnNavigationFailed;

                Xamarin.Forms.Forms.Init(e); 

                if (e!=null && e.PreviousExecutionState == ApplicationExecutionState.Terminated)
                {
                    //TODO: Load state from previously suspended application
                }

                // Place the frame in the current Window
                Window.Current.Content = rootFrame;
            }

            return rootFrame;
        }

**Comment by AlexF12004Roma** [comment]
I think it is the same as "OnFileActivated", this works well because if the app is open rootFrame.Content is not null so i can get the already opened MainPage.


```
protected override void OnFileActivated(FileActivatedEventArgs e)
        {
            base.OnFileActivated(e);                                  
            Frame rootFrame = InitForms(e);
            if (rootFrame.Content == null)
            {
                rootFrame.Navigate(typeof(MainPage), file);
                var mainPage = (MainPage)rootFrame.Content;
                mainPage.OpenIncomingFile(fsItem);
            }
            else
            {
                var mainPage = (MainPage)rootFrame.Content;               
                mainPage.OpenIncomingFile(fsItem);
            }
           
            Window.Current.Activate();            
        }
```

**Comment by PureWeen** [comment]
this is roughly what I mean

```
protected override void OnShareTargetActivated(ShareTargetActivatedEventArgs e)
        {
            base.OnShareTargetActivated(e);
             
            if(e.PreviousExecutionState == ApplicationExecutionState.Running)
            {
                var newWindow = Window.Current;
                Xamarin.Forms.Device.BeginInvokeOnMainThread(async () => 
                {
                    await App4.App.NavPage.PushAsync(new SecondPage());

                    await newWindow.Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, () => {
                        newWindow.Close();
                    });
                });
            }
            else
            {
                Frame rootFrame = Window.Current.Content as Frame;

                // Do not repeat app initialization when the Window already has content,
                // just ensure that the window is active
                if (rootFrame == null)
                {
                    // Create a Frame to act as the navigation context and navigate to the first page
                    rootFrame = new Frame();

                    rootFrame.NavigationFailed += OnNavigationFailed;

                    Xamarin.Forms.Forms.Init(e);

                    if (e.PreviousExecutionState == ApplicationExecutionState.Terminated)
                    {
                        //TODO: Load state from previously suspended application
                    }

                    // Place the frame in the current Window
                    Window.Current.Content = rootFrame;
                }


                if (rootFrame.Content == null)
                {
                    // When the navigation stack isn't restored navigate to the first page,
                    // configuring the new page by passing required information as a navigation
                    // parameter
                    rootFrame.Navigate(typeof(MainPage), null);
                }
                // Ensure the current window is active
                Window.Current.Activate();
            }
        }
```

**Comment by AlexF12004Roma** [comment]
Sorry, there is something i dont understand.

**Case 2**: app not open - OK app starts [The problem was due to async added on method OnShareTargetActivated]; all seems working BUT when i call any **DisplayAlert** app crash, all modal windows let app crash.

**Case 1**: app already open -  BeginInvokeOnMainThread crash the app immediately also if i comment le line [ push new second page] 
App4.App (App is the UWP App class not the PCL one right?)

**Comment by PureWeen** [comment]
So I think with the DisplayAlert you're running into is a Xamarin Forms bug which is essentially this
https://forums.xamarin.com/discussion/94174/crash-calling-displayalert-when-using-windows-assigned-access

Unfortunately I wasn't able to find a way to work within the current Xamarin Forms system to get around the issue so that you can just use the DisplayAlert mechanism.

You can build your own dialog from UWP to coordinate the alert to the right dispatcher though
```
 await CoreApplication.GetCurrentView().Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, async () =>
            {
                var alertDialog = new ContentDialog
                {
                    Content = "conent",
                    Title = "title"
                };

                ContentDialogResult result = await alertDialog.ShowAsync();
            });
```

I'll create an issue around this

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/1790

**Comment by AlexF12004Roma** [comment]
Thank you.
I will wait the Fix.

The crash when i call 
```
await newWindow.Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, () => {
                        newWindow.Close();
                    });
```

Is due to the same issue, right?

**Comment by PureWeen** [comment]
That one I'm not actually not as sure about the direct cause... I saw that exception also but for me I only got that exception when debugging the app.. 

If I just run the app outside of a debugger then it all just works fine with no crash and the window closes without any issue

I haven't followed that thread very far yet though to see what causes that Access Violation error and if it's more related to the debugger then something to be worried about.   I would say that's not a Forms related error though since that's all code inside the UWP space and not inside Forms
