### ISSUE TITLE
[Enhancement] Seal public attributes 

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#1788]
## Rationale 

Some of the attributes in Forms not follow the guidance for [CA1813](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1813-avoid-unsealed-attributes). These include:

- `ExportEffectAttribute`
- `ResolutionGroupNameAttribute`
- `DependencyAttribute`

Sealing these attributes would give us a minor performance boost during application startup (as we search through assemblies for Effects and service implementations). 

We should also seal `PreserveAttribute`; while it is not reflected at runtime, it is currently in the `Internals` namespace which is meant to convey that third parties should not be directly utilizing it. Marking it as `sealed` would allow the compiler to help enforce that intent.

## Difficulty: Trivial

Literally adding four words.

## Risks

Since these attributes have been public and unsealed for a while, it's possible that sealing them would be a breaking change for anyone who has subclassed them.

**Comment by adrianknight89** [comment]
What about `PreserveAttribute`, `DependencyAttribute`, and `ResolutionGroupNameAttribute`? Also, the article suggests that attributes should either be sealed or abstract. Do you care which one you embrace?
 Some attributes like `XmlnsDefinitionAttribute`, `RuntimeNamePropertyAttribute`, `StylePropertyAttribute`, and `ProvideCompiledAttribute` are not public. Should attributes be made public?

Not saying everything has to follow a set pattern, but it might be a good idea to go over all attributes instead of just focusing on one.

**Comment by hartez** [comment]
`ResolutionGroupNameAttribute` should _absolutely_ be marked as `sealed`; it's part of the Effect scenario, we do reflect on it, and there's very little risk that anyone has subclassed it up to now.

`DependencyAttribute` is also a good candidate for the same reasons.

'PreserveAttribute' is used by the compilers and not at runtime, so there's not really a performance case for sealing it. However, there's not much reason for someone to subclass it, and it's in the `Internals` namespace so we do not guarantee that it won't change. Adding `sealed` would go a long way to enforcing what the `Internals` namespace implies.

At the moment, I cannot think of a compelling reason to make `XmlnsDefinitionAttribute`, `RuntimeNamePropertyAttribute`, `StylePropertyAttribute`, or `ProvideCompiledAttribute` public. 

I'm going to update this proposal to include `DependencyAttribute`, `ResolutionGroupNameAttribute`, and `PreserveAttribute`.
