### ISSUE TITLE
[iOS] Hidden NavigationBar causes layout to adjust when navigating

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#1807]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Migrating a 2+ year old bug here - https://bugzilla.xamarin.com/show_bug.cgi?id=36721

When a page is pushed with a hidden navigation bar, the layout is adjusted by the height of the hidden navigation bar. 

### Steps to Reproduce

1.  Run the project on an iOS simulator
2. Press the button to navigate
3. Notice as the animations happens, the red portion is adjusted

### Expected Behavior
The red portion should not be adjusted

### Actual Behavior
The red portion is adjusted when navigating

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  yes
  - Android: nope
  - UWP:  not tested
- Android Support Library Version: N/A
- Nuget Packages: Just forms
- Affected Devices: tested on iPhone 5s iOS 9.3 simulator

### Reproduction Link
Updated bugzilla sample to 2.5.0.122203
https://www.dropbox.com/s/yqd7m9u1zjjdhf8/NavigationBarHideBugSample.zip?dl=0

**Comment by jassmith** [comment]
As I recall it is iOS that moves things around because we cant flow under the bar. Im not sure if we can fix this but I hope we can.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
