### ISSUE TITLE
Clicks/taps stops works after Content property changes in OnAppearing on Xamarin.Forms iOS!

### ISSUE THREAD

**Issue by fernandovm** [xamarin/Xamarin.Forms#1834]
### Description

After a change that I do in the first execution of OnAppearing of a ContentPage the clicks/taps does not works. The change is very simple: I create a new StackLayout (S1) and set it to Content property of the ContentPage. Inside the S1 I create two StackLayout (S2 e S3). Inside S2 I put the old Content (S0) property of ContentPage and in S3 I put another new StackLayout with a Label view.

If I create the content page without do the change, all works fine. If I create the same content page but doing the change, all clicks/taps stops works. In the Android platform all works fine in all conditions.

### Steps to Reproduce

1. Compile and Run the reproduction case attached project - [XamApp.zip](https://github.com/xamarin/Xamarin.Forms/files/1705122/XamApp.zip).
2. Click in the button 'Open without dock' and all will work.
3. Click in the button 'Open with dock' and Clicks/taps stops works.

### Expected Behavior

The clicks/taps must works in both Android and iOS platforms.

### Actual Behavior

The clicks/taps does not works in iOS platform.

### Basic Information

- Version with issue: Xamarin.Forms 2.5.0.121934
- Last known good version: None
- IDE: Visual Studio 2017 15.4.5

- Platform Target Frameworks: 
  - iOS:  Any
  - Android: Any

**Comment by jassmith** [comment]
This is an order of operations issue in the iOS backend it seems. Technically this is not a supported operation you are performing.

You are doing the following things

1) Grabbing the current Page.Content, storing into currentContent variable
2) Packing currentContent variable into a new hierarchy <--- error happens here
3) Setting new hierarchy as Content

If you null out Content right after step 1, the issue goes away. This is because you are effectively reparenting the old content while it is still attached to the live tree.

Ideally this would throw an exception, but clearly it doesn't and we cant add that now because it would be a breaking change :/

**Comment by jassmith** [comment]
Like this:
var currentContent = this.Content;
this.Content = null;
