### ISSUE TITLE
[Android] Setting visibility to gone for for TabLayout does not reclaim space 

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#1855]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Migrating https://bugzilla.xamarin.com/show_bug.cgi?id=56305 here.

I'm trying to hide the tabs in TabLayout when a page is pushed. When I set visibility to gone, the tabs are hidden but space is not reclaimed. Please see repro.

Note: this is fixed in this PR (https://github.com/xamarin/Xamarin.Forms/pull/999). It was closed because some UI tests were failing for an unknown reason. It is a 2 line code change, can someone from the team please look at the failing UI Tests?

### Steps to Reproduce
1. Run app
2. Press the button
3. Note that the space where the tab was is not reclaimed

### Expected Behavior
Space is reclaimed and the whole page is yellow

### Actual Behavior
Space is not reclaimed and there is a white space where the tabs used to be

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  nope
  - Android:  yes
  - UWP:  not tested
- Android Support Library Version: 25
- Nuget Packages: just forms
- Affected Devices: tested on a Nexus 5x running Android 7

### Screenshots
https://imgur.com/a/hR7V5

### Reproduction Link
https://www.dropbox.com/s/l1o8t913vsud9qh/App21.zip?dl=0

**Comment by samhouts** [comment]
@Paul-Brenner-Tangoe Are you still experiencing this issue? Thanks!

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
