### ISSUE TITLE
Slider and thumb can detach on android in certain circumstances

### ISSUE THREAD

**Issue by jt-github** [xamarin/Xamarin.Forms#1858]
### Description
In short, 90 degree rotated Slider elements are limited in height to their available horizontal space (and perhaps this is true for other objects, too).

The issue I have encountered is the same as the one in this forum post:
https://forums.xamarin.com/discussion/69180/vertical-slider-takes-horizontal-space-as-lenght
While the forum post provides some example code, I've created my own below for even easier reproduction.

### Code to Reproduce

```
<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="30*" />
        <ColumnDefinition Width="70*" />
    </Grid.ColumnDefinitions>
    <Grid.RowDefinitions>
        <RowDefinition Height="50*"/>
        <RowDefinition Height="50*"/>
    </Grid.RowDefinitions>
    <BoxView Color="DarkBlue"/>
    <BoxView Color="DarkCyan" Grid.Column="1"/>
    <BoxView Color="Yellow" Grid.Row="1"/>
    <BoxView Color="DarkGreen" Grid.Column="1" Grid.Row="1"/>
    <Slider Grid.Row="1" Maximum="100" Minimum="0" Value="100" Rotation="-90"
          VerticalOptions="Center" />
</Grid>
```
![xamarinverticalslider](https://user-images.githubusercontent.com/1504620/36065553-30737f50-0e62-11e8-84c2-1d57de12c759.png)

Related Bug: If **VerticalOptions="Center"** is removed (defaulting to **Fill**), the handle of the slider detaches from the body of the slider.
![xamarinverticalsliderdetached](https://user-images.githubusercontent.com/1504620/36065566-4ca340b6-0e62-11e8-85e5-dd15afe8903b.png)

Related Bug: Adding any left or right **Margin** (such as "50,0,0,0") also has a non-intuitive effect where the _height_ of the rotated slider is reduced by the margin _and_ the slider moves left or right as expected.
![xamarinverticalsliderwithleftmargin](https://user-images.githubusercontent.com/1504620/36065568-516ee172-0e62-11e8-9256-5a2d1e2ebd3e.png)

### Expected Behavior
Available space and Slider dimensions should be calculated _after_ the rotation is applied so that a vertically rotated Slider can expand to the Height of its container, Margins are sanely handled, etc.

### Actual Behavior
Available space is calculated before rotation, imposing non-intuitive limitations on element position and size after rotation, only allowing a Height which is at maximum only as large as the Width of its container.

### Basic Information
- Version with issue: Xamarin.Forms 2.5
- Last known good version: N/A
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  Not yet testing
  - Android: 4.4 (API 19) running on Visual Studio Emulator for Android
  - UWP:  Not yet testing 
- Android Support Library Version: N/A
- Nuget Packages: None (besides standard Xamarin.Forms)
- Affected Devices: Virtual and Physical

### Screenshots
See above for screen shots in context.

**Comment by StephaneDelcroix** [comment]
Rotation, Scale, and other transforms do not affect the control bounding box.

**Comment by jt-github** [comment]
Is that a limitation of the underlying operating system(s) or is it something within Xamarin.Forms?  If it's the former, there is little to be done.  If it's the latter, then I understand that changing the control's bounding box after a transform would be more of a challenge from a core coding perspective, but the current behavior is so fantastically counterintuitive it makes transforms almost worthless.

Just give it a try and tell me that's not totally goofy.  Any suggestions for workarounds, other than building totally custom controls?  My current workaround is sticking those controls I need rotated out at the root element level and playing with them there, but they still act very strangely once rotated, and that negates the possibility of using transforms in situations like ListViews (for instance in a non-square cell in a Grid).

**Comment by jassmith** [comment]
Pre-layout transforms can't be added to the toolkit by modifying the existing layout mechanisms for fairly obvious reasons (it would be a huge breaking change).

In order to achieve what you want the way I would do it is to make a ContentView subclass that rotates its child and overrides the layout call to transpose the width and height passed. You may also want to mess around with the measure override as well if you need to participate in measurement, again providing the transpose.

The slider detachment seems to be an issue with the underlying toolkit, however we can look into fixing it.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
