### ISSUE TITLE
[iOS] Header template ignores layout options

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#1865]
### Description
Migrating https://bugzilla.xamarin.com/show_bug.cgi?id=58503 here

I have a StackLayout set to CenterAndExpand on a ListView Header Template. 

It works as expected on Android, the stack layout is centered in the header. On iOS it is not centered. It also ignores margin on iOS.

### Steps to Reproduce
1. Run app, note the text is centered on Android, and that it is not on iOS

### Expected Behavior
Text is centered

### Actual Behavior
Text is not centered

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  yes
  - Android: no
  - UWP:  not tested
- Android Support Library Version: 25
- Nuget Packages: just forms
- Affected Devices: Tested on iPhone 5s simulator running iOS 9.3, and nexus 5x running Android 7

### Reproduction Link
https://www.dropbox.com/s/9kcdao17fmtyaek/HeaderTemplateBug.zip?dl=0

**Comment by PureWeen** [comment]
![image](https://user-images.githubusercontent.com/5375137/36124172-4f89894c-100c-11e8-8454-fa78588289f4.png)

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by ish-1313** [comment]
Hi, this (or related) issue is still exists in current XF 4.8 outside margins set in listview header/footer are not working in ios and working good in android
