### ISSUE TITLE
MasterBehaviour is not working as expected in UWP platform

### ISSUE THREAD

**Issue by vishnuprasadDH** [xamarin/Xamarin.Forms#1890]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
I setup a MasterDetailPage as the main UI template for my Xamarin.Form application which is supposed to work in UWP , iOS and Android and kindly consider this bug i'm reporting only on UWP platform as i dont check this issues much on other platforms say iOS and Android.

Problem : I set the MasterBehaviour is to SplitOnLandspace but it does not have any change when i rotate the device or simulator.

### Steps to Reproduce

1. Extract the attached Xamarin.form project and run on UWP simulator
2. Change the orientations are see any changes.

### Expected Behavior
Since Master Behaviour is SplitOnLandscape , the app should show a split on the landscape view and on Portrait only the detail section.
### Actual Behavior
No change when changing the orientations.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

https://drive.google.com/open?id=190sg1Y9klDr2Mo1P88CIvmR_canNkbZa

**Comment by vishnuprasadDH** [comment]
Hi Everyone ,
Is there any update on the above issue , Can i expect a fixed release from Xamarin any time soon  ? 

Thanks,
Vsh

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
