### ISSUE TITLE
Scaling broken on UWP

### ISSUE THREAD

**Issue by nodoid** [xamarin/Xamarin.Forms#1893]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Scaling is broken on UWP

### Steps to Reproduce

Please see https://bugzilla.xamarin.com/show_bug.cgi?id=60879

You can also see this issue by running
https://github.com/xamarin/xamarin-forms-samples/tree/master/XamlSamples
And running Slider Transforms

### Expected Behavior
Scaling should work

### Actual Behavior
Scaling is broken (run the linked to code on the bug)

### Basic Information

- Version with issue: 2.5.0 branch
- Last known good version:
- IDE: VS2017
- Platform Target Frameworks: 
  - UWP:  15063 and above
- Affected Devices: Tested on PC

**Comment by rmarinho** [comment]
Hi i have looked at the reproducion, and can see the difference, but there's just to much custom code to proper identify the issue. Can you start with a blank app, and just add the smallest reproducion to show the scaling issue. 

Thanks

**Comment by nodoid** [comment]
https://www.dropbox.com/s/o2m5piotj39kr6t/dynamicsize.zip?dl=0 - minimal example

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
