### ISSUE TITLE
Updating FontAttributes breaks the layout

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#1921]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
When an item is new, I have the strings bold. After a user taps the item, I set the text to not be bold, to show it has been read. Doing this messes up the layout (see repro, bug is hard to explain)

### Steps to Reproduce

Run app
Tap the first item in the list, then go back
Repeat this for the first 4 items
Note that the padding gets messed up, and the right string has extra padding to its right
Scroll list
Note that the string has correct padding again

### Expected Behavior
Padding does not change when the font attributes change

### Actual Behavior
Padding changes and messes up layout

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  yes, but repro does not show
  - Android: yes
  - UWP:  not tested
- Android Support Library Version: 25
- Nuget Packages: just forms
- Affected Devices: tested on Nexus 5x on Android 7, and iPhone 5s simulator on iOS 9.3

### Screenshots
https://imgur.com/a/7FrRO

### Reproduction Link
Please note that for some reason I could only get the repro to show the issue on Android, but in my project I get this bug on iOS as well. 
https://www.dropbox.com/s/x90pwlszfzl6axi/paddingupdatesample.zip?dl=0

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
