### ISSUE TITLE
Label is clipped when inside a StackLayout with another Label using TrailTruncation

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#1934]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Migrating this 2+ year old bug here - https://bugzilla.xamarin.com/show_bug.cgi?id=34943

With two labels inside a StackLayout (horizontal), 1 of them will be clipped if the other is too long and gets the ellipses from a TrailTruncation WrapMode setting. 

### Steps to Reproduce

Run sample
Note that the labels are clipped

### Expected Behavior
Labels are not clipped

### Actual Behavior
Labels are clipped

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  yes
  - Android: yes
  - UWP:  not tested
- Android Support Library Version: 25
- Nuget Packages: just forms
- Affected Devices: tested on Nexus 5x running Android 7, and iPhone 5s simulator running iOS 9.3

### Screenshots

https://bugzilla.xamarin.com/attachment.cgi?id=13373

### Reproduction Link

https://www.dropbox.com/s/9m3floclu6v81h7/stacklayouttext.zip?dl=0

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
