### ISSUE TITLE
Buttons do not adhere to styles set on android

### ISSUE THREAD

**Issue by twinee** [xamarin/Xamarin.Forms#1954]
### Description
The buttons on android devices no longer adhere to button styles set using the styles resources. They are now narrower and display a shadow, no matter what style is set. Custom button renderers which set the StateListAnimator & Elevation properties also have no effect.

### Steps to Reproduce
1. Update Xamarin.Forms nuget package to 2.5.0.280555
2. Set a buttonStyle using styles.xml
3. fire up an app displaying a Button on an android device

### Expected Behavior
Button objects on android devices adhere to the styles set in styles.xml

### Actual Behavior
Button objects ignore any button style set, and always show a shadow.

### Basic Information
- Version with issue: 2.5.0.280555
- Last known good version: 2.5.0.122203
- IDE: VS2017
- Platform Target Frameworks:
  - Android: 8.0
- Android Support Library Version: v26.1.0.1
- Affected Devices: tested on android 5.0.1

**Comment by samhouts** [comment]
Can you provide a reproduction so we can be sure we're fixing the right issue? Thanks

**Comment by twinee** [comment]
i'll try to get to it tomorrow!

**Comment by samhouts** [comment]
Related to #1909

**Comment by samhouts** [comment]
@twinee If you have a chance to share your styles, I'd still like to test them against the new PR. Thanks!

**Comment by samhouts** [comment]
closed by #1935

**Comment by duckwaffle** [comment]
Hi @samhouts I'm trying to follow the thread between this, #1909 and #1935 but am getting a bit lost.

I'm trying to get flat, shadowless buttons on Android, but it seems that this isn't possible in 2.5.0.280555 . Your PR is marked as being for v3.0.0, but obviously that version is still a ways out. I'm not desperate for a fix this very minute, but I was wondering whether you know if this fix will make it into a release in the near future?

**Comment by bigbbri** [comment]
Hi @samhouts and @duckwaffle.  I fought with this for 2 days only to find a [thread](https://forums.xamarin.com/discussion/122752/removing-shadow-from-android-buttons)  that opened this bug.  I can give you reproducible code.  The fix for me was to downgrade from XF 2.5.0.0280555 to XF 2.5.0.122203 and it works as expected (So frustrating!).  Let me know if you need more...

Here is my xaml snippet:
` <Button   x:Name="Devices" Style="@style/NoShadowButton"  Text="Devices"  VerticalOptions="Center" HorizontalOptions="Start" 
        FontSize="30"   BackgroundColor="White" BorderColor="White" />
`
Here are my styles in styles.xml
`  <style name="MainTheme" parent="MainTheme.Base">
  </style>
  
  <style name="MainTheme.Base" parent="Theme.AppCompat.Light">
    <item name="windowActionBar">false</item>
    <item name="colorPrimary">@color/primary</item>
    <item name="colorPrimaryDark">@color/primaryDark</item>
    <item name="colorAccent">@color/accent</item>
    <item name="android:windowBackground">@color/window_background</item>
    <item name="windowActionModeOverlay">true</item>
    
    <item name="android:buttonStyle">@style/NoShadowButton</item>
    
  
  </style> 
  
  <style name="NoShadowButton" parent="android:style/Widget.Button">
  <item name="android:textColor">@color/ward_blue</item>
  </style>
</resources> `


Thanks,
Brian Adams

**Comment by samhouts** [comment]
Please try version 2.5.1. It's currently in pre-release, but it should be considered stable soon. Buttons will no longer have a shadow by default in that version. Thanks
