### ISSUE TITLE
AbsoluteLayout content does not fill all available space on some devices

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#1963]
### Description
Work that's been done on this for Android

https://bugzilla.xamarin.com/show_bug.cgi?id=40092
https://github.com/xamarin/Xamarin.Forms/pull/1761

### Steps to Reproduce

Test the following repro project on an ipad air 2 in landscape
[AbsoluteLayoutTest.zip](https://github.com/xamarin/Xamarin.Forms/files/1749755/AbsoluteLayoutTest.zip)

### Expected Behavior
There should not be a red line between the white box and the base of the layout

### Actual Behavior
There's a one pixel high line

### Basic Information

- Platform Target Frameworks: 
  - iOS:  Needs to be fixed
  - Android:  Fixed
  - UWP:  Needs to be fixed

- Affected Devices: ipad air 2

**Comment by velocitysystems** [comment]
@samhouts @PureWeen Although this is a minor issue, just wondering if this could be included for fix in 4.4.0?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
