### ISSUE TITLE
HeightRequest Doesn't Change Editor Size - UWP

### ISSUE THREAD

**Issue by MelbourneDeveloper** [xamarin/Xamarin.Forms#1965]
### Description
If an Editor (and probably other controls) is in an Auto sized row on UWP, and the HeightRequest is changed to 0, the control is not resized, but the RowDefinition's height **_is_** changed. 

### Steps to Reproduce
1. Clone this repo https://ChristianFindlay@bitbucket.org/ChristianFindlay/xamarin-forms-scratch.git
2. Open the solution and run the UWP App
3. Click Auto Test Page
4. Click Change Entry Size (this sets the Editor to a HeightRequest of 0)
5. Notice that the Row size changes but the control remains the same.

### Expected Behavior
Control's Height changes to zero.

### Actual Behavior
Control's Height does not change.

### Basic Information
This is not an issue on Android. The behaviour is different

- Version with issue:
- Last known good version: 2.5.0.280555
- IDE: Visual Studio
- Platform Target Frameworks: 
  - UWP:  16299 
- Nuget Packages: Xamarin.Forms
- Affected Devices: Windows 10

### Screenshots
[Full size](https://www.dropbox.com/s/equqswr8464vop0/AutoUWP1.png)

[0 size](https://www.dropbox.com/s/2a6a1yrc9tflgyz/AutoUWP2.png)

### Reproduction Link
https://ChristianFindlay@bitbucket.org/ChristianFindlay/xamarin-forms-scratch.git

**Comment by nodoid** [comment]
Could be related to #1953

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
