### ISSUE TITLE
Navigating to another page is not working inside ListView

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#2082]
### Description

Migrating https://bugzilla.xamarin.com/show_bug.cgi?id=59982 here

### Steps to Reproduce

Run app
Tap image in cell
Note that the ItemTapped code gets hit, but the app does not navigate

### Expected Behavior
App navigates to new page

### Actual Behavior
App does not navigate, seems to ignore the navigation code, no crash, no info in logs

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS: yes
  - Android: yes
  - UWP:  not tested
- Android Support Library Version: 25
- Nuget Packages: just forms
- Affected Devices: tested on Nexus 5x running Android 8, and iPhone 5s simulator running iOS 9.3

### Reproduction Link
https://www.dropbox.com/s/g0fcqf6vcnf8xz2/listviewtapgesture.zip?dl=0

**Comment by StephaneDelcroix** [comment]
I can confirm this issue.

### What I think is happening here:
When the `myview` gets a `Parent` (a `ViewCell`), the `ViewCell` isn't `Parent`ed, so the `Inner` navigation isn't set
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/VisualElement.cs#L642-L658
Later on, when the ViewCell is parented, we do not bubble down the `NavigationProxy`s to set the `Inner` property.

### How to workaround this ?
get a handle on the `Navigation` property of your `NavigationPage` or `ContactsPage`, and navigate from there.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
