### ISSUE TITLE
Listview displays cells with different heights differently on iOS and Android

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#2093]
### Description

Not sure if this is by design or a bug. The sample app has a listview, and the cell height is set with a random number. On iOS when you set ListViewCachingStrategy to RecycleElement, it sets the height of all the cells the same. While on Android it sets the height correctly.

### Steps to Reproduce

Run app
Note that on iOS the cells all have the same height, and that on Android the cells have different heights
Change ListViewCachingStrategy to RetainElement, run app
Note that on iOS the cells have different heights, and that on Android the cells have different heights 

### Expected Behavior
Both platforms display the cells the same

### Actual Behavior
On iOS the cells only display the cells with different heights if you set ListViewCachingStrategy to RetainElement

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  yes
  - Android: yes
  - UWP:  not tested
- Android Support Library Version: 25
- Nuget Packages: just forms
- Affected Devices: tested on Nexus 5x running Android 8 and iPhone 5s simulator running iOS 9.3

### Screenshots
https://imgur.com/a/RBfXb

### Reproduction Link
https://www.dropbox.com/s/dzjlxkfqavpfq7r/listviewscrollsample.zip?dl=0

**Comment by MelbourneDeveloper** [comment]
There is another related bug which I have never logged but maybe can be incorporated here. There is a property called "HasUnevenRows". On UWP, if you do not specify this there is no issue. ListView items take the height of the element generated by the ItemTemplate. But, on Android, this doesn't work. For example, if the DataTemplate has a Grid and that Grid's row has a height of 50, the ListView item will not expand out to 50. But, if you set HasUnevenRows to true, on Android, the functionality will work correctly. Notice that all the rows **_are_** the same height so this property shouldn't do anything.

**Comment by deakjahn** [comment]
Is the bug @MelbourneDeveloper mentioned also accounted for in this issue or shall we file it separately? It took the better part of a day for me to struggle with this on Android and the, finally, accidentally stumble upon this issue here. The HasUnevenRows behaviour or Android is a serious bug that needs to be addressed.

**Comment by MelbourneDeveloper** [comment]
@deakjahn are you able to log this? I won't be at a computer for a while.

**Comment by deakjahn** [comment]
@MelbourneDeveloper, OK, I did so:

https://github.com/xamarin/Xamarin.Forms/issues/3427

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
