### ISSUE TITLE
Difficulty with Sync using Xamarin.Forms Starter App

### ISSUE THREAD

**Issue by tgmcguire** [xamarin/Xamarin.Forms#2105]
Hi there! 👋

First off, my apologies if this is better suited for discussion elsewhere – I'm new to the Azure/Xamarin space and not sure where I'd get the best feedback. Any feedback here is greatly appreciated!

Getting my feet wet with Xamarin, and doing some feasibility testing/research. I've [downloaded the starter app](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started) to test out syncing Xamarin.Forms with Azure Mobile Apps. I've done practically no customization from the starter app generated from Azure – except for adding a few extra fields to my table, just to simulate a little larger dataset. I'm encountering four issues, which I'll detail here – but first, my environment:

# Environment

- Visual Studio for Mac (Community), v7.4 build 1033
- Microsoft.Azure.Mobile.Client v4.0.1
- Microsoft.Azure.Mobile.Client.SQLiteStore v4.0.1
- NETStandard.Library v1.6.1
- Xamarin.Forms v2.3.4.247

## 1. Duplicate items ([Screencast](https://drive.google.com/file/d/1lUm0YC5r-Y8TTsNVSNdYN7-8y370lxsU/view?usp=sharing))

Adding items can sometimes result in duplicate records being added to the database. These duplicate records sometimes clear out over time, but sometimes they don't.

## 2. If there are duplicate items, only one is updated  ([Screencast](https://drive.google.com/file/d/1iAhx4mQCUr2LvTh6N2BLToMqCGTV8dQM/view?usp=sharing))

If there are duplicate items in the database as a result of the above point, and that item is updated within the app, only the one record in the database is updated – not both. So in addition to data duplication, we also don't seem to have a way of knowing which record is authoritative.

## 3. Deleting items in database doesn't delete in app ([Screencast](https://drive.google.com/file/d/1sLQEoruq0Sqi1Nzb5qOdeMdUUlU1mMVp/view?usp=sharing))

If records are deleted from the database, they seem to get "stuck" in the app. In fact, force-closing and re-launching the app does not regenerate the local database. It takes a full re-install before these "stuck" items are removed/database is synced.

## 4. Items can reappear after deletion ([Screencast](https://drive.google.com/file/d/18kDlV1JyQxDV_Jzbxty6g34iZsnMu3_H/view?usp=sharing))

If I delete records from the database, we already know from `3` above that they're not removed from the app. But I found that if I add a new item within the app, they're added back to the database. In this example video, it's also worth noting that the record for "Newmont Mining Corporation" is _not_ re-added to the database, and the "App 2" item I added in the app was not synced to the database either.

---

These issues are obviously a bit concerning, and would be challenging to work with in a production environment. I just want to make sure I'm not missing anything obvious in my initial testing. 🙂

Note that in all of the above examples, the app is connected to the database the whole time. These problems seem to be made worse when the device is offline, especially items getting "stuck" in their old state – but I'm more concerned about the core functionality of syncing with Azure.

Any insight you can provide here would be fantastic. I'm not sure how stable this syncing functionality is "out in the wild", so I'm be curious about that as well, or if we should investigate alternative solutions.

Thanks so much!

**Comment by samhouts** [comment]
Hi! We're glad to see you playing with these features. They're pretty exciting!

It sounds like most of your questions are directed at the Mobile.Client offline sync feature. You may have luck finding answers to your questions on either https://github.com/Azure/azure-mobile-apps-net-server/issues or https://github.com/Azure/azure-mobile-apps-net-client/issues. 

I can tell you that the issue with items appearing to be "stuck" might be answered in this document: https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-offline-data-sync

The incremental sync will actually limit the records returned when you query to just those that have been updated since you last queried the server. Furthermore, the last time I checked, using the `Purge` function doesn't actually clear the date it stores, so any records that were created/updated before you purged won't be returned.

Not sure about the duplicate issue you described. I haven't seen that myself. You may find an issue already open about it on one of the repos linked above. If you have any further questions about Xamarin.Forms itself, please feel free to open a new issue here.

Hope that helps! Thanks!
