### ISSUE TITLE
Using TranslateTo on a ScrollView does not update ScrollX/ScrollY

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#2110]
### Description
Migrating this 2+ year old bug here - https://bugzilla.xamarin.com/show_bug.cgi?id=33385
Note that the report says it only happens on iOS, but I can reproduce on Android as well

### Steps to Reproduce

Run app
Tap the first label
Check output, note that ScrollX/Y is set to 0

### Expected Behavior
ScrollX/Y is updated

### Actual Behavior
ScrollX/Y is 0

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  yes
  - Android: yes
  - UWP:  not tested
- Android Support Library Version: 25
- Nuget Packages: just forms 
- Affected Devices: tested on Nexus 5x running Android 8 and iPhone 5s simulator running iOS 9.3

### Reproduction Link
https://www.dropbox.com/s/jyp1y9my5othp0b/Scrollviewbugsample.zip?dl=0

**Comment by AndreiMisiukevich** [comment]
@samhouts you can close this issue as invalid

**TranslateTo** affects **TranslateX** and **TranslateY**

@Paul-Brenner-Tangoe if you want to change ScrollX/ScrollY properties, you should use **ScrollToAsync** method

**Comment by michielvv** [comment]
@AndreiMisiukevich I think you are misunderstanding the issue.  The issue is that  the Scroll position resets   if you change properties   (such as TranslateX/TranslateY  or the size of the scrollview) that should not affect the scrolling position.
Example:  stacklayout containing a scrollview  and a button.  if you scroll down, hide the button the scrollview resets its scrollposition.

**Comment by AndreiMisiukevich** [comment]
@michielvv thank you for clarifying :)

This issue has been already fixed https://github.com/xamarin/Xamarin.Forms/pull/3842

it can be closed as duplicated, i guess

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
