### ISSUE TITLE
[iOS] Refresh Spinner on iOS disappears when SearchBar or Entry is focused.

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [xamarin/Xamarin.Forms#2119]
### Description

Refresh Spinner on iOS disappears when SearchBar or Entry is focused.

### Steps to Reproduce

1. Create a page with a SearchBar or Entry and a ListView which has `IsRefreshing=True` set.
Like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<ContentPage Title="List View Refresh Example" xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:ListViewRefreshExample" x:Class="ListViewRefreshExample.ListViewRefreshExamplePage">
    <StackLayout Padding="0,40,0,0">
    <SearchBar/>
    <ListView IsRefreshing="true"/>
    </StackLayout>
</ContentPage>
```
or clone the example project from here: https://github.com/RudolfVonKrugstein/XamarinFromsListRefreshProblem

2. Start the App. The ListView is showing with the Refresh Spinner Running.
3. Focus the SearchBar by clicking into it. The Refresh Spinner of the ListView disappears.

### Expected Behavior

The Refresh Spinner of the ListView should remain because IsRefreshing is not changed.

### Actual Behavior

The Refresh Spinner is disappearing.

### Basic Information

- Version with issue: 2.5.0.121934
- Last known good version: Unkown
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - iOS:  11.1
- Affected Devices: Iphone X, iPhone 7 (rest not tested)

### Reproduction Link

https://github.com/RudolfVonKrugstein/XamarinFromsListRefreshProblem

**Comment by RudolfVonKrugstein** [comment]
Is there any progress on this?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
