### ISSUE TITLE
removing multiple pages then popasync flashes through those "removed" pages - ANDROID only

### ISSUE THREAD

**Issue by orangeoctopus** [xamarin/Xamarin.Forms#2162]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Android only phones - when attempting to navigate to a page multiple pages back it flashes the previous screens before arriving at intended page. This is when Navigation.RemovePage BEFORE pushing the intended page (the "removed" pages flash for a brief moment).

### Steps to Reproduce
ANDROID only
1. open project linked
2. tap "next Page" Button
3. tap "next Page" Button
4. tap "next Page" Button
5. tap "insert page before page 3" Button
6. tap "pop 4 pages" Button

### Expected Behavior
should see it go straight to the first page that just says "Next Page"
### Actual Behavior
visibly flashes back through all the pages before showing the first page.
### Basic Information

- Version with issue:
- IDE: Visual Studio Community 2017 for Mac
Version 7.2 (build 636)
- Platform Target Frameworks: 
  - Android: Version: 8.0.0.33 
- nuget: 4.3.1.4445

### Reproduction Link

zip file of sample project (its based off the sample code for working with navigation):
https://www.dropbox.com/s/2jpu8cxbq5lxnxn/Hierarchical.zip?dl=0

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
