### ISSUE TITLE
In XF-IOS, the 'SetPrefersLargeTitles' iOS platform specific method doesn't work when the Grid contains image background with the ScrollView

### ISSUE THREAD

**Issue by Yuvaraj-Syncfusion** [xamarin/Xamarin.Forms#2184]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

Hi Xamarin,

### Description

We have found a strange issue in XF- IOS platform: The 'SetPrefersLargeTitles' method doesn't work in latest Xamarin Forms version (v 2.5.0.280555). The ContentPage title not aligned automatically, while scrolling the view  when load image in Grid with ScrollView.

Here we have loaded the Image within Grid and load it into the ScrollView.

### Steps to Reproduce

1. Run the attached sample.
2. Scroll the view and note that the ContenPage title is not aligned automatically.
3. If image is removed its working fine.

### Expected Behavior
   
     If I added the background image for the view. Then ContentPage title aligned automatically when I perform scrolling.   

### Actual Behavior

    When I added the background image for the view then ContentPage title not aligned when I perform scrolling. It only working fine without background image is set for Grid.

### Basic Information

- Version with issue: Xamarin Forms version (v 2.5.0.280555)
- Last known good version: Xamarin Forms version (v 2.5.0.280555)
- Microsoft Visual Studio Professional 2017 
- Version 15.5.6
- VisualStudio.15.Release/15.5.6+27130.2027
- Microsoft .NET Framework
- Version 4.7.02556

- Xamarin   4.8.0.760 (fc93f3f5b)
- Xamarin.Android SDK   8.1.5.0 (HEAD/75f8c6838)
- Xamarin.Android Reference Assemblies and MSBuild support.

- Xamarin.iOS and Xamarin.Mac SDK   11.6.1.4 (db807ec)

### Reproduction Link

#####Sample:
[GridBackgroundImage.zip](https://github.com/xamarin/Xamarin.Forms/files/1847723/GridBackgroundImage.zip)

**Comment by PureWeen** [comment]
I tried this in version 2.4 of forms and it seems to do the same thing there. 
It seems like it doesn't really have to do with the image and that iOS is finicky about how that title works

For example here it talks about the view order breaking that behavior

https://www.markusbodner.com/2017/10/08/fix-large-navigation-bar-title-not-hiding-on-scroll-in-ios-11/

I'm still messing around with it a bit but wanted to leave that note

**Comment by PureWeen** [comment]
I'm going to close this one for now because AFAICT this is a iOS platform limitation. The ability for that header to shrink while scrolling seems fairly constrained by iOS

I wrote up a native test case to try a few varying scenarios (just to see where Forms might be getting in the way)

From my tests and what I've seen around the web you have to add the scroll view first 
```
 View.AddSubview(scrollView);
View.AddSubview(imageView);
```

At this point if you try to call
```
View.BringSubviewToFront(scrollView);
```
It breaks... 

The only way I've been able to get it to work where you overlay two views is by setting the ZPosition on the scrollview to a number greater than the ImageView and then setting *UserInteractionEnabled* to false on the ImageView

So to set the background image I'm thinking just using a custom renderer to set the background image on the scrollview might be the best option

The other thing I tried (which seemed to work):
- add the Image as the second child on the grid but don't call RaiseChild because that just reorders the children
- Set InputTransparent on the image to True
- Then use a custom renderer on the image to set the ZPosition to something negative
```
 public class CustomImageRenderer : ImageRenderer
    {
        public override void LayoutSubviews()
        {
            base.LayoutSubviews();
            this.Layer.ZPosition = -100;
        }
    }
```

**Comment by Yuvaraj-Syncfusion** [comment]
Hi Xamarin Team,
      Now, It is working fine. Thanks for the quick update and the valuable suggestion to solve my issue.
I really happy to your quick response.

Regards,
Yuvaraj
