### ISSUE TITLE
Xamarin Forms Application Doesn't Startup After Changing The Date to a Past Date

### ISSUE THREAD

**Issue by randalvance** [xamarin/Xamarin.Forms#2194]
Whenever I set the date to a past date (for debugging and testing purposes), the Xamarin App doesn't startup. It is repllicable even in a freshly created new Xamarin Forms application in Visual Studio 2017 15.6.3. I used it to replicate this issue.

### Steps to Reproduce

1. Open the app to verify that it is working.
2. Close the app completely.
3. Go to phone's setting and set the date to a past date.
4. Reopen the app.

### Expected Behavior
The app starts up successfully and it shows the main page.

### Actual Behavior
The app doesn't startup and is stuck on a blank screen.

### Basic Information

- Version with issue: 2.5.0.280555

- Platform Target Frameworks: Android
 - Android: Android SDK 8.1 Oreo
- Android Support Library Version: 25.4.0.2 and 
- Affected Devices: Samsung Galaxy S6, Samsung Galaxy S7 Edge, Samsung Galaxy S8

**Comment by jmielczarkowski** [comment]
@randalvance I am able to reproduce this issue. Spend few hours on finding the root cause :( but looks like it's latest XF fault.

**Comment by Miksier** [comment]
Tested on :
2.2.0.45 (VS 2015 14.0.25431) - to be sure its not VS 2017 fault.
2.4.0.7486 (VS 2017 15.6.4)
2.5.1.444934 (VS 2017 15.6.4)
3.0.0.354232-pre3 (VS 2017 15.6.4)
Didn't do any extent earlier versions checks so cant confirm if its issue from the beginning(it simply can not be).
The issue is present on all tested environments

The hard part is, it's really complex to debug, as starting the app from debugger fixes it...

**Comment by telimichal** [comment]
I also can confirm this issues, however on Android 5.1 instead of freezing app I got crash. 
Also I can add that when building from Visual Studio for Mac on Android O issues doesn't appear.

**Comment by m1thr4nd1r** [comment]
I can also confirm this issue. And sometimes on Lollipop the app also keeps crashing instead of freezing.

Version with issue: 3.4.0.1008975 and 3.1.0.697729

Platform Target Frameworks: Android

Android: Android SDK 8.1 Oreo, SDK 6.0 Lollipop, SDK 4.4.2 (Jelly Beans)

Android Support Library Version: 27.0.2.1 and

Affected Devices: Pixel 2 XL (Emulator), Lenovo Vibe K5

**Comment by GrantBCU** [comment]
Experiencing this issue with Xamarin.Forms version 3.6.0.220655.

**Comment by StormSunCC** [comment]
使用Xamarin.Forms版本4.0.0.425677遇到此问题。

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
