### ISSUE TITLE
Registrar class Register no-ops

### ISSUE THREAD

**Issue by MartinZikmund** [xamarin/Xamarin.Forms#2217]
### Description

I have noticed an unusual no-op logic in `Xamarin.Forms.Internals.Registrar<TRegistrable>`.

The `GetHandlerType` method is trying to cache the result of the handler search, which might be `null` and to avoid repeated `RenderWithAttribute` reflection it uses the `Register` method to cache the result - see [line 98](https://github.com/xamarin/Xamarin.Forms/blob/e0d85bda5ea8a8224dbaf4e4ba5e2fa8361a7708/Xamarin.Forms.Core/Registrar.cs#L98) and [line 113](https://github.com/xamarin/Xamarin.Forms/blob/e0d85bda5ea8a8224dbaf4e4ba5e2fa8361a7708/Xamarin.Forms.Core/Registrar.cs#L113).

```
Register(viewType, null); // Cache this result so we don't have to do GetCustomAttribute again
```

However, if you check the `Register` method, you can see it just skips execution for `null` handler parameter (see [line 26](https://github.com/xamarin/Xamarin.Forms/blob/e0d85bda5ea8a8224dbaf4e4ba5e2fa8361a7708/Xamarin.Forms.Core/Registrar.cs#L26)).

```
public void Register(Type tview, Type trender)
{
    //avoid caching null renderers
    if (trender == null)
        return;
    _handlers[tview] = trender;
}
```

### Expected Behavior

The `GetHandlerType` method seems to expect that the `Register` call will cache even the `null` handler and that will avoid repeated evaulation of the `RenderWith` attribute`.

### Actual Behavior
The `Register` method call does not cache the `null` handler which means the call is effectively a no-op.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
