### ISSUE TITLE
PreferredScreenEdgesDeferringSystemGestures can't be triggered in the PageRenderer of Xamarin.Forms

### ISSUE THREAD

**Issue by landl0526** [xamarin/Xamarin.Forms#2241]
### Description

I want to override the PreferredScreenEdgesDeferringSystemGestures to delay the system behavior when touching the screen edges on iOS 11+. it works properly on Xamarin.iOS, but when I do this in a 
page renderer on Xamarin.Foms it fails. The system will not trigger this property automatically. I want to do the same thing on Forms, and how can I achieve that.

### Steps to Reproduce

1. override the PreferredScreenEdgesDeferringSystemGestures  in a page renderer:
```
public override UIRectEdge PreferredScreenEdgesDeferringSystemGestures
{
    get
    {
        return UIRectEdge.All;
    }
}
```
2. It won't be triggered when this renderer shows.

**Comment by jassmith** [comment]
Yup sure doesn't seem to work, probably needs to be set at the right point in the hierarchy and just haven't figured out where. Good candidate for a PlatformSpecific.

**Comment by NebulaSleuth** [comment]
Anyone know a workaround for this?  I really need to use this feature.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
@victoralvesp Do you need this issue to remain open? Thanks

**Comment by victoralvesp** [comment]
@samhouts No. I found a workaround for my particular problem. Thanks for asking

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
