### ISSUE TITLE
Unable to build solution with pre-release package

### ISSUE THREAD

**Issue by nicolas-garcia** [xamarin/Xamarin.Forms#2285]
Hi!

### Description

Every time I update my Xamarin.Forms NuGet package to a pre-release package from nuget.org, I struggle with the following error:

```
1>C:\Users\gra\.nuget\packages\xamarin.forms\3.0.0.296286-pre2\build\netstandard2.0\Xamarin.Forms.targets(35,3): error MSB4062: The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\Users\gra\.nuget\packages\xamarin.forms\3.0.0.296286-pre2\build\netstandard2.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Le fichier spécifié est introuvable. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

I already tried to clean solution `bin` and `obj` directories. I tried to clean .nuget packages cache. I closed and restarted Visual Studio several times.
I tried to install `Microsoft.Bcl.Build` NuGet package, same error.

This is not the first time I got the error while trying to use a pre-release package. I end up with not using them, but it is quite frustrating...

### Steps to Reproduce

1. Create a new project Xamarin.Forms with .Net Standard 2.0
2. Update Xamarin.Forms package to any pre-release version from nuget.org
3. Build the solution

### Expected Behavior

Solution should build

### Actual Behavior

100% times the following error
```
1>C:\Users\gra\.nuget\packages\xamarin.forms\3.0.0.296286-pre2\build\netstandard2.0\Xamarin.Forms.targets(35,3): error MSB4062: The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\Users\gra\.nuget\packages\xamarin.forms\3.0.0.296286-pre2\build\netstandard2.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Le fichier spécifié est introuvable. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

### Basic Information

- Version with issue: All pre-release packages
- Last known good version: all release packages
- IDE: Visual Studio 15.6.4

### Reproduction Link

[Reproduction project](https://github.com/xamarin/Xamarin.Forms/files/1879336/App2.zip)

**Comment by jassmith** [comment]
Either you didn't restart the IDE after installing the new version of Xamarin.Forms (you have to), or you did not update every project in the solution. This error is basically saying your IDE is trying to use the old targets with the new version of Forms.

**Comment by nicolas-garcia** [comment]
Thank you for your answer.

As I said
>I closed and restarted Visual Studio several times.

I restarted Visual Studio, even the computer!
And as you can see, all project are using the same Xamarin.Forms package version.
![all_project_nuget](https://user-images.githubusercontent.com/1201859/38541500-91e8e2c8-3c9f-11e8-9701-e9ce49c7d103.PNG)

The only computer without this issue is my development computer.
The build VM and my coworker computer got this issue.

**Comment by gcadmes** [comment]
Not sure if you got this working yet or not.
I experienced this too when I upgraded to Visual Studio15.7.1, AND upgraded my Xamarin.Forms from 2.5.1.444934 to 3.0.0.446417.

I eventually got everything to work after updating  .NET Core from 2.0 to 2.1.2, .NET Framework from 4.6.2 to 4.7.2, and ultimately updated my machine to the April 2018 Update. (TBO, the machine update is what finally got it working as I was unable to install .NET 4.7.2 without first updating to the April 2018 update).

After which I ran into another error that I am familiar with (below). Turns out, in  my platform projects, I had an Imports section referring to an old version of Xamarin.Forms:

`<Import Project="..\..\..\packages\Xamarin.Forms.2.5.1.444934\build\netstandard1.0\Xamarin.Forms.props" Condition="Exists('..\..\..\packages\Xamarin.Forms.2.5.1.444934\build\netstandard1.0\Xamarin.Forms.props')" />`

IMHO, The error you and I found _"The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded..."_ was not an accurate description of the real issue.
The real issue is that in one of the platform projects referencing Xamarin.Forms contains an old <Imports> section pointing to an older version of Xamarin.Forms. I'm repeating myself because I should have known better to check my cproj files for issues. 

Having said all that, I may not have needed to upgrade my machine, but happy about it nonetheless. 

One word of caution if you do update your machine to April 2018. The April 2018 Update breaks the Chrome browser and other nasty things. There is a patch already for that located here.
[](https://support.microsoft.com/en-us/help/4103721/windows-10-update-kb4103721)

HTH
