### ISSUE TITLE
[iOS / Android] Cannot focus a custom component

### ISSUE THREAD

**Issue by YGuerin** [xamarin/Xamarin.Forms#2295]
### Description

When using a custom component, it is not possible to handle the Focused event

### Steps to Reproduce

1. Create a new cross-platform project (.NET Standard)
2. Create a new custom component with the focused event handled
3. Include it on the MainPage.xaml
3. On the MainPage.xaml.cs, call MyCustomComponent.Focus()

### Expected Behavior
The Focused event is fired

### Actual Behavior
Nothing happens

### Basic Information

- Version with issue: 
Xamarin.Forms 2.4.0.91020 => KO
Xamarin.Forms 2.5.0.280555 => KO
Xamarin.Forms 2.5.1.44934 => KO

- Last known good version: Unknowm
- IDE: Visual Studio 15.6.5
- Platform Target Frameworks: 
  - iOS: 11.9.1.21
  - Android: 8.2.0.16
  - UWP:  Not included in the scope
- Android Support Library Version: 25.4.0.2
- Nuget Packages: Only those included in the initial project startup
- Affected Devices: iOS, Android at least

### Reproduction Link

[App2.zip](https://github.com/xamarin/Xamarin.Forms/files/1881321/App2.zip)

**Comment by jassmith** [comment]
Layouts are not currently focusable. In general you are just sending a focus event down to the native toolkit asking it very nicely to focus an empty layout which the toolkit is going to promptly ignore because it has no idea what to do with that. Then we dont send you a focused event because well, it's not focused.
