### ISSUE TITLE
[Android] API 22 - MaximumDate not clickable for DatePicker

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#2316]
### Description

Given 
```C#
var datePicker = new DatePicker { AutomationId = "datePicker" };
			datePicker.MinimumDate = new DateTime (2015, 1, 1);
			datePicker.MaximumDate = new DateTime (2015, 6, 1);
			datePicker.Date = DateTime.Now;
```

- The Datepicker will show as having 2015/6/1 as selected
- open the calendar and click a different date
- open the calendar and try to reselect 2015/6/1

This works fine on API 23 but on API 22 it does not

### Steps to Reproduce
Using an API 22 device

- Run Issue2987 in the Android Control Gallery
- The Datepicker will show as having 2015/6/1 as selected
- open the calendar and click a different date
- open the calendar and try to reselect 2015/6/1

### Expected Behavior
I should be able to click on  2015/6/1

### Actual Behavior
I can't click on  2015/6/1

### Basic Information

- Version with issue: 2.5.1 SR1

**Comment by PureWeen** [comment]
I just retested this and it's still an issue

**Comment by shubham-2710** [comment]
Hey, any update on this issue?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
