### ISSUE TITLE
UI Test B40173 renders incorrectly on UWP

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#2343]
Buttons are illegible on UWP

**Comment by lewcianci** [comment]
I've decided to have a look at this to hopefully submit my first PR.  The test won't load on my PC, I've cloned Xamarin.Forms, got the win driver, but the test seems to depend on another app to load for it to do its testing in.  This is shown in WindowsTestBase.cs

appCapabilities.SetCapability("app", "0d4424f6-1e29-4476-ac00-ba22c3789cb6_ph1m9x8skttmg!App");

WinAppDriver fails with this error message

{"status":13,"value":{"error":"unknown error","message":"Package was not found.\r\n\r\nWindows cannot perform the RegisterByPackageFamilyName operation because it could not find 0d4424f6-1e29-4476-ac00-ba22c3789cb6_ph1m9x8skttmg in the repository. Make sure 0d4424f6-1e29-4476-ac00-ba22c3789cb6_ph1m9x8skttmg has been staged or was installed by another user."}}

How can I deploy the "0d4424f6-1e29-4476-ac00-ba22c3789cb6_ph1m9x8skttmg" app so I can have a look at this?  Apoligies if this is a stupid question.

**Comment by PureWeen** [comment]
@lewcianci     It isn't a stupid question.  Running the UWP tests isn't the most obvious thing and there isn't documentation for it

I realize you may have done some of these steps but I'm just listing them in case something is useful
- follow the instructions here to get the winappdriver running https://github.com/Microsoft/WinAppDriver#installing-and-running-windows-application-driver
- From the Xamarin Forms SLN launch the Xamarin.Forms.ControlGallery.WindowsUniversal project (this is what installs the app with that identifier onto your system)
- at this point you should be able to run any of the UWP tests

**Comment by puppetSpace** [comment]
Strange thing happening here. I recreated the view in the sandbox and removed all the unneeded things, which results in this code:
```
void CreateButtonsInGrid()
{
	var testButton = new Button
	{
		Text = "Can't Touch This"
	};

	var testGrid = new Grid
	{
		Children = { testButton }
	};

	var testButtonOk = new Button
	{
		Text = "Can Touch This"
	};

	var testGridOk = new Grid
	{
		Children = { testButtonOk }
	};

	var testListView = new ListView();
	testListView.ItemsSource = new[] { "Foo" };

	Content = new StackLayout
	{
		Children = { testGrid, testGridOk, testListView }
	};
}
```
Which in turns results in this view (has a width of 1141px):
![with_listview_width_1141](https://user-images.githubusercontent.com/14003064/56040038-d7ff6680-5d35-11e9-8bdf-fafa75150edd.jpg)

If I decrease the width, the button text becomes legible.
![with_listview_width_500](https://user-images.githubusercontent.com/14003064/56040334-755a9a80-5d36-11e9-87f6-4ad33a9dda98.jpg)

What makes it stranger is when I remove the listview from the stacklayout, the buttons are legible at every width.
![without_listview](https://user-images.githubusercontent.com/14003064/56040507-d6826e00-5d36-11e9-8507-5bce84fa47d7.jpg)

I don't think this is normal behaviour. Right?

**Comment by t-johnson** [comment]
This can be resolved by adding a line:
`testListView.RowHeight=23;`

after setting the ItemsSource here:
https://github.com/xamarin/Xamarin.Forms/blob/0b6bfd5118a14ed9689f9159ccf3a5f1cb865cbd/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Bugzilla40173.cs#L105

Why this renders this way on UWP and WPF, I can't explain.  My guess is it has something to do with the ListView being greedy about requesting the whole screen here:
https://github.com/xamarin/Xamarin.Forms/blob/0b6bfd5118a14ed9689f9159ccf3a5f1cb865cbd/Xamarin.Forms.Core/ListView.cs#L376
and how that is handled on the windows platforms.
