### ISSUE TITLE
[UWP]  .Focus has no effect on TimePicker

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#2391]
### Description

While fixing this issue, please also add instructions to the test case.

### Steps to Reproduce

1. Run Issue2333 in Control Gallery

### Expected Behavior

Time picker should appear when focus is called

### Actual Behavior

Nothing happens

### Basic Information

- Version with issue:3.0.0 and 2.5.1
- Last known good version:

**Comment by jkastner** [comment]
To second the above comment, I would appreciate the same fix for DatePicker.Focus. I was about to log a bug on that.

**Comment by christoroth** [comment]
I'd love a fix to this too please in TimePicker and DatePicker but looking online I cannot see any way to do this in pure UWP development.  I was quite prepared to call something UWP specific in a renderer but I've found nothing that will work.  If it's true that it's not possible in UWP, we're not going to be able to do it in Xamarin either :(

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
