### ISSUE TITLE
Android Fragment Embedding Doesn't Work When You Rotate The Screen

### ISSUE THREAD

**Issue by cosminstirbu** [xamarin/Xamarin.Forms#2396]
### Description

If you use a fragment created with `CreateFragment / CreateSupportFragment` - after you rotate the screen, all the content (view) of that fragment will be lost because the empty constructor is called by the Android framework.

### Steps to Reproduce

Checkout this commit https://github.com/cosminstirbu/Xamarin.Forms/commit/65fe6f2b0b38496a32320acdaab38092ff244511

1. Run Embedding.Droid
2. Rotate the screen - notice that everything works as expected
3. Tap on "SHOW EMBEDDED PAGE"
4. [Optionally] Set a breakpoint in EmbeddedSupportFragment parameterless constructor
5. Rotate the screen again and notice that the content is not displayed after the screen rotation

### Expected Behavior

The fragment should maintain it's state after re-creation

### Actual Behavior

The fragment doesn't have a view

### Reproduction Link

https://github.com/cosminstirbu/Xamarin.Forms/commit/65fe6f2b0b38496a32320acdaab38092ff244511

I think this is a major blocker in having Embedding feature being widely adopted in traditional Xamarin projects that use platform specific development.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
