### ISSUE TITLE
[Maps]Xamarin.Forms.Maps not able to remove a pin on Android

### ISSUE THREAD

**Issue by winffee** [xamarin/Xamarin.Forms#2411]
### Description

I'm using the latest Xamarin.Forms and Xamarin.Forms.Maps. I used map.Pins.Remove(myPin) to remove a pin in Google Map, which doesn't work at all. I have also tried custom render to remove the marker from map, which also doesn't work. I tried using native mono project to remove marker from map, it works well. Link to my [Xamarin.Forms demo](https://github.com/elvisxia/PinRemoveIssue).

### Steps to Reproduce

1.  Download the demo and build it.
2.  Click the button to remove the pin from map

### Expected Behavior
 Pin should be removed from map

### Actual Behavior
Pin is still there

**Comment by jcmanke** [comment]
My theory:

The `Marker.Id` property is a string. The `Pin.Id` property is an object. In the `AddPins` method, the pin's Id is set to the marker's Id. When the Id is used to look up pin from a marker in `MapOnMarkerClicked` the pin Id is cast to a string to compare to the clicked marker's Id. Alternatively in `RemovePins`, when looking up a marker from a pin, the marker's Id is cast to an object. So I think it's an issue of how the `object ==` operator differs from the `string ==` operator resulting in the lookup in `RemovePins` failing so the native marker is not properly found and removed.

**Comment by KaizerT** [comment]
For anyone looking for an alternative, Xamarin.Forms.GoogleMaps does not have this issue and it's very easy to migrate from Xamarin.Forms.Maps since it's forked from this project. They offer more functionalities that do not require custom renderers.

**Comment by stephenhauck** [comment]
@jcmanke did offer a possible solution [here](https://forums.xamarin.com/discussion/comment/327803#Comment_327803)  but can't someone at Microsoft take a few minutes to fix this.

I mean, the map features should function the same on both platforms.

I cannot give a customer a "half functional" Xamarin.Forms app and expect to be paid and I can't go to an outside vendor for mapping because the Xamarin examples say it works so when I point out this bug the customer doesn't care... "The website says it works" 

Someone .. anyone .. is Microsoft / Xamarin even reading and understanding this problem ?
