### ISSUE TITLE
The ItemSelected event for a grouped ListView is not working as expected.

### ISSUE THREAD

**Issue by davefxy** [xamarin/Xamarin.Forms#2446]
### Description
An item is selected in the grouped ListView. The ItemSelected event handler redirects to another page . Upon return from the redirected page back to the ListView, selecting the same ListView item does not cause ItemSelected event to occur. However when a different ListView item is selected upon return the ItemSelected will work as expected. ItemSelected works as expected upon return to the grouped ListView as long as a different item is selected. If the grouped Listview IsGroupingEnabled=false, it works as expected. I am including a solution with 2 items in the grouped list.
The solution displays the same results with UWP and Android.
### Steps to Reproduce
1.  select the first list item.
2. press the button on the new page to return to the grouped ListView
3. select the same item again. Nothing will happen

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2017 V.15.6.6
- Platform Target Frameworks: 
   - Android: 8.2 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
Microsoft.NETCORE.UniversalWindowsPlatform v6.0.8
Xamarin.Forms v2.5.1.444934
- Affected Devices:

### Reproduction Link

[EmployeeDirectory.zip](https://github.com/xamarin/Xamarin.Forms/files/1903776/EmployeeDirectory.zip)

**Comment by MelbourneDeveloper** [comment]
While you're looking at ListView grouping...

#2454

**Comment by fkbeys** [comment]
Is there a solution about this issue? i solved my problem with using behaviours ,event to command.
But if the xamarin team would solve this issue, it would be easy for developers.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by davefxy** [comment]
Yes I believe it should be closed. It was awhile ago but I believe it was  fixed by setting ItemSelected to null. I should have updated this some time ago.

**Comment by Redth** [comment]
Thanks for the update!
