### ISSUE TITLE
[Android] Force label text direction

### ISSUE THREAD

**Issue by encrypt0r** [xamarin/Xamarin.Forms#2447]
### Description
Currently on Android `FlowDirection` has no effect on how text is aligned in `Label`. Which can be quite problematic especially when the `Label` is used inside `ListView` cells.

I am not sure if this is a bug, but I think that both iOS and Android projects should be consistent (according to @ali-h2010 `Label` on iOS respects `FlowDirection`). Aligning text based on its content is very useful in some cases, but we need to have more control over it.

### Steps to Reproduce

1. Create new project
2. Add Two labels to a page
3. Write English text in the first label and Kurdish/Arabic (`نووسینی کوردی`) text in the other
3. Set Page `FlowDirection` to `RightToLeft`

### Expected Behavior
The text of both labels should be aligned right.

### Actual Behavior
The English text is still aligned left.
### Basic Information

- Version with issue:
- Last known good version: N/A
- IDE: Visual Studio 2017.6

### Screenshots

![img](https://user-images.githubusercontent.com/16880059/38658671-c75bcb10-3e2e-11e8-9d0b-b79ce1c6b465.PNG)

![919470c57e564540a10e4d163d4e4a34](https://user-images.githubusercontent.com/16880059/38698811-fea6aa16-3e9e-11e8-808c-3fd58e0aa26a.jpg)
Screenshot provided by: @ali-h2010

### Reproduction Link
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:App24"
             x:Class="App24.MainPage"
             Padding="10"
             FlowDirection="RightToLeft">

    <StackLayout>
        <Label Text="English Text" FontSize="Large" />
        <Label Text="نووسینی کوردی" FontSize="Large" />
    </StackLayout>
    
</ContentPage>
```
This is the full project: [TextDirectionRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/1901476/TextDirectionRepro.zip)

**Comment by samhouts** [comment]
This is listed as a known limitation on #1222: `TextDirection` property needs to be added. Thanks!

**Comment by huangjinshe** [comment]
In the new releaset version of nuget, the problem still there.  
My problem is more different, Looks like Android just auto handle the flwo direction by font content itselt.  

For me, I never set the flow direction, because I need to always keep it : Left to right.
But when the label content change from English to Arabic, the label layout auto changed to right to left, I don't know how should I let it keep to left to right......

**Comment by huangjinshe** [comment]
@memu8 , @samhouts .  What did you guys fixed in v4.8 ? I saw the issues still didn't fixed.

![001](https://user-images.githubusercontent.com/3822799/89752652-d56a7800-db07-11ea-8c05-4fc76da82047.png)
![002](https://user-images.githubusercontent.com/3822799/89752656-d8656880-db07-11ea-95e7-d77a10290b60.png)

Currently problem is: Android will auto changing the text layout direction based on the current language. If the language direction is RTL, it still show the text from right to left(also the layout will based on that).
If you guys need a project support multiple languages and which include language direction LTR and RTL for test, use this: [Oybab Trading System](https://github.com/oybab/TradingSystem)

**Comment by huangjinshe** [comment]
`FlowDirection="LeftToRight" HorizontalOptions="FillAndExpand"`  not working BTW.

**Comment by memu8** [comment]
@huangjinshe We fixed Labels, but this issue may still be present for Pickers and Entries. Can you please open a new issue for that? Thanks!
