### ISSUE TITLE
InputTransparent does not work on Android devices.

### ISSUE THREAD

**Issue by dkandrov** [xamarin/Xamarin.Forms#2455]
### Description
When user adds two overlapping grids on page, then controls at back grid doesn't work on Android devices. Option `InputTransparent` does not help.

### Steps to Reproduce

1. Create two overlapping grids with entries on them like on first screenshot.
2. Build and execute project for UWP, user can click and enter data to both entries. See second screenshot.
3. Build and execute project for Android, user can click and enter data only to front entry. See third screenshot.

### Expected Behavior
User can click and enter data to both entries which placed on overlapping grids (On Android devices application should work as on UWP devices).
### Actual Behavior
User can click and enter data only to front entry in application for Android.
### Basic Information

- Version with issue: 4.9.0.753
- Last known good version: - 
- IDE: Visual Studio 2017 (15.6.6)
- Platform Target Frameworks: 
  - iOS: - 
  - Android: 8.2.0.16  
  - UWP: 16299  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Meizu U10 Android 6.0

### Screenshots
- Screenshot of grids layout (step 1):
  ![image](https://user-images.githubusercontent.com/5506989/38722448-21f56ed8-3f28-11e8-8c1c-52f67d4a3736.png)
- Video how it works on UWP  (step 2)
  ![xamarin-forms-layers](https://user-images.githubusercontent.com/5506989/38722620-a33907a2-3f28-11e8-9422-dc9f8f0cb5a1.gif)
- Screenshot from android device  (step 3):
  ![image](https://user-images.githubusercontent.com/5506989/38722696-f0a81122-3f28-11e8-8e48-fe32f9675777.png)

### Reproduction Link
https://github.com/dkandrov/xamarin-bug-with-InputTransparent

**Comment by hartez** [comment]
@dkandrov The layout you're aiming for is not possible on Android with Xamarin.Forms 2.5 (and it only works in UWP because of a quirk in how UWP handles hit testing). 

We added a feature in XF 3.0 (PRs [1621](https://github.com/xamarin/Xamarin.Forms/pull/1621) and [1771](https://github.com/xamarin/Xamarin.Forms/pull/1771)) to make your layout possible. With 3.0, you would change line 29 of your example's MainPage.xaml from 

```
<Grid InputTransparent="False">
```

to

```
<Grid InputTransparent="True" CascadeInputTransparent="False">
```

This will make the Grid input transparent while leaving the "front entry" non-transparent. This will work for Android, iOS, and UWP.

The stable release of 3.0 will be coming out soon; in the meantime, you can try the latest pre-release packages: https://www.nuget.org/packages/Xamarin.Forms/3.0.0.354232-pre3

**Comment by dkandrov** [comment]
I checked on the pre-release version, and everything works.
Thanks.
