### ISSUE TITLE
XAMLC fails on lowercase color even though it works

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#2459]
### Description
XAMLC complains about `red` even though it should work and Previewer doesn't mind.

### Steps to Reproduce

```
<BoxView BackgroundColor="red"/>
```

### Expected Behavior
Works in Previewer. Compiles. Works on device.

### Actual Behavior
Works in Previewer. Fails XAMLC.

`Views/CameraView.xaml(31,31): Error: Position 14:31. Cannot convert "red" into Xamarin.Forms.Color`

### Basic Information

- Version with issue: 3.0-pre3

### Screenshots
<img width="1246" alt="screenshot 2018-04-13 08 36 02" src="https://user-images.githubusercontent.com/41873/38738586-2276f992-3ef8-11e8-888e-6980db576cc8.png">

**Comment by StephaneDelcroix** [comment]
The correct spelling for the Xaml value is `Red` (uppercase `R`). Since we also have to accept css-style values, the runtime TypeConverter accepts `red`. This is why it works in the previewer, or with XamlC turned off.

But we don't have be strict on that. And as it doesn't cost anything to also accept lowercase colors (or css-style ones, I think we should allow those.
