### ISSUE TITLE
[UWP]ListView ItemAppearing Event has a weird behavior

### ISSUE THREAD

**Issue by dydeW** [xamarin/Xamarin.Forms#2478]
### Description
I'm trying to do pagination of data when scrolling on a ListView. I use the ItemAppearing event on the ListView to detect when the last item of the list is shown so that I can ask my ViewModel to load more. It wortks fine on Android and iOS but on UWP there is a weird behavior with the ItemAppearing event.

### Steps to Reproduce

1.  Use a similar OnItemAppearing event to this on the ListView : 
 ```
void OnItemAppearing(object sender, ItemVisibilityEventArgs args)
        {
            var item = (Item)args.Item;
            if (item == null)
                return;

            var items = ItemsListView.ItemsSource as System.Collections.IList;
            var index = items.Count - 1;

            if (item == items[index])
            {
                Debug.Write("Last item of collection has appeared");
            }

        }
```
And don't forget to put into the xaml in the listView properties: 
`ItemAppearing="OnItemAppearing"`
2. Run the sample and debug the method

### Expected Behavior
We should see the "Last item of collection has appeared" only if the item is being shown or is totally shown.

### Actual Behavior
At the launch of the app, even though there are 30 items in the list, the last item has "appeared" for UWP. If I scroll to the bottom nothing more is written. The Debug.Write is never called again.

This works fine on Android and iOS. The "Last item of collection has appeared" appears correctly only when the last item has appeared while scrolling. And if I scroll back to top then again to bottom it still has the correct behavior : The Debug.Write is called each time the last item is appearing/has appeared.

### Basic Information

- Version with issue: Xamarin Forms 2.5.0.280555 (still present on 2.5.1.444934)
- Last known good version:
- IDE: Visual Studio 2017 15.6.6
- Platform Target Frameworks: 
  - iOS:  11.3
  - Android: 8
  - UWP:  16299 
- Nuget Packages:
- Affected Devices:

### Reproduction Link
[TestItemAppearing.zip](https://github.com/xamarin/Xamarin.Forms/files/1915843/TestItemAppearing.zip)

**Comment by samhouts** [comment]
Each platform preloads a certain number of items in its collection to ensure that smooth scrolling will occur. This is a function of the OS, not of Xamarin.Forms.

UWP has a high realization threshold, especially on desktop, since it has more memory to work with. What you're seeing here is UWP realizing all of your list items so it can display the list as it scrolls without too much of a delay. If you increase your mock items to, say, 1000 items, you won't see your appearing message until you've scroll almost all the way to the bottom. 

```csharp
var mockItems = Enumerable.Range(0, 1000).Select(p => new Item { Id = Guid.NewGuid().ToString(), Text = $"{p} item", Description = "This is an item description." }).ToList();
```

This is an old blog post, but I like the diagrams that it uses to explain the realization window. https://blogs.msdn.microsoft.com/alainza/2014/09/03/listview-basics-and-virtualization-concepts/

I hope that helps!

Thanks
