### ISSUE TITLE
[UWP, Android] Changing HasUnevenRows at runtime on UWP or Android has no effect

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#2484]
### Description

 Changing HasUnevenRows at runtime on UWP has no effect

### Steps to Reproduce

1. Run issue bugzilla 59298 on UWP or Android
2 . Click Add new Data
3.  Click Toogle Uneven Rows

### Expected Behavior
Should show rows with diferent height

### Actual Behavior

Row height's are the same even after toggling the HasUNevenRows property 

### Reproduction Link

Gallery issue 59298

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
