### ISSUE TITLE
MarkupExtension not found with net standard 2.0

### ISSUE THREAD

**Issue by EltonGarcia** [xamarin/Xamarin.Forms#2521]
### Description
MarkupExtension not found with net standard 2.0

### Steps to Reproduce

1. Clone the issue project sample (https://github.com/EltonGarcia/XamarinMarkupExtensionIssue)
2. Build the project

### Expected Behavior
Build successful

### Actual Behavior
Build fails with error: Type design:HslColorExtension not found in xmlns clr-namespace:Design.Extensions;assembly:Design (MarkupIssue)

### Basic Information

- Version with issue: 2.5.1.444934
- Last known good version: ?
- IDE: Visual Studio for Mac
- Nuget Packages: Xamarin Forms and System.ComponentModel

### Reproduction Link

https://github.com/EltonGarcia/XamarinMarkupExtensionIssue

**Comment by StephaneDelcroix** [comment]
Some preliminary remarks about your sample:

- the correct usage of a markup extension would be `<BoxView Color="{design:HslColor H=0, S=1, L=5, A=1}" />`. The element syntax works as well, but then it's not a markup extension anymore...
- as you're not using the serviceProvider, you can instruct the Xaml compiler and the runtime inflater to avoid generating one by decorating your markup extension class with `[AcceptEmptyServiceProvider]`
- the ColorTypeConverter supports the `hsla(120, 100%, 50%, .8)` or `hsl(120, 100%, 50%)` CSS syntaxes, so your markup extension isn't required (since 2.4.0)

and about your issue... The correct syntax for the `clr-namespace` xmlns is
```
xmlns:design="clr-namespace:Design.Extensions;assembly=Design"
```
and not
```
xmlns:design="clr-namespace:Design.Extensions;assembly:Design"
```
