### ISSUE TITLE
macOS: ActivityIndicator freezes after window de-minimizes

### ISSUE THREAD

**Issue by johannes-schmitt** [xamarin/Xamarin.Forms#2537]
### Description
On macOS, ActivityIndicator freezes after the Window de-minimizes.
### Steps to Reproduce

1. Build and Run the attached project
[ActivityIndicatorStuck.zip](https://github.com/xamarin/Xamarin.Forms/files/1942612/ActivityIndicatorStuck.zip) on macOS (I have 10.13.4) - it's as minimal as I could get it, only one ContentPage with a StackPanel and an ActivityIndicator
2. Observe that the ActivityIndicator spins
2. Minimize the Window (e.g. using the yellow minimize button in top left corner of the window)
3. De-minimize the Window by clicking the app's "thumbnail" in the dock (next to the trash). Interestingly, the problem does not appear, if the app is de-minimized using the app icon in the dock (not the one next to the trash). I attached a screen recording to make this more obvious: 
[screen_recording.zip](https://github.com/xamarin/Xamarin.Forms/files/1942649/screen_recording.zip)

### Expected Behavior
The ActivityIndicator continues spinning
### Actual Behavior
The ActivityIndicator stops spinning

### Screenshots
[screen_recording.zip](https://github.com/xamarin/Xamarin.Forms/files/1942649/screen_recording.zip)

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
