### ISSUE TITLE
[iOS] Map.UserTrackingMode broken when inside MasterDetailPage

### ISSUE THREAD

**Issue by duzenko** [xamarin/Xamarin.Forms#2540]
Map does not show user location and/or direction headlight when UserTrackingMode is set the second time.

### Steps to Reproduce

1. Start the attached app
2. Click the 'nav' button
3. Click the 'switch' button
4. Click the 'switch' button
5. Click the 'nav' button

### Expected Behavior
Map shows current location and direction headlight.

### Actual Behavior
Map does not show user location and/or direction headlight

### Basic Information

- Version with issue: 2.5
- Last known good version: 2.3
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  11

### Screenshots

![simulator screen shot - iphone 6 - 2018-04-24 at 18 32 07](https://user-images.githubusercontent.com/1481807/39198243-43f570bc-47ef-11e8-9475-99dbad6d9fdd.png)
![simulator screen shot - iphone 6 - 2018-04-24 at 18 32 20](https://user-images.githubusercontent.com/1481807/39198245-44291df4-47ef-11e8-939c-273409b08ea7.png)

### Reproduction Link

[asd.zip](https://github.com/xamarin/Xamarin.Forms/files/1943644/asd.zip)

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by duzenko** [comment]
We gave up on Xamarin and rewrote the app in React Native a long time ago
Feel free to close this issue now that you have been too busy for look at for two years
