### ISSUE TITLE
ActivityIndicator does not work on Android

### ISSUE THREAD

**Issue by SamuelLioult** [xamarin/Xamarin.Forms#2541]
### Description
I have an issue with the ActivityIndicator control. This one is not displayed on Android. But it is correctly displayed on other platforms (iOS and UWP).

### Steps to Reproduce

1. I just add an ActivityIndicator control in a blank Xamarin App.
2. You can reproduce my issue with the uploaded project

### Expected Behavior
The ActivityIndicator should be displayed at the start of the app.

### Actual Behavior
The expected behavior only works on iOS and UWP but it does not work on my Android device (Nexus 5, Android 6.0.1)

### Basic Information

- Version with issue: Xamarin Forms 2.5.0.122203
- IDE: Visual Studio 2017 Community Edition
- Platform Target Frameworks:
  - Android: 6.0
- Affected Devices: Nexus 5

### Reproduction Link
[SimpleActivityIndicator.zip](https://github.com/xamarin/Xamarin.Forms/files/1945905/SimpleActivityIndicator.zip)

**Comment by bbenetskyy** [comment]
Hi, reproduce this issue for Android only.

**Basic Information**
- Version with issue: Xamarin Forms 4.0.0.425677
- IDE: Visual Studio 2019 Professional Version 16.1.2
- Platform Target Frameworks:
   - Android: 6.0.1
- Affected Devices: Galaxy S6


For other devices except Galaxy S6 all work correctly

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
