### ISSUE TITLE
[Android] Editor components not focus properly inside ListView in Android

### ISSUE THREAD

**Issue by RathanakumarSekar** [xamarin/Xamarin.Forms#2573]
### Description
We have using 3rd party components in application and 3rd party Editor component (Like NumericTextBox, AutoComplete) doesn't focus properly, inside the ListView ItemTemplate.

### Expected Behavior
It should focus.

### Actual Behavior
Components doesn't focus properly inside ListView.

### Basic Information

- Version with issue:2.5.1.444934

- Platform Target Frameworks: 
 Android
[SyncfusionListView.zip](https://github.com/xamarin/Xamarin.Forms/files/2040760/SyncfusionListView.zip)

**Comment by RathanakumarSekar** [comment]
Hi @hartez 

This issue occur while use Syncfusion editor components.

**Comment by PureWeen** [comment]
@RathanakumarSekar   can you open an issue with syncfusion and link them this issue?  I was able to see what you're seeing but at this point I would put the issue in their court.

**Comment by RathanakumarSekar** [comment]
Hi @PureWeen,

I have attached the call stack image for your reference. In that EditText focus changed override method called continuously when placed inside Listview.
![screen shot 2018-06-21 at 3 53 29 pm](https://user-images.githubusercontent.com/36629214/41713779-d136f1cc-756b-11e8-81f6-930e12c0a441.png)

**Comment by RathanakumarSekar** [comment]
Hi Team,

Any update on this?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
