### ISSUE TITLE
Regression - Android - Exception thrown when page is popped

### ISSUE THREAD

**Issue by ceblanda** [xamarin/Xamarin.Forms#2576]
PopAsync after a PushAsync throws Unhandled Exception:
System.InvalidOperationException: Collection was modified; enumeration operation may not execute. occurred

Run the attached program.  It will present a list of 'Announcements'.  
1. Tap one of the items to open a second page
2. press the back button to return to the previous page
3. exception is thrown

Page will pop without exception

Exception is thrown

- Version with issue:  2.5.1.444934
- Last known good version:  2.5.0.122203
- IDE: VS2017
- Platform Target Frameworks: 
  - Android: 8.1
- Android Support Library Version: 27.0.2
- Nuget Packages:
- Affected Devices:

[PopException.zip](https://github.com/xamarin/Xamarin.Forms/files/1965013/PopException.zip)

**Comment by ceblanda** [comment]
This is also an issue in 3.0.0.427558-pre4

**Comment by ceblanda** [comment]
This is only an issue using Material Design.  If I switch the Android MainActivity to inherit from FormsApplicationActivity instead of FormsAppCompatActivity there is no exception thrown.

**Comment by kingces95** [comment]
https://github.com/xamarin/Xamarin.Forms/pull/2792

**Comment by aquisio** [comment]
I am seeing a similar problem (but a different exception) when executing PopAsync after inserting a page into the navigation stack, which seems to be a regression of [this issue](https://bugzilla.xamarin.com/show_bug.cgi?id=53179).

```
System.ArgumentOutOfRangeException: Index was out of range.
at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.GetFragment
```
As noted by @ceblanda, this only affects Android projects using Material Design (FormsAppCompatActivity).

I have tested multiple Xamarin.Forms and Xamarin.Android.Support versions.

It affects all versions of Xamarin.Forms since v2.5.1.444934 and is present with both Xamarin.Android.Support v25.4.0.2 and v27.0.2.

[BugRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/2034437/BugRepro.zip)
[StackTrace.txt](https://github.com/xamarin/Xamarin.Forms/files/2034439/StackTrace.txt)

**Comment by kingces95** [comment]
@aquisio Could you open a separate issue for you exception and reference this one?
