### ISSUE TITLE
CompressedLayout.SetIsHeadless will renderer twice on iOS platform.

### ISSUE THREAD

**Issue by jessejiang0214** [xamarin/Xamarin.Forms#2590]
### Description
I try to use CompressedLayout.SetIsHeadless on my App, I find some time it will call custom renderer twice in some situation. As it called twice OnElementChanged in some custom control and that control cannot show the right UI, like it added subview twice. And this only happens on iOS.

### Steps to Reproduce

1. Create some custom control 
2. Put it the custom control into a StackLayout set CompressedLayout.SetIsHeadless is true for StackLayout
3. Put the StackLayout into a Grid and the Grid set CompressedLayout.SetIsHeadless as false.
4. Print out something in ElementChanged.

### Expected Behavior
It should print once.

### Actual Behavior
iOS print twice, but Android print once.
### Basic Information

- Version with issue: 2.5.1.444934
- Last known good version: Unknow
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  11.9.1.24
  - Android: 8.2.0.16 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[Demo project](https://www.dropbox.com/s/dqsonznv5qlaglt/LayoutCompressionIssues.zip?dl=0)

**Comment by aimore** [comment]
Any news?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
