### ISSUE TITLE
Basic examples for usage with PowerShell Core

### ISSUE THREAD

**Issue by Juanito99** [xamarin/Xamarin.Forms#2640]
Hi there,

could you provide a few simple examples that show how to use it with PowerShell Core?
That would open also cross platform GUIs for sysadmins like me :bowing_man: 

Thanks in advance

Ruben

PS: An example traditional [windows.forms](https://docs.microsoft.com/en-us/powershell/scripting/getting-started/cookbooks/creating-a-custom-input-box?view=powershell-6) with PowerShell.

**Comment by conceptdev** [comment]
Thanks for the suggestion. We'll keep it in mind for the future.

**Comment by mi-hol** [comment]
@conceptdev would it not make more sense to keep this issue open, so it stays visible for future planning?
I had raised basically the same request on https://github.com/dlwyatt/WinFormsExampleUpdates

**Comment by mi-hol** [comment]
@samhouts @conceptdev would it be possible to share your plan to address this gap?

**Comment by agowa338** [comment]
@samhouts Or should we just recreate this issue in a view weeks to get some insight, if you're unwilling to provide it within this issue?

**Comment by conceptdev** [comment]
PowerShell is not currently a supported scenario for Xamarin.Forms, so there are no plans to share. 

Xamarin.Forms is open-source, so if someone in the community wishes to investigate further, all the code is available. Note that Xamarin.Forms projects have a separate project for each platform-specific app, because each platform requires a different set of platform-specific assemblies and startup routine. This suggests that it will not be possible to have a single script (like the WinForms example given above) that would automatically run on all PowerShell platforms.
