### ISSUE TITLE
UWP frozen & eating CPU

### ISSUE THREAD

**Issue by thomai-d** [xamarin/Xamarin.Forms#2681]
### Description
After upgrading XF from 2.5.1.527436 to 3.0.0.446417 my app freezes in a particular screen after calling PushAsync / Navigate.

I managed to reproduce the bug in the attached project.

### Steps to Reproduce

1. Download & run the attached project
2. Click the button => Freeze
3. Downgrade the Xamarin.Forms package to 2.5.1.527436 => No Freeze

- IDE: VisualStudio 15.7.1
- Platform Target Frameworks: 
  - UWP:  16299
- Nuget Packages: Xamarin.Forms 3.0.0.446417
- Affected Devices: Windows 10 1709 (Build 16299.431)

### Reproduction Link
[XF.Bug.zip](https://github.com/xamarin/Xamarin.Forms/files/1996345/XF.Bug.zip)

**Comment by PureWeen** [comment]
I tested this with the latest 3.1 bits and I can't recreate the issue

If you want to you can test the nightly
https://blog.xamarin.com/try-the-latest-in-xamarin-forms-with-nightly-builds/

Otherwise when the next 3.1 pre build comes out can you test against that and let me know if you see the issue?

**Comment by thomai-d** [comment]
I tested my app as well as the given demo project with 3.1.0.469394-pre1 and the bug is still present.

**Comment by PureWeen** [comment]
I'm still looking further into the root cause of this one

On the latest code this one doesn't crash because of this fix
https://github.com/xamarin/Xamarin.Forms/pull/2515

Which isn't directly related to the deadlock in this code so I'm still pinpointing a more reliable fix.  I can only really get this one to fail on one of my dev systems as well. On my main system the repro project never crashes and always works fine.

**Comment by thomai-d** [comment]
Fixed with the newest 3.0.0.482510 NuGet-Package.

Thanks a lot!

**Comment by patsadow2** [comment]
Still suck in 3.0.0.482510 how did u achieve it ? thomai-d

 _viewModel.Messages.CollectionChanged += (sender, e) =>
            {
                var target = _viewModel.Messages[_viewModel.Messages.Count - 1];
                MessagesListView.ScrollTo(target, ScrollToPosition.End, false);
     
            };

**Comment by PureWeen** [comment]
@patsadow2  can you put that code in the CollectionChanged inside a *Device.BeginInvoke* and let me know if that fixes?
