### ISSUE TITLE
Issue in latest update of Xamarin.Forms(v3.0). Items are not shown when change the border color in the renderer.

### ISSUE THREAD

**Issue by RawoofSharief** [xamarin/Xamarin.Forms#2732]
Hi Team,

### Description

I have write the extended class of **ContentView** and load the label as a content, then add the contentview as a children of StackLayout which is loaded inside the ScrollView.
I have a property IsSelected in the ContentView and changed the IsSelected property in the TapGesture event of the label loaded in the ContentView.
I have write the Renderer class for the ContentView in the UWP platform, and set the border color for the element, but the label text is not shown.

### Steps to Reproduce

1. Run the attached sample
2. Navigate the page by click the button.
3. Click the label and you can see that the label text is not shown.

### Expected Behavior
Label should shown when change the color.
### Actual Behavior
Label is not shown.
### Basic Information

- Version with issue: **Xamarin.Forms(v3.0.0.446417)**
- Last known good version: **Xamarin.Forms(v2.5.1.5274636)**
- UWP:  < 16299 >

### Screenshots

**Before changing the color**

![image](https://user-images.githubusercontent.com/39043330/40096791-18d81a3a-58f0-11e8-95e7-da89fe5afe9c.png)

**After changing the color**

![image](https://user-images.githubusercontent.com/39043330/40096798-25d74044-58f0-11e8-9e77-21abca7c1c83.png)

### Reproduction Link

[BugSample.zip](https://github.com/xamarin/Xamarin.Forms/files/2007529/BugSample.zip)

**Comment by paymicro** [comment]
I think PR https://github.com/xamarin/Xamarin.Forms/pull/2762 fixes his issue.
Since the problem is in `ZIndex` of Labels

**Comment by StephaneDelcroix** [comment]
@pauldipietro could you confirm that the latest 3.0.0-sr fixes the issue ?

**Comment by pauldipietro** [comment]
Appears to behave the same as before for me

**Comment by rmarinho** [comment]
@RawoofSharief we are looking at this issue, in the meanwhile you can update your  nuget package on 3.0.0  or 3.1.0 and use this, the trick is set the Z-Index

``` 
  protected override void OnElementChanged(ElementChangedEventArgs<ContentViewExt> e)
 {
		base.OnElementChanged(e);
		if (e.NewElement != null)
		{
			this.border = new Border();
			Canvas.SetZIndex(this.border, -1);
			this.SetNativeControl(this.border);
		}
	}

```

**Comment by PureWeen** [comment]
Hmm this is an interesting one
This originally worked on 2.5 because in 2.5 the Z-Indexes of everything in UWP were set from 1 to N by default

So the border being added in this sample would default as 0 and thus be lower than 1 to N 

After this PR https://github.com/xamarin/Xamarin.Forms/pull/1196  the Z-Index is only set if some operation (RaiseChild, LowerChilder, Insert) causes a view to want to move around in the Z-Index hierarchy.  The way the controls are added now is just the natural ordering of UWP without intervention from us

This now means that the Border when added via this renderer just gets added with it's natural Z-Index against all the other controls Z-Indexes and that's the behavior we now see

The only way I can currently think to make the sample here work would be to totally reverse the performance benefits of
 https://github.com/xamarin/Xamarin.Forms/pull/1196 and just go back to setting everyone's z-indexes

**Comment by rmarinho** [comment]
We talked on our standup today and we think the best for the users and going forward is to keep the fix of the Z-Index hierarchy. We will make sure to add to the release notes.

Please use the above fix of setting the Z-Index on the border to -1. Reopen this issue if you have any troubles. 

Thanks.
