### ISSUE TITLE
[UWP] An InkCanvas in a Custom Renderer in a <Frame> does not work

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Xamarin.Forms#2748]
### Description

I crated a custom control to host an `InkCanvas` in an app, but when placed inside a `<Frame>`, the ink does not work.

### Steps to Reproduce

1. Create a new Forms view
2. Create a new native control that hosts an `InkCanvas`
3. Create a custom renderer
4. Put the custom view into a `<Frame>`
5. Drawing does not work

### Expected Behavior

Drawing should work in a `<Frame>`.

### Actual Behavior

Drawing does not work.

### Basic Information

- Version with issue: 2.5.x and 3.0.x
- Last known good version: -
- IDE: VS2017
- Platform Target Frameworks: 
  - UWP:  10.0.16299.0 
- Affected Devices: Surface Book

### Reproduction Link

A full repro repo ;) lives here: https://github.com/mattleibow/FrameBlockers

**Comment by mattleibow** [comment]
Another observation that was made was if the `InputTransparent="True"` on the `<Frame>`, then the ink works again. I am not sure of all the inner workings of Xamarin.Forms, but that may be helpful.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by mattleibow** [comment]
Soooo, this seems to be working now... I just downloaded my sample and it just works. I think this may have been a Windows issue because I didn't even update the version of Xamarin.Forms.

Closing this and hopefully all is well forevermore!
