### ISSUE TITLE
Focused entry doesn't come upper of the keyboard while use in ListView

### ISSUE THREAD

**Issue by RathanakumarSekar** [xamarin/Xamarin.Forms#2768]
Description:

We have used the Entry in ItemTemplate of the ListView and while focusing the entry, It doesn't come upper of keyboard. So, Keyboard make that entry disappear. 

### Expected Behavior

Focused entry should come automatically upper of keyboard.

### Actual Behavior

Focused entry doesn't come top of keyboard.

### Basic Information

- Version with issue: 3.0.0.482510
- Platform Target Frameworks: 
  - iOS:  11.3

- Affected Devices:
iOS Simulator iPhone 8 v11.3

**Comment by pauldipietro** [comment]
Can you provide a reproduction? This may have been reported at some point as well elsewhere; it sounds at least vaguely familiar.

**Comment by rjantz3** [comment]
Here's a repro of this problem. This is a Xamarin.Forms File->New solution with just a few tweaks.

[EntryKeyboardTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2024594/EntryKeyboardTest.zip)

**Comment by HarkerTech** [comment]
We have recently run into this bug in one of our projects. We have found that this occurs when CachingStrategy is set to "RecycleElement" or "RecycleElementAndDataTemplate". A workaround is to set the CachingStrategy to "RetainElement". Verified bug still exists in Xamarin.Forms 3.2.0.839982, hope this helps.

**Comment by felipesouto** [comment]
Any news on a fix for this?
Setting CachingStrategy="RetainElement" is a bad workaround for this problem.

**Comment by RathnaPrem** [comment]
Any update on a fix?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
