### ISSUE TITLE
[Android] The method Dispose in TabbedRenderer would be called twice if the page which extends TabbedPage is popped out.

### ISSUE THREAD

**Issue by devinZhou102** [xamarin/Xamarin.Forms#2777]
### Description
In Android ,The method Dispose in TabbedRenderer would be called twice if the page which extends TabbedPage is popped out. 
### Steps to Reproduce

1.  Custom a page extends TabbedPage
2.  Custom a renderer extens TabbedRenderer 
3.  Use the custom page in project 
4.  pop out the custom page

### Expected Behavior
he method Dispose in TabbedRenderer should be called once.

### Actual Behavior
The method Dispose in TabbedRenderer would be called twice 

### Basic Information

- Version with issue:Xamarin.Forms Version >= 3.0
- Last known good version: Xamarin.Forms Version < 3.0
- IDE: Vistual Studio 2017  v15.7.1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  Android8.1 
  - UWP:   
- Android Support Library Version: V27.0.2
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment]
@devinZhou102   can you provide a repro?  I've attached a test of this one and I am only seeing dispose being called once

[TabbedRendererDispose.zip](https://github.com/xamarin/Xamarin.Forms/files/2025360/TabbedRendererDispose.zip)

**Comment by devinZhou102** [comment]
@PureWeen I think that I made a mistake while describing the issue. While I am setting App.Current.MainPage = new NavigationPage(...) in  the page which extends TabbedPage it cause the problem.
[TabbedPageRendererDispose.zip](https://github.com/xamarin/Xamarin.Forms/files/2026611/TabbedPageRendererDispose.zip)

**Comment by PureWeen** [comment]
Thank you for the repro

I still don't think I would call this a bug though as the dispose is called in multiple places just due to making sure we catch all the scenarios for cleaning up resources.

If you look at the documentation on dispose pattern
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern

> ✓ DO allow the Dispose(bool) method to be called more than once. The method might choose to do nothing after the first call. 

Whatever bug is occurring because of this duplicate call is more an indication that the dispose pattern isn't being properly implemented.

is there a defect internally to Xamarin Forms caused by this being called multiple times? Or is it something in the *NAXAM* library?  The *NAXAM* library should be able to handle multiple calls to dispose on the tabbed renderer and be able to adjust accordingly

**Comment by devinZhou102** [comment]
@PureWeen  Thank you for your help.
I think the method Dispose is called multiple times is used to ensure that resources are cleaned up is ok, but sometimes confusing.
