### ISSUE TITLE
[Android] Right-to-Left MasterDetail in Xamarin.Forms v3 Hamburger icon issue

### ISSUE THREAD

**Issue by paradisehuman** [xamarin/Xamarin.Forms#2818]
### Description
We have a masterdetail navigation in our app, the issue is when we set culture to RTL and set FlowDriection to RTL, the Hamburger icon is not going to right side and still is on the left side !
### Steps to Reproduce

1. Add master detail page to your app
2. Set device culture to Arabic or Persian 
3. Set FlowDirection to RTL

### Expected Behavior
Seeing Hamburger and back button on the right side
### Actual Behavior
Seeing Hamburger and back button on the left side
### Basic Information

- Version with issue: 3.0.0.482510
- Last known good version: -
- IDE: Visual Studio 15.7.2
- Platform Target Frameworks: 
  - Android: 8.1
- Android Support Library Version: 27.0.2
- Nuget Packages: Xamarin.Forms 
- Affected Devices: Android Emulator

**Comment by rabih-harb** [comment]
this is also in IOS...

**Comment by paradisehuman** [comment]
@rabih-harb 
If you Add this peace of code to your info.plist : 
`<key>CFBundleLocalizations</key>
  <array>
    <string>ar</string>
  </array>`
It force your iOS device to have RTL culture and move the Hamburger icon to right side.

**Comment by rabih-harb** [comment]
thx paradise it slipped.. am trying to change that i runtime - but it seems to get stuck on the initial culture the device started on
AppDelegate.cs
```
if (lang == 3)
            {//arabic 
                var userSelectedCulture = new System.Globalization.CultureInfo("ar");
                //Thread.CurrentThread.CurrentCulture = userSelectedCulture;
                Thread.CurrentThread.CurrentUICulture = userSelectedCulture;
            }

```
it doesnt seem to change anything.

**Comment by rabih-harb** [comment]
guys found out that the **

> master-detail page icon always read from Device.cultureinfo and not from anything at runtime

**. maybe this should speed up its fix!! it needs to read from the user selected language makes more sense cause most apps offer the user to select the preferred language

**Comment by rabih-harb** [comment]
well, Ahmed, the solution turned out to be a bit dirty coding, and it works for ios9 +, if you are  on ios 8 and below the changes won't happen until the next app restart, so to force the layout RTL and LTR on IOS :

AppDelegate.cs
` ....... code .......
       PathManager_IOS pathManager = new PathManager_IOS();
            if (lang == 3)
            {//arabic 
                //var userSelectedCulture = new System.Globalization.CultureInfo("ar");
                pathManager.SetLayoutRTL();//<-----///

            }
            if (lang == 1||lang == 2)
            {//English or other 
                //var userSelectedCulture = new System.Globalization.CultureInfo("en");
                pathManager.SetLayoutLTR();//----->///
            }
        ....... code .......
            LoadApplication(new App(m, lang));
`
this sets the layout on app startup depending on the value saved in the database or depending on the current localization.
below is the code of path manager which is a shared service for PCL
`using System;
using System.IO;
using Xamarin.Forms;
using bureaupedagogic.iOS;
using bureaupedagogic.database;
using ObjCRuntime;
using System.Runtime.InteropServices;
using UIKit;
using System.Diagnostics;

[assembly: Dependency(typeof(PathManager_IOS))]
namespace bureaupedagogic.iOS
{
	public class PathManager_IOS : IPathManager
    {
        **[DllImport(ObjCRuntime.Constants.ObjectiveCLibrary, EntryPoint = "objc_msgSend")]
        internal extern static IntPtr IntPtr_objc_msgSend(IntPtr receiver, IntPtr selector, UISemanticContentAttribute arg1);**

        public PathManager_IOS()
        {

        }
       public void SetLayoutRTL()
        {
            try
            {
                Selector selector = new Selector("setSemanticContentAttribute:");
                IntPtr_objc_msgSend(UIView.Appearance.Handle, selector.Handle, UISemanticContentAttribute.**ForceRightToLeft**);
            }
            catch (Exception s)
            {
                Debug.WriteLine("failed to set layout...."+s.Message.ToString());
            }
        }
        public void SetLayoutLTR()
        {
            try
            {
                Selector selector = new Selector("setSemanticContentAttribute:");
                IntPtr_objc_msgSend(UIView.Appearance.Handle, selector.Handle, UISemanticContentAttribute.**ForceLeftToRight**);
            }
            catch (Exception s)
            {
                Debug.WriteLine("failed to set layout...." + s.Message.ToString());
            }
        }
    }
}`



to set the layout on runtime, just refer to it on button click or something

```
// arabic 
DependencyService.Get<IPathManager>().SetLayoutRTL();

// English 
DependencyService.Get<IPathManager>().SetLayoutLTR();
```
so guys at the end all this, is to set the master details page icon to RTL during runtime and on startup without the localization. maybe in the future, you guys could make its property accessible
something similar to flow direction 

![simulator screen shot - iphone 8 - 2018-05-31 at 18 36 05](https://user-images.githubusercontent.com/366373/40792026-8e92c028-6501-11e8-8624-1b4ee0e18ccc.png)
![Uploading Simulator Screen Shot - iPhone 8 - 2018-05-31 at 18.27.59.png…]()

**Comment by Rajeswari06** [comment]
@samhouts Can you let me know, When this will be available to public users?

**Comment by dannykhreet** [comment]
@samhouts  on which version well get the RTL ?
