### ISSUE TITLE
[MacOS] It's not possible to set transparent background color for a listview

### ISSUE THREAD

**Issue by anton-makarevich** [xamarin/Xamarin.Forms#2820]
### Description
It's not possible to set transparent background color for a listview

### Steps to Reproduce

1. Put a lisview into some container that has any color different from white. 
2. Set listview background color to transparent

### Expected Behavior
ListView is transparent and container color is visible through it (it works like that on iOS, Android and UWP)

### Actual Behavior
Listview has a white background.

### Basic Information

- Version with issue: 3.0.0.482510
- Last known good version: N/A
- IDE: VisualStudio for Mac 7.5 (build 1254)

The bug is actually very simple. Native tableView is hosted by a NSScrollView and when tableView is transparent you can see ScrollView through it. 
The basic fix (or workaround) is to set `DrawsBackground` property of a scrollview to false (`Xamarin.Forms.Platform.MacOS/Renderers/ListViewRenderer.cs, line 110`).

### Reproduction
```C#
ListView view = new ListView(ListViewCachingStrategy.RecycleElement);
			view.BackgroundColor = Color.Transparent;

			view.ItemTemplate = new DataTemplate(() =>
			{
				ViewCell cell = new ViewCell();
				Label label = new Label();
				label.Text = "Candy Mountain";
				cell.View = label;
				return cell;
			});

			view.ItemsSource = Enumerable.Range(0, 100);
			return new NavigationPage(new ContentPage()
			{
				Content = new StackLayout()
				{
					Children =
					{
						new Label(){
							Text = "You should be seeing pink everywhere"
						},
						view
					}
				},
				BackgroundColor = Color.Pink
			});
```

**Comment by GalaxiaGuy** [comment]
I believe this was fixed here: https://github.com/xamarin/Xamarin.Forms/pull/6050

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
