### ISSUE TITLE
[Android] Renderers associated with ListView cells are occasionaly not being disposed of which causes left over events to propagate to disposed views

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#2829]
### Description
A number of issues have popped up related to the renderers of a ListView not all correctly disposing. The use cases are generally the same
- Setup list view for recycling
- Navigate to a page with the listview
- scroll some
- pop the page off
- do this over and over again and at some point an exception will occur related to dispose

This issue is meant to be the root issue for the set of issues people have logged for this problem.

My current theory on this goes as follows 

In certain cases when you scroll a list view and it creates a new view using view recycling this would cause a view to become non visible but still exist in memory.

Because of this when iterating with GetChildAt you would be returned NULL for a given position because that view isn't visible though it and its resources still exist in memory. 

What this means is that DisposeCells now will not be able to access said View 

```C#
void DisposeCells()
		{
			var cellCount = _realListView?.ChildCount ?? 0;
			for (int i = 0; i < cellCount; i++)
			{
				var layout = _realListView.GetChildAt(i) as ConditionalFocusLayout;

				// Headers and footers will be skipped. They are disposed elsewhere.
				if (layout == null || layout.IsDisposed())
					continue;
```

### Steps to Reproduce

https://github.com/xamarin/Xamarin.Forms/issues/2746
https://github.com/xamarin/Xamarin.Forms/issues/2004
https://github.com/xamarin/Xamarin.Forms/issues/2421
https://github.com/xamarin/Xamarin.Forms/issues/2406
https://github.com/xamarin/Xamarin.Forms/issues/2041
https://github.com/xamarin/Xamarin.Forms/issues/2317
https://bugzilla.xamarin.com/show_bug.cgi?id=57789

### Proposed Fix
https://github.com/xamarin/Xamarin.Forms/tree/fix-gh2829

### Expected Behavior
All created views should be disposed of

### Actual Behavior
Occasionally a non visible view is not recycled

### Basic Information

- Version with issue: 3.0
- Last known good version: unknown

### Resolution 
I have a branch https://github.com/xamarin/Xamarin.Forms/tree/fix-gh2829  where I've been messing around with some thoughts

**Comment by bastianbecker21** [comment]
@PureWeen @samhouts Xamarin.Forms 3.1.0.583944 has this fix? I am still getting this crash, please help me to fix, thanks

**Comment by PureWeen** [comment]
@bastianbecker21  @kamrankhalil   the best thing would be if you can create a repro of your use case. For example with this fix I've had a number of people report that for them it fixed the issue so your cases are different.   This is an exception that can manifest for a very large permutation of reasons so there's a good chance this type of exception will always happen but it's all about figuring out if it's something in our code or possibly something in the user code.  

Think of it like a NullReferenceException. There will always be NRE's but every NRE is it's own special snowflake :-) 

There are some fixes coming from some Fragment fixes that I'm thinking may help but if you can articulate your case in a way that I can reproduce then we can try to address your particular snowflakes

**Comment by kamrankhalil** [comment]
@PureWeen I created a similar repro, navigating continuously between pages. That seems like same issue. Should we expect fix anytime soon ?

**Comment by PureWeen** [comment]
Timelines are always hard to guarantee but it is a high priority fix.

**Comment by MitchSchulz** [comment]
I have a case, which is reproducible. May be it helps. The problem happens in my Startup-Code. I do nothing more than building a ViewPage, which includes directly from MainPage a Stacklayout. This Stacklayout has only a Headline-Label inside.  After that there should be an OuterScrollView (Orientation=Horizontal) with an OuterGrid and an InnerScrollView (Orientation=Vertical) with an InnerGrid. 

On a SizeChange-Event I am (re)placing all my Elements in the View. Normally for the case of orientation changes but actually happens during initialization, not while changing orientation.  It happens during the first build up, and at the end of the second realignment during a "LayoutChanged" Event.   
In the SizeChange I create the Grids, the Inner ScrollView and put a lot of Entry/Label/BoxView-Items in the Grid. 
At the end of the second LayoutChanged Cycle I am Adding the OuterScrollView to the StackLayout in the MainWindow. Immediately thereafter comes the "System.ObjectDisposedException".

**Comment by Ivan-Z** [comment]
Any updates on this?

**Comment by ngalicoco** [comment]
This issue is still happening when an Image is used in a ListView ItemTemplate, irrespective of the Caching Strategy

**App Center Crash Report**

JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.ImageRenderer'.

JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeVirtualInt32Method (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
View.get_Visibility ()
VisualElementTracker.UpdateIsVisible ()
VisualElementTracker.HandlePropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e)
(wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
BindableObject.OnPropertyChanged (System.String propertyName)
Element.OnPropertyChanged (System.String propertyName)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget)
BindingExpression.Apply (System.Boolean fromTarget)
BindingExpression+BindingExpressionPart.<PropertyChanged>b__49_0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object.34(intptr,intptr)

**Xamarin.Forms Version**: 3.4.0.1008975
**Compile SDK Version** :  Crashes in both Android 9.0 and 8.1
**Target SDK Version**: API 28
**Android Support Compat version:** 27.0.2.1

**Comment by marthinch** [comment]
I also get similar problem when i do fast scroll down on my listview which contains some label with an image (FFimageloading), i use XF 3.4.0.1.008975. Anyone fix this ?

**Comment by pouyactm** [comment]
Is there any update on this? The issue still persists!

**Comment by PureWeen** [comment]
@pouyactm  do you have a repro we can use to see your issue?

**Comment by pouyactm** [comment]
@PureWeen, I don't have the repro project unfortunately, just have crash reports from AppCenter (not sure if it helps)
