### ISSUE TITLE
[UWP] grouped listiview which can load more crashes if scroll too fast

### ISSUE THREAD

**Issue by jaykainlabs** [xamarin/Xamarin.Forms#2832]
### Description
Here is a customize listview which load 30 more items each time, if I turn on isgroupingenabled, then the user can not scroll too fast. Everything works fine for non-grouped listivew.
I tried to change the number to load to a larger number, the issue still exists.

### Steps to Reproduce

1. Run the sample app
2. scroll rapidly vs scroll slowly
3. crash / work

### Expected Behavior
Everything should be fine
### Actual Behavior
scroll too fast crashes the app
### Basic Information
[BlankApp1.zip](https://github.com/xamarin/Xamarin.Forms/files/2039445/BlankApp1.zip)

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jaykainlabs** [comment]
Hey,
I just test the app with the latest Xmarin Forms3.1.0.637273, and I do not think the issue is being fixed. Can anyone check again?
Thanks.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
