### ISSUE TITLE
[Android] Mobile App template in VS 15.7.2 is generating incorrect icon files

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#2839]
Mobile App template for new projects is incorrectly naming icon files. Under mipmap-anydpi-v26, the xml files should be named `ic_launcher.xml` and `ic_launcher_round.xml`. All `icon.png` files should be named `ic_launcher.png` while all `launcher_foreground.png` files should be named `ic_launcher_foreground.png`. Also, the template is missing `ic_launcher_round.png` files. 

Every mipmap folder should have three images:

> ic_launcher.png
> ic_launcher_round.png (same resoulution as above)
> ic_launcher_foreground.png (for adaptive icons. resolution is much bigger than the two above)

while mipmap-anydpi-v26 should have two xml files.

**Bonus:**

It'd also be nice if you could add a basic `splash.xml` to the `drawable` folder so that people get acquainted with `layer-list` along with a `SplashActivity` because pretty much every app has to add a splash screen when dealing with a cold start. 

```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
	<item>
		<color android:color="@color/ic_launcher_background"/>
	</item>
	<item>
		<bitmap android:src="@mipmap/ic_launcher_foreground" android:tileMode="disabled" android:gravity="center"/>
	</item>
</layer-list>
```

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
