### ISSUE TITLE
In UWP Form Password Entry field is only allowing to edit the text at the end

### ISSUE THREAD

**Issue by vishnuprasadDH** [xamarin/Xamarin.Forms#2865]
### Description
Default Entry control with IsPassword=True  , allowing to edit the text only at the end of the line. Let suppose i already enter "1234"  in my password field , then decided to replace the character "2" with "a" . Then i moved the cursor between 2  & 3 and pressed the backspace button . Then i have noticed that cursror moved to the end of the line . Even if i tried reposition the cursor between 2&3 and press "a" then also the cursor moved to last . Later i debugged and figured it out that all edits are happening only at the end of input , be it removing a character or addition new character. 
### Steps to Reproduce

1. Run the UWP application in Windows 10 64 bit desktop 
2. Try to edit the password in the middle and check

### Basic Information

- Version with issue:Xamarin.forms 2.5.0.91635
- Last known good version:
- IDE:Visual Studio 2017
- Platform Target Frameworks: 

  - UWP:  Min Version 10240 and Target
[LoginSample.zip](https://github.com/xamarin/Xamarin.Forms/files/2053553/LoginSample.zip)

 version 10586
- Nuget Packages:
- Affected Devices: Tried using my Dell 64 bit Corei5 Laptop

**Comment by pauldipietro** [comment]
Related issues: #677 / #2388

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
