### ISSUE TITLE
Images not rendering as expected

### ISSUE THREAD

**Issue by PaulVrugt** [xamarin/Xamarin.Forms#2885]
### Description

Images do not adhere to the options set by horizontaloptions and verticaloptions, and "bleed" outside of their container layout. It doesn't matter what aspect option you choose, none of them seem to do with is expected. This seems to make it impossible to properly show images scaled relatively to the size of the screen.

### Steps to Reproduce

1. open the repro project and run it
2. check the image

### Expected Behavior
Images should not size to be larger than 100x100

### Actual Behavior

android:
Everything is messed up. The first image is stretched over the entire screen, while everything should be 100x100 max, and IsClippedToBounds doesn't seem to work. The absolutelayout block actually seems to work.

ios:
the clippedtobounds is working, but except for the last image (in the absolutelayout) all images seem to be larger than 100x100

### Basic Information

- Version with issue: xamarin 2.5, xamarin 3 and nightly build
- Last known good version: -
- IDE: Visual studio 2017
- Platform Target Frameworks: 
  - iOS:  9
  - Android: 8.1

### Screenshots

android:
![image](https://user-images.githubusercontent.com/7567114/40787442-e19f23f6-64ed-11e8-8e7b-aceed51c847c.png)

ios:
![image](https://user-images.githubusercontent.com/7567114/40787659-6d1edc46-64ee-11e8-976f-2f9e21444995.png)

### Reproduction Link

[AspectFitBug.zip](https://github.com/xamarin/Xamarin.Forms/files/2090502/AspectFitBug.zip)

**Comment by PaulVrugt** [comment]
@jassmith 
My bad, I was too eager in removing obsolete files from the repro. I've added a new repro that includes the sln file.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
