### ISSUE TITLE
[UWP] AccessViolationException when adding items with the appearance of the item.

### ISSUE THREAD

**Issue by paymicro** [xamarin/Xamarin.Forms#2959]
### Description

When added items in ItemSource in `OnItemAppearing` throws `AccessViolationException`

### Steps to Reproduce

1. Create `ListView` with `ItemsSource`
2. Add event `ItemAppearing`
3. In event body add new item to `ItemsSource`

### Expected Behavior

Items are added without errors.

### Actual Behavior

Throw `AccessViolationException`

### Basic Information

- Version with issue: on `master` branch

### Screenshots

https://prnt.sc/jrkdsi

### Reproduction Link

https://github.com/paymicro/Xamarin.Forms/commit/eed5ab74e682a8f9936daa0e78447cefad64a668

Relation bug: #2832

**Comment by nbevans** [comment]
This is still an issue. AccessViolationException's being thrown, intermittently, in certain nuanced scenarios with ListView on UWP.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
