### ISSUE TITLE
UWP map renderer error message improvements

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#2980]
### Description

The UWP map renderer doesn't provide a meaningful error message when an invalid Bing maps API key is used. The UWP/maps support team is suggesting that Forms is swallowing the exception details.

See https://github.com/xamarin/xamarin-forms-samples/issues/330 for more details.

**Comment by PorkiePie** [comment]
Any news on a fix for this? Or a workaround? My uwp app keeps breaking on this regardless of the app type I use.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
