### ISSUE TITLE
Navigation Push Modal is much much slower then in other app not created by Xamarin

### ISSUE THREAD

**Issue by patsadow2** [xamarin/Xamarin.Forms#3002]
Hello,

I see the existing in Xamarin.Form 3.0 navigation push modal is much slower then navigation for example in Linkin, Facebook etc. application, how could it be improve ??

It's much much better to rerender existing page but i dont think in all case it a good solution ;/

Any ideas ?

**Comment by patsadow2** [comment]
In big pages never create new one :) always use old.

**Comment by samhouts** [comment]
Hi @patsadow2! Which platforms do you notice this in? Does it seem to be a problem when you are loading a complex page, or is it also a problem for simple/empty pages?

**Comment by patsadow2** [comment]
@samhouts rather a complex page

**Comment by Charuwaka** [comment]
I have same Issue in Android, PushModal Flickers/Slow while opening, but same page if i open from another page ,its buttery smooth dont know where i am doing wrong.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
