### ISSUE TITLE
Tapping on picker crashes Android app(built in release mode)

### ISSUE THREAD

**Issue by bojan96** [xamarin/Xamarin.Forms#3005]
### Description
Tapping on picker crashes Android app(built in release mode)
### Steps to Reproduce

1. Build Android project in release mode
2. Deploy to device 

### Expected Behavior
Display alert should display concatenated NativeName properties.
Tapping on picker we should see available options.
### Actual Behavior
Display alert displays empty string. Tapping on picker crashes Android app
### Basic Information

- Version with issue: 3.0.0.550146 (also happens with 3.0.0.561731)
- IDE: Visual Studio 15.7.1
- Platform Target Frameworks: 
  - Android: Android 8.1
### Reproduction Link

Project [repo](https://github.com/bojan96/PickerTest)

**Comment by bojan96** [comment]
I investigated issue in more detail, It looks like this happens only when CultureInfo is used as picker item. On branch custom-menu-item I made custom class (MenuItem) to be used as picker item. It that case crash does not happen. Also this issue exist with latest stable version (3.0.0.561731).

**Comment by samhouts** [comment]
When you're in Release configuration, the Linker defaults to `SDK Assemblies`, which strips out the types and properties it assumes are unused. In this case, it is stripping out pieces of `System.Globalization`.

Here is more information on how the Linker works on Android and how to preserve code: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker

Since the code that you want is in the `mscorlib` SDK, you may want to create a custom Linker instruction file that just excludes `System.Globalization` from the Linker. The general instructions for that are here: https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker

I was able to avoid the crash with this sample linker file:

```xml
<linker>
	<assembly fullname="mscorlib">
		<namespace fullname="System.Globalization" />
	</assembly>
</linker>
```

Please let us know if you have any further questions! Thanks!

**Comment by bojan96** [comment]
Thank you for investigating this issue.
Would it be possible to add note to XF documentation(possibly referencing Xamarin.Android linker docs).
I think most people would expect this to work without issues.
