### ISSUE TITLE
[UWP] Editor control changes line break characters.

### ISSUE THREAD

**Issue by CarstenGruenzner** [xamarin/Xamarin.Forms#3020]
### Description

In a customer SQL Server database all multiline text has \r\n as a line break characters. The Editor control changed them to \r.

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior

Use the platform specific line break characters or make the behavior configurable.

### Actual Behavior

Always \r is used as line break characters.

### Basic Information

- Version with issue: 3.0.0
- Last known good version:
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  16299 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by Brosten** [comment]
Any progress on this one? Suggested workaround?

**Comment by stevehurcombe** [comment]
This is hitting me too. What's the plan?

**Comment by stevehurcombe** [comment]
I wrote around it by adding a special, platform aware, property to my model. It ensures that everything in my model is stored as \n.

**Content** is the true property. **WorkAroundContent** is the one I'm binding to the editor. 

``` C#
        // Work around for bug [UWP] Editor control changes line break characters
        // https://github.com/xamarin/Xamarin.Forms/issues/3020
        [Ignore]
        public string WorkAroundContent
        {
            get {
                switch (Device.RuntimePlatform)
                {
                    case Device.UWP:
                        return _Content.Replace("\n", "\r");
                    default:
                        return _Content;
                }
            }
            set
            {
                string newContent;
                switch (Device.RuntimePlatform)
                {
                    case Device.UWP:
                        newContent = value.Replace("\r", "\n");
                        break;
                    default:
                        newContent = value;
                        break;
                }

                if (_Content == newContent) return;
                Content = newContent;
            }
        }

```

**Comment by samhouts** [comment]
@stevehurcombe I'd like to see this implemented as an opt-in platform specific. I wouldn't want to break any legacy apps that are depending on the original behavior, but this looks like a great addition.

We'd welcome a PR! Thanks!

**Comment by donaldnp** [comment]
I've run into this yesterday. My work-around is...
string fixedText=EditPage.Results.Replace("\r","\r\n");

To provide you guys with further info, I'm using this on both Android and Windows. I could be viewing the file on either platform, and I could be running the app on either platform (depending on if I'm on my phone or my PC at the time). I noticed when I loaded the file into the Editor, there were extra lines appearing. I'm starting with \r\n, and seems to be treating them as separate newlines. i.e. a newline for each \r, and a newline for each \n. When I view the output on Windows the \n's have disappeared and I have no newlines at all - just one long line.

If it comes to a choice between extra lines on Android, or no newlines on Windows, then obviously I'd prefer extra lines on Android. No newlines at all is a disaster!

I'd also like to note that when I view same files on Android, I use Jota text editor, and it DOESN'T display extra lines. i.e. Jota treats \r\n as a single newline. This would be the preferred behaviour, because then it appears correctly on both platforms.

**Comment by jfversluis** [comment]
I don't think this is going to be something we're going to implement at this stage for Xamarin.Forms. Thanks everyone for the time and effort here. Please check to see if this is still an issue with .NET MAUI and if you'd like we can discuss making it better there!

**Comment by SmartmanApps** [comment]
Thanks @jfversluis. I haven't got around to trying this in MAUI yet, but if I run into issues with it I'll let you know.
