### ISSUE TITLE
Why UI can kill xamarin in the future

### ISSUE THREAD

**Issue by patsadow2** [xamarin/Xamarin.Forms#3028]
There is a bunch of features which are not support by Xamarin which have to be implemented by custom and very common used by developers.

- support shadow for all kind of layouts, buttons, boxview, entry etc in all kind of directions
- support of radius corner for all kind of layouts, buttons, boxview, entry etc (each corner can be different)
- support for polygon layouts and full filed by other layout cutting out unnecessary view
- support for gradient backgrounds and perhaps texts or all kind of layouts, buttons, boxview, entry etc
- support for more advanced animations
- support for better performance in navigation across the pages
- support for blurred background / transparent

:( i cannot find out more but other ppl can for sure :(

**Comment by mattrichnz** [comment]
You'll find you can do pretty much everything above already, just with a little time, effort and ingenuity.

**Comment by patsadow2** [comment]
@mattrichnz i totally agree with you, but when you make up something is it the best option with the best performance ?

**Comment by BradChase2011** [comment]
@patsadow2 Funny you mention this, we have custom renderers or effects for over half of that :).  And the majority are for all platforms.  So its not a platform issue at this point.  I think the main problem you are going to run into is alot of developers want what is broken to be fixed before moving on to enhancements.  That is why you see alot of bugs being attacked right now rather than enhancements.  On the other hand the great part about X.F is its open sources now!  They have stated numerous times they would love for the community to jump in and PR those enhancements.

I know thats not what you wanted to hear, but since so many people have created the renderers/effects, it prolly isnt a bad idea for someone to get the ball rolling.  I would but that is not at the top of my todo list right now.

**Comment by samhouts** [comment]
I encourage you to take a look at the issues labeled `F100`. I think you'll find that many of these features are in that list. 

If you see any that are missing, please feel free to submit separate issues for each feature. We do have a great community that has taken on the task of adding some of these features already. 

We welcome you to share your renderers and/or modify them to be part of the core code if you'd like. The team (and community!) will review each pull request for best practices and performance before it is added to the product.

We agree that these features are important to add. As @BradChase2011 mentioned, our current focus is bug fixes. We will return to enhancements shortly. 

As I mentioned, please open separate issues for each feature you find missing from our list. It's difficult to track many features in one issue, so we will close this one for now.

Thank you!
