### ISSUE TITLE
DisplayActionSheet freezes app in iOS custom renderer

### ISSUE THREAD

**Issue by duzenko** [xamarin/Xamarin.Forms#3049]
### Steps to Reproduce

1. Run the attached project.
2. Click on a picker.
3. Click outside the action sheet.

### Expected Behavior
App does not freeze.

### Actual Behavior
App freezes.

### Basic Information

- Version with issue: 3.0
- Last known good version: N/A
- IDE: VS2017

### Reproduction Link
[repos.zip](https://github.com/xamarin/Xamarin.Forms/files/2105687/repos.zip)

**Comment by samhouts** [comment]
I don't see the app freezing. If I click outside of the ActionSheet, nothing happens. But I can then click an option on the ActionSheet to dismiss it and carry on. Are you using a particular device or simulator? Is there an error generated, or does anything appear in your application output that might help pinpoint the issue?

Thanks!

**Comment by Kuraimegami** [comment]
Since I'm having a similar issue I tried running the provided code on an iPad and run into the same issue described. Clicking outside of the ActionSheet doesn't dismiss it and the app freezes.

I am not sure if my own issue is related to this issue or just simmilar. I use an ActionSheet as well upon longpress and the ActionSheet never returns after clicking outside, but it does get dismissed before the app freezes. 
1. Run project
2. Long press one of the three entries
3. Click outside the ActionSheet
-> ActionSheet gets dismissed and App freezes because "await DisplayActionSheet(...)" never returns
[ActionSheetTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2115840/ActionSheetTest.zip)

**Comment by samhouts** [comment]
Closed by https://github.com/xamarin/Xamarin.Forms/pull/3636
