### ISSUE TITLE
WebView Navigating event does not work for server redirects on MacOS

### ISSUE THREAD

**Issue by DennisWeluDts** [xamarin/Xamarin.Forms#3138]
### Description
The Navigating event for a WebView on MacOS only ever fires once even if the server redirects the request to another url. Other platforms will re-trigger the Navigating event.

### Steps to Reproduce

1. Add a WebView to a form on the MacOS platform
2. Set the source to a server URL that has a redirect, e.g. "insights.xamarin.com" (which redirects to https://appcenter.ms/apps).
3. Add a handler for the Navigating event.
4. Run the form and see that the event only triggers once

### Expected Behavior
The Navigating event should be raised for each new url that is redirected

### Actual Behavior
The navigating event is only raised for the initial url

### Basic Information

- Version with issue: Xamarin.Forms Mac 3.1
- Last known good version: N/A
- IDE: Any
- Platform Target Frameworks: 
  - MacOS:  10.13.4

### Workaround
I was able to workaround this by extending WebView and customizing the WebViewRenderer (https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.MacOS/Renderers/WebViewRenderer.cs). By commenting out the "_sentNavigating" on line 16 and all guards that checked it, the behavior was more as expected. However I don't know why that field was added and if that is going to break something else. (see attached file)
[WebViewExRenderer.zip](https://github.com/xamarin/Xamarin.Forms/files/2131679/WebViewExRenderer.zip)

**Comment by ncarandini** [comment]
WebViewRender implementations on Android and iOS platforms are less than optimal.
On the Android side, many overridable methods of the Android.WebKit.WebViewClient are not used.
As an example, in case of a SSL certificate error, because the OnReceivedSslError method is not overrode, the Xamarin.Forms WebView Navigated event is fired with a WebNavigationResult.Success result value (!!!).
I've created a WebView Lab project on GitHub where I've made an extended version of the Xamarin Forms WebView and related Android and iOS renderers copied from the Xamarin.Forms project.
I'm learning and testing many things while I'm changing and adding code, and I'll eventually use it to make a PR on the Xamarin.Forms GitHub project.

**Comment by volcano619** [comment]
This seems to be happening on Android as well

**Comment by DennisWelu** [comment]
I have tested https://github.com/xamarin/Xamarin.Forms/pull/4737 and it fixes this issue (for macOS).

**Comment by samhouts** [comment]
fixed by #4737
