### ISSUE TITLE
Forms 3.1 UWP DisplayActionSheet - The parameter is incorrect. Placement target needs to be in the visual tree

### ISSUE THREAD

**Issue by aherrick** [xamarin/Xamarin.Forms#3144]
### Description

I upgraded my Xamarin Forms project to Forms 3.1

In UWP, I'm displaying Action Sheet inside of a static class like below:

`App.Current.MainPage.DisplayActionSheet();`

Forms 2.5 displays the Action Sheet with no issue.

Forms 3.1 crashes.

```
ArgumentException: The parameter is incorrect.
Placement target needs to be in the visual tree.
```
https://stackoverflow.com/questions/51026398/xamarin-forms-3-1-uwp-displayactionsheet-the-parameter-is-incorrect-placement?noredirect=1#comment89046491_51026398

### Basic Information

- Version with issue: 3.1.0.583944
- Last known good version: 2.5.1
- IDE: Visual Studio
- Platform Target Frameworks: 
  - UWP:  16299
- Android Support Library Version:

**Comment by BradChase2011** [comment]
Thats because I presume you are calling it while another page is being displayed?  To get around it in the mean time, use something like this:

    public static class CurrentPage
    {
        public static Page Instance
        {
            get
            {
                Page ret = null;
                if( Application.Current.MainPage.Navigation.NavigationStack != null )
                    ret = Application.Current.MainPage.Navigation.NavigationStack.LastOrDefault();

                if (ret == null)
                    ret = Application.Current.MainPage;

                return ret;
            }    
        }
    }

The problem is, not all targets use the NavigationStack... So it will be null on different operating systems.  And of course as you found, on UWP you need to use the NavigationStack.

**Comment by aherrick** [comment]
@BradChase2011 Thanks for the thought. Unfortunately it's doing the same thing.

I've published a spike showing the behavior:

https://github.com/aherrick/UWPDisplayActionSheet

**Comment by aherrick** [comment]
Just a heads up the answer here I found to be a work around: https://stackoverflow.com/a/51039399/20446

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
