### ISSUE TITLE
SelectionMode None dosn't prevent Animation/MouseOver

### ISSUE THREAD

**Issue by MaxFe** [xamarin/Xamarin.Forms#3156]
The current implementation only prevents setting the SelectedItemProperty. The onItemPressen animation is active as in SelectionMode=Single. It's the same for MouseOver.

See: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ListView.cs -> Method NotifyRowTapped
```c#
if (SelectionMode != ListViewSelectionMode.None)
				SetValueCore(SelectedItemProperty, cell?.BindingContext, SetValueFlags.ClearOneWayBindings | SetValueFlags.ClearDynamicResource | (changed ? SetValueFlags.RaiseOnEqual : 0));
```

### Expected Behavior
1) OnMouseOver shouldn't have any visual effect  
2) OnTapped shouldn't have any visual effect  

### Actual Behavior
1) OnMouseOver shouldn't have any effect
![image](https://user-images.githubusercontent.com/31653042/41922699-f8a97cd6-7965-11e8-9de6-40d941e38895.png)
2) OnTapped invokes an animation  (like one plus itemContent gets zoomed out)
### Basic Information

- Version with issue: Xamarin Forms 3.1.0.583944
- IDE: Visual Studio 15.7.4
- Platform Target Frameworks: 
  - UWP:  Only tested on UWP

**Comment by gtbuchanan** [comment]
The workaround for this is to set `SelectionMode="None"` _and_ the legacy accessibility setting:
```c#
InitializeComponent();
ListViewName.On<Windows>().SetSelectionMode(ListViewSelectionMode.Inaccessible);
```

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
