### ISSUE TITLE
Image Scale ignored on UWP apps

### ISSUE THREAD

**Issue by paulelong** [xamarin/Xamarin.Forms#3169]
### Description

I have a few images with a scale set to .3.  They were showing up correctly on UWP, but I recently updated the xamarin.forms packages and now on UWP only, the scale seems to be ignored.

### Steps to Reproduce

1.  Create blank Xamarin.Forms standard.net app
2. Updage Xamarin.Forms package to 3.1.0.583944
3. Add this to XAML
```xaml
          <Image Source="MetroIcon.png" Scale=".3"/>
```
4.  Run on UWP and Android and see that UWP is large and ignores scale

### Expected Behavior
Used to scale correctly before ???

- Version with issue:
Xamarin.Forms 3.1.0.583944

- Last known good version:
Xamarin.Forms 3.1.0.482410
- IDE:
Visual Studio 2017 community version

**Comment by deakjahn** [comment]
There is some movement here but not OK yet. With a simple Image, all rotations and similar properties are working fine but not Scale. Consequently, scale cannot be animated (eg. if I set it to 0.25 and try to animate is back to 1 with ScaleTo(), it will get optimized away because the system considers Scale to be still 1 and doesn't see the need for the animation.

Just put into any demo app, into the OnAppearing of a new Page:

```
Root.AnchorX = 0.1;
Root.AnchorY = 0.9;
Root.Scale = 0.25;
await Root.ScaleTo(1, 500, Easing.CubicOut);
```

where Root is the name of the outermost view.
