### ISSUE TITLE
Tap gestures are inconsistently recognized as pan gesture

### ISSUE THREAD

**Issue by PuppyDev** [xamarin/Xamarin.Forms#3173]
### Description
A very fast tap or a rapid series of taps on an UI element will sporadically get recognized as a pan gesture. I discovered even the smallest linear motions while tapping are triggering the pan event instead of the tap event, as if there is some threshold value that is set too low.

### Steps to Reproduce
(Please see attached zip file with sample project)
1. Create a new Blank Forms App
2. Add a TapGestureRecognizer to an object (such as a Frame)
3. Add a PanGestureRecognizer to the same object
4. Deploy to an Android device 
5. Tap the UI object as fast as you can

### Expected Behavior
Consistent tap callback responses or some way to either ignore the pan gesture or change the threshold to recognize it.

### Actual Behavior
A mix of tap and pan callback responses

### Basic Information

- Version with issue: 3.1.0.583944
- Last known good version: n/a
- IDE: Visual Studio 2017 Community for MacOS
- Platform Target Frameworks: 
  - iOS:  n/a
  - Android: 8.1 (API level 27)
  - UWP:  n/a
- Android Support Library Version: 
- Nuget Packages: 
  - Xamarin.Forms
  - Xamarin.Android.Support.Design
  - Xamarin.Android.Support.v4
  - Xamarin.Android.Support.v7.AppCompat
  - Xamarin.Android.Support.v7.CardView
  - Xamarin.Android.Support.v7.MediaRouter
- Affected Devices: All Android devices, but my sample project was tested on a Nexus 9

### Reproduction Link
Uploaded sample project.

[TapTests.zip](https://github.com/xamarin/Xamarin.Forms/files/2143157/TapTests.zip)

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
