### ISSUE TITLE
[iOS] Changing out the MainPage during certain life cycle points doesn't work on iOS

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#3188]
### Description

Swapping out the MainPage at certain points in the life cycle causes iOS 

### Steps to Reproduce

Run these UI tests from the Control Gallery

SwapPagesOut_MasterDetailsPage [iOS] - This doesn't crash but the page that should be showing up doesn't

### Expected Behavior
All three platforms should not crash and respond the same for the above UI Tests

### Actual Behavior
iOS  doesn't load new page

### Basic Information

- Version with issue: 3.0+

**Comment by PureWeen** [comment]
UWP is fixed but iOS still is exhibiting the same issues

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
