### ISSUE TITLE
Changing the image source leaks memory.

### ISSUE THREAD

**Issue by sf-ica** [xamarin/Xamarin.Forms#3204]
### Description

When changing the source of an image memory isn't released properly.

### Steps to Reproduce

1. Create a new page with an image.
2. Change the source of the image at runtime.

```
using System.Threading.Tasks;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace Demo
{
	[XamlCompilation(XamlCompilationOptions.Compile)]
	public partial class Test : ContentPage
	{
		public Test()
		{
			InitializeComponent();
		}

		protected override void OnAppearing()
		{
			base.OnAppearing();

			Task.Run(async () =>
			{
				var state = true;

				while (true)
				{
					await Task.Delay(250);

					state = !state;

					Device.BeginInvokeOnMainThread(() =>
					{
						TestImage.Source = string.Format("Assets/{0}.png", state ? "foo" : "bar");
					});
				}
			});
		}
	}
}
```

### Expected Behavior

Memory consumption shouldn't increase significantly.

### Actual Behavior

Memory consumption increases significantly.

### Basic Information

- Version with issue: Xamarin.Forms.Platform.GTK 3.1.0.583944
- Last known good version: n/a
- IDE: Visual Studio 2017
- Affected Devices: Raspberry Pi Zero with latest Raspbian

**Comment by myroot** [comment]
It seem to no chance to GC thread was run
How about add GC.Collect() in loop?
``` C#
            System.GC.Collect();
            System.GC.WaitForFullGCComplete();
```

**Comment by hartez** [comment]
> Memory consumption increases significantly.

What are you using to measure memory consumption?

**Comment by jsuarezruiz** [comment]
I will take a look. Thanks for the info.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
