### ISSUE TITLE
UriImageSource should treat zero length file as invalid

### ISSUE THREAD

**Issue by deakjahn** [xamarin/Xamarin.Forms#3209]
If, for any reason, the downloaded and cached file is corrupted (eg. zero length), it stays there stuck as long as valid, UriImageSource will not make another attempt to download the file later.

### Expected Behavior

The validity check `GetHasLocallyCachedCopyAsync()` should also check for zero length and consider it invalid at any time.

### Actual Behavior

Zero length files are kept in the cache as long as validity time allows it.

### Basic Information

- Version with issue: current
- Last known good version: none

**Comment by hartez** [comment]
At the very least, we should provide some means for clearing an image out of the cache if the user determines that it's invalid.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
