### ISSUE TITLE
In ListView, ViewCell's ContextActions is disappear when swipe right to left on iOS only 

### ISSUE THREAD

**Issue by jcjc200** [xamarin/Xamarin.Forms#3217]
### Description
Original: https://bugzilla.xamarin.com/show_bug.cgi?id=58351
This is the same problem in the above link that is still reproducible in the latest Xamarin Form.

When using ContextAction in ViewCell, that is in the ListView. The Context Actions disappear when swipe from right to left. 

This is easy reproducible especially when the hand is not steady and moving a little bit to the left and right before swiping all the way from right to left.  

### Steps to Reproduce

1. Simulate a non steady hand by moving the ViewCell a few pixels to the left and the to the right.
2. Swipe the ViewCell all the way from right to left.

### Expected Behavior

The Context Action (Menu) is shown in the right side of the ViewCell

### Actual Behavior

The Context Action (Menu) area is blank

### Basic Information

- Version with issue: Xamarin Form 3.0.0.482510
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  iOS11.3
  - Android: No
  - UWP:  No
- Android Support Library Version: N/A
- Nuget Packages:
- Affected Devices: iPhone X iOS11.3 simulator, iPad Air

### Reproduction Link

https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/ListView/Interactivity/interactivityListView

**Comment by hartez** [comment]
I was able to get this to reproduce somewhat consistently on a device by opening a context menu and then quickly swiping left twice on another item in the list: 

https://www.dropbox.com/s/86q6cxlwe4h9yrg/20180705_100515.mp4?dl=0

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
