### ISSUE TITLE
Xamarin.Forms WebViewRenderer.LoadUrl() does not include Uri.UserInfo

### ISSUE THREAD

**Issue by davidhardie** [xamarin/Xamarin.Forms#3227]
### Description
The Xamarin.Forms.Platform.iOS/Renderers/WebViewRenderer does not include Uri.UserInfo when reconstructing the Uri to pass to LoadRequest()

### Steps to Reproduce
1. Create a new Xamarin Forms project
2. Include a WebView with a Source property resembling https://user:password@server.com/test
3. Run on iOS simulator or device.

### Expected Behavior
The WebView renders the Uri on the page

### Actual Behavior
The WebView is blank.

### Basic Information
The safeHostUri var should also respect the Url.UserInfo Property, if supplied, when reconstructing the Uri for the LoadRequest() call.

- Version with issue: Xamarin.Forms 3.1.0.583944
- Last known good version: Xamarin.Forms 2.5
- IDE: Visual Studio Mac 7.5.3
- Platform Target Frameworks: iOS
- Affected Devices: iOS all devices running 9.3.5-11.4

### Reproduction Link
See the changes to Xamarin.Forms.Platform.iOS/Renderers/WebViewRenderer.cs in https://github.com/xamarin/Xamarin.Forms/commit/3b2be6912c35a0991ff08b26b92414a9eefb1cd0

**Comment by hartez** [comment]
`LoadUrl` in `WebViewRenderer` should be doing something like this:

```csharp
public void LoadUrl(string url)
{
	var uri = new Uri(url);

	var userInfo = uri.UserInfo;
	if (userInfo.Length > 0)
	{
		userInfo += "@";
	}

	var safeHostUri = new Uri($"{uri.Scheme}://{userInfo}{uri.Authority}", UriKind.Absolute);
	var safeRelativeUri = new Uri($"{uri.PathAndQuery}{uri.Fragment}", UriKind.Relative);
	LoadRequest(new NSUrlRequest(new Uri(safeHostUri, safeRelativeUri)));
}
```

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!
