### ISSUE TITLE
Soft Keyboard Input Mode Ignored In ListViews

### ISSUE THREAD

**Issue by wollac11** [xamarin/Xamarin.Forms#3233]
### Description
The soft-keyboard adjustment mode is ignored for Entries within ListViews (and possibly other parent views). Regardless of the set value, "AdjustPan" behaviour is always used.

### Steps to Reproduce

1. Create a ListView inside a StackLayout.
2. Add some Entry items into the ListView (either add enough Entries to fill most of the screen, or position the ListView at the bottom of the page).
3. Below the ListView, add another Entry (directly into the StackLayout - not inside the ListView!).
4. Set WindowSoftInputModeAdjust to "Resize" in App.xaml as per [documentation](https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/platform/platform-specifics/consuming/android#Setting_the_Soft_Keyboard_Input_Mode).
5. Tap an entry inside the ListView which falls in the bottom half of the screen (so that it would be covered by the soft keyboard area without adjustment) and observe.
6. Tap in the Entry outside the ListView and compare behaviour.

### Expected Behaviour
Page should resize to accommodate the soft keyboard when any entry is selected.

### Actual Behaviour
Page pans up with the default "AdjustPan" behaviour when an Entry nested within a ListView is selected. Behaviour is correct for Entries directly in the parent StackLayout.

### Basic Information

- Version with issue: 2.5.0.280555 (but latest 3.1.0.58944 also tested with the same issue)
- Last known good version: None
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - Android: 8.0, 8.1

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
