### ISSUE TITLE
Default NavigationPage's NavigationBar is different in Android compared to iOS

### ISSUE THREAD

**Issue by knocte** [xamarin/Xamarin.Forms#3329]
### Description
When wrapping a Page inside a NavigationPage, and not calling `NavigationPage.SetHasNavigationBar(navPage, false)`, the default NavigationBar that appears in iOS is much different than the one that appears in Android.

### Steps to Reproduce

1. git clone https://github.com/knocte/gwallet.git
2. checkout branch bugreport/xamarinforms-defaultnavbar
3. run the iOS frontend, fill all the forms until you reach the balances page, then click on any currency, and then look up at the navigation bar, it looks like this:
<img width="405" alt="screen shot 2018-07-18 at 5 02 58 pm" src="https://user-images.githubusercontent.com/331303/42871247-75dba290-8aac-11e8-9e49-5e9da1a10c4a.png">
4. run the Android frontend, do the same steps to reach the same page

### Actual Behavior

- In Android, it doesn't have any text, just an arrow pointing to the left, while in iOS, it says "Back".
- In Android, the default size is quite big (more than 50% of the phone's screen), while in iOS, it's enough to fit a row of text (the text "Back" mentioned before).

See screenshot of Android:
<img width="398" alt="screen shot 2018-07-18 at 4 58 05 pm" src="https://user-images.githubusercontent.com/331303/42871327-ab1c6cc8-8aac-11e8-81c6-a5b363109178.png">

### Expected Behavior
Should look more similar to the iOS NavigationBar.

### Basic Information

- Version with issue: 3.1.0.637273 (latest); bug also present in 3.0.0.446417
- Last known good version: don't know, possibly not a regression
- IDE: Visual Studio for Mac Community 7.5.3 (build 7) running in macOS High Sierra 10.13.4
- Platform Target Frameworks:
  - iOS:  xamarinios10
  - Android: monoandroid81
- Android Support Library Version: 27.0.2
- Nuget Packages: Xamarin.Forms.3.1.0.637273
- Affected Devices: iOS&Android

**Comment by PureWeen** [comment]
So we need to modify the F# templates to just includes this but you have to load your resource file inside AssemblyInfo.fs otherwise they don't quite load correctly

Here's an example
https://github.com/jimbobbennett/TicTacToe/blob/master/Droid/Properties/AssemblyInfo.fs#L6-L8

Once you do that it should apply the proper Resource settings to the ToolBar

**Comment by knocte** [comment]
> So we need to modify the F# templates

Is that work tracked somewhere?

> Here's an example

Mmm, that's an F# project but the Resources folder contains .cs files...

**Comment by PureWeen** [comment]
> Is that work tracked somewhere?
https://github.com/mono/monodevelop/issues/5452

> The text "Back" is still not in it.
This is where it's more of a platform difference. On iOS it's expected for that text to represent the previous page so if you set the title on your pages it'll show that text.   Android natively doesn't use text for the back button.  This is definitely a place where some enhancements could be made to make the customization of that Android back button possible but the current behavior most likely won't be changed because that would cause too much change on existing apps

**Comment by nosami** [comment]
@knocte
> Mmm, that's an F# project but the Resources folder contains .cs files...

> Interestingly enough, in my android project, the GWallet.Frontend.Android.Resource type exists at compile time (even if there's no class for it, not even in .cs file), and adding the assembly attribute works.

F# type provider 'magic' :)

The Android build process generates the `.cs` file using System.CodeDom. It used to generate a `.fs` file, but there were countless issues where F# Android projects wouldn't build without manual fix ups on the generated `.fs`.

So, I changed it some time ago to use the C# file instead. The `.cs` file is compiled on the fly using the C# compiler, but the types are augmented into the F# assembly using [a type provider](https://github.com/xamarin/Xamarin.Android.FSharp.ResourceProvider).

The `.cs` file can be considered a temporary artifact and doesn't need to be in source control.
