### ISSUE TITLE
[UWP]with ListView on page, Navigation.PopAsync() throws exception

### ISSUE THREAD

**Issue by sude22** [xamarin/Xamarin.Forms#3333]
### Description
Happens on UWP, Android seems to be OK, iOS not used.
```
ContentPage
-Grid
--ScrollView
---Grid
----StackLayout
-----ListView 
```
calling Navigation.PopAsync();
throws Exception:
```
Object reference not set to an instance of an object.
StackTrace:
   at Xamarin.Forms.Platform.UWP.TaskExtensions.<>c.<WatchForError>b__2_1(Object e)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

Without the ListView on the page PopAsync() works fine.
Up to Version 2.5.1.527436 it works even with ListView on page.
Could not test latest preview version due to compile errors in project.

### Steps to Reproduce
1. Navigate to page with ListView control
2. Pop from page
3. Exception is thrown

### Expected Behavior
no exception is thrown
### Actual Behavior
exception is thrown
### Basic Information

- Version with issue: 3.1.0.637273
- Last known good version: 2.5.1.527436
- IDE: VS2017 15.7.1
- Platform Target Frameworks: 
  - UWP:

**Comment by siggiull** [comment]
I tried to verify that bug in a smaller project, but I could not reproduce the error till now.
So there must be a difference in my project, I try to find what that is.

**Comment by jalbertSyncroTech** [comment]
@PureWeen We're still seeing an exception from PopAsync() in v3.2.0.839982, however instead of a null reference it's now:

System.ArgumentException: 'Value does not fall within the expected range.'
Xamarin.Forms.Platform.UAP.dll!Xamarin.Forms.Platform.UWP.ListViewRenderer.OnElementItemSelected(object sender, Xamarin.Forms.SelectedItemChangedEventArgs e)

In our particular case we:
1. Add items to a bound ListView
2. Navigate to the page displaying the list and delete one of the items
3. Navigate away from the page displaying the list
4. Navigate back to the page display the list, we're using InsertPageBefore() and PopToRootAsync() but likely any navigation will reproduce the issue.

I'll work on putting together a solution that reproduces the issue.

**Comment by jalbertSyncroTech** [comment]
@PureWeen I've opened a separate issue and attached a reproducible case.  I could only reproduce the ArgumentException exception with ListView Grouping enabled.

#3887 [UWP] PopAsync() crashes when navigating back to a page with a ListView with grouping after an item has been removed

**Comment by PureWeen** [comment]
Awesome thanks for doing that @jalbertSyncroTech  !!
