### ISSUE TITLE
Feature Request: ContentView OnAppearing

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3486]
Hi,

It will be great if you add an OnAppearing and onDisappearing to the ContentView.

Thanks,
Jassim

**Comment by adrianknight89** [comment]
Can you elaborate on the use case for this? If we add these events to `ContentView`, why not add them to pretty much any container/wrapper?

**Comment by jrahma** [comment]
It's just the the ContentPage, you need to run a code OnAppearing and OnDisappearing.. For example, now if you want to run a code when the ContentView appears you will need to use:

myContentView.MyCode();

and there is no way to track when the ContentView disappeared as far as I know or maybe there but not straightforward

**Comment by dbwelch** [comment]
For example, the Shell (in v4) requires a ContentView for it's main content, there is no way (that I know of) to trigger any changes in the ConventView when showing the Shell without OnAppearing/OnDisappearing in the ContentView.  I'm sure there are other use cases, but this seems very obvious to me, "needs specification"?

**Comment by Tam66662** [comment]
This issue has just hit me on a very basic architecture.  I have a main ContentPage with multiple ContentViews that I switch to based on a user's current "view" that I wish to show them.  Two of these views share the same underlying BindingContext.  When I update the BindingContext from one of the views, it does not refresh the binding on the other view because there is no event such as OnAppearing like on a ContentPage.  The ContentView's OnLayoutChanged isn't good enough because the ContentView was never destroyed, so it won't fire when I switch from one ContentView to another.

**Comment by jrahma** [comment]
another example is Register and DeRegister which needs to be inside the OnAppearing and OnDisappearing

`App.Current.AppLinks.RegisterLink(_appLink);`

**Comment by MortMH** [comment]
I need this as well.

I've built a custom tab bar using a ContentPage and two ContentViews that switch in and out when the user tabs on the two menu items and I need OnAppearing for automatic refreshing functionality.

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/2210

**Comment by ali-h2010** [comment]
Any update on this issue?

**Comment by webnard** [comment]
@ali-h2010 Looks like the Xamarin Community Toolkit LifecycleEffect was introduced that may do what you need: https://docs.microsoft.com/en-us/xamarin/community-toolkit/effects/lifecycleeffect

**Comment by GaijinFizz** [comment]
Unfortunately LifeCycleEffect_Loaded will be triggered once only, not every time the tab is shown.
