### ISSUE TITLE
[Android] Can't Overlap a Button with any view

### ISSUE THREAD

**Issue by Phenek** [xamarin/Xamarin.Forms#3543]
### Description
It's for now impossible to overlap a button on Android with another view.

### Steps to Reproduce

1. Add a button on a layout (AbsoluteLayout, Grid,.. "kind of layout that allows overlap")
2. Then add another view (ActivityIndicator, Image, Notification Badges, text, ..) on the layout
3. The Button always in front

### Expected Behavior
The expected hierarchy of the visual stack would be:
- Button would be on the back of the visual stack.
- The other view would be on the front of the visual stack.

### Actual Behavior
The button is stuck on the front of the visual stack.

### Basic Information
- Xamarin.Forms: 3.1.0.697729
- Android : 8.1

**Comment by samhouts** [comment]
[Issue3543.zip](https://github.com/xamarin/Xamarin.Forms/files/2279790/Issue3543.zip)

I am not seeing the behavior described. Please test the attached project and alter it such that it exhibits the problem. Thank you!

**Comment by clovs** [comment]
First thanks for your time,

I figured out, the only things that create this bug.
It's because I was using this flag in my MainActivity.cs: 
```Forms.SetFlags("FastRenderers_Experimental"); ```

Obviously the Button FastRenderer is rendering on top of the visual stack.
Seems this issue can be close or can be move to an experimental section.

Regards,

PS: Another thing with FastRenderers
If you create a layout (AbsoluteLayout, Grid,.. "kind of layout that allows overlap") with a Xaml button in Xaml, then add another button programmatically to overlap the Xaml button.
At this moment the Xaml button is on front overlapping everything, 
so Xaml have the priority to be on front, or it's rendering at the end?

**Comment by samhouts** [comment]
Yep, you are correct! The FastRenderer Button sticks on top. 

Priority should be given to whatever element is added to the layout last, regardless of XAML or programmatic. Your experience seems to be another artifact of FastRenderers not being layered properly.

Thanks!

**Comment by WarBorg** [comment]
@samhouts  this is still an issue with fast renderers if you place the button on a layout (AbsoluteLayout, Grid,.. "kind of layout that allows overlap") and all of that into a ScrollView and into a NavigationPage it will duplicate the same behaviour as mentioned in the original bug

there is also a related issue with this, having the button on a layout (AbsoluteLayout, Grid,.. "kind of layout that allows overlap") with something in front of it, it I click the button it will come in front of the other visual elements

### Test app
please see the test app I made for this scenarios
https://github.com/WarBorg/TestActivityButtonXamForms

### Basic Information
using latest Xamarin Framework 4.5.0.396
using Android 9.0 - api 28 emulator

### Known workaround:
switch to "UseLegacyRenderers"

**PS please tell me if I need to create a new issue and I will do that, thank you**

**Comment by samhouts** [comment]
@WarBorg Yes, please create a new issue! Thank you!!!
