### ISSUE TITLE
DatePicker NULL value 

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3728]
Hi

Please allow to set a null value to the DatePicker..

Currently it forces a value but most of the times we want to initially show it with a placeholder, e.g. [Select], Birthday, etc

Thanks,
Jassim

**Comment by jfversluis** [comment]
Started to look into this. iOS and Android are pretty straight-forward, however, on UWP this can't be done. At least not with the control that is used now.

**Comment by albilaga** [comment]
hi @jfversluis do you have sample code to make it nullable? I need one with placeholder. For now I already make it for android and iOS but the problem in android is I can't detect cancel button clicked and event DateSelected not triggered when choosing date with the same previous date. iOS works fine because there is no cancel event.

**Comment by mina5500** [comment]
Is it published yet?
@samhouts

**Comment by jfversluis** [comment]
@mina5500 this has not been implemented yet

**Comment by mina5500** [comment]
@jfversluis Is it going to be implemented?
We are waiting for this feature since 2016 😅
Null value
Clear button
Placeholder text

**Comment by mina5500** [comment]
Do you have any ETA? 😊🙏
@samhouts

**Comment by mina5500** [comment]
Is it in out in 4.6?

**Comment by jfversluis** [comment]
Unfortunately not

**Comment by eopeter** [comment]
Can we merge this PR?

**Comment by amirvenus** [comment]
It's so sad that it keeps getting removed from in progress...

**Comment by mina5500** [comment]
why removed from In Progress ??

**Comment by injenuityltd** [comment]
We have been waiting this functionality since 2014, and I was hopeful that finally we would get this capability.
Come on guys, merge this code in!

**Comment by jfversluis** [comment]
Hey everyone! I see some mentions of years, which is crazy! Thank you for being patient. Unfortunately, since Forms is now in maintenance mode we're not going to be able to add this to Xamarin.Forms anymore. I see there is a lot of engagement and also in my years of developing with Forms and then on Forms, I have seen this request many, many times. I have added it to my list of things to consider for .NET MAUI.

Please feel free to see if there is already a feature request open for it and upvote that, if not, please feel free to open one with all the details you can add. Let's get it in there and not let it take years again 😬

Thanks!

**Comment by injenuityltd** [comment]
Basic functionality ignored.


We have decided to move over to flutter as we feel MS have lost touch of developers needs.
Get Outlook for Android

**Comment by jfversluis** [comment]
@injenuityltd thanks for letting us know, good luck with your endeavours and the best for 2022!
