### ISSUE TITLE
Mobile controls

### ISSUE THREAD

**Issue by RenaudAvenas** [xamarin/Xamarin.Forms#3765]
Hey, I work to simplify interface creation with xamarin forms. I have made a solution with multiple controls that are very useful for my team and my Customer project. If it's possible, I propose that you integrate a part or entire solution in Xamarin.Forms. I pushed the code on github here : https://github.com/RenaudAvenas/Mobile.Controls. (Sorry for my English ^^)

**Comment by PureWeen** [comment]
Hey @RenaudAvenas  this is a great addition to the ecosystem thanks for publishing your work out to open source

I've posted a few issues below where it seems like your controls might be helpful

https://github.com/xamarin/Xamarin.Forms/issues/1728
https://github.com/xamarin/Xamarin.Forms/issues/2404
https://github.com/xamarin/Xamarin.Forms/issues/1743

We have a community sprint that we've been pushing a lot of these types of additions to
https://github.com/xamarin/Xamarin.Forms/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22f100%22+

If you see additional issues there where your controls would be useful I'd say make a note in the issue of existing work you've accomplished.

Another recommendation I'd have for reusing some of your bits would be to add what kind of License you want for your library. As is since I don't see one we couldn't really use or reference anything you have

**Comment by RenaudAvenas** [comment]
Hello, thanks for your answer!
 My code is totally free for Xamarin.Forms ^^. Licence is GPL. I will mentionned it in a .txt in source code on github.

**Comment by GalaxiaGuy** [comment]
Xamarin Forms is MIT licensed, meaning it cannot accept GPL licensed code.

**Comment by andreinitescu** [comment]
@RenaudAvenas Your repository is not accessible anymore https://github.com/RenaudAvenas/Mobile.Controls
Are you planning to make it available again? Thanks

**Comment by RenaudAvenas** [comment]
Hello,
Indeed it was removed for legal reasons but I develop a new free library that will have same functionnality. I notified you when it will be done.

**Comment by RenaudAvenas** [comment]
Hello, my new Library is comming soon and is already on GitHub at https://github.com/RenaudAvenas/Oxard.XControls. Package nuget will follow when Library will be more complete
