### ISSUE TITLE
ObjectDisposedException during SetNativeControl in ViewRenderer for Android WebView

### ISSUE THREAD

**Issue by rbluethl** [xamarin/Xamarin.Forms#3804]
### Description

Hey there! I'm having quite a strange issue with my custom renderer for an Android WebView.
In my application, I support opening multiple web views. I have a MasterDetailPage, where the master page contains a simple menu and the detail page contains the currently visible web view.
The web views are of type ContentPage which contain the custom WebView `SubWebView`.

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:controls="clr-namespace:Nxa.Touch.Controls;assembly=Nxa.Touch"
             x:Class="Nxa.Touch.SubWebViewPage">
    <ContentPage.Content>
        <StackLayout>
            <!-- the custom web view -->
            <controls:SubWebView ...></controls:SubWebView>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

The pages are being cached in a dictionary in my MasterDetailPage, since I want the user to be able to reopen a view that was previously opened.

```
private IDictionary<string, SubWebViewPage> _views = new Dictionary<string, SubWebViewPage>();
```

When a view needs to be shown, I'm fetching the page from my dictionary and show it like this:

```
var identifier = "view1";
Detail = _views[identifier];
IsPresented = false;
```

The first time it works perfectly, but the second time I try to show it, I get an `ObjectDisposedException` during `SetNativeControl` in the renderer of my custom WebView, which looks like this:

```
public class SubWebViewRenderer : ViewRenderer<Touch.Controls.SubWebView, WebView>
    {
        public SubWebViewRenderer(Context context) : base(context) { }

        protected override void OnElementChanged(ElementChangedEventArgs<Touch.Controls.SubWebView> e)
        {
            base.OnElementChanged(e);

            var subWebView = e.NewElement;
            // subWebView.WebView is being set by the MasterDetailPage when a new web view is request to be opened
            if (subWebView.WebView != null)
            {
                SetNativeControl((WebView)subWebView.WebView);
            }
        }
    }
```

Now I know that there is a lot of code missing here, but there's quite a lot going on in my application. I've come across a few issues with getting ObjectDisposedExceptions in custom renderers, so I thought maybe it's a known problem already? I'm already sorry if the issue isn't clear enough. Please let me know if I can explain something in more detail.

Thank you,
Ronald

### Basic Information

- Version with issue: 3.1.0.697729
- Last known good version: None
- IDE: Visual Studio 2017 15.8.4
- Platform Target Frameworks:
  - Android: Android 8.1 - API 27

**Comment by hartez** [comment]
When you switch out the Master Detail Page's detail view, the renderer for the previous view is disposed (i.e., the `Dispose(bool disposing)` method is called on it. So the `WebView` you're caching is being disposed, which results in an `ObjectDisposedException` next time you try to use it. 

At the moment, what you're trying to accomplish isn't officially supported; you will probably just have to create a new `WebView` when pulling your `SubviewView` out of the cache. Having the option of retaining renderers instead of immediately disposing of them is a feature folks have been requesting for a while, but so far it hasn't made the cut.

That said: there _might_ be a way to make your caching work. There _is_ a means of preventing the native control from being disposed; you can override the `ManageNativeControlLifetime` property on your `SubWebViewRenderer` to return `false`. This is a mechanism we put in place to support native control embedding; it tells the `Dispose` method of the renderer not to call `Dispose` on the native control. So it _might_ solve your problem here.

**Comment by rbluethl** [comment]
Thanks a lot for the detailed explanation, very appreciated.
Overriding the `ManageNativeControlLifetime` seems to work fine.

Any side effects I need to be aware of in that case?

**Comment by hartez** [comment]
Nothing comes immediately to mind. Just be sure to call Dispose on the controls when you're done with them.
