### ISSUE TITLE
UWP: Changing Scale property has no effect via a binding

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#3830]
### Description

Changing the `Scale` property of a `Label` via a binding on a `Slider` has no effect on UWP, but works fine on iOS/Android.

Also note that (on UWP) moving the ScaleX/ScaleY sliders after moving the Scale slider, has no effect. However, the ScaleX/ScaleY sliders work provided you haven't moved the Scale slider first.

### Steps to Reproduce

1. Run the attached sample on UWP.
2. Browse to the Scale and Rotate (XAML) page.
3. Move the top (Scale) slider.

### Expected Behavior

The "SCALE AND ROTATE" text is scaled.

### Actual Behavior

The "SCALE AND ROTATE" text remains unscaled.

### Basic Information

- Version with issue: 3.2.0.839982
- IDE: VS2017  15.8.4
- Platform Target Frameworks:  
  - UWP:  16299 (problem still exists on 17134)

### Reproduction Link

[ScaleAndRotate.zip](https://github.com/xamarin/Xamarin.Forms/files/2397274/ScaleAndRotate.zip)

**Comment by deakjahn** [comment]
Very probably related to https://github.com/xamarin/Xamarin.Forms/issues/3279 and lots of previous reports. It's supposed to be fixed in a future version, 3.3 while we're still at 3.2. I tried to ask why on earth would something actually fixed delayed by who knows how many interim releases but I didn't even get a reply. :-)

**Comment by davidbritch** [comment]
Looks like this maybe fixed by https://github.com/xamarin/Xamarin.Forms/pull/3178

**Comment by hartez** [comment]
> Looks like this maybe fixed by #3178

Yes - scaling works in 3.3.0-pre1.
