### ISSUE TITLE
[Enhancement] Make AutomationID Bindable

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#3845]
## Rationale

See https://xamarin.uservoice.com/forums/144858/suggestions/13865469

## Implementation

TBD

## API

TBD

**Comment by johnshardman** [comment]
I logged a bug ( https://bugzilla.xamarin.com/show_bug.cgi?id=40817 ) in May 2016 because AutomationId couldn't be changed after it had initially been set. The bug was closed and the reason given was because UITest does not reevaluate the UI tree, so would not pick up a changed AutomationId. Is this still a concern, or has UITest been updated to cope?

**Comment by hartez** [comment]
@johnshardman That's still the situation. And the bindable AutomationId can still only be set once - changing it after the initial set will still throw an exception. The only difference is that the initial setting of the property can now happen via binding.

**Comment by Petersimonssolarwinds** [comment]
Well that's the behaviour that has been defined, but if you have a good case you could remove the 3 lines of code that are forcing that exception and do a pr for it

**Comment by johnshardman** [comment]
Thanks for the clarification. It's probably only worth removing this restriction if UITest includes an option to re-evaluate the UI tree.

**Comment by Petersimonssolarwinds** [comment]
Well we have solved the issue by having custom renderers that specifically set and reset the platform specific accessibility IDs whenever some of our cells get recycled and uitest just works, if you have an app result in memory you would have to do another app query to get a result with updated values.

**Comment by johnshardman** [comment]
That's interesting. If UITest works, then it's worth removing the restriction to allow for recycling of cells etc. Having binding change other aspects of an item, but not be able to change the AutomationId, is a strange restriction that messes with how automated testing would otherwise be done. It shouldn't be necessary to implement custom renderers to do this.
