### ISSUE TITLE
[Feedback] Xamarin Forms 3.2 Android entry cursor jumps back and forth

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#3923]
### Description

<p>Xamarin.Forms 3.2 appears to introduce and error, in some cases, where when typing into an entry field, the cursor continually jumps from the beginning to the end of input and back continuously.  Thus when attempting to enter &quot;123456789&quot;, it comes out as &quot;975312468&quot;.  It occurs when typing directly and using on-screen keyboard.  I've repeated the problem using an emulator and debugging on a device.  It seems to only occur on Android.

In my case, the issue only happens when I am brought to my initial login screen on startup.  If I reset the cursor after each character and login successfully, I no longer have a problem, even if I log off and back on during the session.  If I start a new session and currently have valid login information cached and bypass the sign in page, I also do not have a problem.  I've only seen this problem on my sign on page.

Reverting back to Xamarin.Forms 3.1 fixes the problem.

Visual Studio 15.8.5
Xamarin   4.11.0.776 (d15-8@1ae9b59d7)
Xamarin Designer   4.15.9 (d000f568b)
Xamarin Templates   1.1.116 (9619170)
Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
Xamarin.iOS and Xamarin.Mac SDK   12.0.0.15 (84552a4)
Xamarin.Forms 3.2.0.839982</p>
<a href="https://developercommunity.visualstudio.com/content/problem/343323/xamarin-forms-32-android-entry-cursor-jumps-back-a.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/691272">original linked feedback ticket</a>.

### Source

[692432](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/692432)

**Comment by lukazh** [comment]
`OnCreateView` method in `Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer` class is called twice for the same "initial login screen" page on startup, result in double renderers created for the single page. That could be the root cause of this issue.

**Comment by kvpt** [comment]
Made a fix on the 3.6 branch.

**Comment by kvpt** [comment]
@ndcs Thanks for the reproduction.
@lukazh Thanks to have raise the issue to the top

**Comment by lukazh** [comment]
@kvpt The fix only fixes cursor jump behavior, while the problem of duplicate call on `OnCreateView` for single page still exists, which could be the cause of "certain circumstances". Would you please take some time to invest this?

**Comment by kvpt** [comment]
@lukazh The issue here is for the cursor jump and what cause this is a focus problem.
The duplicate call of OnCreateView is not related to this issue. I'm sure of this, because all the events here come from Android and there can only be one "MainView" at a time.

So if you have this issue and have reproduction example, I invite you to open a dedicated issue.

From previous debug session, if I remember, I have encountered this case of double call.
From the stacktrace it was caused by the registrar (used by depency injection) class which initialized all the renderers which trigger the OnCreateView but those views was never attached.
You can check it yourself, use a breakpoint and compare the stacktraces of the two calls.

**Comment by lukazh** [comment]
[repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3350928/repro.zip)
@kvpt  I made a much simpler reproduction with only two pages and nothing else. The duplicate method call occurs as well, which means it has nothing to do with dependency injection.

If you make a breakpoint in `OnTextChanged` method in `Xamarin.Forms.Platform.Android.EntryRenderer` class and then input in the Entry, you will find that the method is called twice, from two different instances (use `GetHashCode()` or somehow). These two renderer instances interfere with each other causing problems including focus and cursor.

When one of the two calls on `OnCreateView` is discarded, everything works well and we don't need to care about the focus stuff.

**Comment by kvpt** [comment]
@lukazh Thanks for the reproduction, I will test that.

**Comment by kvpt** [comment]
@lukazh Your problem is caused by the navigation during the MainPage appearing. 
This edge case is broken in Xamarin.Forms, I fixed it in #4730 but it has not been merged yet.
You have to solution :
- Had a delay/wait before your push async inside the OnAppearing (1 second is normaly enough)
- Use my custom package which contain the fix _(the nupkg is inside the zip)_, However it's based on the 3.6 branch (I don't use 3.2 branch anymore).
[xamarin.forms.3.6.8.zip](https://github.com/xamarin/Xamarin.Forms/files/3352152/xamarin.forms.3.6.8.zip)

I will check the other reproduction to see if the same patch fix also the issue here.

**Comment by kvpt** [comment]
It's also the same case in the other reproduction. 
The init method of the MainViewModel make a navigation to another page in the init, I did not see that.
So the right fix is #4730 and not #6736, so I will close #6736.

**Comment by snice1981** [comment]
Hi 

I have the same problem in Xamarin Forms 4.3. I need to type two times the same character. For instance, if I want 1234, I need to do 11223344. Same for backspace, need to do 2x backspace.

How did you solve the problem?

**Comment by kvpt** [comment]
Hi @snice1981,
From the previous reproduction cases in this post, the issue is related to a navigation during the init.
So if you make a navigation at this place too, it's the same root cause.
As the fix for this is not merged yet, you will have to do the workaround, which is to add a Task.Delay (1 second should do it) before the navigation to give more time for the main page to load before navigating.
If it's not your case, can you provide a reproduction ?

**Comment by snice1981** [comment]
Hi @kvpt 

Here is my reproduction:
From the Main page, I have a LongPressedEffect command that navigate to a Settings page (`App.NavigationService.NavigateAsync(NavigationPages.SettingsPage)`)

Here is the OnAppearing in SettingsPage.xaml.cs:

![image](https://user-images.githubusercontent.com/25153628/70517981-d04cc780-1b39-11ea-80a6-acb7487a7156.png)


The Settings page is pretty easy and just contains 3-4 Labels + 3-4 Entry
I have the problem on all Entry in that page.

Here is an example of Entry that cause the issue:

![image](https://user-images.githubusercontent.com/25153628/70518096-0b4efb00-1b3a-11ea-907e-845d1f3d31d9.png)

![image](https://user-images.githubusercontent.com/25153628/70518076-fe320c00-1b39-11ea-93ff-e242a4e9bf6b.png)

This code was working since months until I upgraded from Xamarin Forms v3.0 to latest (v4.3)

**Comment by snice1981** [comment]
I think I have found the reason! 
If I put SetValue after Settings.ServerURL it works!

![image](https://user-images.githubusercontent.com/25153628/70522738-01c99100-1b42-11ea-9613-3982827450f7.png)

And that's how it should be of course, as in the SetValue we are firing OnPropertyChange event which will rebind the Entry to not yet changed value...

However it doesn't explain why it was working since months...
