### ISSUE TITLE
android:TabbedPage.ToolbarPlacement="Bottom"

### ISSUE THREAD

**Issue by IamPeek** [xamarin/Xamarin.Forms#3945]
### Description
This Property doesn´t work well. I needed 5 hours to run it, and my IDE still doesnt recognize it, I got it somehow to run by rebuilding and starting the project(have to do this every time). When I change something on the code IDE will instantly throw the error that it doesn´t regonice it. And still after making it run it doesn´t look like the TabbedPage on Top(behaves more like a CarouselPage)
### Steps to Reproduce

1. Don´t know IDE just doesn´t recognice it(Xamarin Version 3.2)
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
https://picload.org/view/dcgalacw/u.png.html

**Comment by IamPeek** [comment]
@kingces95 yes, but it does also not look like the bar when it is at the top, especially when you have more than 3 elements --> then it looks kind of weird...

**Comment by GalaxiaGuy** [comment]
By design, it's not intended to look like the bar at the top:

https://material.io/design/components/tabs.html
https://material.io/design/components/bottom-navigation.html

The weirdness with more than 3 items is also by design, but weird enough that there is an open enhancement to allow it to be disabled: #3083
