### ISSUE TITLE
Binding does not update view when BindingContext is page itself

### ISSUE THREAD

**Issue by Maxima078** [xamarin/Xamarin.Forms#3994]
### Description
I just noticed a strange behaviour when BindingContext is set to a page itself. If I use a binding such as `Text="{Binding BindingContext.TestLabel, Source={x:Reference myPage}}"` in a Label for instance, Text will never be updated.
`Text="{Binding TestLabel}"` is OK.
`Text="{Binding TestLabel, Source={x:Reference myPage}}"` is OK
Note that this issue does not exist when BindingContext is set to something else than the page itself.

### Steps to Reproduce

1. Set `BindingContext = this` in a page
2. Put a Label with Text bound to a page prop using BindingContext `Text="{Binding BindingContext.TestLabel, Source={x:Reference myPage}}"`
3. At runtime update this prop 

### Expected Behavior
Text is updated
### Actual Behavior
Text is not updated
### Basic Information

- Version with issue: 3.2.0.839982
- Android: 7.0

### Reproduction Link
[Xamarin.samples.navigation.bindingcontext.zip](https://github.com/xamarin/Xamarin.Forms/files/2446708/Xamarin.samples.navigation.bindingcontext.zip)

**Comment by kingces95** [comment]
Reproduces as described.

**Comment by StephaneDelcroix** [comment]
mmm, I can not reproduce in a unitest...

```sharp
		[Test]
		//https://github.com/xamarin/Xamarin.Forms/issues/3994
		public void INPCOnBindingWithSource()
		{
			var vm = new MockViewModel{Text="Foo"};
			var label = new Label();
			var layout = new StackLayout{
				Children={label},
				BindingContext = vm,
			};
			label.SetBinding(Label.TextProperty, new Binding("BindingContext.Text", source:layout));
			Assert.That(label.Text, Is.EqualTo("Foo"));

			vm.Text="Bar";
			Assert.That(label.Text, Is.EqualTo("Bar"));
		}
```

**Comment by AmrAlSayed0** [comment]
I think what he means is this:
```csharp
[Test]
public void INPCWhenPageBindingContextIsItself()
{
	var page = new ContentPageWithTextProperty();
        page.Text = "Foo";
        page.BindingContext = page;
	var label = new Label();
	page.Content = label;
	label.SetBinding(Label.TextProperty, new Binding("BindingContext.Text", source:page));
	Assert.That(label.Text, Is.EqualTo("Foo"));

	page.Text="Bar";
	Assert.That(label.Text, Is.EqualTo("Bar"));
}
```

**Comment by RodgerLeblanc** [comment]
@AmrAlSayed0 is right, here's a modifed version of his unit test that you can run and fails. I'm using the Page.Title property instead of creating a TestLabel bindable property.

`
[Test]
//https://github.com/xamarin/Xamarin.Forms/issues/3994
public void INPCWhenPageBindingContextIsItself()
{
    ContentPage page = new ContentPage();
    page.Title = "Foo";
    page.BindingContext = page;
    Label label = new Label();
    page.Content = label;
    label.SetBinding(Label.TextProperty, new Binding("BindingContext.Title", source: page));
    Assert.That(label.Text, Is.EqualTo("Foo"));

    page.SetValue(Page.TitleProperty, "Bar");
    Assert.That(label.Text, Is.EqualTo("Bar"));
}
`

**Comment by mattisam** [comment]
This issue still exists. It just happens to work, because in description and in reproduction the BindingContext is set to 'this', where the TestLabel is located, but if binding context is set to anything else e.g. view model or null, the Source={x:Reference myPage}} still doesn't work. (Tested with 4.0.0-pre1)

Here is an example:
[BindingTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2747362/BindingTest.zip)
