### ISSUE TITLE
Adding OnColor property for SwitchCell

### ISSUE THREAD

**Issue by manutdkid77** [xamarin/Xamarin.Forms#4027]
## Summary
It would be nice to have the functionality to change the color of SwitchCell control since it's now available for the Switch control

## API Changes

```
public class SwitchCell : Cell
{
     public Color OnColor { get; set; }
} 
```
I would like to submit a PR if this proposal is accepted.

**Comment by StephaneDelcroix** [comment]
it make sense

**Comment by andreinitescu** [comment]
Is this in order to customize the color of the Switch on the SwitchCell?
I haven't seen properties with the prefix 'On' , it's usually used on virtual methods.
Wouldn't be better if it's called `SwitchColor` instead? Even if it sounds redundant to use "Switch" suffix, it's more obvious what it is doing. It also be on par with this EntryCell's LabelColor, see [here](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.entrycell.labelcolor?view=xamarin-forms#Xamarin_Forms_EntryCell_LabelColor)

**Comment by hartez** [comment]
> Wouldn't be better if it's called SwitchColor instead? Even if it sounds redundant to use "Switch" suffix, it's more obvious what it is doing. 

"OnColor" refers to the color of the switch when it is in the "on" position: https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.switch.oncolor?view=xamarin-forms

**Comment by andreinitescu** [comment]
@hartez  Yes, I realized it after I commented, stupid me :) Should had deleted the comment
