### ISSUE TITLE
StackLayout incorrect Error message when adding child controls

### ISSUE THREAD

**Issue by CasNouwens** [xamarin/Xamarin.Forms#4141]
### Description
Adding items to a stacklayout in the Shared codebase produces an error that controls are not allowed to be added

### Steps to Reproduce

1. Create empty project
2. Update Xamarin.forms to most recent Stable Build
3. Add stacklayout to grid
4. Build solution
5. Observe error

### Expected Behavior
Expecting no error

### Actual Behavior
An error in the error log, but running the application works fine.

### Basic Information

- Version with issue: 3.3.0.912540
- Last known good version: 3.2.0.839982
- IDE: Visual Studio 2017
(Default project settings, the way Visual Studio produces them)

### Screenshots

![afbeelding](https://user-images.githubusercontent.com/27767738/47219512-4975e200-d3af-11e8-9611-82698f17fe64.png)

### Reproduction Link
It occurs in a default project... This seems a bit excessive.

**Comment by hartez** [comment]
@CasNouwens Which default project template are you using? (Blank, Master-Detail, Tabbed)

**Comment by CasNouwens** [comment]
The Blank Project :)

**Comment by mgoertz-msft** [comment]
This does not repro for me. The APPX4001 error is suspicious though. There were a couple of reports around this on the Developer Community:
https://developercommunity.visualstudio.com/content/problem/24389/warning-appx4001-is-shown-for-uwp-class-library-pr.html
https://developercommunity.visualstudio.com/content/problem/250663/appx4001-build-property-appxbundleplatforms.html

@CasNouwens:  Could you please share the repro project so that I can pass it to the team that would own this issue for investigation?

**Comment by CasNouwens** [comment]
Creating the repo:
Step 1:
![afbeelding](https://user-images.githubusercontent.com/27767738/47414907-72f98980-d772-11e8-927d-5a451809e040.png)

Step 2: Update solution packages
![afbeelding](https://user-images.githubusercontent.com/27767738/47415043-c66bd780-d772-11e8-8e6f-6cc1d8e3dabf.png)

Step 3: Unload the iOS project, set UWP as startup project and Rebuild Solution
![afbeelding](https://user-images.githubusercontent.com/27767738/47419582-ccff4c80-d77c-11e8-95bc-0f6445e073f3.png)

**Comment by StephaneDelcroix** [comment]
great
