### ISSUE TITLE
Change the namespace for all the Issues in the control gallery to *Xamarin.Forms.Controls.Issues*

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#4150]
### Description
If a UI Test isn't in the *Xamarin.Forms.Controls.Issues* namespace and you run that as the first UI Test then this code doesn't run

```
#if UITEST
namespace Xamarin.Forms.Controls.Issues
{
	using System;
	using NUnit.Framework;

	// Run setup once for all tests in the Xamarin.Forms.Controls.Issues namespace
	// (instead of once for each test)
	[SetUpFixture]
	public class IssuesSetup
	{
		[SetUp]
		public void RunBeforeAnyTests()
		{
			AppSetup.RunningApp = AppSetup.Setup(null);
		}
	}
}
#endif
```

And you get a Null Reference Exception
https://github.com/xamarin/Xamarin.Forms/pull/4144#discussion_r226783148

### Steps to Reproduce

1.  Find a UI Test
2.  change the namespace to namespace Xamarin.Forms.Controls
3. Try to run the UI Test

### Expected Behavior
Make it easier for contributors to add UI Tests to existing issues and not have them fail

**Comment by ionixjunior** [comment]
Performing a quick verification, exists three different namespaces: 

- Xamarin.Forms.Controls (167 files)
- Xamarin.Forms.Controls.Issues (484 files)
- Xamarin.Forms.Controls.TestCasesPages (16 files)

To see this verifications just execute the follow command in terminal inside **Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared** folder:

```bash
grep '^namespace' *.cs | awk '{print $2}' | sort | uniq -c
```

Basically is change all to a single namespace (Xamarin.Forms.Controls.Issues) and change class reference on tests that have XAML files, ok?

I can proceed with this changes.

**Comment by ionixjunior** [comment]
@PureWeen  the build broke after changes because some classes of **Xamarin.Forms.Controls** project has **ViewModelBase** class reference - located in **Xamarin.Forms.Controls.Issues.Shared in AddingMultipleItemsListView.cs file**.

**AddingMultipleItemsListView.cs file** contains an UI test too, so I changed the namespace to **Xamarin.Forms.Controls.Issues**. 

I believe the **ViewModelBase** implementation should be in another file with namespace **Xamarin.Forms.Controls**. 

I will make this change and check build again.

**Comment by PureWeen** [comment]
@ionixjunior  Sounds good. I figured it would cause some collisions getting all those normalized. Thanks for taking this one on
