### ISSUE TITLE
XF 3.3 sets TabbedPage color based on NavigationPage.BarBackgroundColorProperty

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#4246]
### Description
In XP 3.2 and below, setting the Navigation colors as below below in the app.xaml.cs correctly render the colors in the NavigationBar. When upgraded to XF 3.3, these change the background of the TabbedPage to Pink

			Current.MainPage.SetValue(NavigationPage.BarTextColorProperty, Color.Black);
			Current.MainPage.SetValue(NavigationPage.BarBackgroundColorProperty, Color.Pink);

iOS and Android

### Steps to Reproduce

1.  Add a simple TabbedPage to a new XF 3.2 project. Add a few Navigation pages as children of the TabbedPage
2. Set the Main Page to this Tabbed Page
3. In App.xaml.cs set the Navigation Colors:

			Current.MainPage.SetValue(NavigationPage.BarTextColorProperty, Color.Black);
			Current.MainPage.SetValue(NavigationPage.BarBackgroundColorProperty, Color.Pink);

Works fine

Upgrade to XF 3.3, the TabbedPage changes to Pink

### Expected Behavior
Tabbed Page should not be pink

### Actual Behavior
Tabbed Page goes Pink in XF 3.3

### Basic Information

- Version with issue:
- Last known good version: 3.2 Release
- IDE: VS 21017
- Platform Target Frameworks: 
  - iOS: 12
  - Android: 9

### Screenshots

![xf tabbed page 3 2](https://user-images.githubusercontent.com/112916/47621221-ee7c7300-dab1-11e8-91e7-d858f7684bd6.png)

![xf 3 3](https://user-images.githubusercontent.com/112916/47621233-179d0380-dab2-11e8-9b85-eaaf37bae834.png)

**Comment by jfversluis** [comment]
OK, I have started looking into this and here is what I got.

I think the behavior is not necessary wrong. In the above reproduction, the `Current.MainPage` is a `TabbedPage` which has a property `BarBackgroundColor` which is identical to the one on `NavigationPage`. And since some time they are now both coming from the `IBarElement` interface, which might be the cause of this error.

By the time I get inside the `SetValue` call [here](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/BindableObject.cs#L325), I cannot seem to distinguish if we want the `NavigationPage.BarBackgroundColor` or the `TabbedPage.BarBackgroundColor`.

Output from immediate window at that time:
> \> NavigationPage.BarBackgroundColorProperty.Equals(property)
> true
> \> TabbedPage.BarBackgroundColorProperty.Equals(property)
> true

And since the `Current.MainPage` at that time is a `TabbedPage` and that type also has an identical `BarBackgroundColor` property, the value is applied there. 

If you want to actually set the bar color for the navigation pages wouldn't it make more sense to set that on the navigation page directly @ianvink? Do you remember what the use-case was for this?

@StephaneDelcroix would you be able to verify this? Am I overlooking something here? I've pushed a `fix-4246` branch with a reproduction

**Comment by jfversluis** [comment]
I think (hope?) that this is resolved by now! Let me know if this is still an issue for anyone!
