### ISSUE TITLE
Picker value cleared when scroll the listview item

### ISSUE THREAD

**Issue by RawoofSharief** [xamarin/Xamarin.Forms#4250]
### Description
Hi Team,

Listview item template contains picker and set the itemsource from the view model. Everything is loaded in the view but when i scroll the listview items then the picker values cleared.
### Steps to Reproduce

1. Run the sample
2. Scroll down listview items 
3. Now scroll the up the listview items you can see that the picker values cleared.

### Expected Behavior
Picker values should not clear
### Actual Behavior
Picker values cleared
### Basic Information

- Version with issue:
- Last known good version:
- IDE: 2017
- Platform Target Frameworks: 
  - iOS: 
  - Android: 

### Reproduction Link

[Picker_Issue.zip](https://github.com/xamarin/Xamarin.Forms/files/2524928/Picker_Issue.zip)

**Comment by pauldipietro** [comment]
The behavior appears it may be due to using `RecycleElement` not updating the BindingContext correctly upon virtualization, as removing its use causes the pickers to not be cleared. I would refer to the [docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/performance) for its usage to see if that aids you.
