### ISSUE TITLE
(Android) Entry open keyboard pushes the whole page content up

### ISSUE THREAD

**Issue by henryyue2010** [xamarin/Xamarin.Forms#4273]
### Description
When uses Entry in the page, opening keyboard of it causes the whole page moving up, including the page's top NavigationBar and TitleView  

### Expected Behavior
Not to move part of the navigation bar when the entry keyboard appears. Or is it possible to make Entry control where its keyboard overlaps the content of the page? like ScrollView has the method scrollTo?

**Comment by rmarinho** [comment]
Hi, can you please upload a reproduction to try show us your issue and specify what platforms you see this.

I have tried a simple sample and I don't see the NavigationBar moving, here's the example I used:

```
var page = new ContentPage
{
	Title = "Hello",
	Content = new ScrollView { Content = new Entry { } }
};
SetMainPage(new NavigationPage(page));
```

Thanks

**Comment by hartez** [comment]
@henryyue2010 You might want to take a look at the [WindowSoftInputModeAdjust property](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.platformconfiguration.androidspecific.application.windowsoftinputmodeadjustproperty?view=xamarin-forms). 

Try setting `Application.Current.On<Android>().UseWindowSoftInputModeAdjust(WindowSoftInputModeAdjust.Resize);` - this will change the [windowSoftInputMode](https://developer.android.com/guide/topics/manifest/activity-element#wsoft) for the Android application to resize the page rather than panning it up to make room.

**Comment by PureWeen** [comment]
Closing. I'm assuming @hartez comment resolved the issue for you

**Comment by maksym-husiev** [comment]
Hi, everyone! 

What about Shell Component? When I'm using **WindowSoftInputModeAdjust.Resize** bottom part of Shell (Tab Bar) appears just above the keyboard. 

On iOS all working well, when I'm opening keyboard, all panels (navigation bar on the top of the screen and tab bar on the bottom) stay where they suppose to be, but page (loaded into Shell) scrolling up if it's needed when I'm opening keyboard.

What I want to see: the same behaviour for android and iOS (and it's should be like on iOS) or at least have some option to set such behaviour.

P.S. for iOS exists other problem, when you really need to resize whole app including tab bar. Lets say we have an app with chat-like page (we set Shell Tab Bar visibility to False and placed some Entry on the bottom of the screen), in this case **WindowSoftInputModeAdjust.Resize** solve the issue for Android, but for iOS we need to create some workaround code (there exists several typical solutions).

P.S.S. I'm have not so much experience in Xamarin development. Maybe solutions was already included in the latest versions of Xamarin.Forms?
