### ISSUE TITLE
Make backing classes optional for XAML files

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#4327]
### Description

A lot of Pages or custom Layouts/Views are done in XAML today often with no actual code behind. With XamlC turned on we should be able to eliminate the cs file completely since XamlC is generating the class for us. The behavior should allow for flexibility as the developer needs so that if your entire class looks like:

```cs
public class MyPage : ContentPage
{
    public MyPage()
    {
        InitializeComponent();
    }
}
```

you should be able to simply delete the file and have all of your code continue to work.

cc: @kzu

**Comment by StephaneDelcroix** [comment]
We already do that for ResourceDictionaries without x:Class, but that's easier as we have a way to reference a ResourceDictionary with a `Source` uri, but we don't have a way to instantiate a view without a constructor.

We could, indeed, create the default ctor if one is not present, but as the code-behind is created by the template, I fail to see the added value here...

**Comment by dansiegel** [comment]
IMO there's not much point in having a bunch of files that exist purely to declare a default ctor that invokes `InitializeComponent()`. It seems to me that if XamlC is already generating a class, it might as well generate a ctor if one doesn't exist. This would also help clean up code bases for other scenarios where you don't need to do anything in the ctor but maybe you want an event handler or to override something like OnAppearing.

**Comment by andreinitescu** [comment]
It's OK to make it optional, as long as it's not enabled by default to remove the backing class when XAML compilation is on. Otherwise, some way in the tooling is needed to add the backing class back easily when needed, without having to manually add a class with same name and call InitializeComponent() by yourself. Today, you don't actually even see the partial .cs file because VS keeps it collapsed under the .XAML file.

**Comment by dansiegel** [comment]
@andreinitescu This isn't an opt-in/opt-out sort of thing where you turn something on/off... rather it should simply be a little extra logic in to determine there isn't a declared ctor and one should be added to the generated {pagename}.xaml.g.cs in the obj folder.

As for the collapsing you're referring to that's simply an MSBuild/IDE trick to group related files which has nothing to do with actually eliminating the requirement for the backing code class in the first place.

**Comment by andreinitescu** [comment]
@dansiegel 
>  This isn't an opt-in/opt-out sort of thing where you turn something on/off... rather it should simply be a little extra logic in to determine there isn't a declared ctor and one should be added to the generated {pagename}.xaml.g.cs in the obj folder.

XAML compilation is currently enabled by default, meaning with the current XF template in VS, when I create a project, the XAML Compilation is on. What you're suggesting I think is automatically not generate the backing class.  I don't agree with this idea of automatically eliminating the backing class from start. The reason is, like I said, if I decide I need it, I don't want to be forced to add the backing class manually. Instead, there should be a mechanism, maybe an attribute (maybe use existing XamlCompilation attribute with a new flag) to remove the backing class if you want it.

> As for the collapsing you're referring to that's simply an MSBuild/IDE trick to group related files which has nothing to do with actually eliminating the requirement for the backing code class in the first place.

I know how collapsing works. The reason I mentioned it is, even today, you don't actually see it in Visual Studio, so it doesn't actually get in your way much. Except being an inconvenience of having the actual the *.xaml.cs file near every XAML file in your Views folder. 

I am not against your idea, I just wouldn't it to be turned on by default.

**Comment by andreinitescu** [comment]
Or, have it turned on by default, meaning no backing class is generated, but have a way to tell XAMLC to generate the backing class, maybe like this:

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MyApp.Views.MainPage"
             xamlc:BackingClass="True">
```

**Comment by dansiegel** [comment]
@andreinitescu I don't believe you understand any part of what I've suggested here... and you're way over complicating this.

It's really quite simple... If you have `SomePage.xaml` and you have `SomePage.xaml.cs` and there is no declared ctor the XamlC task should take care of simply adding the ctor in the generated code for you....

If you have `SomePage.xaml` and `SomePage.xaml.cs` does NOT exist... then great XamlC should be able to pick that up and simply add the ctor in the generated code... I'm not suggesting anything complex for a developer... it's simple, if you want the file great... if you don't, that's fine too.

As I already said... this isn't about turning a feature on or off... it's about adding a little bit of extra logic to make XamlC better. There should be absolutely zero configuration ever needed one way or the other. If you still want to have a code class in your project that's great.. if you still want a ctor then you would see zero change in behavior from what you would currently experience... but if you delete the code file everything would still work with what I've suggested here.

**Comment by andreinitescu** [comment]
@dansiegel You seem to only think only of two scenarios:
- Either you have SomePage.xaml.cs without no c-tor
- You don't have SomePage.xaml.cs

What if you want to have SomePage.xaml.cs with a c-tor?

Suppose I create a new XF project. And per your suggestion, there is no MainPage.xaml.cs generated, there's only MainPage.xaml.

At some point later on, I decide I actually need the backing class, so what should I do? I guess I will have to add the recreate myself the partial class which is generated today. I need to use right filename in case I want the nice file grouping in VS, and make sure to call InitializeComponent():

    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();

            // My own c-tor initialization code here
        }
   }

**Comment by StephaneDelcroix** [comment]
@dansiegel: I think @andreinitescu understands quite well what's the problem here. The problem is far from being simple.

At XamlC time, there is always a constructor, because your class is compiled, and the C# compiler takes care of adding one (if the class is not abstract). We could look into that constructor, and see if it calls InitializeComponent(), but again, we have no way to figure out if it's a deliberate choice from the dev (calling InitializeComponent from somewhere else), or if it's the default ctor generated by CSC. So it's a no go.

At XamlG time, it's too early to make that decision.

We _could_ (but it's unlikely at this time) add a new task, that is executed BeforeCompile, look at the current code (thx Roslyn), and from there, decide if there's a code behind partial class (in addition to the one generated by XamlG) and if it should add a default ctor calling InitializeComponent(). This will slow the build by a huge factor, and it's quite hard to have the heuristic JustRight(™) so it doesn't affect existing code. 

All of that for some convenience, but very little benefits.

Feel free to keep discussing this here, provided to you keep the discussion civil, but it's unlikely to change my mind for the coming months.

**Comment by kzu** [comment]
I think @StephaneDelcroix original comparison with the `ResourceDictionary` approach is likely the simpler and more intuitive way: use the presence (or absense) of the `x:Class` attribute and add a `Source` property to `ContentPage` and `ContentView`.

I agree that the increased complexity added by the "delete the .xaml.cs" scenario, is probably not worth it. Even if the resulting user experience would be slightly better.

**Comment by kzu** [comment]
The templates could be `ContentPage (with code-behind)` vs just `ContentPage` for example.

**Comment by andreinitescu** [comment]
Right now, you can delete the backing class file {page}.xaml.cs, it does not get regenerated, but obviously the problem is nobody calls the generated `InitializeComponent()` from {page}.xaml.g.cs anymore.  What if XAMLG checks presence of the {page}.xaml.cs, and if it's not there, it emits a call to `InitializeComponent()`? 

So the flow would still be like today: backing class is still generated, but it can be deleted. It might be inconvenient for Dan having to manually delete all the empty backing class files, but it does the job done, and it requires a very small change in the tooling, and for people who actually need the backing class, it's still there.

**Comment by dansiegel** [comment]
@andreinitescu I've never proposed changing any templates... so when you create a new page you should get the same experience you do today... and I have not forgotten the 3rd scenario:

>If you still want to have a code class in your project that's great.. if you still want a ctor then you would see zero change in behavior from what you would currently experience...

@StephaneDelcroix: What I've proposed is simple... The actual implementation is going to be a little more challenging.  It should be a relatively easy task at XamlG time to say there is no `{PageName}.xaml.cs`... add a ctor and invoke `InitializeComponent()`... I could also see that XamlC may not execute at the right time to handle what is needed... I would imagine what may be required is something like a custom Fody Weaver.

**Comment by StephaneDelcroix** [comment]
>  It should be a relatively easy task at XamlG time to say there is no {PageName}.xaml.cs

that's no a guarantee that there's no class at all, in a file named differently

**Comment by ysmoradi** [comment]
> that's no a guarantee that there's no class at all, in a file named differently

Are there any guarantee about InitializeComponent method? Maybe I've one method with that name in my code behind!

**Comment by jfversluis** [comment]
This would be so cool! But not for Xamarin.Forms anymore unfortunately at this stage :(

Thanks everyone for the time and effort that you have put into this!
