### ISSUE TITLE
[Feedback] Xamarin Forms Page StringFormat incorrect error

### ISSUE THREAD

**Issue by pauldipietro** [xamarin/Xamarin.Forms#4336]
### Description
<Label Text="{x:Binding BindingObjectFoo, StringFormat='{0} myText'}"  on compilation gives error on VS Preview and Warning on VS stable

Preview Error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	XLS0112	Expected '_'.	Views	MyPage.xaml	12	
Error	XLS0112	Expected '_'.	Views	MyPage.xaml	12	
Error	XLS0112	Expected '''.	Views	MyPage.xaml	12	
Error	XLS0112	Expected '}'.	Views	MyPage.xaml	12 

[View on Developer Community](https://developercommunity.visualstudio.com/content/problem/338750/xamarin-forms-page-stringformat-incorrect-error.html)

To find diagnostic information, see the [original linked feedback ticket](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/686599).

**Comment by mgoertz-msft** [comment]
@StephaneDelcroix , we have talked about this before. This is expected and should probably produce a compile error too. String values that begin with a '{' need to be escaped with "{}" in order to distinguish them from MarkupExtensions, so in this example the markup should look like this:

`<Label Text="{x:Binding BindingObjectFoo, StringFormat='{}{0} myText'}"`

**Comment by StephaneDelcroix** [comment]
🤦‍♂️of course, we talked about this

**Comment by StephaneDelcroix** [comment]
dupe of #2756
