### ISSUE TITLE
[Proposal] Better exception reporting

### ISSUE THREAD

**Issue by PieterjanDeClippel** [xamarin/Xamarin.Forms#4440]
I really like the evolution of Xamarin.Forms.

I'm working with Xamarin.Forms all the time now and I'm thinking of 2 major improvements.

### Binding exceptions: display path

When an exception occurs evaluating a binding in the XF page, you're getting exception messages that get you nowhere. For example: https://forums.xamarin.com/discussion/6800/unhandled-exception-details-in-vs-2012-where-is-it

If you get this exception, I now know it means Xamarin.Forms failed to evaluate a binding from viewmodel to page (source to target or vice-versa). But you wouldn't know which binding failed to update.
The best way i found around this error is by commenting code-blocks, re-testing your application, and again uncomment one-by-one.

If you'd actually get the path of the binding that fails to be evaluated, you'd immediately be able to put breakpoints at specific places in your c# code, and check for like NullReferences or IndexOutOfRangeExceptions.

This issue actually bothers me a bit...

### Evaluate binding in page

This would be pretty hard though.
But if possible it would be interesting if you'd be able to hover the variables in the page and have them mapped to the page's bindingcontext, so you'd see what they contain (in debug mode off course).

Now you have to put a breakpoint in the page c# code and trigger it. Next you have to stay inside the code-behind of the page, and evaluate expressions from there (through the immediate window or watch window).
You can't go to the xaml file of the same page and see the content of viewmodel variables.

This is just a nice to have

**Comment by bmacombe** [comment]
This is probably related so I'll add it here instead of creating a new issue.

I just had a weird error that would hard crash UWP and iOS at least.  Turns out it was a dumb mistake on my part, but took a bit to track down.  I was using a value converter on a binding and set the ConverterParamter instead of the Converter property...auto fill got me.

IsVisible="{Binding Description.Value, ConverterParameter={StaticResource ValueConverterNotEmptyString}}"

On UWP I was able to log an exception that at least told me it was a binding issue and I knew in which it was crashing, on iOS I didn't get much at all.  To make it more fun, I couldn't get Visual Studio to break on the exception either.  I've included exception details below for reference from UWP and iOS for the same mistake.

UWP
{  "Type": "System.NullReferenceException",  "Message": "Object reference not set to an instance of an object.",  "StackTrace": "   at Xamarin.Forms.VisualElement.<>c.<.cctor>b__268_3(BindableObject bindable, Object oldvalue, Object newvalue)\r\n   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)\r\n   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)\r\n   at Xamarin.Forms.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget)\r\n   at Xamarin.Forms.BindingExpression.Apply(Object sourceObject, BindableObject target, BindableProperty property)\r\n   at Xamarin.Forms.Binding.Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged)\r\n   at Xamarin.Forms.BindableObject.ApplyBindings(Boolean skipBindingContext, Boolean fromBindingContextChanged)\r\n   at Xamarin.Forms.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)\r\n   at Xamarin.Forms.Element.SetChildInheritedBindingContext(Element child, Object context)\r\n   at Xamarin.Forms.Element.<OnBindingContextChanged>b__78_0(BindableObject child, Object bc)\r\n   at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext[T](BindableObject self, IList`1 children, Action`2 setChildBindingContext)\r\n   at Xamarin.Forms.Element.OnBindingContextChanged()\r\n   at Xamarin.Forms.View.OnBindingContextChanged()\r\n   at Xamarin.Forms.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)\r\n   at Xamarin.Forms.TemplatedView.SetChildInheritedBindingContext(Element child, Object context)\r\n   at Xamarin.Forms.Element.<OnBindingContextChanged>b__78_0(BindableObject child, Object bc)\r\n   at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext[T](BindableObject self, IList`1 children, Action`2 setChildBindingContext)\r\n   at Xamarin.Forms.Element.OnBindingContextChanged()\r\n   at Xamarin.Forms.View.OnBindingContextChanged()\r\n   at Xamarin.Forms.ContentView.OnBindingContextChanged()\r\n   at Xamarin.Forms.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)\r\n   at Xamarin.Forms.TemplatedView.SetChildInheritedBindingContext(Element child, Object context)\r\n   at Xamarin.Forms.Element.<OnBindingContextChanged>b__78_0(BindableObject child, Object bc)\r\n   at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext[T](BindableObject self, IList`1 children, Action`2 setChildBindingContext)\r\n   at Xamarin.Forms.Element.OnBindingContextChanged()\r\n   at Xamarin.Forms.View.OnBindingContextChanged()\r\n   at Xamarin.Forms.ContentView.OnBindingContextChanged()\r\n   at Xamarin.Forms.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)\r\n   at Xamarin.Forms.Element.SetChildInheritedBindingContext(Element child, Object context)\r\n   at Xamarin.Forms.Element.<OnBindingContextChanged>b__78_0(BindableObject child, Object bc)\r\n   at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext[T](BindableObject self, IList`1 children, Action`2 setChildBindingContext)\r\n   at Xamarin.Forms.Element.OnBindingContextChanged()\r\n   at Xamarin.Forms.Cell.OnBindingContextChanged()\r\n   at Xamarin.Forms.BindableObject.BindingContextPropertyChanged(BindableObject bindable, Object oldvalue, Object newvalue)\r\n   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)\r\n   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)\r\n   at Xamarin.Forms.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)\r\n   at Xamarin.Forms.Internals.TemplatedItemsList`2.UpdateContent(TItem content, Int32 index, Object item)\r\n   at Xamarin.Forms.Internals.TemplatedItemsList`2.ActivateContent(Int32 index, Object item)\r\n   at Xamarin.Forms.Internals.TemplatedItemsList`2.CreateContent(Int32 index, Object item, Boolean insert)\r\n   at Xamarin.Forms.Internals.TemplatedItemsList`2.GetOrCreateContent(Int32 index, Object item)\r\n   at Xamarin.Forms.Internals.TemplatedItemsList`2.get_Item(Int32 index)\r\n   at Xamarin.Forms.ListView.NotifyRowTapped(Int32 groupIndex, Int32 inGroupIndex, Cell cell)\r\n   at Xamarin.Forms.ListView.NotifyRowTapped(Int32 index, Cell cell)\r\n   at Xamarin.Forms.Platform.UWP.ListViewRenderer.OnListItemClicked(Object sender, ItemClickEventArgs e)\r\n   at Windows.ApplicationModel.Core.UnhandledError.Propagate()\r\n   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, UnhandledErrorDetectedEventArgs eventArgs)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, UnhandledErrorDetectedEventArgs eventArgs)"}

iOS
{  "Type": null,  "Message": null,  "StackTrace": null}

**Comment by StephaneDelcroix** [comment]
Better exception messages is what we aim at. When you get an generic exception while parsing a Xaml file, or evaluating a Binding path, it means you found a case we are not testing for. In that case, please report with the particular issue, and a reproduction project so we can
1/ fix it
2/ add the case to our regression testing.

Debugging Xaml files would indeed be nice, but unfortunately not part of our priorities right now

So, can I ask you to reopen a new ticket with the Binding issue you found ? Thanks

**Comment by bmacombe** [comment]
Figured out it had to be a non-null property, such as IsVisible

#4446 has repo
