### ISSUE TITLE
Request to make some controls.

### ISSUE THREAD

**Issue by tp16190** [xamarin/Xamarin.Forms#4530]
Request to handle for nullable value and current date selection value in datepicker.

Request to make material design type radio buttons (group as well ) and checkbox controls(group as well)

Make new datetimepicker controls.

Why such great library has not these controls?

**Comment by nadjibus** [comment]
> Why such great library has not these controls?

I would say because it's an extremely complicated thing to write such a great library as you said, it takes a lot of time to write, optimize, test and fix bugs for 5 (6 with Tizen) different platforms, which leads to prioritization of tasks, and those controls (tbh most of the controls) are not a top priority as they are easy to implement via custom renderers (or already existing libraries, a Google search provided several of them).

Also, the good news is that Xamarin.Forms is open source, so maybe a developer will do a PR 😉

**Comment by samhouts** [comment]
@tp16190 Thank you for the feedback! We have an open spec for checkbox (#1728), and open spec for Radio Button (#2404). We have an open suggestion for null value on DatePicker (#3728). If you would like to contribute to these issues, you are more than welcome. If you would like to see your other suggestions added to the list, please submit one issue per request, and please use [this](https://github.com/xamarin/Xamarin.Forms/issues/new?template=feature_request.md) template to help us and the community better understand your needs. Thank you!
