### ISSUE TITLE
Xamarin.Forms 3.4.0 release on Nuget is missing UAP .pdb files

### ISSUE THREAD

**Issue by jalbertSyncroTech** [xamarin/Xamarin.Forms#4666]
### Description

Xamarin.Forms 3.4.0 release on NuGet.org is missing UAP .pdb files

Probably related to this pull request by @kingces95 
#4015 add pdb for uap into nuget

### Steps to Reproduce

Examine the file xamarin.forms.3.4.0.1008975.nupkg published on NuGet
there are no .pdb files in lib\uap10.0\ or anywhere else in the package,
but they are present for other platforms such as lib\MonoAndroid10\Xamarin.Forms.Platform.Android.pdb

### Expected Behavior

Should be able to use the .pdb files from NuGet to debug the v3.4.0 release

### Actual Behavior

Files are missing

### Basic Information

- Version with issue: 3.4.0.1008975
- Last known good version: Appears they've never been present, checked every major release back to v2.5.1
- Platform Target Frameworks:
  - UWP
- Nuget Packages: xamarin.forms.3.4.0.1008975.nupkg

**Comment by kingces95** [comment]
Hm, well, this doesn't break anything, right?

Not sure if it's better practice to include or exclude symbols from published nugets. Pretty sure my change would add the symbols if present. As you say, "Appears they've never been present," for UAP. That's why I added 'em... When reproducing locally I create a local nuget to install into the reproduction. 

I use .create-nuget.bat but that's not officially supported or used for buildnig nugets and as such may not always work. I update it whenever I use it -- https://github.com/xamarin/Xamarin.Forms/pull/4668.

Generally, if you need symbols then you're debugging an issue and so you'll want to be on the latest greatest build to make sure it's not already fixed so you'll want to build and create the nuget locally. Also, just having the symbols without the source doesn't do much good. And even if the source is synced you'll likely still want to test a patch which requires building. So I'd vote for not investing too much energy in packaging the symbols. 

All that said, if there's a reason for ensuring symbol inclusion in the package, then I'm all for it and please re-open.

**Comment by jalbertSyncroTech** [comment]
@kingces95 please re-open this - at the least UAP should have parity with Android, iOS, and the other supported platforms.  That sounds like something's broken to me, and the fact that it never worked doesn't negate that.  It's fine if you don't want to fix this now, or if you want to change Xamarin.Forms itself to exclude .pdb files for all platforms, but either way the issue isn't "closed".

**Comment by jalbertSyncroTech** [comment]
@kingces95 in my specific case I encountered a crash in the UAP FrameRenderer.  It seemed to be similar to this forum post:
https://forums.xamarin.com/discussion/125971/system-argumentexception-crash-in-custom-uwp-framerenderer

I was able to work around the crash this time, but when I've needed to debug other platform renderers for crashes like this I combine the .pds with the source published on github to debug the issue.

Also, using the latest and greatest isn't a viable solution in this case, since we were already on the latest stable version.  In most cases we'll write a custom renderer or effect to work-around the issue once we've discovered the specific cause, rather than moving onto an untested pre-release which invariably introduces new issues.
