### ISSUE TITLE
Metadata missing for Intellisense for constructor parameters

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Xamarin.Forms#4738]
### Description
IntelliSense either doesn't show or gives squiggles for the following:
* ListView -> CachingStrategy
* Android Platform Specifics: TabbedPage.ToolbarPlacement, BarItemColor, BarSelectedItemColor, VisualElement, ImageButton, Application, NavigationPage, anything in AppCompat specifics

Also there are a bunch of iOS ones that don't show up as well:
* Entry.CursorColor 

I am also seeing that on Android any of the "Application" ones are missing too.

There may be more.

### Steps to Reproduce

1.  In VS 2017 try to set these... they don't come up in intellisense and some give squiggles.

### Expected Behavior
They show up

### Actual Behavior
They don't :(

### Basic Information

- Version with issue: All, tested with 3.1-3.4
- Last known good version: None
- IDE: VS 2017

### Screenshots

![image](https://user-images.githubusercontent.com/1676321/50014600-41828a80-ff79-11e8-9f6e-9a2ef89e60ed.png)

**Comment by hartez** [comment]
I'm seeing squiggles for ToolbarPlacement, but Intellisense for the values seems fine:

![2018-12-14_14-08-04](https://user-images.githubusercontent.com/538025/50027561-e2893980-ffa9-11e8-9fb4-047b254d97b1.png)

**Comment by jamesmontemagno** [comment]
I think for that one it does come up, but if you just type:

```csharp
android:TabbedPage.
```

it does not.

Also on ListView CachingStrategy never comes up

**Comment by hartez** [comment]
I actually _don't_ get squiggles for the properties with value types (IsSwipePagingEnabled, IsSmoothScrollEnabled, OffscreenPageLimit). But the properties whose types are defined in Forms (ToolbarPlacement, BarSelectedItemColor, BarItemColor) I'm seeing squiggles.

**Comment by hartez** [comment]
> I think for that one it does come up, but if you just type:
> 
> ```cs
> android:TabbedPage.
> ```
> 
> it does not.
> 

I'm getting full-on Intellisense for that stuff. Something is definitely (and inconsistently) broken. 

![2018-12-14_14-18-50](https://user-images.githubusercontent.com/538025/50027953-48c28c00-ffab-11e8-9580-d0da7249f236.gif)

**Comment by jamesmontemagno** [comment]
@hartez do you have some extension installed? I am on 15.9.4 and Xamarin.Forms 3.4.X

![nointellisense](https://user-images.githubusercontent.com/1676321/50037646-9d283480-ffc8-11e8-97f3-b608f3aff4bb.gif)

**Comment by jamesmontemagno** [comment]
I am also seeing that on Android any of the "Application" ones are missing too.

**Comment by jamesmontemagno** [comment]
Any update on the Tabs stuff? I think we got some of them done?

**Comment by StephaneDelcroix** [comment]
//cc @mgoertz-msft

**Comment by hartez** [comment]
My bad, I thought I'd added these notes a while ago. Anyway ...

For the Platform Specifics which don't show up in Intellisense (and get squiggles):

The problem is that some of them (the ones that don't work) have overloads, and it confuses Intellisense.

So `IsSmoothScrollEnabled` works because the two methods are:

```
public static bool GetIsSmoothScrollEnabled(BindableObject element);
```

and 

```
public static bool IsSmoothScrollEnabled(this IPlatformElementConfiguration<Android, Forms.TabbedPage> config);
```

The attached property Intellisense follows the pattern for the getter (Get[PropertyName]) and finds the first method. No problem.

The ones that _don't_ work look like this:

```
public static Color GetBarSelectedItemColor(this IPlatformElementConfiguration<Android, Forms.TabbedPage> config);
```

and

```
public static Color GetBarSelectedItemColor(BindableObject element);
```

It follows the name pattern, but there are two matching methods. So it gives up/gets confused and decides it can't find the "property" on that type.

So one fix that works (I've tested this) - just rename the extension methods (the ones with `this IPlatformElementConfiguration`) so they don't conflict. But they're public methods, so we _can't_ just rename them. 

I _think_ we _could_ work around this by creating new methods, obsoleting the old ones, and marking the old ones with `EditorBrowsable.Never`; 

If not, maybe there's some other kind of attribute we can decorate the correct methods with so that Intellisense can find them.

**Comment by mgoertz-msft** [comment]
The dark themed screenshots look like the IntelliSense is coming from Resharper - ours doesn't actually have help tooltips for completion items.

**Comment by jfversluis** [comment]
Hope this is long resolved by now!

**Comment by jfversluis** [comment]
Else just get GitHub Copilot to write it for you 🤷
