### ISSUE TITLE
[Previewer] Errors running Previewer with 4.0 features

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4741]
### Description
When trying to preview a XAML page using `Visual` I get an error about the SetFlag not being set.

<img width="1217" alt="screenshot 2018-12-14 11 52 57" src="https://user-images.githubusercontent.com/41873/50019364-ffb50c80-ff97-11e8-9d43-fcd75ea1966d.png">

When trying to preview a XAML page using `CollectionView` I get an error about ItemsView ctor.

<img width="527" alt="screenshot 2018-12-14 11 57 01" src="https://user-images.githubusercontent.com/41873/50019408-2a06ca00-ff98-11e8-85b1-ff18063e0017.png">

### Basic Information

- Version with issue:  4.0.1.33101, 4.0.0.8055-pre1
- IDE: VS Mac 8.0

### Reproduction Link

https://github.com/PureWeen/VisualTesting

https://github.com/hartez/TeamBuilderDemo

> VS bug [#752072](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/752072)

**Comment by adrianknight89** [comment]
@davidortinau @hartez I was just going to file a bug similar to this. I have run into the same `SetFlags` issue with `CollectionView`. For me, the problem was the presence of the fast renderers experimental flag along with the other one.

```
Forms.SetFlags("FastRenderers_Experimental");
Forms.SetFlags("CollectionView_Experimental");
```

This blows up for some reason. The workaround was to swap the order of statements so `CollectionView` gets turned on first.

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '4.0.0' that is not in the list of supported values

**Comment by samhouts** [comment]
This was fixed in Visual Studio 2019 Preview 3.
