### ISSUE TITLE
[Android] No method with name='setClipBounds' crash in ImageElementManager

### ISSUE THREAD

**Issue by velocitysystems** [xamarin/Xamarin.Forms#4789]
### Description

Crash `Java.Lang.LinkageError: no method with name='setClipBounds'` on Android 4.1/4.2.
`ClipBounds` property on the `ImageView` is set _without_ an API check for >= API 18.
https://github.com/xamarin/Xamarin.Forms/blob/27f83582e9493c02058875deb7ca3d47e3b65e42/Xamarin.Forms.Platform.Android/FastRenderers/ImageElementManager.cs#L23

**ClipBounds** property was added in API Level 18.
https://developer.xamarin.com/api/property/Android.Views.View.ClipBounds/

This change was introduced with #4218 in the fast `ImageRenderer` and recently moved to `ImageElementManager`.

### Steps to Reproduce

1. Enable fast renderers on the application.
2. Use a `Xamarin.Forms.Image` control.

### Expected Behavior
App should not crash.

### Actual Behavior
App crash on an Android 4.1/4.2 device.

### Basic Information

- Version with issue: XF 3.4.0
- Last known good version: XF 3.3.0 (introduced in XF 3.3.0 SR1)
- Affected Devices: Android 4.1/4.2

### Suggestion
- Can we use the `ViewCompat` method available [here](https://android.googlesource.com/platform/frameworks/support/+/e5f75a851fbee9fbf1de31c738577fd86861a101/compat/java/android/support/v4/view/ViewCompat.java#1547) in Android.Support.V4.View?
```

**Comment by pauldipietro** [comment]
We no longer support any APIs below 19, so this will be closed.

**Comment by velocitysystems** [comment]
@pauldipietro This is a huge problem for us, I mean a **massive** problem.
Our team have used XF for a very large scale app and we have tens of thousands of devices we still support on Android 4.1-4.3.

Where was this officially announced? Why was no notice given?

**Comment by pauldipietro** [comment]
I'm sorry that you're affected by this. If the fix ends up being simple and definitively does not break anything else, then perhaps we can make an exception, but we recently made this change and plan to stick to it. I should clarify that when I say that "we no longer support" APIs below 19, we are not actively making fixes for those versions, which is why we didn't make any sort of big announcement regarding this. Apps as they exist may still run, or they may not, depending on what functionality is being used.

The reality is that global marketshare of devices running below API 19 is extremely low at this point, and there are issues that come into consideration when continuing to support such old versions. For example, RTL support requires at least API 17, but there are others. Another major factor we took into consideration is that Xamarin.Essentials doesn't support anything below API 19, and our long term goal is to remain in parity with it so as to not cause confusion for our users.

We can discuss adding this fix internally, but I do not wish to set a precedent.

**Comment by velocitysystems** [comment]
@pauldipietro Thank you so much, let me reach out to you directly.

**Comment by velocitysystems** [comment]
@pauldipietro `Android.Support.V4.View.ViewCompat` fix could be used here e.g.:

```
using Android.Support.V4.View;

protected override void OnLayout(bool changed, int left, int top, int right, int bottom)
{
    base.OnLayout(changed, left, top, right, bottom);
    ViewCompat.SetClipBounds(this, GetScaleType() == ScaleType.CenterCrop ? new Rect(0, 0, right - left, bottom - top) : null);
}
```

**Comment by velocitysystems** [comment]
@pauldipietro Looks like `ViewCompat.SetClipBounds` is just syntactic sugar for a conditional API check and a call to the original property.

_"Sets a rectangular area on this view to which the view will be clipped when it is drawn. Setting the value to null will remove the clip bounds and the view will draw normally, using its full bounds. Prior to API 18 this does nothing."_

https://developer.android.com/reference/android/support/v4/view/ViewCompat.html#setClipBounds(android.view.View,%20android.graphics.Rect)

It seems you would have to implement `SetClipBounds` for the method (perhaps in an extension method) to work correctly on <API 18 ie. See Java example [here](https://stackoverflow.com/questions/18724976/can-setclipbounds-be-called-on-a-view-before-it-has-been-drawn).

If a non-breaking fix was to be made for this in the XF 3.x branch, I would probably recommend going ahead with Stephane's proposed change. While AspectFill behaviour will be broken, it won't crash on <API 18 when using fast renderers.
