### ISSUE TITLE
[Android] ObjectDisposedException in LabelRenderer

### ISSUE THREAD

**Issue by velocitysystems** [xamarin/Xamarin.Forms#4864]
### Description
`System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Android.Text.SpannableString'`.

Stack Trace:
```
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
SpannableStringInternal.ToString ()
TextViewExtensions.RecalculateSpanPositions (Android.Widget.TextView textView, Xamarin.Forms.Label element, Android.Text.SpannableString spannableString, Xamarin.Forms.SizeRequest finalSize)
LabelRenderer.OnLayout (System.Boolean changed, System.Int32 left, System.Int32 top, System.Int32 right, System.Int32 bottom)
View.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean changed, System.Int32 left, System.Int32 top, System.Int32 right, System.Int32 bottom)
(wrapper dynamic-method) System.Object.49(intptr,intptr,bool,int,int,int,int)
```

### Steps to Reproduce

1. Use a `Label` inside a ViewCell `DataTemplate` for a ListView.
2. Add 10 or more rows of data.
3. Rotate the device between portrait and landscape.

### Expected Behavior
App should not crash.

### Actual Behavior
App crash on an Android 6.0/7.0/8.0 devices.
Affects both the standard and fast-renderer versions.

### Basic Information

- Version with issue: XF 3.4.0
- Last known good version: XF 3.1.x
- Affected Devices: Android

Note: I believe the issue may have been introduced in this PR https://github.com/xamarin/Xamarin.Forms/pull/2173/

**Comment by 1Cor125** [comment]
I am seeing this on pre-Oreo including 6.0 and 7.x devices. Also, *_truncation is not a factor_* in the views where this is crashing.

**Comment by velocitysystems** [comment]
@1Cor125 @pauldipietro Thanks for the feedback, I have updated the ticket accordingly.

**Comment by velocitysystems** [comment]
I was just wondering if @adamped you have any thoughts on this? It seems that keeping a reference to the `SpannableString` (in a private field) and accessing it in the `OnLayout` method is leading to the `ObjectDisposedException`.

https://github.com/xamarin/Xamarin.Forms/blob/8f3804de4dc63d41ef9687cfa38bff8238c5743a/Xamarin.Forms.Platform.Android/Renderers/LabelRenderer.cs#L248

Previously before #2173, a reference was not being kept and this problem didn't happen.
I'm very keen to get a fix in for this as we can't QA a production release due to this bug.

**Comment by adamped** [comment]
Unfortunately this is another never ending whack-a-mole situation with Android renderers disposing objects. 

But to solve this particular one, due to the heavy usage of SpannableString in here: https://github.com/xamarin/Xamarin.Forms/blob/1f23022d920a7529ea2c180eb3ef13605e3428f4/Xamarin.Forms.Platform.Android/Extensions/TextViewExtensions.cs#L75

That could be disposed of at anytime, would be to make a clone of it, inside the function, after a null check, then use that one in the function.

Cloning of course comes with some minor perf loss and memory consumption. However, doing a null / disposed check at every point where SpannableString is used, might also cause a perf loss, but at least no additional memory consumption.

Ideally the team should look at locking that OnLayout, Binding and Gesture Triggers with a dispose, to stop these never ending errors :) But that would take a larger effort and some design work by the team to accomplish (it's not a simple effort), vs a quicker fix here of null checking for this particular issue.

**Comment by velocitysystems** [comment]
Thanks for your thoughts and feedback @adamped.
I'm just testing [this fix](https://github.com/velocitysystems/Xamarin.Forms/commit/52343cb6da26bea6dea0af15e8d5a1ff4bbcabe7#diff-fdec73b1ec21d98ada9ca7cbbff66bd2).

I'm seeing if a single null/disposed check inside the extension method will suffice before examining the cloning option you suggest. Agree with the concept of locking critical methods like `OnLayout`, this would definitely reduce the likelihood of these problems.

Do you have any thoughts on how we could remove the mutable object reference `_spannableString`? I'm always concerned about holding references to mutable objects, especially Android native ones which sit on the delicate 'balancing bridge' between the Android and Mono runtimes and their respective GC cycles.

**Comment by adamped** [comment]
It needed that reference, because you couldn't get it back out of the TextView once you set it. If you can find a way to extract the SpannableString back out of the TextView when required, then you could remove that variable.

**Comment by velocitysystems** [comment]
@adamped Thanks so much. We've verified the fix did the job nicely and have done extensive testing on a range of Android devices from 4.1 to 8.0 (we're using a custom XF 3.4 build until fix is merged).

PR has been created. #4878
