### ISSUE TITLE
[Android] WebView Navigating Cancel property not working with custom scheme

### ISSUE THREAD

**Issue by kensykora** [xamarin/Xamarin.Forms#4891]
### Description

We utilize custom URL schemes heavily within our app for app communication with an external website's javascript, so that the website can invoke behavior in-app and vice versa.

Since Xamarin Forms 3.3.0, the `Navigating`/`Navigated` event behavior has changed such that this is broken due to several issues found.

This is a very similar issue to #4223 but is different because their issue is occurring on first load, not on navigation events.

### Steps to Reproduce

See example repository. This same code was tested and working with 3.2.0, and when updating to 3.3.0, behavior is broken

1. Create a WebView - https://github.com/kensykora/xamarin-forms-4223/blob/master/XamarinFormsIssue_4223/MainPage.xaml
2. Bind the `WebView`'s starting content to some HTML that contains a link to a custom URL scheme. - https://github.com/kensykora/xamarin-forms-4223/blob/master/XamarinFormsIssue_4223/MainPage.xaml.cs#L20-L23
2. Bind events to `Navigating` / `Navigated`. In the `Navigating` event, look for a custom scheme and cancel the request if navigation occurs with the custom scheme, such that you can intercept the URL and perform some behavior in-app. https://github.com/kensykora/xamarin-forms-4223/blob/master/XamarinFormsIssue_4223/MainPage.xaml.cs#L26-L35
4. Run the app
5. Tap on the link with the custom scheme

### Expected Behavior

Navigation does not occur. App is able to get a `Navigating` callback and successfully cancel the event. If `Navigated` event does fire, the underlying webview does not actually navigate, since `Cancel` was invoked (in 3.2.0, `Navigated` does not fire)

### Actual Behavior

Sporadic: as you can see in the screen capture, 3 things occur incorrectly:

1) Webview shows android error saying it's an unknown scheme. A navigation does occur despite us trying to cancel it.
2) Multiple `Navigated` events (failure) occur. I would expect just 1, if trying to stay backwards compatible (which using semver, a minor version 3.2 -> 3.3 should!!!) there should be no `Navigated` events called to maintain backward compatibility
3) in some cases the underlying `WebView` seems to stop responding to taps.

### Basic Information

- Version with issue: 3.3.0.967583
- Last known good version: 3.2.0.871581
- IDE: Xamarin 
- Platform Target Frameworks:
  - Android: 8.1 (API 27)
- Android Support Library Version: 27.0.2.1
- Nuget Packages: none other than Xamarin Forms and Support Packages
- Affected Devices: Tested on a simulator, but observed on all android devices in another app

### Screenshots

3.2.0 Behavior - Working as expected:

![3 2 0-behavior](https://user-images.githubusercontent.com/64756/50653030-db709e00-0f4d-11e9-8f4e-3b20d9f4d199.gif)

3.3.0 Behavior - Broken

![3 3 0-behavior](https://user-images.githubusercontent.com/64756/50653069-f7743f80-0f4d-11e9-98b2-99fc53b0c787.gif)

### Reproduction Link

https://github.com/kensykora/xamarin-forms-4223

[XamForms4223-3.2.0.zip](https://github.com/xamarin/Xamarin.Forms/files/2724791/XamForms4223-3.2.0.zip)

[XamForms4223-3.3.0.zip](https://github.com/xamarin/Xamarin.Forms/files/2724795/XamForms4223-3.3.0.zip)

Edit: Clarified expectations to maintain backward compatibility

**Comment by PureWeen** [comment]
Probably broke with this commit

https://github.com/xamarin/Xamarin.Forms/commit/bd663038ba8fb48dec1b665a604ba0648b59d038#diff-f3d7621fa7540d1a5c137082353a3f51

**Comment by mjjames** [comment]
I have also hit this issue, do we know if there will be a work around or preview patch for this?

**Comment by brackert** [comment]
Same issue. 

In limited testing: 
On Android 8.0 it navigates to the page, completely ignoring the 'Cancel' set in the navigating event. 
On 9.0 it does NOT navigate to the page, however the 'Navigated' event occurs anyway.

**Comment by mpatel283** [comment]
Same issue here as well. The Cancel Property works on iOS however on API 25 to 28 the Cancel property doesn't work.

**Comment by brackert** [comment]
> Probably broke with this commit
> bd66303#diff-f3d7621fa7540d1a5c137082353a3f51

I spent a few hours investigating this bug and have a solution that also keeps the fix for the commit mentioned above. All changes are to class `FormsWebViewClient`.

Depending on the API version, Android's `StopLoading` does not work as expected/consistently which is used to cancel the load in `OnPageStarted`. This is why the commit above created this 'custom scheme' problem. 

In addition, Android's `ShouldOverrideUrlLoading` is NOT executed when the `WebView.Source` is explicitly set. This is why the commit above fixed the problem of `Navigating` not firing when the `Source` is set. However, in my opinion, `ShouldOverrideUrlLoading` should _always_ be used when possible to reliably cancel the load. That is it's main (sole?) purpose. 

Recommendation: Don't cancel `Navigating` when the `WebView.Source` is explicitly set. I recommend pre-checking the url before setting `Source`. This will eliminate the problems/inconsistencies introduced by `StopLoading`. In fairness, there may be exceptions that I'm not thinking of. 

In a day or 2, I will create a pull request for the fix. Or, if someone wants to submit it for me, great! (I'll send you the code, including a test class.)

Thanks

**Comment by kensykora** [comment]
Hey @brackert

> Recommendation: Don't cancel Navigating when the WebView.Source is explicitly set. 

Thanks for looking at this, VERY much looking forward to a fix so we can update our Xamarin Forms past 3.2

Just to be clear, in the code sample I provided in my original post, I am not canceling navigation when WebView.Source is explicitly set, only during subsequent navigations from that page.

Feel free to use my sample as a case for testing the fix.

**Comment by brackert** [comment]
@kensykora 

You're welcome!

> Feel free to use my sample as a case for testing the fix.

I _did_ use your code. Thanks! I added a few more tests as well. 

We've been using the custom scheme technique in various projects since the 90s. I have a couple of questions and thoughts on using custom schemes that I would like your thoughts on. My email is public on GitHub if you are interested.

**Comment by brackert** [comment]
> In a day or 2, I will create a pull request for the fix. Or, if someone wants to submit it for me, great! (I'll send you the code, including a test class.)

I forgot it's Friday when I wrote this. I'll probably get to this on Monday. :)
