### ISSUE TITLE
[WPF] Slider converts Value to minimum when minimum is greater than zero

### ISSUE THREAD

**Issue by senbeiwabaka** [xamarin/Xamarin.Forms#4902]
### Description
As a developer, if I set the minimum value of a slider to anything other than 0, Xamarin.WPF will set the value to the minimum value.

### Steps to Reproduce

1. Set Minimum to 8 
2. Set Maximum to any number greater than 8
3. Bind Value to a property
4. Set property value to a value greater than 8 but less than Maximum

### Expected Behavior
Value should be what you set it to.

### Actual Behavior
Value gets set to minimum.

### Basic Information

- Version with issue: 3.4.X
- Last known good version: N/A
- IDE: Visual Studio 2017 15.9.4
- Platform Target Frameworks: 
  - WPF:  3.4
- Nuget Packages: Xamarin.Forms, Xamarin.Platforms.WPF
- Affected Devices: Windows?

**Comment by krdmllr** [comment]
I looked into this and the order of the update value calls in the renderer 

```
UpdateMinimum();
UpdateMaximum();
UpdateValue();
```
**Issue**

I logged every call and when HandleValueChanged is rised:
```
UpdateMinimum (10)
HandleValueChanged (10)
UpdateValue (10)
UpdateMaximum (20)
UpdateValue (10)
```

So the initial `HandleValueChanged` event seems to set the Value which causes the bug.

**Solution:**

I found two solutions, first is to change the order of the initial updates because this triggers a second `HandleValueChanged` which corrects the value. 

Fix:
```
UpdateValue();
UpdateMinimum();
UpdateMaximum();
```

Calls
```
UpdateValue (18)
HandleValueChanged (10)  <--- ???? why is it doing this ?!
UpdateValue (10)
UpdateMinimum (10)
UpdateMaximum (20)
HandleValueChanged (18)
UpdateValue (18)
```

This seems a bit random because the initial `HandleValueChanged` is still called with the min value which was never set and we are "lucky" that it is raised a second time by the initial `UpdateValue`. 

The second solution is to set the values in the constructor of the native view. This does not trigger the `HandleValueChanged` at all somehow.

The downside of this is that changing the "Element" value would trigger the update calls in the wrong order which would overwrite the value if the **old** value is out of the **new** min/max range.

I created a PR #7959 based on this, which combines both solutions:
- Set the initial values in the constructor
- Changes the order in case the element gets set again

The pr contains a repro sample for the control gallery for testing.

**Comment by charlesroddie** [comment]
Do you have an argument that your combination of methods works in all situations?

This behaviour is buggy across all platforms and I suspect it needs a fix to Xamarin.Forms. I suggested a fix here: https://github.com/xamarin/Xamarin.Forms/issues/1943#issuecomment-431508922

**Comment by krdmllr** [comment]
@charlesroddie this fixes that the value from the Xamarin.Forms core view is correctly set in the renderer, it does not change how the min/max/value is validated which is all done in the core view. I think the issue you references needs to be implemented in the core view in the first place, right?

**Comment by charlesroddie** [comment]
Yes although it looks like order of updates is a common theme. Are you able to give an argument or confirmation that with any possible values of XFMin <= XFValue <= XFMax (less than or greater than the initial defaults), the WPF control both does not crash and ends up with the right values?

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
