### ISSUE TITLE
Support dynamic height resizing of ViewCells

### ISSUE THREAD

**Issue by hulluP** [xamarin/Xamarin.Forms#4905]
### Description
ForceUpdateSize slows UI on iOS and disables the keyboard

### Steps to Reproduce

1. Create page with a TableView
2. Change Cell height on Unfocused event, and call ForceUpdateSize afterwards
After 3-4 taps on the same cell the UI starts to slow down, eventually almost freezes

## in the added example
1. click on plus several times to add user
2. add random letters for the first name
3. tab out by selecting the last name of the same user
4. try typing with on screen keyboard. after each click the keyboard disappears
5. repeating steps 2 -4 will slow down the whole ui

### Expected Behavior
UI should be fluent and keyboard should behave like it does when ForceUpdateSize is commented out.
### Actual Behavior
UI is becomes non responsive
### Basic Information
very similar to the bug https://github.com/xamarin/Xamarin.Forms/issues/2735 may be related what is happening in listview as well

- Version with issue: 3.4.0
- Last known good version: looks like this never worked
- IDE: Mac Visual Studio
- Platform Target Frameworks: 
  - iOS:  11 +
  - Android: seems to work fine

- Nuget Packages: Xamarin.forms
- Affected Devices:

### Reproduction Link
[tableViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/2729399/tableViewBug.zip)

**Comment by kingces95** [comment]
Yeah, ListView is not designed/tested for dynamically changing the row heights. Not to say it shouldn't, but that's the story. That said, I've followed your bread crumbs around the interwebs and wonder if you've tried https://stackoverflow.com/questions/48183532/forceupdatesize-listview-issue-on-ios. Short of that, I'll file this under enhancement because, well, from the design perspective of ListView, that's what this is. And we're blocking all ListView features on the upcoming release of CollectionView. Should that SO work around not work for you let us know and we'll try another because honestly, I doubt we'd support dynamic updating of cells in ListView. @hartez might be more optimistic.

**Comment by hulluP** [comment]
Update: I tried " https://stackoverflow.com/questions/48183532/forceupdatesize-listview-issue-on-ios. " and this solves the performance and the issue the entry boxes have under iOS.
But I only need to run this on iOS on Android the code as uploaded works fine.

**Comment by adrianknight89** [comment]
> And we're blocking all ListView features on the upcoming release of CollectionView

Let's just hope CV does not suffer from this problem.

**Comment by knightmeister** [comment]
+1 on this, causing me issues with dynamic cell height resizing on iOS

**Comment by SaskiaL** [comment]
In my case the listview has labels per item for the status of that item. This status is not filled at first. After setting the status using the bindable field, the height is not changed and the status overlaps the entry of the next item.

Using a ColectionView in stead of a ListView is unfortunately not possible since the CollectionView has a bug on iOS with the soft keyboard overlapping entries on the bottom of the list and the list cannot be scrolled high enough to show the entry. This is an even bigger problem since users cannot see what they are entering.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
