### ISSUE TITLE
[CollectionView] The Horizontal Grid test layout looks different on iOS vs Android

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#4936]
### Description
https://github.com/xamarin/Xamarin.Forms/pull/4414#issuecomment-452399726

The Horizontal Grid test layout looks different on iOS vs Android. 

![image](https://user-images.githubusercontent.com/5375137/50850481-35e77100-1337-11e9-93e8-8e54e46557ab.png)

possibly related
https://github.com/xamarin/Xamarin.Forms/issues/4406

**Comment by hartez** [comment]
This is no longer an issue on the latest of the 3.5.0 branch.

**Comment by hartez** [comment]
@PureWeen that DataTemplate has the images set to AspectFit (the default); the images look different because you're on devices with different vertical resolutions (which means different grid row sizes, which means the images size differently). Nothing to do with the platforms. Here are two iPhone sizes side-by-side:

![2019-02-01_13-13-53](https://user-images.githubusercontent.com/538025/52147256-5c8d8480-2623-11e9-93cd-8c93e3720d1d.png)
