### ISSUE TITLE
[iOS] CollectionView alignment when using Grid

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#5019]
### Description
When writting some UITests for position of items using CollectionView grid horizontal mode, seems that using the default text of a item (no template) the item in the 2nd row isn't fully aligned.

Test failing on iOS : https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=234060

AppCenter test run iOS12 : https://appcenter.ms/orgs/xtc-Xamarin-Forms/apps/XamControl/test/series/pull-4697/runs/f8e90aab-d973-4d1f-aa4d-d9c5dee6ae17

### Steps to Reproduce

1. Run the 3.5.0 branch and visit the Default Text (Grid) Gallery
2. Check the alignment of the 1st items of each row
3. the item on the 2nd row doesn't start and X=0

### Expected Behavior

Item should be align left no margin

### Actual Behavior

Item has a 3 pixel margin from the left edge

### Basic Information

- Version with issue: 3.5.0
- Platform Target Frameworks: 
  - iOS: 

### Screenshots

![simulator screen shot - iphone xs max - 2019-01-18 at 18 38 41](https://user-images.githubusercontent.com/1235097/51406231-6ce82e80-1b50-11e9-9acd-a669fa1ee85f.png)

### Reproduction Link

https://github.com/xamarin/Xamarin.Forms/pull/4697/files#diff-cc0239ff3cfcc0116d0fca2ce481a6cdR150

**Comment by hartez** [comment]
So this is happening because the strings in the labels have different lengths. The default cell (used when the user does not specify an ItemTemplate) just contains a UILabel with the text set to the ToString() method of the item. So each UILabel is a different size, and the edges of the UILabels don't line up.

If you change the `ToString()` override of `CollectionViewGalleryTestItem` to emit the same string every time, you'll see the edges line up. Or you can set the `ItemSizingStrategy` to `MeasureFirstItem` (though that will cause a different layout issue).
