### ISSUE TITLE
Xamarin.Forms 4.0 Pre2 CollectionView.EmptyView cannot arrange content in center.

### ISSUE THREAD

**Issue by mayurprasad** [xamarin/Xamarin.Forms#5041]
### Steps to Reproduce

1. Create a project with Xamarin.Forms 4.0 Pre2
2. Add a page with an empty CollectionView with a label in the CollectionView.EmptyView
3. Run on Android

### Expected Behavior
Should be able to arrange CollectionView.EmptyView content in center.
### Actual Behavior
Not able to arrange CollectionView.EmptyView content in center.
### Basic Information

- Version with issue: 4.0 Pre2
- Last known good version: never
- IDE: VS 2017 Windows
- Platform Target Frameworks: 
  - Android: 8.1

**Comment by samhouts** [comment]
[Issue5041.zip](https://github.com/xamarin/Xamarin.Forms/files/2793758/Issue5041.zip)

Confirmed; without a layout, the Label doesn't center.

**Comment by mayurprasad** [comment]
> 
> 
> [Issue5041.zip](https://github.com/xamarin/Xamarin.Forms/files/2793758/Issue5041.zip)
> 
> Confirmed; without a layout, the Label doesn't center.

Yes, but for that we have to set VerticalOptions="CenterAndExpand". But what if i want to use Image and Label both or multiple contols.

**Comment by hartez** [comment]
The issue is not The issue is not that your Label is not centered; it's that your Label is filling up the entire EmptyView. Try setting your Label's `BackgroundColor` property and you will see what I mean.

If you just want the Label's text to be centered, you can set the Label's HorizontalTextAlignment and VerticalTextAlignment properties to "Center":

```
<CollectionView>
    <CollectionView.EmptyView>
        <Label Text="Welcome to Xamarin.Forms!" HorizontalTextAlignment="Center" VerticalTextAlignment="Center" BackgroundColor="Green" />
    </CollectionView.EmptyView>
</CollectionView>
```

Because the Label is the entire EmptyView, the Label will fill up the space inside the CollectionView and the text will be centered vertically and horizontally inside the Label.

If you want the Label to behave as if you had added it to a ContentPage, you'll need to put it into some kind of layout; for example, a ContentView:

```
<CollectionView>
    <CollectionView.EmptyView>
            <ContentView>
                <Label Text="Welcome to Xamarin.Forms!" HorizontalOptions="Center" VerticalOptions="CenterAndExpand" BackgroundColor="Green" />
            </ContentView>
        </CollectionView.EmptyView>
</CollectionView>
```
