### ISSUE TITLE
After calling TranslateTo function Grid loses gesture recognition area.

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#5163]
### Description
When I move a Grid, it loses the ability to recognize gestures.

I made the application, you may find that the buttons on the first screen are pressed normally.
But when I start moving the grid, the buttons are no longer pressed.

### Steps to Reproduce
1. Create grid
2. Call TranslateTo
3. make sure that the buttons do not respond to pressing.
4. Check my project

### Expected Behavior
The buttons must be pressed. Gestures do work.

### Actual Behavior
Buttons do not press. Gestures do not work.

### Basic Information

- Version with issue: 3.4, 3.5, 4
- Last known good version:
- IDE: VS 2019, VS 2017
- Platform Target Frameworks: All

### Reproduction Link

[GridBug.zip](https://github.com/xamarin/Xamarin.Forms/files/2842221/GridBug.zip)

**Comment by KSemenenko** [comment]
@andreinitescu Maybe you know what's going on here?

**Comment by andreinitescu** [comment]
Sure, I can try help. I haven't looked very much into it for the root cause of the issue, but here's a workaround when sliding to 2nd StackLayout:

        private async void ShowSecond()
        {
            currintPanel = 2;
            var x = Width * -1;
            await RootGrid.TranslateTo(x, 0, 500U, Easing.CubicIn);

            Panel1.Width = 0;
            await RootGrid.TranslateTo(0, 0, 0, Easing.CubicIn);
        }

Other better ideas: You could also try animating the width of the first StackLayout to zero, Even better, try use maybe a ScrollView, which could be much better.
You could also try debug the root cause of the issue in the framework.

**Comment by KSemenenko** [comment]
it's not about animating the width or scrollview. Problem is that if you move the grid, it loses the ability to receive touch events. and this is a bug in the platform.

**Comment by KSemenenko** [comment]
@samhouts Maybe you can help us?

**Comment by AndreiMisiukevich** [comment]
@KSemenenko Hi, don't think, that it is related to animations.
Seems, it is bug in your code - You move columns out of grid's bounds

Try to set IsClippedToBounds = false for all grids and click right/left -- you will se white screen (i presume, there is no bug in XF.)

How about to change your markup? You may use CarouselView or just AbsoluteLayout and manage columns positions with TranslateX props or something else.. ?

**Comment by KSemenenko** [comment]
@AndreiMisiukevich width is another thing. It is interesting to me exactly why Grid loses the ability to recognize gestures.

**Comment by AndreiMisiukevich** [comment]
@KSemenenko I have already replied :)

Look: your grid has any width (375 for example).
Every column has width equal grid's one (every one is 375 as well). In total your two columns are OUT of the grid, because the first one occupies all available space (all grid's size!). 

When you shift your grid to any side, you also shift touch area (because it is the same thing as control size). You still see your all other columns, because IsClippedToBounds property is false by default.

Does it make sense ?

**Comment by andreinitescu** [comment]
@KSemenenko I took another look at your code, here's something you could try:

        protected override void OnSizeAllocated(double width, double height)
        {
            base.OnSizeAllocated(width, height);
            if (Panel1.Width.Value != width)
            {
                Panel1.Width = width;
                Panel2.Width = width;
                Panel3.Width = width;

                var b = RootGrid.Bounds;
                RootGrid.Layout(new Rectangle(b.Left, b.Top, width * 3, height - b.Top));
                RootGrid.TranslationX = -(currintPanel - 1) * width;
            }
        }

**Comment by samhouts** [comment]
Hi! If you're still looking for assistance, try https://forums.xamarin.com/categories/xamarin-forms. Thanks!
