### ISSUE TITLE
Strings containing `{` needs to be escaped. Start the string with `{}`

### ISSUE THREAD

**Issue by stevehurcombe** [xamarin/Xamarin.Forms#5282]
### Description
I'm getting a new syntax error in my XAML.

Strings containing `{` needs to be escaped. Start the string with `{}`

The offending line of code is:

```
<Label class="RadioText" Text="{Binding PocketEmail, StringFormat='You are are connected to Pocket as {0}'}"></Label>
```

### Basic Information

- Version with issue:
4.0.0.135214-pre4
- Last known good version:
4.0.0.94569-pre3
- IDE:
Visual Studio 2017 15.9.4

**Comment by PureWeen** [comment]
Duplicate https://github.com/xamarin/Xamarin.Forms/issues/5152 
Fixed in pre5

**Comment by ianvink** [comment]
Occurs in 3.6.* as well.

**Comment by francis2** [comment]
It may be fixed in pre5 of #5152 (FormsGallery) but it is still broken in Xamarin.forms.pre4 and above for me. None of the solutions above worked. Compiler even removed my extra {}. I just reverted to 3.5 so I could continue working.

None of these worked.
<Label Margin="{StaticResource ListViewMargin}" Text="{Binding Price, StringFormat='{0:C2}'}" />
<Label Margin="{StaticResource ListViewMargin}" Text="{Binding Price, StringFormat='{}{0:C2}'}" />
<Label Margin="{StaticResource ListViewMargin}" Text="{Binding Price, StringFormat={}'{0:C2}'}" />

**Comment by francis2** [comment]
I found a format that works with Forms pre5: a space is required between the bracket pairs. It would save programmers around the world a lot of hair if the error message said that instead of _Strings containing `{` needs to be escaped_  ;-)

**`StringFormat='{} {0:C2}'`**

**Comment by melucas** [comment]
@francis2 that works!  Thank you.

**Comment by dansiegel** [comment]
I actually encountered this very issue recently. I found it to be a very easy work around to just add it as a resource and reference it like this:

```xml
<ContentPage.Resources>
  <ResourceDictionary>
    <x:String x:Key="myFormat">{0:C2}</x:String>
  </ResourceDictionary>
</ContentPage.Resources>
<Label Text="{Binding Foo,StringFormat={StaticResource myFormat}}" />
