### ISSUE TITLE
Crash assigning excessively long text to Editor with MaxLength property set

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#5367]
### Description

When you have an Editor control with a MaxLength set, and you assign it text longer than the MaxLength, it will crash.

### Steps to Reproduce

1. Have an Editor in a page, with MaxLength=500
2. Assign it a 1000 character string after initialization
3. Observe the crash

### Expected Behavior

No crash.

### Actual Behavior

```
Unhandled Exception:
Java.Lang.IndexOutOfBoundsException: setSpan (1000 ... 1000) ends beyond length 500

 	0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#
 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException	C#
 	0x20 in object.39	C#
 	0x12 in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw	C#
 	0x89 in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod	C#
 	0x5F in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod	C#
 	0x29 in Android.Widget.EditText.SetSelection	C#
 	0x41 in Xamarin.Forms.Platform.Android.EditorRenderer.UpdateText at D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\EditorRenderer.cs:200,4	C#
 	0x18 in Xamarin.Forms.Platform.Android.EditorRenderer.OnElementPropertyChanged at D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\EditorRenderer.cs:100,5	C#
 	0x12 in Xamarin.Forms.BindableObject.OnPropertyChanged at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:173,7	C#
 	0x2 in Xamarin.Forms.Element.OnPropertyChanged at D:\a\1\s\Xamarin.Forms.Core\Element.cs:339,4	C#
 	0x11B in Xamarin.Forms.BindableObject.SetValueActual at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:622,5	C#
 	0x164 in Xamarin.Forms.BindableObject.SetValueCore at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:422,5	C#
 	0x227 in Xamarin.Forms.BindingExpression.ApplyCore at D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:167,5	C#
 	0x48 in Xamarin.Forms.BindingExpression.Apply at D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:57,5	C#
 	0x7 in Xamarin.Forms.BindingExpression.BindingExpressionPart.<PropertyChanged>b__49_0 at D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:618,42	C#
 	0xE in Java.Lang.Thread.RunnableImplementor.Run	C#
 	0xA in Java.Lang.IRunnableInvoker.n_Run	C#
 	0x11 in object.39	C#
```

### Basic Information

- Version with issue: 3.5.0.169047
- Last known good version: Unknown
- IDE: VS 2017
- Platform Target Frameworks: 
  - Android: 8.1
- Android Support Library Version: 28.0.0.1
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[XamarinFormsSample.zip](https://github.com/xamarin/Xamarin.Forms/files/2899323/XamarinFormsSample.zip)

**Comment by ckrempp91** [comment]
I have been encountering this issue as well, and after some investigation it seems that the call to the [`EditText.Text = newText`](https://github.com/xamarin/Xamarin.Forms/blob/341ddc758b1e8570433531230850883c70263ef9/Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs#L246) located within the EditorRenderer is not actually performing the update to the native controls Text property, and thus causing the `EditText.SetSelection(newText.Length)` call to fail.

I believe I have found a workaround, if you have a custom renderer and if you use this code before you call `base.OnElementChanged(e)`: 
`            if (EditText != null)
            {
                string newText = Element.Text ?? "";
                if (EditText.Text != newText)
                {
                    EditText.Text = newText;
                    EditText.SetSelection(Java.Lang.Math.Min(Control.Text.Length, newText.Length));
                }
            }`

This is a modified version of the [`UpdateText()`](https://github.com/xamarin/Xamarin.Forms/blob/341ddc758b1e8570433531230850883c70263ef9/Xamarin.Forms.Platform.Android/Renderers/EditorRenderer.cs#L239) function located within the EditorRenderer. With this code executing first it seems that app does not crash, but this does not solve the underlying problem. 

I imagine the real issue is that there is some improper caching of the EditText control because there is another problem where if you have a ScrollView with multiple Editors (having enough cells to allow for scrolling to occur) setting the first one to have a MaxLength of 5 and the last one with a MaxLength of 600. Scroll down and then back up, it is apparent that the first EditText control will now have a max length of 600 instead of the expected 5 when you attempt to enter some text with more than 5 characters.

**Comment by mfeingol** [comment]
This is still an issue in 4.0.0.482894.
