### ISSUE TITLE
[Previewer,iOS] Does not currently work with Visual="Material"

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#5396]
### Description
When you set Visual to Material
- it has no effect on VS Mac (android)
- on windows the Android previewer crashes with an exception. This most likely happens because the Android Material renderers wrap the Context with a *ContextThemeWrapper* which applies the material theme and that wrapper isn't compatible with previewer

### Steps to Reproduce
- update to the latest 3.6
- install Xamarin Forms Visual Material 3.6
- Setup a Button set to Material
```XAML
    <StackLayout>
        <!-- Place new controls here -->
        <Button Text="Welcome to Xamarin.Forms!" 
           HorizontalOptions="Center"
			Visual="Material"
           VerticalOptions="CenterAndExpand" />	
    </StackLayout>
```

### Expected Behavior
Components should renderer material version of controls

### Actual Behavior

- When you first load (without compile) it throws an exception 
- When you compile it renders

For Android it throws an exception because the resource Material is asking for can't be found. The material resources are compiled with the external dll

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Material.Android/Resources/values/styles.xml

My guess is that the resource files aren't copied to a place the previewer can use until you physically compile the application

I tested a variation of the ContextThemeWrapper and this is the line it crashes on 

https://github.com/xamarin/Xamarin.Forms/blob/visual_MaterialContextThemeWrapper/Xamarin.Forms.Material.Android/MaterialContextThemeWrapper.cs#L22

Because it's unable to load the resource. It has an ID for the resource but once the android system tries to load it it can't be found and throws an exception

Here's the crash from the previewer
```
[2019-03-07 22:45:10.5] ERROR: : The renderer encountered an error while rendering this file: Java.Lang.NullPointerException: Exception of type 'Java.Lang.NullPointerException' was thrown.
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <95c2d89012b84874addbfe6a6ffa1095>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.FinishCreateInstance (System.String constructorSignature, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0004f] in <95c2d89012b84874addbfe6a6ffa1095>:0 
  at Android.Support.Design.Button.MaterialButton..ctor (Android.Content.Context context) [0x0007a] in <b2fc8b4d821e403089b09dd7e80edb90>:0 
```

### Reproduction Link

[App72.zip](https://github.com/xamarin/Xamarin.Forms/files/2908004/App72.zip)

> VS bug [#802781](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/802781)

**Comment by TimBarham** [comment]
For the Android crash, we should probably update Forms to not crash in this scenario (at least when running in the Previewer). Going forward we should work on a mechanism to make the required stuff available to Forms when the project is not built.

**Comment by PureWeen** [comment]
@TimBarham 

Looks to be an upstream issue with XA design time builds and how it works with resources so this isn't something we can account for with forms.

**Comment by jonathanpeppers** [comment]
We discussed this in person.

The issue is how this code works: https://github.com/xamarin/xamarin-android/blob/d006fa832a8149aa9d5791bf9cc78425ca93799d/src/Mono.Android/Android.Runtime/ResourceIdManager.cs

If there is no build, then the Android head project won't have an assembly containing the code from `Resource.designer.cs`. Then Xamarin.Forms will use invalid Resource Ids--which will cause an exception on the Java side.

@garuma and I discussed how it could be solved, but did not come up with a good answer. Xamarin.Android could (should?) add a linker step to remove this `System.Reflection` code on startup. However, that doesn't even solve this problem because the linker only runs during a build.

@garuma can correct me if I'm wrong, but I think the plan was for the designer to somehow ship its own `UpdateIdValues()` method in an assembly and use the information from `R.txt`?

**Comment by garuma** [comment]
Correct.

We will attempt to initially do a proof of concept for the Forms Previewer case only[1] by implementing this method via the assembly we already have that contains the Forms/Android renderer and using the R.txt values we know about. Ultimately we would want to at least move said prototype into a Xamarin.Android location (likely `ResourceIdManager`) so that we don't have to maintain an extra assembly on our side for the general Android case.

Alternatively (or concurrently to the above), the linker or build-time processing idea can be researched on the Xamarin.Android front so that the reflection-based approach is removed (which should slightly improve startup time as well).

[1]  The problem is more general than Forms and affects any managed library with resources referenced by the main Android project
