### ISSUE TITLE
[Previewer] catch invalid markup

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/Xamarin.Forms#5508]
### Description
this xaml

```xaml
<Label Text="{Binding foo" />
```

is invalid, and fails, but as ti might happens while typing, the previewer should be able to recover from that.

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

> VS bug [#817668](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/817668)

**Comment by TimBarham** [comment]
BTW... The previewer will ignore `XamlParseExceptions`, so a simple fix for this would be to throw a `XamlParseException` rather than a `System.Exception`.

However... While that will prevent the previewer showing an error while typing, it doesn't help if the error exists during initial render. For that, we'd need Forms to do the usual "ignore error and pass it to ExceptionHandler" thing.

**Comment by drewgillies** [comment]
A partial fix thus far. Moves the throwing code downstream to `MarkupExpressionParser.cs` which does not have an available `HydrationContext` for handling the exception. I can change the type of Exception to XamlP{arseException, but it doesn't address your concern above, @TimBarham, so I'll look for a way to get a context reference to the throwing code, or to catch and rethrow in a scope that includes one.

**Comment by StephaneDelcroix** [comment]
@TimBarham even if the previewer ignore XPE, Create(xaml, true) will not returns a valid object tree...

**Comment by TimBarham** [comment]
@StephaneDelcroix ... hence my second paragraph 😄
