### ISSUE TITLE
Button Command does not fire in TitleView with Xamarin.Forms 4 pre-6

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#5554]
### Description
I can use a `Button` and `ImageButton` within `TitleView`, but only with the `Clicked` event. When using `Command` it doesn't fire.

**Works**
```
<Shell.TitleView>
        <StackLayout HorizontalOptions="End" VerticalOptions="Center" >
          <ImageButton Source="add_buyer" HorizontalOptions="End" Clicked="OnAddBuyer" 
        </StackLayout>
    </Shell.TitleView>
```
**Does not Work**
```
 <Shell.TitleView>
        <StackLayout HorizontalOptions="End" VerticalOptions="Center" >
          <ImageButton Source="add_buyer" HorizontalOptions="End" Command="{Binding AddBuyerButtonCommand}"/>
        </StackLayout>
    </Shell.TitleView>
```

- Version with issue:Xamarin.Forms 4.0.0.232914-pre6
- Last known good version:NA
- IDE:Visual Studio for Mac preview

**Comment by samhouts** [comment]
Hmm, this should have been covered by #3823. 

@HobDev Can you please provide a complete reproduction project showing this issue? Did this work before and is newly broken in pre6? Thanks!

**Comment by HobDev** [comment]
@samhouts  The fault is in my code. The Command in ViewModel had private `access specifier`. **Sorry**

**Comment by HobDev** [comment]
@samhouts  Later, while debugging on Android I find out that the issue is `Android` only. Attaching the sample project.
[TitleViewSample.zip](https://github.com/xamarin/Xamarin.Forms/files/2971955/TitleViewSample.zip)

**Comment by spruceDevelopment** [comment]
So I tested this and I guess it isn't issue with TitleView but with the **Button** alone.
Something got broke and no Button (neither in TitleView, CollectionView, StackLayout or ContentPage etc.) gets attached to Command on Android. Tested the same code on UWP and Command gets attached to Button.
So I'm pretty sure it touches also #5414 and both would be fixed when patch will be applied. 
I will try to fix this and create a pull request regarding both of them.

**Comment by spruceDevelopment** [comment]
@samhouts I need assistance from Xamarin or Mono member because I guess the issue is with the Android Runtime.
Reproducing of the real issue:
1. Download my fork
2. Run project Xamarin.Forms.ControlGallery.**Android**.csproj
3. Find case Github 5554
4. Set breakpoint at Xamarin.Forms.Core.BindingExpression.cs:354
5. Open Case 5554, breakpoint should trigger
6. You will see that the "property" object has wrong values ie: "CanRead is set to false"

7. Now run the project Xamarin.Forms.ControlGallery.**WindowsUniversal**.csproj and do 3-5 steps. 
8. "property" will have proper values ie: "CanRead set to true"

So there is something wrong with Xamarin.Android implementation of **TypeInfo.GetDeclaredProperty(string)**

**Comment by hartez** [comment]
> Hmm, this should have been covered by #3823.

This is a Shell.TitleView issue; I believe #3823 was just for the original TitleView.

**Comment by hartez** [comment]
Ah, here's the problem:

https://github.com/xamarin/Xamarin.Forms/blob/4.0.0/Xamarin.Forms.Platform.Android/Renderers/ShellToolbarTracker.cs#L389

The Button is binding to the Command just fine, but line 390 is setting the `Parent` property for the `TitleView`, which resets the `BindingContext` to `_shellContext.Shell`, rather than whatever it was previously (the view model, in this case).

**Comment by samhouts** [comment]
I tested with pre10, and this is now resolved! 🎉 Thanks!
