### ISSUE TITLE
In macOS Mojave, navigation bar title text is not centered.

### ISSUE THREAD

**Issue by zhuxinghan** [xamarin/Xamarin.Forms#5575]
### Steps to Reproduce

1. Create a Xamarin.Forms project which uses a NavigationPage and has a title.
2. Create a Xamarin.Mac project based on the previous project.
3. Run the project, and you will find that the title is not centered in Mojave but is centered in High Sierra or lower.

### Expected Behavior

Navigation title is centered like this image (captured in macOS High Sierra):
<img width="512" alt="屏幕快照 2019-03-15 下午2 31 03" src="https://user-images.githubusercontent.com/15711862/54412912-2e758700-472f-11e9-986f-c2d6768ee68f.png">

### Actual Behavior

Navigation title is not centered like this image (captured in macOS Mojave):
<img width="512" alt="屏幕快照 2019-03-15 下午2 34 14" src="https://user-images.githubusercontent.com/15711862/54413061-844a2f00-472f-11e9-914a-727b22db0ffe.png">

**Comment by TomomiSawako** [comment]
+1

**Comment by HankiDesign** [comment]
I haven't been able to run it under the debugger yet but the issue seems to be with the manual calculation of the title element:

https://github.com/xamarin/Xamarin.Forms/blob/f98c5563af3fd46c7d8baa09a53691d49bbf714e/Xamarin.Forms.Platform.MacOS/NativeToolbarTracker.cs#L333-L337

macOS 10.14 introduced a new property for the NSToolbar, called [centeredItemIdentifier](https://developer.apple.com/documentation/appkit/nstoolbar/2967178-centereditemidentifier?language=objc), which lets a single item be centered absolutely in the window. That could probably be used to fix the issue. 

I'll give it a try once I have my macOS development up and running again, in case the issue hasn't been fixed by then.
