### ISSUE TITLE
[CollectionView] CollectionView Expands to full screen with FlexLayout

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#5763]
### Description
I have developed a screen for an app. When FlexLayout is the Content of the ContentPage the CollectionView expand to whole screen. Whereas when StackLayout is the Content of the ContentPage  the CollectionView takes remaining space after adjusting all other views. 
### Steps to Reproduce
Run my sample and swap FlexLayout with StackLayout. 

### Basic Information

- Version with issue: Xamarin.Forms-pre7
- IDE: Visual Studio for Mac Preview

- Affected Devices: iOS and Android

### Reproduction Link

[MyApp.zip](https://github.com/xamarin/Xamarin.Forms/files/3025438/MyApp.zip)

**Comment by samhouts** [comment]
I think this is pretty consistent with our expectations. The CollectionView is meant to expand to its available vertical space. The StackLayout is meant to adjust the height of all items appropriately, so it effectively sets the height of its children. Thanks!

**Comment by HobDev** [comment]
> I think this is pretty consistent with our expectations. The CollectionView is meant to expand to its available vertical space. The StackLayout is meant to adjust the height of all items appropriately, so it effectively sets the height of its children. Thanks!

FlexLayout should also adjust the height of all items appropriately.  It is not doing so. The problem is with FlexLayout.

**Comment by MeikandaNayanar** [comment]
> I think this is pretty consistent with our expectations. The CollectionView is meant to expand to its available vertical space. The StackLayout is meant to adjust the height of all items appropriately, so it effectively sets the height of its children. Thanks!

Do we have any documentation stating this?. If so can you please update me the links? I don't see any information as you said in below documentation.
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/

**Comment by EvoPulseGaming** [comment]
CollectionView should only take up the space needed to display the items, if we want to take up the entire screen we would specify this as we do with everything else.

**Comment by nwikechisom** [comment]
This is still a bug in Xamarin.Forms 4.3 and has not been resolved. I used a StackLayout and Grid in the collection view and gave it a height yet I get a huge space I don't need from the CollectionView. The slider in the image below is supposed to be immediately after the collection View but I have this huge space. This is an urgent need for me. I have to deliver on this project soon.

![view](https://user-images.githubusercontent.com/26902155/70119204-0b4a8900-166a-11ea-9b74-d37b92576084.jpeg)

**Comment by BillyMartin1964** [comment]
This is extremely silly that you can't center a collectionview when you don't have enough items to fill the screen. Instead of saying it's designed that way... please fix it. How does anyone know ahead of time how may items the user will have. Ridiculous.

**Comment by Tuurash** [comment]
This seems to be a very effective workaround :)
https://stackoverflow.com/questions/65767461/xamarin-forms-adjusting-height-of-collectionview-to-be-minimum-size-to-fit-chi

**Comment by junaidp27** [comment]
A recommendation: In short, when displaying a collection that does not expand on the whole screen use `StackLayout`'s `BindableLayout`. Keep the collection minimal, and optimal, so it will only show a glimpse of the collection. Provide an option to expand this minimal collection that will show whole collection in its original form, display this using `CollectionView` on another page. But only use `CollectionView` when you desire to display collection on the whole page/screen.

`CollectionView` offers virtualization and optimizations on both iOS and Android, hence it does not calculate size of its children and expands to the whole page. Hence use `CollectionView` when you want to show large collection with complex layout or template. Like list of all records, entries or rows in your app.

Otherwise use `StackLayout`'s `BindableLayout` to show small minimal collection/list like predictions for search entry, autocomplete, etc.

Hope this helps.
