### ISSUE TITLE
[Android / Fast Renderer] Frame size gets corrupted when ListView is scrolled

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#5766]
### Description

If you put a `Frame` in a `ViewCell` and scroll the `ListView` up and down several times, you will notice that `Frame` size gets corrupted. This only happens when Fast Renderers are turned on.

### Steps to Reproduce

1. Run attachment
2. Scroll up and down several times
3. Observe that some frames have inaccurate lengths

### Reproduction Link

[App155.zip](https://github.com/xamarin/Xamarin.Forms/files/3025617/App155.zip)

**Comment by kingces95** [comment]
Huh. I see it corrupted w/o Fast Renderers too.

**Comment by kingces95** [comment]
Actually, we regressed the non-fast renderers. Worked on 3.6 (int pre template) but fails on 4.0.0.

**Comment by kingces95** [comment]
@paymicro The reproduction also fails for non-fast-renderers on 4.0.0. I tracked that regression down to change bf0733129dda78349c14d7cb6ae39cd61ebe2288. I think you fixed that in the 3.6.0 branch which is why knight reports it only happens on fast-renderers. Not sure why fast renderers broke but figure you've got more context on this bug. At least you'll know how to fix the non-fast-renderers, so gonna hand this off to you. 

![image](https://user-images.githubusercontent.com/4120386/55993079-e2dccd00-5c49-11e9-92a6-dea3d18963a3.png)

**Comment by adrianknight89** [comment]
@paymicro Do you expect to work on this anytime soon?
