### ISSUE TITLE
Xamarin Form Maps - Pins - Drag & Drop Functionality

### ISSUE THREAD

**Issue by pamela032709** [xamarin/Xamarin.Forms#5786]
### Description
I would like to know when this functionality will be available in xamarin forms maps. without using any platform renders or behaviors 

### Expected Behavior
Xmarin Forms Maps - pins- drag and drop all over the map with their annotations

### Actual Behavior
Pins drag and drop doesn't exist in the latest xamarin forms maps

**Comment by pamela032709** [comment]
any update on this feature?

**Comment by burrowj** [comment]
I have a question on this.  The ability to drop and drag pins and drop and draw polyline and polygons along with their events would seem an almost standard feature for a maps plugin for Xamarin Forms.  I was wondering if Microsoft could take on this task?  If resources are low then where do I go to recommend Microsoft dedicate more resources to this?  This lack of function means I will use Xamarin.Forms.GoogleMaps as it supports these features but I think this should be a Microsoft plugin

**Comment by pamela032709** [comment]
I been fighting on this for over 2 years . and they never listen.

Pamela Rios

**Comment by novreis** [comment]
I agree with Palmela, it is  time to have these features implemented and cannot understand why Microsoft Xamarin team does not do the job

**Comment by Stuart88** [comment]
Yep, this drag and drop issue is about to ruin a huge project for me. Most other Xamarin functionality issues could be overlooked, but this is a show stopper. Come on Microsoft, this isn't acceptable. You're _Microsoft_!

**Comment by LittleCornerDev** [comment]
Since this feature doesn't look like it's happening anytime soon, can someone on this thread point me to some resources to help me figure out how to do this with custom renderers?   I have seen a couple nuget extensions based solely on GoogleMaps, but Xamarin.Forms.Maps uses Apple Maps for iOS.  I haven't seen a draggable pin custom renderer for iOS.

I am new to app dev and unfortunately unfamiliar with both native platform methodologies, which is why I have been trying to leverage cross-platform features with Xamarin.Forms in the first place. 😕

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
