### ISSUE TITLE
[Shell] Adding Navigation.PushAsync to a Shell element causes a crash

### ISSUE THREAD

**Issue by Moltroon** [xamarin/Xamarin.Forms#5928]
### Description

If I add a Navigation.PushAsync to a Shell element, app crash with DrawLayout error

### Steps to Reproduce

Run my example

### Expected Behavior
Navigate to the shell

### Actual Behavior
Crash

### Basic Information

- Version with issue: Xamarin.Forms 4.0 pre8

### Reproduction Link
[ShellNavigationBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3084945/ShellNavigationBug.zip)

**Comment by samhouts** [comment]
@Moltroon We don't support multiple Shells at this time. May I ask what your use case is? Thanks!

**Comment by MaxenceSAUNIER** [comment]
Because I have 2 Shell type in my app. The first for follow operations and control them and the second is a big CRM to perform operations with a dynamic ShellMenu. So, my application have 2 functionnality for one client type.

I use 2 shell because it allows the separation of features and a customization environment for my users to prevent them from getting lost.

I have overcome the problem by overloading the back button and adding a menu to the right.

**Comment by PureWeen** [comment]
@MaxenceSAUNIER if we get this implemented would that be enough for you to condense down to one shell Type?

https://github.com/xamarin/Xamarin.Forms/issues/5232

**Comment by MaxenceSAUNIER** [comment]
Hum. Possible. Today, I need #5232 to hide Administrator menu. 
That would correct 2 problems concerning me

**Comment by PureWeen** [comment]
@MaxenceSAUNIER good to hear!! We should have a PR for IsVisible in the next couple/few weeks. We would like to get to a point where users never have to swap out the MainPage so just let us know the areas of Shell that make this difficult for you so we can get some enhancements together
