### ISSUE TITLE
Renderer not found exception occurs on Version 3.6.0

### ISSUE THREAD

**Issue by ArunSivaR** [xamarin/Xamarin.Forms#6019]
**Description:**
Renderer not found exception occurs after updated to version 3.6.0 when opening a custom date picker, which created by using custom renderers

**Basic Information:**
Tested Version: 3.6.0.344457
Works fine with version : 3.5.0.274416

**Replication procedure:**

- 1. Run the attached sample on andoir [PicerSample](https://drive.google.com/file/d/1UG83P6YdD7_z8uvxeR4d5iKcJmmZ01s4/view?usp=sharing)
- 2. Tap on the date picker, exception will occur

**Comment by PureWeen** [comment]
@ArunSivaR The exception has been removed in 4.0 (sorry about that) 

But there looks to still be a regression with how you are using the renderer since you're not allocating that to the view hierarchy at all

I'm not sure of a workaround for this off hand. I've assigned it to myself and I'll try to get this into a 4.0 SR

out of curiosity why are you removing the renderer and just using the view?

**Comment by ArunSivaR** [comment]
Hi @PureWeen 

Thank you for the response.

We have used the native view from the respective platform renderers and respective native view rendered in each platform layouts.
