### ISSUE TITLE
[Bug]Unable override SetTabIcon in CustomTabbedPageRenderer

### ISSUE THREAD

**Issue by o1298098** [xamarin/Xamarin.Forms#6088]
### Description
I had create a  CustomTabbedPageRenderer with a CustomTabLayout ,after update to 4.0.0 Pre Release 10, SetTabIcon can not be override any more.
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue: 4.0.0 Pre Release 10
- Last known good version:4.0.0 Pre Release 8
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by GalaxiaGuy** [comment]
The last commit on `TabbedPageRenderer` (part of "Unify the image handling") seems to have changed quite a bit, including some virtual methods. One example that is related to the reported issue is that undos #3967.

https://github.com/xamarin/Xamarin.Forms/commit/a8d0d7a1d4a4629b06c3adcdba56e7da94613095#diff-7feeca82b01e77527e9263a06421f443L692

Was this intentional, or an oversight?

**Comment by samhouts** [comment]
Oversight! It'll be fixed in the next version. Sorry about that!

**Comment by samhouts** [comment]
closed by #6133
