### ISSUE TITLE
[Enhancement] Inherit IFontElement into ITextElement

### ISSUE THREAD

**Issue by pranshaggarwal** [xamarin/Xamarin.Forms#6209]
## Summary
Can we please inherit IFontElement into ITextElement? Currently, ITextElement has only TextColor property but every TextElement will also have font property attached to it. So it makes sense to have all the font properties in ITextElement as well.

## API Changes
None

## Intended Use Case
This will be useful in defining the global text style. Currently, we have to define text style for each element like Label, Button, Entry, Picker etc.

**Comment by StephaneDelcroix** [comment]
ITextElement and IFontElement are semi-private API (decorated with [EditorBrowsable]). Their purpose is not to be used as an abstraction, but to provide support internally.

Feel free to use them if they fit one of your need, but that's about all we can do for you  ¯\_(ツ)_/¯

**Comment by programmation** [comment]
@StephaneDelcroix IME they are actually very hard to use because they depend on some other things that are set as `internal`. The last time I tried to create an enhanced text-based widget I had to face either re-implementing things that were already done in XF but inaccessible in the base widgets, or ignoring those features altogether. I'm not trying to be contentious or rude, but has anyone from the XF team ever tried to create a new widget based on one of the XF widgets? I think if you ever do it you'll also want these interfaces and implementations exposed in public. If they are useful for the XF team why should they not be for everyone else too?
