### ISSUE TITLE
Flow Direction Doesn't Change When Used With Password Entries

### ISSUE THREAD

**Issue by Scarnet** [xamarin/Xamarin.Forms#6226]
### Description
Setting flow direction to RightToLeft on Entry controls doesn't seem to change the direction 
### Steps to Reproduce

1. Add an Entry to Xaml page
2. Set IsPassword property to true
3. Set FlowDirection Property to RightToLeft

### Expected Behavior
The place holder of the Entry to start from right to left
### Actual Behavior
The place holder of the Entry is starting from the left to right 
### Basic Information

- Version with issue: 3.6.0.344457
- IDE: Visual Studio 2019 16.0.4 Enterprise Edition
- Platform Target Frameworks: 
- Android: 8.1

**Comment by samhouts** [comment]
@Scarnet  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@Scarnet  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by michael-stroehlein** [comment]
This issue still exists even in recent versions. It can easily be reproduced using the RTL Lightning Lecture example code which can be found here: https://github.com/glennstephens/RightToLeftLanguages

_RTLExamplePage.xml_:
`<Entry Placeholder="{local:ize NamePlaceholder}" Grid.Column="1" Grid.Row="0" HorizontalTextAlignment="Start" IsPassword="True"/>`

It only happens when _IsPassword="True"_ is set:

![rtlPasswordWrongFlowDirection](https://user-images.githubusercontent.com/72811962/177999876-ca4fa3ce-8b50-4e7a-9631-faa905fb732d.gif)
