### ISSUE TITLE
[Bug] TwoWay Data Binding on Entry when using a nullable property

### ISSUE THREAD

**Issue by amirvenus** [xamarin/Xamarin.Forms#6280]
### Steps to Reproduce

1.  Create a new XF Project
2.  Create a VideModel that implements INotifyPropertyChanged
3.  Inside the VM, create a property that is nullable:

 
```
        private int? _stock_quantity;
        public int? stock_quantity
        {
             get => _stock_quantity;
             set
            {
                _stock_quantity = value;
                Change(nameof(stock_quantity));
            }
        }
```

4. Create an Entry whose Text value is bound to that property:

  ` <Entry Text="{Binding stock_quantity, Mode=TwoWay}" Placeholder="Units in stock"   />`

### Expected Behavior

It should update the VM but seems that the TwoWay mode is ignored.  

### Actual Behavior

It doesn't update the view model and the breakpoint set on the setter is not hit. 

### Basic Information

- Version with issue:  4.0.0.425677
- Last known good version: N/A
- IDE: VS 2017 
- Platform Target Frameworks: All

**Comment by EduardCampo** [comment]
Just noticed this behaviour in my application. I was going to report it right away and saw it's already here. I have only tested this with nullable integers.

**Comment by samhouts** [comment]
@amirvenus  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@EduardCampo Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by judithbellido** [comment]
### Steps to Reproduce

1. Create a new XF Project
2. Create a VideModel that implements INotifyPropertyChanged
3. Inside the VM, create a property that is nullable
4. Create an Entry whose Text value is bound to that property

### Expected Behavior
It should update the VM properties but seems that the TwoWay mode is ignored.
### Actual Behavior
It doesn't update the view model properties.
### Basic Information

- Version with issue: 4.0.0.425677
- Last known good version: unknown
- IDE: Visual Studio Professional 16.1.5
- Platform Target Frameworks: 
  - iOS: untested
  - Android: 9.0 
  - UWP:  17763

### Reproduction Link
[ErrorBindingIntNullable.zip](https://github.com/xamarin/Xamarin.Forms/files/3376909/ErrorBindingIntNullable.zip)
