### ISSUE TITLE
[Bug] [Android] ImageCell does not load image (4.0.0.425677)

### ISSUE THREAD

**Issue by xaruzim2155** [xamarin/Xamarin.Forms#6313]
### Steps to Reproduce

1. Clone https://github.com/MicrosoftDocs/mslearn-display-collections-in-xamarin-forms-apps-with-listview
2. Open solution FlagFacts.sln in display-collections-in-xamarin-forms-apps-with-listview > exercise2 > final
2. Update Xamarin.Forms to 4.0.0.425677 for the solution
3. Run the FlagFacts.Android on Android Emulator (9.0, x86, API 28)

**Comment by veletron2** [comment]
Hopefully this is the issue I am seeing in the new CollectionView as well as the ListView and the 3rd Party Nuget MultiSelectListView. I have icon + text in every element, and some of the icons are failing to load (randomly!). The issue is particularly noticeable if, in my List<Class>, instead of:

`public ImageSource ActivityImage => GetActivityIcon.GetImage(ActivityIconId);`

I do:

`public ImageSource ActivityImage => ImageSource.FromStream(() => GetActivityIcon.GetImageStream(ActivityIconId));`

My reason for pulling in from a stream is that I share the GetActivityIcon class between Android,iOS and non-UWP Windows via a .net2.0 class lib into which I do not want to include xamarin.forms. Using the stream mechanism may help to prove that this issue really has gone away post fix. Last XF version it worked properly in was 3.6.0.344457

```
static readonly string _rootResource = "Proteus.Shared.ProteusComms.LibProteusEnumsAndTypes.MobileApps.PatientApp.SymptomActivityIcons.ActivityIcons.";
 public static Stream GetImageStream(ActivititiyIconsEnum activity)
        {
            var assembly = Assembly.GetExecutingAssembly();
            switch (activity)
            {
                case ActivititiyIconsEnum.IconCooking:
                   return assembly.GetManifestResourceStream($"{_rootResource}Cooking.png");

                case ActivititiyIconsEnum.IconCycling:
                    return assembly.GetManifestResourceStream($"{_rootResource}Cycling.png");

               ........
          }
}
```

**Comment by veletron2** [comment]
I have just confirmed that the issue still exists in XF4.0.0.497661 13th June

Subjectively, its better, but images are still failing to load in a list control while on 3.6.0344457 they load perfectly. Loading from URI might be fixed loading from a Stream is not fixed.
