### ISSUE TITLE
[Bug] Custom renderers are disposed but not finalized, resulting in managed memory leaks

### ISSUE THREAD

**Issue by johnshardman** [xamarin/Xamarin.Forms#6331]
### Description
Custom renderers are disposed but not finalized, resulting in managed memory leaks

### Steps to Reproduce

1. Take any existing custom renderer.
2. Add a finalizer.
3. Add a breakpoint to the finalizer.
4. Run the app in the debugger and see if the breakpoint is ever hit.

(have asked in forums for somebody else to confirm before logging this issue, but to no avail)

### Expected Behavior
The breakpoint should be hit at some point after the View being rendered is deleted or goes out of scope.

### Actual Behavior
The breakpoint is never hit.

### Basic Information

- Version with issue: 3.4.0.1008975
- Last known good version: N/A
- IDE: Vs2017
- Platform Target Frameworks:
  - iOS:  12.0
  - Android: 9.0
  - UWP:  16299

**Comment by PureWeen** [comment]
My guess is that this is happening because we mostly call SuppressFinalizer from the dispose so the finalizer isn't going to be called

https://github.com/xamarin/Xamarin.Forms/blob/d7bfb0cb7bdbea47a09c228550e64541184fe9b9/Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs#L263

If you're looking to demonstrate that the code is leaking I would recommend using Xamarin Profiler, Android Studio, UWP performance analyzer, or other things to show objects that are leaking.

**Comment by johnshardman** [comment]
Thanks @PureWeen.

GC.SuppressFinalize should only be called by classes that have a finalizer. VisualElementRenderer does not have a finalizer. Any call to GC.SuppressFinalize should be in a Dispose override in a derived class. Hence, if somebody implements a custom renderer without a finalizer, they don't need to call GC.SuppressFinalize. If somebody implements a custom renderer with a finalizer, it is up to the author of the custom renderer to decide whether or not to call GC.SuppressFinalize. The way it is now, with GC.SuppressFinalize in VisualElementRenderer (there are a few others in XF source code too - I haven't checked those) appears to be the wrong way to do things.

If it is decided to keep things the way they are (I strongly suggest otherwise), then documentation and samples need to be updated to make it very clear that custom renderers should clean up both managed and unmanaged resources in Dispose, and that finalizers will not be called. But, as I said, I don't think that is the way to go.

**Comment by johnshardman** [comment]
BTW - even if things are kept the way they are, there are still odd cases where a finalizer does get called. I've just been testing on UWP, and in the test run 2771 renderer instances were created. All were Disposed, and 3 were finalized. I've seen this in testing previously, so it would seem that even if suppression is kept in the base class, there are execution paths that miss that suppression.

**Comment by johnshardman** [comment]
I have confirmed that the GC.SuppressFinalize is the cause of the problem, by adding GC.ReRegisterForFinalize(this); into the Dispose override in each custom renderer. Having done that, the finalizers are being executed. Whilst this works, it would still be better to remove GC.SuppressFinalize from VisualElementRenderer (and potentially elsewhere)

**Comment by PureWeen** [comment]
Looking through the code it does seem like only UAP Suppresses that finalization in the base class which does seem incorrect.  Most of the other suppress cases 

In your title you say this

> resulting in managed memory leaks

Were you making this statement because of no call to the finalizer? or are you seeing renderers actually sticking around in memory? One thing to note about UAP is that the ListView is a bit buggy and leaky. We have issues logged around that but most other cases (hopefully) aren't leaking renderers

**Comment by johnshardman** [comment]
The "resulting in managed memory leaks" was a misinterpretation of what is going on. I meant that the finalizer wasn't being called, which I was assuming was a leak, but turns out not to be the case. The finalizer suppression should still be removed though.

**Comment by PureWeen** [comment]
We don't really want to remove the suppression because relying on finalization is expensive
https://stackoverflow.com/a/4303315

What we should be doing though is calling Dispose(false) from the finalizer on the most base class as they do in this sample
https://docs.microsoft.com/en-us/dotnet/api/system.idisposable?view=netframework-4.8#examples

And then subclasses can override dispose and if disposing is false then they can run code that they want to run during finalization vs during dispose

I have an Issue here talking about normalizing all of our dispose patterns. So I'm going to close this issue for now and if you have additional comments can you please comment over there? 

https://github.com/xamarin/Xamarin.Forms/issues/6305
