### ISSUE TITLE
[Bug] Nightly builds are not updated

### ISSUE THREAD

**Issue by b-straub** [xamarin/Xamarin.Forms#6347]
### Description

Nightly builds are not updated each day as the name suggests.

### Steps to Reproduce

Check [Latest nightly build](https://myget.org/feed/xamarinforms-ci/package/nuget/Xamarin.Forms)

### Expected Behavior

The automatic build system should release a nightly build each day.

### Actual Behavior

The latest nightly build has been submitted Sat, 27 Apr 2019.

### Basic Information

Building XF has some complexity, especially for Mac users and since the usage of Azure Devops for this task has not been explained yet. Thus verifying the latest improvements/bug fixes can be painful.

**Comment by adrianknight89** [comment]
I agree that build is complex and the Azure DevOps side has not been explained properly. See #5815.

As for nightly builds, I'd expect to see a new build at the end of the day every time the master branch is different from the latest nightly. This doesn't necessarily mean a new build every night if there are no check-ins to master since the last build.

**Comment by rmarinho** [comment]
Hi, we are updating but we have a new feed:

https://aka.ms/xf-ci/index.json

**Comment by adrianknight89** [comment]
@rmarinho What will happen to the old feed (i.e. how long will it stay up)? I can't use the new feed because it lacks 4.0.1.268567-nightly, which is the latest working version for me.
