### ISSUE TITLE
[Enhancement] Support HTML

### ISSUE THREAD

**Issue by CodeSwimBikeRunner** [xamarin/Xamarin.Forms#6637]
## Summary
This product is so close to becoming the absolute best in the business. Allow support for HTML, heck, go to HTML fully, no one really wants xaml. You guys had to have researched how much adoption you would receive with going to HTML or allowing HTML.

## Intended Use Case
For the purpose of having a better/easier to manage ui.

**Comment by GalaxiaGuy** [comment]
I want XAML.

On a more useful note, what support for HTML would you want that would be different from making a web app (or a hybrid app using something like Ionic)?

**Comment by ValonK** [comment]
No one wants XAML ?    **I LOVE XAML**   
Please don't add html, use the manpower for thins like Performance, Stability...

**Comment by andreinitescu** [comment]
@CodeSwimBikeRunner 

**XAML** and **HTML** are both based on **XML**. XAML is a superset of HTML. In other words, if you're using HTML, you should be very familiar with XAML from a syntax point of view (tags and attributes). There's some specific syntax for things like binding, but so it's in some web frameworks like Angular, just to name a very popular one.

Also, since XAML tags and attributes map closely to the Xamarin.Forms C# classes and properties (`<Button Text="" />` maps to is `Button.Text` property), so as long as you're familiar with the Xamarin.Forms UI class hierarchy and the controls work, you should not have any problem with writing XAML.

**Comment by jfversluis** [comment]
I think you will be really happy with the Blazor support in .NET MAUI! 🎉
