### ISSUE TITLE
[XAMLC] Add compile-time validation for mismatched style targets

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#6689]
@samhouts I'd merge this, and add a new task for me to add compile-time validation for this

_Originally posted by @StephaneDelcroix in https://github.com/xamarin/Xamarin.Forms/pull/6677#issuecomment-506278042_

**Comment by samhouts** [comment]
It doesn't fail compilation if you try to do this in code, either. Can we fail both?

**Comment by StephaneDelcroix** [comment]
> It doesn't fail compilation if you try to do this in code, either. Can we fail both?

that would require changing the API so the Style property is generic. we need to investigate the feasibility, costs, and benefits of that approach

**Comment by StephaneDelcroix** [comment]
@samhouts here's what required to have compile-time validation of target type for c# and xaml:

1. generify `IStyle` and make it covariant to `IStyle<out TargetType>`: we can do that, `IStyle` isn't public
2. change the `IStyleable` interface to have `IStyle<IStyleable> Style {get;}` instead of `IStyle Style {get;}`
3. on every type deriving from a type implementing `IStyleable`, overload the property (similar to what we do with `Children` in `Layout`: 
```csharp
public class VisualElement : IStyleable {
    public IStyle<VisualElement> Style {get;} 
}
public class Button : VisualElement {
    public new IStyle<Button> Style {get;}
}
```
4. simplify the syntax of creating generic types in c# (like we do for ctor params)

But, short of hard-deprecating the non-generic version of Style, all C# defined style will stop working, and there's no magic to invoke here, as we can't write implicit operator TO generic interface.

So, my recommendation would be to _not_ change the API, but add validation if possible in XamlC.

**Comment by samhouts** [comment]
@StephaneDelcroix I second your recommendation. Thank you for investigating!
