### ISSUE TITLE
[Bug] Error messages reference bugzilla not Github issues

### ISSUE THREAD

**Issue by johnshardman** [xamarin/Xamarin.Forms#6727]
### Description

Error messages generated when building XF project still refer to bugzilla (which is now static readonly) rather than Github issues.

### Steps to Reproduce

I encountered this when I hit a known issue building my XF project for iOS. That issue was resolved by only building for ARM64. That would probably be difficult for Xamarin to reproduce, even though it is now a closed issue in Github, so I advise searching the codebase and resource files for "bugzilla.com"

### Expected Behavior

Error messages should reference Github issues where appropriate.

### Actual Behavior

Error messages still reference bugzilla.com

### Basic Information

VS2017 v15.9.13
XF 4.0.0.497661

**Comment by HeroicHitesh** [comment]
I'll like to work on this but I don't how to do. If someone can guide me along it'll be great.

**Comment by CliffAgius** [comment]
Was going to pick this up but for your first PR @HeroicHitesh take a look at my blog post on how I went about my first PR.  Good luck and any issues/help needed ping me and I will try and help, or just ask the team on here they are awesome and more than happy to help.

**Comment by HeroicHitesh** [comment]
Thanks @CliffAgius actually I know about PRs and I am doing them for last 1 year, I was actually asking for the help regarding the issue, like how to go about it. If you can point me to some tutorials for that. It will be great.

**Comment by CliffAgius** [comment]
@HeroicHitesh happy to help you with this we can do it together if you want.  First thing is to get the Xamarin.Forms repo on your device and be able to build the project so that you know it';s working.  When you have that we can look further into this issue.

Let me know when you have that working and we can take the next step.

**Comment by HeroicHitesh** [comment]
> Any issues getting this far then I refer you to my Blog Post or just ask away.

I have cloned the repository to my local system but I don't know how to create a project using it. Please add link to your Blog Post so that I can refer it.

Btw Excited to collaborate.

**Comment by CliffAgius** [comment]
@HeroicHitesh you can view the way I did my first PR into XamarinForms by looking at my blog post which is here:

https://cliffordagius.co.uk/2019/09/21/10-steps-to-submitting-your-first-xamarin-forms-pr/

If you need any more help let me know.

**Comment by HeroicHitesh** [comment]
Sorry for late reply actually my university exams are going on and also there's a lot on my plate right now so, you can go ahead with solving the issue and I will learn from your approach when I get time or I will try to solve this issue when I get time(which is probably in March or April in next year)

**Comment by hartez** [comment]
Searching the codebase for "bugzilla", "bugzilla.com" and "bugzilla.xamarin.com" reveals only comments and Issue attributes. I can't find any user-facing error messages which reference it. 

I'm guessing they've all been removed or updated since this issue was created. Going to close it for now, if someone finds one I missed we'll reopen.
