### ISSUE TITLE
[Bug] Memory leak in grouping enabled ListView

### ISSUE THREAD

**Issue by zeniya-takeshi** [xamarin/Xamarin.Forms#6742]
### Description
First ListView(IsGroupingEnabled="TRUE", HasUnevenRows="TRUE") item is never collected by GC.
If HasUnevenRows is set to "FALSE",  first ListView item is collected by GC.

### Steps to Reproduce

1. Create ListView with IsGroupingEnabled="TRUE" and HasUnevenRows="TRUE".
2. Clear ListView group items and their items.
3. First ListView item was not collected.

### Expected Behavior
First ListView item is collected.
### Actual Behavior
First ListView item was not collected.
### Basic Information

- Version with issue: 4.1.0.555618
- Last known good version: I don't know
- IDE: Visual studio 2019 Professional
- Platform Target Frameworks: 
  - iOS: 12.3.1 
- Nuget Packages:
- Affected Devices:
iPod touch 6
### Reproduction Link

[MemoryTest2.zip](https://github.com/xamarin/Xamarin.Forms/files/3348673/MemoryTest2.zip)

**Comment by jsuarezruiz** [comment]
Verified. Related to: #6761

**Comment by t-johnson** [comment]
I'm going to have a stab at this and #6761 since they seem related.  my guess is something to do with how the IOS renderer uses the first cell to measure height in CalculateHeightForCell, or in the _prototypicalCellByTypeOrDataTemplate cache that it seems to use in GetPrototypicalCell.

**Comment by t-johnson** [comment]
The bug is actually caused by the line:

https://github.com/xamarin/Xamarin.Forms/blob/5d6659c3eaeb952d4363c61ad8dd400e104313d1/Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs#L853

After removing this line (and the if condition before it) there is no memory leak.  the templatedItems list returns the same first item regardless of whether we access it through the main list, or the group, so there does not seem to be any change in behavior.

**Comment by t-johnson** [comment]
@jsuarezruiz  I do not believe this is related to #6761.

**Comment by t-johnson** [comment]
Okay so its been bugging me as to why my fix proposed the other day was "working", as it didn't make sense to me.  It also seemed to be causing GC.GetTotalMemory to continually increase.

I've finally got clarity - it works because its creating the view from a different path  (ie, child of the group) gets a different native cell.  When we use the cell from the main list, we actually end up using the same native cell that will get displayed vs one we create just to measure and then ...  um...  there is the bug.  A native cell is created to measure, and it is never removed.  It seems that if we use the main list then the native cells is the same as would have been created for actually drawing, so it gets re-used.

So instead of removing that odd If statement, a better fix is to actually call TemplatedItemsView.UnhookContent(firstCell) before returning from GetEstimatedRowHeight.

With this fix, we do not see the number of items increasing, and GC.GetTotalMemory is stable.

I will prepare a PR with this fix when i get a chance.
