### ISSUE TITLE
[Enhancement] Modal dialog / page with swipe down to dismiss

### ISSUE THREAD

**Issue by modplug** [xamarin/Xamarin.Forms#6807]
## Summary
Modal dialogs / pages with swipe down to dismiss is becoming more and more popular and Xamarin Forms should support it.
This is already possible in Xamarin Forms by creating a custom control and doing custom animations but I think it should be a part of the framework as it's own control.

## Intended Use Case
A control that look and feel just like the one in AppStore for iOS

**Comment by samhouts** [comment]
@modplug Are you hoping for something like #6713 or #1778 or something else? Thanks!

**Comment by adrianknight89** [comment]
Since you said dismiss with swipe down, I'm guessing it would be a modal page with a transparent background (so that it can cover only a part of the whole screen if desired). A swipe gesture would need to be supported out of the box. XF needs to support popup pages first, imo. To me, this sounds like #1778.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
