### ISSUE TITLE
[Enhancement] MultipleSelection in CollectionView SelectedItems Mode TwoWay.

### ISSUE THREAD

**Issue by MaxenceSAUNIER** [xamarin/Xamarin.Forms#6891]
## Summary
Add TwoWay possibility with a CollectionView MultipleSelection and with CollectionView list

Example:
[CollectionViewSample.zip](https://github.com/xamarin/Xamarin.Forms/files/3397975/CollectionViewSample.zip)

**Comment by hartez** [comment]
CollectionView already supports two-way binding for SelectedItems. 

Your sample project has a few problems. First, `MyObjectsSelected` in your viewmodel is of type `ObservableCollection<MyObject>`. You need to change the type in your viewmodel to `ObservableCollection<object>`; otherwise, you'll see a binding error (something like "cannot convert to type") and the binding will fail.

Second, you are never calling `OnPropertyChanged` in your viewmodel. And if you were, you still wouldn't see changes to the _contents_ of your `ObservableCollection`; for that, you need to be subscribed to the `CollectionChanged` event.

Here's an updated version of your sample that illustrates a way to accomplish your goal:

[CollectionViewSample_updated.zip](https://github.com/xamarin/Xamarin.Forms/files/3398603/CollectionViewSample_updated.zip)

**Comment by mshwf** [comment]
@hartez It seems it's only possible to bind `ItemsSelected`  to `ObservableCollection<object>`
for example if the `ItemsSource` of type `ObservableCollection<MyObject>` then `MyObjectsSelected` can't be of that type, it only works if its type is `ObservableCollection<object>`.
I need its type in compile time!

**Comment by hartez** [comment]
@mshwf This is being addressed by #8323

**Comment by Tommigun1980** [comment]
> CollectionView already supports two-way binding for SelectedItems.
> 
> Your sample project has a few problems. First, `MyObjectsSelected` in your viewmodel is of type `ObservableCollection<MyObject>`. You need to change the type in your viewmodel to `ObservableCollection<object>`; otherwise, you'll see a binding error (something like "cannot convert to type") and the binding will fail.
> 
> Second, you are never calling `OnPropertyChanged` in your viewmodel. And if you were, you still wouldn't see changes to the _contents_ of your `ObservableCollection`; for that, you need to be subscribed to the `CollectionChanged` event.
> 
> Here's an updated version of your sample that illustrates a way to accomplish your goal:
> 
> [CollectionViewSample_updated.zip](https://github.com/xamarin/Xamarin.Forms/files/3398603/CollectionViewSample_updated.zip)

@hartez I think this has regressed as InitialSelection doesn't seem to work anymore; please see https://github.com/xamarin/Xamarin.Forms/issues/13592.
