### ISSUE TITLE
New Lines in Editor

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7066]
Hi,

Why when I send the Editor content to email it shows all as one paragraph although user has entered several paragraphs separated by New Lines?

I tried the below but still showing as one paragraph:

`body += "<td>" + txtFeedBackMessage.Text.Replace("\r", Environment.NewLine) + "</td>";
`

Thanks,
[Jassim](https://www.softnames.com)

**Comment by jfversluis** [comment]
Hi @jrahma! A couple of questions to better identify what we are dealing with here. On which platforms do you see this behavior? What is the mail client that is being used? Does it also happen when you send the text somewhere else? What happens when the users copies the text manually?

Since you are using HTML, did you try converting the new lines into `<br />` tags?

Thanks!

**Comment by jrahma** [comment]
oh sorry, my mistake.

all clear now

Sorry Gerald :)
