### ISSUE TITLE
[Bug] Autogenerated E-Mail with Standard-Client (Android) - No HTML Content

### ISSUE THREAD

**Issue by MickLesk** [xamarin/Xamarin.Forms#7091]
### Description
Hey Guys,

we have for out app an "Error-Handling" with E-Mail.

- When I do this, with the offical GMail App, then the <.br>(breaks) work fine, but the <.b> (bold) and the <.i> (italic) not.

- When i use the standard mail program (samsung, huawei, LG) then the bugmail has no breaks, no bolds, no italic tags

The iOS Devices works fine! The Mail has breaks, bolds and italics.

### Steps to Reproduce

1. Look Screenshot #1 for Code-Snippet  

### Expected Behavior
- Mail has the correct format (breaks, bolds, italics)

### Actual Behavior
- Gmail has breaks, but no bolds, italics
- Standard Mail has nothing

### Basic Information

- Version with issue: Xamarin.Forms 4.1.0.618606
- Last known good version: ---
- IDE: Visual Studio Windows
- Platform Target Frameworks: Android
  - iOS:  Work fine with 12.x 
  - Android: 8 / 8.1 / 9 (Samsung, Huawei, Honor, LG)
- Android Support Library Version: 28.0.0.1
- Nuget Packages: 
- Affected Devices: Samsung S9+, Honor, LG G6, HUAWEI P30 Pro

### Screenshots
Screenshot - Code-Snippet: https://i.imgur.com/orIQacO.png
Screenshot - Wrong Mail (Android): https://i.imgur.com/eY08c9O.png
Screenshot - Correct Mail (iOS zoom 70%): https://i.imgur.com/wvWkhZC.png

**Comment by jfversluis** [comment]
Hi @MickLesk 

Could you please add the relevant code here as text instead of an image? Then we don't have to type everything again and makes it better indexable for search engines.

Even better would be if you could add a small sample that shows this issue so we can take a look ourselves.

I do have a feeling though that this is not really Forms related. You probably want to look at how the email is composed on Android and tinker with some settings there.

Thanks!

**Comment by jfversluis** [comment]
@MickLesk in addition, I see I failed to mention: I think the most important part here is how you compose the actual email. And as far as I can see I don't see that in the code you provided.

You might want to have a look at Xamarin.Essentials. They offer an API specifically for sending emails: https://docs.microsoft.com/en-us/xamarin/essentials/email

On this actual page I also noticed this remark especially for Android

> Not all email clients for Android support Html, since there is no way to detect this we recommend using PlainText when sending emails.

That is probably why you are seeing this. For now I will close the issue here. If you feel this _is_ related to Forms, please add a reproduction and reopen the issue.

Thanks!
