### ISSUE TITLE
xamarin.forms navigating event is not firing from custom webview

### ISSUE THREAD

**Issue by anirugu** [xamarin/Xamarin.Forms#7154]
I have made a custom class derived from WebViewRenderer and when I am using it in xaml and set navigating and navigated event, it doesn't fire at all.

I have tried setting event from xaml and .xaml.cs code. both are not working.

Is there something I missing. I means I need to hook some event in my class's renderer in droid and ios project. 

or some kind of property I need to set. What exactly I does it I call the API get the html and it's showing in webview. Is there some property I need to enable or set to make it work.

**Comment by jcmanke** [comment]
I have a guess for Android at least. Are you setting a custom WebViewClient?

**Comment by anirugu** [comment]
yes 

Control.SetWebViewClient(new CustomWebViewClient(e.NewElement as CustomWebView));

**Comment by jcmanke** [comment]
I recommend you take a look at the changes made in #3780. Instead of directly setting the client, override `GetWebViewClient()`, and make your `CustomWebViewClient` subclass `FormsWebViewClient`.

For iOS it's harder because it's not as opened up (see #6340). Easiest solution is probably to copy and modify the private delegate classes from the source code.

**Comment by anirugu** [comment]
@jcmanke 

Thanks for help. I solved this by overriding the method provided in ios and android renderer.

**Comment by Chidt12** [comment]
Can you post your solution ? 

> @jcmanke
> 
> Thanks for help. I solved this by overriding the method provided in ios and android rendere
