### ISSUE TITLE
[Bug] ScrollView movable in all directions when Keyboard is up

### ISSUE THREAD

**Issue by chris579** [xamarin/Xamarin.Forms#7419]
# Description
I have a StackLayout with horizontal orientation in a ScrollView with horizontal orientation. It's not possible to scroll vertically. However, when opening the keyboard, it's possible to scroll vertically.

### Steps to Reproduce

1. Create a ScrollView with horizontal orientation. Put a stack layout with horizontal orientation inside. 
2. Add items to your stack layout.
3. Open your keyboard and see that it's possible to scroll in every direction.

### Expected Behavior
Scrolling respects the `Orientation` setting.

### Actual Behavior
Scrolling is possible in every direction.

### Basic Information

- Version with issue: 4.2.0.709249
- IDE: VS17
- Platform Target Frameworks:
  - iOS:  12

[Video](https://github.com/xamarin/Xamarin.Forms/files/3582726/video.zip)

**Comment by samhouts** [comment]
@chris579  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@chris579  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by stephanpalmer** [comment]
We recently encountered the same problem with Xamarin.Forms Version 5.0.0.2291 on iOS. For us, the issue does not appear on Android. The issue occurs in a similar scenario as shown in the video attached to the original bug report. A horizontally scrolling ScrollView is partially covered by the open keyboard. Then, scrolling is possible in both directions. Additionally, the scroll bar is shown in the middle of the inner, horizontally scrolling ScrollView when embedded in a vertically scrolling outer ScrollView.

It seems this behaviour is caused by the ContentInset which is set by the ScrollViewRenderer when the keyboard is opened ([code](https://github.com/xamarin/Xamarin.Forms/blob/02dee20dfa1365d0104758e534581d1fa5958990/Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs#L79)).

As a workaround, we created a custom renderer which disables the ContentInset for vertically scrolling ScrollViews. Conceptionally, setting the ContentInset when the keyboard appears seems to only make sense for vertically scrolling ScrollViews, and not for horizontally scrolling ScrollViews. The workaround uses reflection, and relies on some implementation details of the KeyboardInsetTracker class. This is not ideal, and thus, the workaround needs to be re-tested with each Xamarin.Forms update.

``` C#
[assembly: ExportRenderer(typeof(ScrollView), typeof(GeaScrollViewRenderer))]

namespace ExampleWorkaround
{
    public class WorkaroundScrollViewRenderer : ScrollViewRenderer
    {
        protected override void OnElementChanged(VisualElementChangedEventArgs e)
        {
            base.OnElementChanged(e);
            var scrollView = e.NewElement as ScrollView;
            if (scrollView != null && scrollView.Orientation == ScrollOrientation.Horizontal) {
                var scrollViewRendererType = typeof(ScrollViewRenderer);
                var insetTrackerField = scrollViewRendererType.GetField("_insetTracker", BindingFlags.Instance | BindingFlags.NonPublic);
                var insetTracker = insetTrackerField.GetValue(this) as IDisposable;
                insetTracker.Dispose();
            }
        }
    }
}
```
