### ISSUE TITLE
[Bug] CollectionView freeze the UI if the items have different height - iOS only

### ISSUE THREAD

**Issue by georgemichailou** [xamarin/Xamarin.Forms#7520]
I use Xamarin.Forms 4.3.0.778476-pre1

On iOS the CollectionView items if they have different height freeze the UI on scroll and not adjust the space like android.

![Simulator Screen Shot - iPhone 8 - 2019-09-14 at 20 27 26](https://user-images.githubusercontent.com/14372162/64911828-5326d780-d72f-11e9-8e64-f13024c9b656.png)

On Android both of the above problems working correct.

![70320867_968460320179370_2749116447711035392_n](https://user-images.githubusercontent.com/14372162/64911824-4c986000-d72f-11e9-9f5c-b3985dff4a0b.jpg)

Here is my demo
https://github.com/georgemichailou/ShaXam

**Comment by hartez** [comment]
On iOS 12, the app launches and the problems mentioned upthread happen (the layout for the first album is different on iOS than on Android, after scrolling a bit the application locks up and eventually quits). 

On iOS 11, the app crashes on launch.

**Comment by JoacimWall** [comment]
Hi i have the same problem. 

Works on Android but not on IOS. for me was the problem that i also have Images that has different hight and I had the row hight in the template grid set to Auto and the Image aspect=AspectFill if i change to  aspect=AspectFit it works on IOS. i should also say that the resolution of the images was larger then the Images container.  
  
Below is the only sort of error message i get after that the app freeze on scroll.


19-09-18 15:59:13.675197+0200 iOS[12269:12053237] [Warning] Warning: sizing information will be ignored since the section referenced 0 does not currently exist. layout=<Xamarin_Forms_Platform_iOS_ListViewLayout: 0x7fcd906c3180>; collectionView=<UICollectionView: 0x7fcd978fa000; frame = (0 0; 345 575); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x6000030e3180>; layer = <CALayer: 0x600003670880>; contentOffset: {0, 0}; contentSize: {345, 1209}; adjustedContentInset: {0, 0, 0, 0}> collection view layout: <Xamarin_Forms_Platform_iOS_ListViewLayout: 0x7fcd906c3180>

**Comment by divDrones** [comment]
I have the same issue on iOS only. I am running Xcode 11 and iOS 13 with VS for Mac on the Xcode 11 preview. Happens in the simulator and on a device.

**Comment by vniehues** [comment]
Thanks for the video @divDrones! This is exactly, what happens in my projects too.

**Comment by thisdarktao** [comment]
I have experienced the same issue on iOS 13 when using a very simple layout containing a `Label`. I know this is marked "experimental" but what are we to do when the current `ListView` implementation means cells don't resize correctly on iOS and we are forced to use `CollectionView`?

**Comment by jcl71** [comment]
Same problem here, getting "sizing information will be ignored since the section referenced 0 does not currently exist" when scrolling longer lists in IOS

**Comment by georgemichailou** [comment]
This bug fixed on pre3 !!! Thanks !!

**Comment by tonyfonager** [comment]
Yes, thanks for fixing it - any idea when it will be released in stable version ?

**Comment by thisdarktao** [comment]
@samhouts Any official word on this yet? This is still 'To Do' in the `CollectionView` project.

**Comment by jfversluis** [comment]
@thisdarktao is the issue fixed for you as well? What is the "official word" you are waiting for if you don't mind me asking? This issue is probably fixed because of another underlaying problem but wasn't referenced as such, that's why it's still open but already seems fixed. Typically you should not have to worry about the status it has on our boards 🙂 

@tonyfonager the stable should arrive pretty soon! Can't give you the exact timing, but not long.
