### ISSUE TITLE
masterbehavior.popover not being observed in Xamarin.Apple SDK 16.2.0.198

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#7556]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/731792/masterbehaviorpopover-not-being-observed-in-xamari.html)._

---
After updating to Visual Studio Tools for Xamarin (Alpha) Preview 4 with Xamarin.Apple SDK v16.2.0.198 MasterBehavior.Popover is not being observed by iOS Xamarin App.  The popover is being observed just fine in UWP, just not on iOS.  I have attached a screenshot of the app with the menu displayed on my iPad.

---
#### Visual Studio Feedback System on 9/11/2019, 11:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### norton287 on 9/12/2019, 04:15 AM: 

This should be Preview 6 not 4 of Visual Studio Tools for Xamarin (Alpha)
#### norton287 on 9/15/2019, 03:19 PM: 

This is still broken in Preview 7
#### Samantha Houts [MSFT] on 9/17/2019, 00:45 PM: 

<p>Can you please attach a small project that demonstrates this issue? Thanks!</p>

#### norton287 on 9/17/2019, 01:08 PM: 

I have attached my project

---
### Original Solutions
(no solutions)

**Comment by norton287** [comment]
This is my project you can use to test.
[GroceryList.zip](https://github.com/xamarin/Xamarin.Forms/files/3623498/GroceryList.zip)

**Comment by norton287** [comment]
Screenshot of the app
![99A60B79-9839-4433-86EC-2BCBB7958B62](https://user-images.githubusercontent.com/42098364/65130005-1c1c2480-d9c2-11e9-98a9-4e7c6f43edb5.png)

**Comment by norton287** [comment]
Here is a much simpler solution to test with:

[MasterDetailBug](https://github.com/norton287/MasterDetailBug)

**Comment by hartez** [comment]
@norton287 I cloned your repro project and ran it on the iPad simulator, and the popover appears to work correctly. Is there a detail I'm missing to reproduce this?

![_7556_iPad](https://user-images.githubusercontent.com/538025/65359608-4801fa80-dbba-11e9-950c-8d28c9a50816.png)

**Comment by norton287** [comment]
@hartez The popover should be retracted, and only pop out when the menu button is pressed.  After preview 6 it stays open all the time and will not retract.  In the masterdetailpage I have set the:

MasterBehavior = MasterBehavior.PopOver

Which should keep the menu retracted until the menu button is clicked not stay open all the time.

**Comment by hartez** [comment]
@norton287 This is what I'm seeing: 

![2019-09-20_15-51-08 (1)](https://user-images.githubusercontent.com/538025/65360905-ec863b80-dbbe-11e9-8c57-bcb8ed5e4c84.gif)

It opens when I click the "Master" button and retracts when I tap off of it.

**Comment by norton287** [comment]
@hartez This is on iOS 13 on my iPad using Preview 7 of the Xamarin Tools for Visual Studio.  It works fine without the beta tools and iOS 13

**Comment by norton287** [comment]
@hartez this is in my first post:

>  After updating to Visual Studio Tools for Xamarin (Alpha) Preview 6 with Xamarin.Apple SDK v16.2.0.198 MasterBehavior.Popover is not being observed by iOS Xamarin App. The popover is being observed just fine in UWP, just not on iOS. I have attached a screenshot of the app with the menu displayed on my iPad.

**Comment by hartez** [comment]
I'm seeing the same behavior (the popover behaving correctly) with Visual Studio 16.3 Preview 4.0 (Xamarin version 16.3.0.199, Xamarin.iOS SDK version 12.16.1.24) on an iPad Pro simulator running iOS 13. 

If you update to the latest VS preview, do you still see this problem when running the repro project?

**Comment by norton287** [comment]
@hartez I am on Preview 7 of Visual Studio Tools for Xamarin (Alpha) v16.2.0.3049028 and Xamarin.Apple SDK v16.2.0.202 and Xamarin.iOS v13.0.0.19 and iPadOS 13.1 Beta 4 and the issue is still happening.

The popover stopped working in Preview 6 and is still occurring in Preview 7.  The popover worked fine on all previews up to Preview 5 for me.

Here is how it looks for me on my iPad.
![IMG_0068](https://user-images.githubusercontent.com/42098364/65410164-49484880-ddaf-11e9-884a-68745e73e664.GIF)

**Comment by norton287** [comment]
@hartez I installed Visual Studio 2019 Mac on my mac and with the stable release the issue is still happening.  Here is the configuration of VS Mac:

=== Visual Studio Community 2019 for Mac ===

Version 8.3 (build 1805)
Installation UUID: 19c8c2b2-2db0-4590-9a3a-ba50296def4f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000198

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.198 (2019-06/fe64a4765e6) (64-bit)
	Package version: 604000198

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.1.701
	2.1.700
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13
	2.1.12
	2.1.11

=== Xamarin.Profiler ===

Version: 1.6.11.16
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.0 (14936)
Build 11A420a

=== Xamarin.Mac ===

Version: 6.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin.iOS ===

Version: 13.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin Designer ===

Version: 16.3.0.230
Hash: bbe518670
Branch: remotes/origin/d16-3-xcode11
Build date: 2019-09-17 18:39:30 UTC

=== Xamarin.Android ===

Version: 10.0.0.43 (Visual Studio Community)
Commit: xamarin-android/d16-3/8af1ca8
Android SDK: /Users/jnorton/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.1
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-06@7af64d1ebe9
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/jnorton/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:42:44 UTC

=== Android Device Manager ===

Version: 1.2.0.115
Hash: 724ea69
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:43:06 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803001805
Git revision: df50511ccb08d4d84a53939f1d7fc0b40cbb0ee1
Build date: 2019-09-20 16:10:55+00
Build branch: release-8.3
Xamarin extensions: da8d448cd65f2cc87c5e6dc7e2c2ca7b96d20c72

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by tbarry-crs** [comment]
I am experiencing the same issue as norton287.  I only see the issue happening in landscape mode on iOS tablets though.  In portrait mode everything works as expected.  I can reproduce the issue running the sample code provided by norton on an iOS tablet simulator (iPad Pro (12.9-inch) (3rd generation) iOS 13.0) if that helps.

Microsoft Visual Studio Enterprise 2019
Version 16.3.0
VisualStudio.16.Release/16.3.0+29318.209
Microsoft .NET Framework
Version 4.7.03062

...

Xamarin   16.3.0.274 (d16-3@06531f8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.230 (remotes/origin/d16-3-xcode11@bbe518670)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.0.43 (d16-3/8af1ca8)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@7af64d1ebe9
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333


Xamarin.iOS and Xamarin.Mac SDK   13.2.0.42 (5e8a208)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by norton287** [comment]
It is working only in portrait mode, here is the video
![DCAA92EF-71E4-4221-BE6B-5F3B66C77157](https://user-images.githubusercontent.com/42098364/65624790-2e80fa00-df90-11e9-9b22-047b3c002c25.gif)

**Comment by Sean-LINKSOFT** [comment]
After having reports of issues with the new IOS release, I performed some tests on a development iPad running IOS 12 and found no problems.  I then upgraded the iPad to 13.1 (no change to app) and the above problem appeared.  On portrait the Popover works fine, but on landscape it is ignored and behaves like SplitOnLandscape instead.

**Comment by PureWeen** [comment]
https://developer.apple.com/documentation/uikit/uisplitviewcontrollerdelegate/1623174-splitviewcontroller?language=objc

Has been deprecated in iOS 13

Which is my guess why it stopped working

If I run this on iOS 13 that method is never even called

**Comment by PureWeen** [comment]
Correction it's been deprecated for a bit but it looks like they only acted on that deprecation with iOS 13

**Comment by lachlanwgordon** [comment]
Interstingly Shell Flyout behaviour is still functioning correctly on iOS 13 on iPads in landscape mode, there could be some hints in the shell implentation on how to fix.

I can confirm the same behavior. Apps with MasterDetail work fine on iOS 12 but always show the menu when run on iOS 13.

**Comment by PureWeen** [comment]
Yea Shell uses *PreferredDisplayMode* which is what the TabletDetailsMasterRenderer needs to be updated to use. It's just that the TabletDetailsMasterRenderer was written so long ago (pre iOS8 where PreferredDisplayMode was added) so it did what had to be done pre *PreferredDisplayMode*

I'll have a PR here soon. The workaround would basically be to use a custom renderer and set PreferredDisplayMode to *UISplitViewControllerDisplayMode.PrimaryHidden*

**Comment by kalyanmungi** [comment]
@PureWeen  This commit to Tabletmasterdetailpagerenderer broke our app. Now, masterdetail page on iPad OS 13.1 is showing blank after updating to Xamarin iOS 13.2.0.47.

**Comment by norton287** [comment]
@PureWeen  when will this fix be released?

**Comment by PureWeen** [comment]
@norton287 Hopefully in the next week

Builds still need to go through some internal testing but we're anxious to get this out

**Comment by norton287** [comment]
@PureWeen Thanks for the update!

**Comment by Jalroka** [comment]
Is the fix available currently in preview 4.3.0.85 or the nightly builds?

**Comment by DanielGlos** [comment]
How is this going?

**Comment by PureWeen** [comment]
Releases went out yesterday

**Comment by norton287** [comment]
Thanks @PureWeen
