### ISSUE TITLE
[Bug] MasterDetailPage 

### ISSUE THREAD

**Issue by nbleak** [xamarin/Xamarin.Forms#7654]
### no display at all on ipad - just a white modal box!!

Latest version as of 24th September 2019

![image](https://user-images.githubusercontent.com/11393618/65529793-b0b8e200-deee-11e9-8812-3dc883998a69.png)

**Comment by StephaneDelcroix** [comment]
Thank you for taking the time to replace the bug template by your own formatting. Writing in bold indicates that this is very important to you, but I'm sure you could make your point more obvious by writing in ALL-CAPS.

Please read https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues, use the issue template, and file all the meaningful information, like actual version numbers, and provide a reproduction project. Without all of that, we're not able to understand what your problem is.

Thanks a lot

the XF team

**Comment by nbleak** [comment]
honestly! 

Can't see the issue?? Maybe had you guys not published something so poorly implemented and tested I would not be writing here.  

Thanks for the sarcasm, I am sure the powers that be would love to read this comment

**Comment by StephaneDelcroix** [comment]
> Can't see the issue??

I can see that in your app, you get a blank page. But everything past that is pure speculation. Feel free to update the OP using the template, provide a repro, and we will reopen the issue.

**Comment by vitalii-smal** [comment]
@StephaneDelcroix @nbleak I experience the same issue on iPad OS 13 and Xamarin.Forms (2.5.1.444934).

**Comment by vitalii-smal** [comment]
@nbleak I managed to fix issue with such workaround: I created renderer for MasterDetailPage which inherits PhoneMasterDetailRenderer. https://pastebin.com/bC7Qk4gS
Hope it helps you.

**Comment by PureWeen** [comment]
what version are you on?
The latest patch version of 3.6+ should all work on ios13
we fixed an issue with MDP not showing on Ios13
Can you attach a repro if you're still having issues?

We haven't applied the fix back to 2.5

I just tested locally with the latest version of XF 3.6 and it worked fine for me on iOS 13 / XCODE 11

This is why the template is important. Because all of our internal tests work with the scenario outlined in this issue

Plus from your screen shots I can tell that the Modal is using PageScreen instead oof Full Screen so that tells me you aren't on a version of XF that we've updated to be compatible with iOS 13

**Comment by vitalii-smal** [comment]
@PureWeen Thanks! I am using 2.5, so I have not included fix. But I implemented fix (borrowed from latest master branch) by myself in TabletMasterDetailRenderer.

**Comment by nbleak** [comment]
@PureWeen Thanks I have updated all to the latest patch and it has fixed the issue.

**Comment by jessecanderson** [comment]
@PureWeen I'm seeing a blank screen issue as well. What is the oldest patch version of Forms that is updated for iPad iOS 13? Is 3.6 the minimum suggested XF version?

**Comment by PureWeen** [comment]
Yes 3.6

I tested this on 3.6 and it worked for me so if you are seeing this issue on the most recent patch version of any XF 3.6+ please attach a repro so we can fix

**Comment by jessecanderson** [comment]
@PureWeen our version is 3.1 from what I was seeing. I just needed to validate the minimum required Forms patch level to support iOS 13. Thank you.

**Comment by PureWeen** [comment]
@jessecanderson so on this point

> I just needed to validate the minimum required Forms patch level to support iOS 13. 

I just want to emphasize that we haven't picked 3.6+ as being where all iOS 13 fixes are going to go this was just a pretty major one and timing worked out to get this into 3.6.

For example this fix 
https://github.com/xamarin/Xamarin.Forms/pull/7705

We're currently only targeting to 4.2 

If you're stuck on older versions because of bugs please let us know so we can try and get you up to the latest versions!

**Comment by jessecanderson** [comment]
@PureWeen I understand that and appreciate the guidance. We are looking at upgrade options for this app now but and this information really helps us.

**Comment by faisalmaqsood12345** [comment]
Hi I am having same problem, i am trying to publish an app but Ipad screen is blank for master details page and is not being approved by App store. 
I tried to change the XF to 3.6 and 4.2 but it keep giving different compatibility issues. Any suggestion please

**Comment by nbleak** [comment]
Hi,

I now do not have this problem, however I think something that is interesting is that ever since updating everything to the latest versions including xamarin.ios.dll then regardless of the settings used.  Nothing will run on any equipment with a 32 bit processor i.e. pre iPad Air.

And yes Arm7 7s and 64bit are all selected.

Could this be investigated please.

**Comment by faisalmaqsood12345** [comment]
@nbleak  how did you solve the empty master detail page problem

**Comment by paulius1994zukas** [comment]
Issue still persists with our configuration: 

Latest Xamarin.Forms version (4.3.0.908675);
iPad Pro (3rd generation), Software version: 13.1.3;
Xcode version 11.1;
Visual Studio for Mac, Version 8.3.4 (build 8)

**Comment by PureWeen** [comment]
@paulius1994zukas can you attach a repro?

**Comment by MichaelRumpler** [comment]
Unfortunately I still depend on [DevExpress.Mobile.Grid](https://www.nuget.org/packages/DevExpress.Mobile.Grid/) which is fixed to XF 3.6.0.264807. So I cannot update to a newer XF version.

But I used the `TabletMasterDetailRenderer` from the current master as renderer of my custom MDP and that seems to work.

Funny thing is that the last time I released my app was ~2 months ago and that release still works with iOS 13. But when I compile the same code (with the same dependencies) from two months ago now, the `MasterDetailPage` does not work anymore.
