### ISSUE TITLE
[Bug] CollectionView crash with only footer

### ISSUE THREAD

**Issue by davidmclennan** [xamarin/Xamarin.Forms#7694]
### Description
CollectionView will crash if given a footer when no header has been added

### Steps to Reproduce

1. Add CollectionView to ContentPage
2. Assign footer but don't assign header
3. Run

### Expected Behavior
Footer displays

### Actual Behavior
Crash with **System.ArgumentOutOfRangeException:** 'Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index'

### Basic Information

- Version with issue: XF 4.2.0.815419
- Last known good version: Don't know
- IDE: Visual Studio 2019
- Platform Target Frameworks:
  - Android: 9.0
- Android Support Library Version: 28.0.0.3
- Affected Devices: Android emulator, 9.0, x86

```
<CollectionView Footer="footer">
        <CollectionView.ItemsSource>
            <x:Array Type="{x:Type x:String}">
                <x:String>Baboon</x:String>
                <x:String>Capuchin Monkey</x:String>
                <x:String>Blue Monkey</x:String>
                <x:String>Squirrel Monkey</x:String>
                <x:String>Golden Lion Tamarin</x:String>
                <x:String>Howler Monkey</x:String>
                <x:String>Japanese Macaque</x:String>
            </x:Array>
        </CollectionView.ItemsSource>
    </CollectionView>
```

**Comment by jsuarezruiz** [comment]
I have done several tests. With Xamarin.Forms 4.2 I reproduce your problem. However, with Xamarin.Forms 4.3 the problem is fixed (no crash and elements are rendered, etc.).

<img width="441" alt="Captura de pantalla 2019-10-03 a las 12 04 06" src="https://user-images.githubusercontent.com/6755973/66118139-f30cae00-e5d5-11e9-9d71-c9a28da5f975.png">

I attach a sample:
[Issue7694.zip](https://github.com/xamarin/Xamarin.Forms/files/3685491/Issue7694.zip)

.

**Comment by PureWeen** [comment]
@davidmclennan can you test on the latest 4.3 pre3 and let us know if you still see the crash?
