### ISSUE TITLE
[Bug] ImageButton aspect and background problems

### ISSUE THREAD

**Issue by RocketPop** [xamarin/Xamarin.Forms#7740]
### Description
  Setting a background color or binding to an image source breaks the scaling of the image. In both cases, aspect mode is not respected

### Steps to Reproduce

1.  Instantiate an image button
2. Bind to an image that is not the same size as the button
3. Set a background color
4. Set an aspect mode

### Expected Behavior
 Settings should perform as expected. Image size should be respected

### Actual Behavior
  Image is sized to larger than visible area somehow
  Aspect fill/fit does not work
  Image can distort.

### Basic Information

- Version with issue: 4.2.0.815419
- Last known good version: unknown
- IDE: VS 2019 16.3.1
- Platform Target Frameworks: 
  - iOS:  13.2.0.42 
  - Android: 10.0.0.43  
  - UWP: n/a  
- Android Support Library Version: 
- Nuget Packages: 
- Affected Devices:
  android

### Screenshots
The first image in this grid has a transparent background color set. Remove it or the source binding and it looks like the other two.

![image](https://user-images.githubusercontent.com/1441557/65847521-7c3a9100-e307-11e9-9f91-eddd64cbf0ec.png)

**Comment by PureWeen** [comment]
@RocketPop can you attach a repro? I tried a few permutations of setting the background and source binding for different aspects and I don't see the issue you are referring to

As you can see below the way it looks matches between differing backgrounds

![image](https://user-images.githubusercontent.com/5375137/66006831-4d3e2f80-e46d-11e9-8344-21693bc8b9c4.png)

**Comment by samhouts** [comment]
@RocketPop  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by jennablackwell** [comment]
I am having this issue now with latest Xamarin Forms on iOS.  If I have a fontimagesource inside an ImageButton, the icon is distorted.  Setting the Aspect does not do anything.

**Comment by RocketPop** [comment]
I think that's a different thing, but I also have problems with fontimagesource on iOS - the right hand side of apparently wider glyphs (for example the bootstrap icons : truck, truck-pickup, credit card) are clipped. Android does not do this. The controls don't respond to padding or margins or anything 😞 This problem still exists on Xamarin.Forms (4.2.0.815419). For me changing the aspect does alter the image, but it is never correctly framed as it is on android.

iOS | Android
-----------  | ----------
![image](https://user-images.githubusercontent.com/1441557/71737782-4df2b300-2e1a-11ea-92fc-acd752feb325.png)  | ![image](https://user-images.githubusercontent.com/1441557/71738046-0de00000-2e1b-11ea-9903-e9e8b8ffce25.png)

**Comment by sumeyyaarar** [comment]
Hello, I have a problem with ImageButton on iOS (see attachment). Instead of fitting, image is stretching in Image Button . I think problem in the FormsButton class which is added with this commit: 
https://github.com/xamarin/Xamarin.Forms/commit/d012853bd28e1cdda1e73e035feb0c5315c58250#diff-17042de9e1e45b58f4029bbce074127f

When I commented on this code:

` return new FormsButton();`

 and compile with the the previous version code, it works as expected:

`  return new UIButton(UIButtonType.System);`

Note: Problem is start with the Xamarin.Forms version 4.4.0.991265

<img src="https://user-images.githubusercontent.com/12747384/71919112-e4193700-3194-11ea-8ef1-3b088e6d3f59.png" data-canonical-src="https://user-images.githubusercontent.com/12747384/71919112-e4193700-3194-11ea-8ef1-3b088e6d3f59.png" width="250" height="500" />
