### ISSUE TITLE
[Bug] iOS 13 OverrideUserInterfaceStyle makes some controls weird

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#7845]
Using `UIApplication.SharedApplication.KeyWindow.RootViewController.OverrideUserInterfaceStyle` to override the system UI style causes some controls like the SearchBar to have the wrong colors. I'm trying to use this to make the whole app match the selected theme which can be configured within my app. Setting this to a "Light" theme while iOS 13 itself is set to Dark theme causes the SearchBar to have a white background with white text. Same goes the other way around. System set to light theme, overwriting to dark causes the SearchBar to be black background with black text. 

Next issue is, that if you change the iOS 13 system theme and awake the own app, the background updates and the text is not. So causing this issue is also possible without having to overwrite it in code I guess.

**Comment by jfversluis** [comment]
Hi @Sebastian1989101, thank you for reporting this.

We are aware that there are some hardcoded colors also in Xamarin.Forms that we need to get rid of, so that is probably one part of the problem. Although you should be able to work around that if you are implementing your own colors and styling.

Could you maybe provide a repro project that shows (a part) of this behavior? It would also help if you could use the issue template that is provided when opening a new issue.

Thanks!

**Comment by samhouts** [comment]
@Sebastian1989101  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
