### ISSUE TITLE
Startup performance on Android using Shell[Bug] 

### ISSUE THREAD

**Issue by ryanharding** [xamarin/Xamarin.Forms#7855]
### Description

There is a difference in startup speed when using shell on older phones. 

I created a blank Xamarin Forms (4.2.0.848062) project with all nuget packages updated, updated .csproj file with all the recommended startup performance boosters , Ran a speed test in release.
 
3552  3614 I ActivityManager: Displayed
com.companyname.xamspeedtestnormal/md5e789a5efb4f1caf24707be2f168fbc30.MainActivity: +1s723ms

I then add a bare bones AppShell.cs and changed the MainPage to use the new AppShell then ran a speed test in release,

3552  3614 I ActivityManager: Displayed
com.companyname.xamspeedtestshell/md5d47bbd79522c21e0418d609b9f3f3979.MainActivity: +2s447ms

There is close to a second additional start up time with using shell. 

### Steps to Reproduce

1. Create blank Xamarin Forms project. Run speed test. 
2. Create Xamarin Forms Shell project, remove clutter / Add Shell to blank Forms project. Run speed test.

### Expected Behavior

Expect startup time to be hardly affected by using Shell.

### Actual Behavior

Startup time is increased.

### Basic Information

- Version with issue: 4.2.0.848062
- IDE: Visual Studio 16.3.2
- Platform Target Frameworks: 
  - Android: 9.0
- Affected Devices: Older devices

**Comment by jfversluis** [comment]
Hi @ryanharding, thanks for your efforts in investigating this.

A couple of things below.

> .csproj file with all the recommended startup performance boosters

Could you specify what this is exactly?

> 3552 3614 I ActivityManager: Displayed
com.companyname.xamspeedtestnormal/md5e789a5efb4f1caf24707be2f168fbc30.MainActivity: +1s723ms

You mention a blank Forms project, which template? The really blank one? So the one just showing a Label? Because if that is the case, I don't think this comparison is really fair. Yes, Shell is slower then, but with Shell you will also get a NavigationPage and some other things for free that will take some time to load, certainly true.

If you want to make this a fair comparison, I guess you would have to create a Xamarin.Forms app with the same ingredients that Shell provides for you, so maybe a simple app with some tabs and a flyout menu. Then measure that speed with vanilla Xamarin.Forms and then create the same thing with Shell, measure that and compare those values.

If you did use some other template, could you please explain what you did exactly? 

> Steps to Reproduce

To overcome the unfair comparison I mentioned above, would it be possible to include reproduction projects for this? That way we can see what you are measuring exactly and how you measure it. This will make it much easier for us to see if there is anything that we need to do in this regard.

Thanks!

**Comment by ryanharding** [comment]
Hi Gerald,

Thanks for the feedback.

To clarify,

.csproj settings, I followed @JonDouglas post and used ;
<PropertyGroup>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <AndroidDexTool>d8</AndroidDexTool>
    <DebugType>portable</DebugType>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
</PropertyGroup>

I have created a repo with a Xamarin Forms project with burger menu and a tabbed page to more closely resemble a Shell project for a fair comparison. 

Link: ( https://github.com/ryanharding/XFSpeedTest )

Here are my speed results:
ActivityManager: Displayed
com.companyname.xamspeedtest/md561725bc2e16853a7e91d3c56c81ade61.MainActivity: +1s507ms
ActivityManager: Displayed
com.companyname.xamspeedtestshell/md5d47bbd79522c21e0418d609b9f3f3979.MainActivity: +1s930ms

The shell is still slower in starting up.

------
FYI:

We want to use shell in our companies new mobile app, and have a number of our clients on older devices. We are struggling with the startup speed on these devices while using shell, our current start up is : ActivityManager: Displayed
com.xxxx.xxxxx/md5a9edb309212fcb2a7f54003073b79715.MainActivity: +3s363ms (total +4s554ms) 

I understand lots of things contribute to it, but this is just an UI project without any additional nuget packages. Hence this investigation.

**Comment by hartez** [comment]
@ryanharding I'm trying to run the XamSpeedTestShell but I keep getting `System.MissingMethodException: 'Default constructor not found for type XamSpeedTestShell.Views.ItemsPage'`

**Comment by samhouts** [comment]
@ryanharding  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
