### ISSUE TITLE
[Bug] [iOS] a task is canceled exception when iOS prompts for permissions during a HTTP call.

### ISSUE THREAD

**Issue by czuck** [xamarin/Xamarin.Forms#7861]
### Description
Using Xamarion.iOS 12.10 and above, when iOS prompts for a permission while the code is awaiting a HTTP call, the HTTP call ends with a 'A task was canceled' exception.  This appears to be a timing issue, it doesn't happen every time but does with some consistency.

### Steps to Reproduce
1. Run the attached sample project.
2. Respond to the Notification Permission prompt
3. If the exception occurs an error will be displayed, if not you will see the Welcome to Xamarin Forms message.
4. If you do see the error, tapping try again will re-initiate the HTTP call, which will complete successfully. 
5. Stop the debug session and delete the app from the device to run the test again.  If the app is not deleted iOS will not display the permission prompt which is necessary to recreate the issue.

### Expected Behavior
The HTTP call should complete successfully

### Actual Behavior
"A task was canceled' exception is thrown

### Basic Information
Version with issue:
  - iOS:  12.10 and above, currently using 13.2
Last known good version:
  - iOS:  12.8

### Reproduction Link
[Connection.zip](https://github.com/xamarin/Xamarin.Forms/files/3698791/Connection.zip)

**Comment by jfversluis** [comment]
Hi @czuck, thanks for the report!

Although this does seem very specific to iOS. Do you see this specifically with Xamarin.Forms applications? Otherwise it might make more sense to open this issue on the [Xamarin.iOS repo](https://github.com/xamarin/xamarin-macios).

It looks a bit like [this issue](https://github.com/xamarin/xamarin-macios/issues/6936) also describes the same thing?

If it's not specific to XamForms, could you please close this issue and follow up on the Xamarin.iOS repo? Thanks :)

**Comment by czuck** [comment]
@jfversluis all of the apps I deal with are Forms apps, so it's difficult to determine if this is Forms or iOS.  I'll close this and follow the iOS report, if that fix doesn't fix this I can always report it again.
