### ISSUE TITLE
Firebase Analytics and Crashlytics for Xamarin Forms

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7882]
Hi,

I hope you'll soon have a Xamarin Forms package for Firebase Analytics and Crashlytics instead of using interfaces.

Thanks,
Jassim

**Comment by jfversluis** [comment]
Hey @jrahma, thanks for the suggestion.

Could you elaborate a bit more about what you mean with this? What functionality are you looking for? And what do you mean by "instead of using interfaces"?

I don't think we will be creating packages ourselves for implementing Firebase services anytime soon I'm not entirely up-to-date with what is out there in this regard, but aren't there already packages that do this?

Also, have you considered using App Center?

**Comment by jamesmontemagno** [comment]
The core bindings already exist and something like this would fall under a community plugin of some sort and not into xamarin.forms

**Comment by jfversluis** [comment]
Happy to discuss this any further if you have any input @jrahma but closing this for now due to this not becoming part of Xamarin.Forms core.
