### ISSUE TITLE
Binding updates to shell component pages delayed

### ISSUE THREAD

**Issue by heathbm** [xamarin/Xamarin.Forms#7912]
So I have a Shell that has a home page and a settings page. The settings page makes changes to a singleton service that the home's ViewModel is binded to (MVVM).

I have set up break points on the PropertyChangedEvents of elements on the Home page and they hit as soon as changes are made to the service's properties and their PropertyChanged is executed.

However, upon going back to the home page via the Shell, the page's UI only updates when the page is active and visible. This causes fields to flash when they change. But the breakpoints suggest that they should have updated before.

Is there a way to force refresh the UI before or are there any other alternatives?

For now I have made my view perform a Fade In animation so that changes to the ViewModel don't cause flashing

**Comment by jfversluis** [comment]
Hey @heathbm, thanks for opening the issue.

Since you didn't use the issue template, I'm assuming this is more of a question than a bug? Of course we are happy to have a look, but typically questions like these get better results on website like the Xamarin Forums or StackOverflow. If it is a bug according to you, I would kindly ask you to add all the info that is requested through the template and most importantly; a reproduction. The latter is also something that might greatly speed up answering your question 🙂 

Having that said, for your question. I don't think Shell does anything special in terms of databinding in comparison to regular Xamarin.Forms.

> However, upon going back to the home page via the Shell, the page's UI only updates when the page is active and visible. This causes fields to flash when they change. But the breakpoints suggest that they should have updated before.

Do you mean that when the page where values are changing is visible everything is working correctly? And the flashing is just happening whenever you switch over to another page where values have been changed in the meantime?

**Comment by samhouts** [comment]
@heathbm  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
