### ISSUE TITLE
[Enhancement] YOUR IDEA!

### ISSUE THREAD

**Issue by sakshamtaneja21** [xamarin/Xamarin.Forms#7973]
## Summary
we can have a good readme of all folders with ppt to give a good demonstration

## API Changes

Include a list of all API changes, additions, subtractions as would be required by your proposal. These APIs should be considered placeholders, so the naming is not as important as getting the concepts correct. If possible you should include some "example" code of usage of your new API.

e.g.

In order to facilitate the new Shiny Button api, a bool is added to the Button class. This is done as a bool because it is simpler to data bind and other reasons...

    var button = new Button ();
    button.MakeShiny = true; // new API

The MakeShiny API works even if the button is already visible.

## Intended Use Case
Provide a detailed example of where your proposal would be used and for what purpose.

**Comment by adrianknight89** [comment]
@sakshamtaneja21 Hey, can you make sure you have written a proper title and removed the templated text so people aren't confused? Also, you submitted several changes that could have been a single PR instead of multiple ones. At this point, everything feels like spam.

**Comment by Happypig375** [comment]
Just look at his profile... The amount of low-quality PRs amazes me.

**Comment by jfversluis** [comment]
Hey @sakshamtaneja21, we'd love to have a look at your new proposal, but in the current state it is kind of hard to understand what you mean. Because of that, I'm closing this one for now.

When you open a new one (or reopen this one) please make sure to give it an appropriate title and extensive description and remove any text that is in the template but does not correspond to your idea.

Thanks!
