### ISSUE TITLE
[Bug] Xamarin slider custom renderer DragCompleted event not working in iOS

### ISSUE THREAD

**Issue by john-heaven** [xamarin/Xamarin.Forms#8017]
### Description
I am trying to put in function an IOS custom renderer for Slider control. Due to wrapping class SlideriOS the event are not firing and I need DragCompleted event. I have a try with `TouchDragExit` , `TouchDragOutside `method , however they all not working .

```
[assembly: ExportRenderer(typeof(CustomSlider), typeof(CustomSliderRenderer))]
namespace App8.iOS
{
    public class CustomSliderRenderer : SliderRenderer
    {
        CustomSlider customSlider;
        protected override void OnElementChanged(ElementChangedEventArgs<Slider> e)
        {
            base.OnElementChanged(e);

            if (null != Control)
            {
                customSlider = (CustomSlider)e.NewElement;
               
                customSlider.DragCompleted += CustomSlider_DragCompleted;
                Control.TouchDragExit += Control_TouchDragExit;
                Control.TouchDragOutside += Control_TouchDragOutside;
            }
        }

      
        private void CustomSlider_DragCompleted(object sender, EventArgs e)
        {
            //throw new NotImplementedException();
            Console.WriteLine("------CustomSlider_DragCompleted-------");
        }

        private void Control_TouchDragOutside(object sender, EventArgs e)
        {
            //throw new NotImplementedException();
            Console.WriteLine("------Control_TouchDragOutside-------");
        }

        private void Control_TouchDragExit(object sender, EventArgs e)
        {
            //throw new NotImplementedException();
            Console.WriteLine("------TouchDragExit-------");
        }
   }
}
```

It works in Android, how can I fire the DragCompleted event for the slider control in iOS?

### Expected Behavior
![20191015_155743](https://user-images.githubusercontent.com/7145819/66811987-9a89c900-ef64-11e9-8145-ed422ed17385.gif)

### Actual Behavior
![20191015_160718](https://user-images.githubusercontent.com/7145819/66812657-e9842e00-ef65-11e9-86a0-d9747be888f1.gif)

### Basic Information

- IDE: Visual Studio 16.3.4 2019 Enterprise
- Xamarin Forms: 4.2.0.848062
- iOS:  13.1

### Reproduction Link

SO link : https://stackoverflow.com/questions/58311746/xamarin-slider-custom-renderer-dragcompleted-event

Reproduce sample link : https://www.dropbox.com/s/fp6cdzaqlidea8g/App15.rar?dl=0

**Comment by sthewissen** [comment]
I can probably take a look at this.

**Comment by sthewissen** [comment]
I just implemented it how I would, but cannot reproduce the issue you mention. Please see your adjusted sample attached below. Just adding this code in the XAML does what you describe that you want to do. The custom renderer isn't needed. I feel like your reproduction project and what you're trying to achieve aren't completely aligned or parts are missing.

```
public MainPage()
{
    InitializeComponent();
    customSlider.DragCompleted += CustomSlider_DragCompleted;
}

private void CustomSlider_DragCompleted(object sender, EventArgs e)
{
    myentry.Text = "Slider complete !";
}
```

This works exactly as you described it should.

[App15_adjusted.zip](https://github.com/xamarin/Xamarin.Forms/files/3738914/App15_adjusted.zip)

Looking at your SO link you're mentioning something completely different where you're using `SetNativeControl` to override the actual native control being used. If that's what you want to do you will have to also implement the events yourself since you're essentially removing the control Xamarin.Forms uses. Take a look at Xamarin.Forms `SliderRenderer` [for iOS](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/SliderRenderer.cs) to see how.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
