### ISSUE TITLE
[Bug] ToolbatItem command is not executed

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#8152]
Add toolbar item to the ContentPage
<ToolbarItem
            Command="{Binding MyCommand, Source={x:Reference MyContentPage}}"
            IconImageSource="MenuIcon.png"
            Order="Primary"
            Priority="0"
            Text="Item" />

Expected behavior:
Command is executed

Current behavior:
Command is not executed

if I add Clicked event Clicked="MenuItem_OnClicked" and in code behind :
```
private void MenuItem_OnClicked(object sender, EventArgs e)
        {
            var t = sender as ToolbarItem;
            t.Command.Execute(null);
        }
```

Command is null here

**Comment by jfversluis** [comment]
Hi @VladislavAntonyuk thanks for the issue!

I'm afraid we need a bit more information regarding this though. Did you actually assign something to the `Command` property? Could you show the code for that?

Is this not working for a specific platform or for all of them from what you can tell?

Would you be able to provide more info, preferably through the issue template and add a reproduction project if possible?

Thanks!

**Comment by VladislavAntonyuk** [comment]
`
    <ContentPage.ToolbarItems>
        <ToolbarItem
            Command="{Binding MyCommand, Source={x:Reference MyContentPage}}"
            IconImageSource="Icon.png"
            Order="Primary"
            Priority="0"
            Text="Command text" />
    </ContentPage.ToolbarItems>
`

in code behind:
`
MyContentPage(){
BindingContext = new ViewModel();
InitializeComponent();
}
`

**Comment by VladislavAntonyuk** [comment]
@jfversluis I have verified it on Android and iOS, also I use Shell, but I am not sure it is related to the issue,

**Comment by jfversluis** [comment]
@VladislavAntonyuk I've taken the liberty to create a Shell project to reproduce this.

Notice how I created a `FooCommand` in the view model that I bind to the Add button in the main screen. Through the clicked handler of that Add button I pull out the `Command` and execute that. I see the `Debug.WriteLine` being executed without any problems.

See the repro here: [Repro8152.zip](https://github.com/xamarin/Xamarin.Forms/files/3766535/Repro8152.zip)

While typing this I notice this line your posted:

`<ContentPage.ToolbarItems> <ToolbarItem Command="{Binding MyCommand, Source={x:Reference MyContentPage}}" IconImageSource="Icon.png" Order="Primary" Priority="0" Text="Command text" /> </ContentPage.ToolbarItems>`

I think your problem might be here: `{Binding MyCommand, Source={x:Reference MyContentPage}}` change it to `{Binding BindingContext.MyCommand, Source={x:Reference MyContentPage}}`

Notice how I added the `BindingContext`. Since you're referencing through another element, you need to go through the `BindingContext` property to the properties that are contained within that. Does that make sense?

Hope this fixes your problem!

**Comment by VladislavAntonyuk** [comment]
@jfversluis yes, it works!
