### ISSUE TITLE
[Bug, Android, iOS] Setting SelectedItem on CollectionView from OnItemSelected to null throws exception

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#8184]
### Description

Setting `SelectedItem` to null inside the `OnItemSelected` event throws an exception on Android

> System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index'

```C#
        async void OnItemSelected(object sender, SelectionChangedEventArgs e)
        {
            var item = (Item)e.CurrentSelection[0];
            await Navigation.PushAsync(new ItemDetailPage(new ItemDetailViewModel(item)));

            // Manually deselect item.
            ItemsCollectionView.SelectedItem = null;
        }
```

#### Android
1.  Run sample
2. Click on any items in the list

#### iOS
1.  Run sample
2. Click on any items in the list
3. click the back button

### Expected Behavior
When you click on an item it should navigate to details page
Then when you return to the list whatever item you clicked on should be unselected

### Actual Behavior
App crashes

### Basic Information

- Version with issue: master
- Last known good version: not sure
- IDE:
- Platform Target Frameworks: 
  - Android: 9.0
  - iOS: 13.1

### Reproduction Link
[TemplateCV.zip](https://github.com/xamarin/Xamarin.Forms/files/3765011/TemplateCV.zip)

**Comment by jsuarezruiz** [comment]
I reproduce the error. I am going to detail what happens because I am not sure if we should modify the current behavior or not.

What happens is the following:
1. Click on an item in the CollectionView. This will internally set `SelectedItem` and `SelectionChanged` will be invoked.
2. When `SelectedItem` is set to null, `SelectionChanged` is invoked again. But this time `CurrentSelection` will be empty and when you try to access by index you get the error.

You can fix this in your code just not using the index.

**Comment by EvoPulseGaming** [comment]
I would say the default is desirable, as null would let you know that an item was deselected. (For example if you generate a list based off what was selected, if de-selected you would want to clear the list. )

I would put a null check in user code, and call it a day
