### ISSUE TITLE
[Bug] [iOS] RefreshView draws behind CollectionView Header

### ISSUE THREAD

**Issue by janschoelchAtOK** [xamarin/Xamarin.Forms#8282]
### Description

When using a `RefreshView` and wrap a `CollectionView` with header in it, the `RefreshView` draws behind the `CollectionView` header on iOS.
This leads to unwanted behaviour, for instance: `CollectionView` in some cases scrolls out of screen bounds (as it scrolls up too far after refreshing).

### Steps to Reproduce
I just re-used and adjusted the Xamarin.Forms `CollectionView` Demo to reproduce the issue.

1. Open the attached Solution
2. Navigate to "Pull to Refresh using RefreshView -> Vertical List"
3. Pull the CollectionView down to refresh

### Expected Behavior

The `RefreshView` should draw above the `CollectionView` header.

### Actual Behavior

The `RefreshView` draws behind the `CollectionView` header on iOS.

### Basic Information

- Version with issue: Tested on Xamarin.Forms 4.3.0.908675
- Last known good version: N/A
- IDE: Tested on Visual Studio Professional 2019
- Platform Target Frameworks:
  - iOS: 11.0
  - Android: 9.0
  - UWP:  N/A
- Android Support Library Version: N/A
- Nuget Packages: Xamarin.Forms 4.3.0.908675
- Affected Devices: Tested on iPhone 8 running iOS 13.1.3 and Huawei P Smart + (2019) running Android 8.1. 

### Screenshots

The screencasts were made on Emulators (iPhone 8 iOS13, Google Nexus 5X Android 8.1).

**iOS**

![OMMZ7DvVCg](https://user-images.githubusercontent.com/44392293/67758697-75a25500-fa3e-11e9-9508-12b20bc1c9bd.gif)

**Android**

![fmULH9FL7K](https://user-images.githubusercontent.com/44392293/67758751-8b177f00-fa3e-11e9-84be-7b8c5bfa5604.gif)

### Reproduction Link

[CollectionViewHeader.zip](https://github.com/xamarin/Xamarin.Forms/files/3783031/CollectionViewHeader.zip)

**Comment by rmayrink** [comment]
Same issue here on iOS. CollectionView with Header and RefreshView.

**Comment by shanranm** [comment]
I think the proper wording should be Header drawn above refreshview.
The same occurs for empty view also #7457

**Comment by huyjack178** [comment]
What is the progress of this issue?

**Comment by Flaviocrtt** [comment]
Same problem here, it makes space for activity indicator on the top of all, but it appears ignoring the header.

**Comment by jsauve** [comment]
I am also experiencing this in `4.4.0.991220-pre3`. I have a large header at the top of my CollectionView. The CollectionView element is the root element of my `ContentPage.Content`. When performing a pull-to-refresh gesture, the RefreshView's ActivityIndicator is rendered above (y-axis) the CollectionView's "cells" and below (y-axis) the CollectionView's Header. Since the point of using Header is for above-collection-view-cells content (per Jason Smith's Evolve 2016 talk), and because that implicitly suggests that CollectionView will be used as the root element of a page, then I would expect RefreshView's ActivityIndicator control to render *above* the CollectionView Header (above (y-axis) the outermost UI element of CollectionView).

**Comment by jsauve** [comment]
I'll try to take a look at the existing renderer and, make a fix, and submit a PR.

**Comment by mtsrdr** [comment]
I have a similar issue, where a put an empty grid with a padding as my CollectionView (since it does not have a padding property) and the result is this:

**Comment by mtsrdr** [comment]
I have a similar issue where I put an empty Grid with a padding as a Header for my CollectionView (Since it does not own a Padding property) and the result is this:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33626789/72016973-855ec680-3243-11ea-91e0-2c28fd020f2d.gif)

As you can see, the first time I select my tab with a CollectionView wrapped in a RefreshView it scrolls out of screen bounds. This happens only on iOS.

This was recorded in IPhone 7 Simulator iOS 11.3. 
When I run my app in IPhone 11 Pro iOS 13.3 only the Activity Indicator is out of screen bounds in first refresh. 

Tested on Xamarin.Forms 4.4.0.991265
IPhone 7 iOS 11.3
IPhone 11 Pro iOS 13.3

**Comment by raver99** [comment]
Because I needed this to work, I came up with a workaround that does the job, at least for my project.

It involves replicating the RefreshViewRenderer, adding some Xamarin Forms internal helper methods (just a few, really) and adding one line to fix it.
The fix is extending the bounds of the UIRefreshView with content offset of the scrollviewer.

I didn't really have the time to investigate all the layouting that happens here, I suspect some Autolayout constraints.
Extending the bounds is one way to fix it, probably not the real fix of the issue.

Here is the gist of my [workaround](https://gist.github.com/raver99/fcb36f98d1791901d5741df5d6c91c74)

Hope it helps

**Comment by TingtingAn** [comment]
Hi everyone, any soultion here? I got the same issue.

**Comment by jamesmontemagno** [comment]
Same here today, it looks just as if the RefreshView is being added to the main CollectionView content and not including the Header above it.

**Comment by daniVerz** [comment]
Same here! Funny that after any minor change and Hot Reload it renders the header right.
Any hope? I have to release a new version...

**Comment by xleon** [comment]
Same here with XF 4.7.0.1260. RefreshView is not usable in iOS with a Header. 
More problems (artefacts) come into place when the page does not use a Navigation bar (`NavigationPage.HasNavigationBar="False"`)

**Comment by alexmartinezm** [comment]
C'mon guys, we can have this fixed before MAUI, can't we?

**Comment by xamiell** [comment]
Having the Same problem.

Xamarin.Forms 4.8.0.1560
Visual Studio for Mac 8.8 build 2913

**Comment by luismts** [comment]
@jsuarezruiz this is kind of annoying. Is there a workaround at least?

**Comment by xamiell** [comment]
Hi, any update?

**Comment by giuseppenovielli** [comment]
Same problem, please fix it. I can't use CollectionView with header and still using ListView!!!! Please prioritize!!

Thanks!!

**Comment by Nelo-cool** [comment]
> Because I needed this to work, I came up with a workaround that does the job, at least for my project.
> 
> It involves replicating the RefreshViewRenderer, adding some Xamarin Forms internal helper methods (just a few, really) and adding one line to fix it.
> The fix is extending the bounds of the UIRefreshView with content offset of the scrollviewer.
> 
> I didn't really have the time to investigate all the layouting that happens here, I suspect some Autolayout constraints.
> Extending the bounds is one way to fix it, probably not the real fix of the issue.
> 
> Here is the gist of my [workaround](https://gist.github.com/raver99/fcb36f98d1791901d5741df5d6c91c74)
> You can find it by looking at the "todo"
> 
> Hope it helps

Thanks! This is workaround. it really works!

**Comment by Outtake** [comment]
How is this not fixed yet? Would really like to start using collectionview any time soon.
Sadly the workaround from @raver99 doesn't work for me.

**Comment by xamiell** [comment]
@Outtake same here, doesn't work for me too.
Production apps :'(

**Comment by giuseppenovielli** [comment]
@jsuarezruiz @hartez @samhouts i can't use CollectionView with this bug!!

**Comment by jsuarezruiz** [comment]
The issue will be fixed by https://github.com/xamarin/Xamarin.Forms/pull/13773

**Comment by Outtake** [comment]
thanks

**Comment by giuseppenovielli** [comment]
@jsuarezruiz 
Thank you so much!!  Perfect!! :)

**Comment by xamiell** [comment]
Thanks @jsuarezruiz!

**Comment by matteovelati** [comment]
Is this bug solved? I'm having the same problem

**Comment by giuseppenovielli** [comment]
@matteovelati yes there is a pullrequest, thank @jsuarezruiz, but must be added to a new xamarin.forms' release.

**Comment by matteovelati** [comment]
@giuseppenovielli is there a way to include the fix in my project in the meanwhile?

**Comment by giuseppenovielli** [comment]
@matteovelati check this pullrequest 

https://github.com/xamarin/Xamarin.Forms/pull/13773/files

Clone Xamarin.Forms github project and edit manually files update by pullrequest
