### ISSUE TITLE
[Bug]  Navigation between pages is slow

### ISSUE THREAD

**Issue by amer2737** [xamarin/Xamarin.Forms#8411]
### Description
in xamarin forms
Navigation between pages is slow just on android on ios it is good
these video for IOS it is good speed
https://drive.google.com/open?id=162U0XmPw-NZvMZhqNgyDOtCPcy52EhHy
these for Android it slow not good like IOS
https://drive.google.com/open?id=15yedNiqzwypFx8RIN22UTltFmCSIIFIl
these my simple
https://drive.google.com/open?id=1eK-6efyw37LUH78p3ze-fflWXJI_3tlQ

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE: visual studio 2019 enterprise 16.3.7 
- Platform Target Frameworks: 
  - iOS:  13.1
  - Android: Android 9 API 28  
  - UWP:   
- Android Support Library Version: 28.0.0.3
- Nuget Packages:
- Affected Devices:

### Screenshots
these video for IOS it is good speed
https://drive.google.com/open?id=162U0XmPw-NZvMZhqNgyDOtCPcy52EhHy
these for Android it slow not good like IOS
https://drive.google.com/open?id=15yedNiqzwypFx8RIN22UTltFmCSIIFIl

### Reproduction Link
these my simple
https://drive.google.com/open?id=1eK-6efyw37LUH78p3ze-fflWXJI_3tlQ

**Comment by jfversluis** [comment]
Hi @amer2737 thanks for the report.

I definitely see a difference in speed. But the problem seems kind of broad. Also, I see you have attached your full project, which also actually does different things when navigating on iOS and on Android. For example, on Android I see you are creating a new `NavigationPage` each time within a modal for each new page that you open from the dashboard.

There are a lot of things that could cause this behavior and I'm not sure if this is a problem within Xamarin.Forms or maybe because of code that is implemented in your app. Would you be able to create a reproduction project with just this navigation issue and the least amount of other code so we can see if the problem still shows then?

What you could try in your code is put in `Stopwatch`es to see what calls take a long time and maybe figure out if there is any code in there that can be optimized.

Another thing I noticed is that it looks like you have attached your entire project to this issue, including some secret values for App Center etc. I think it would be wise to regenerate those secrets and remove your project from the Google Drive location since it is accessible by anyone.

Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by YBENZAKOUR** [comment]
@amer2737  Hello, I have the same issue in my App, in IOS my app is fast but in Android NO, do you have found any solution for this problem ?
Can you help me please.
Thank you
