### ISSUE TITLE
[Bug] [Xamarin.iOS] ListView System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by camos-os** [xamarin/Xamarin.Forms#8514]
May relate to: https://xamarin.github.io/bugzilla-archives/58/58592/bug.html

### Description
Refreshing a listview that is bound to an observable collection will sometimes crash the application with IndexOutOfRangeException when multiple ObservableCollection.Clear() calls are made.

### Steps to Reproduce

1. refresh list repeatedly
2. crash occurs at random. took about 10-20 refresh attempts to reproduce.

### Expected Behavior
Should be able to call ObservableCollection.Clear() as often as needed. IndexOutOfRangeException should be handled and not cause application crash.

### Actual Behavior
Multiple calls to ObservableCollection.Clear() seem to be causing iOS crashes with unhandled IndexOutOfRangeException that can't be caught in application code.

### Basic Information

- Version with issue: Xamarin.Forms 4.2
- Last known good version: Unknown
- IDE: Visual Studio (Mac)
- Platform Target Frameworks: .NET Core SDK 3.0
  - iOS:  13.6.0.12
  - Android: N/A
  - UWP: N/A
- Android Support Library Version: N/A
- Nuget Packages:
- Affected Devices: iOS 12.4 (12.x)

**Comment by VladislavAntonyuk** [comment]
Could you please attach a call stack or small project?

**Comment by MappingSteve** [comment]
@camos-os  - Are you on UI thread, or on background (worker) thread?

I think it is only possible to get this IndexOutOfRangeException if you alter collection on a background thread.

This might be fixed by [8392](https://github.com/xamarin/Xamarin.Forms/issues/8392).

In the meantime, two possible work-arounds:

1. Don't alter a collection that is bound to a listview. Instead, build a new collection with the desired elements, and replace the property value with that new collection.

OR 2. Wrap the Clear call in BeginInvokeOnMainThread. To be sure it happens on UI thread.

**Comment by camos-os** [comment]
in this case ObservableCollection.Clear() was being invoked twice from a worker thread during the list refresh

**Comment by samhouts** [comment]
@camos-os  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
