### ISSUE TITLE
[Bug] [Shell] iOS - BackButtonBehavior Command property binding throws InvalidCastException when using a custom command class that implements ICommand

### ISSUE THREAD

**Issue by brunck** [xamarin/Xamarin.Forms#8529]
### Description
Binding the `Shell.BackButtonBehavior` `Command` property on a `ContentPage` in iOS to a custom command class that does implement `ICommand` results in an `InvalidCastException` at runtime. The sample includes an alternate implementation of `ICommand` and uses it in binding the `BackButtonBehavior` on the Monkeys detail page.

This appears to be a regression at some point during 4.2 development. It works using a pre-release version of 4.2, but fails beginning with at least the latest stable version of 4.2, and continues in the latest stable of 4.3.

This was confirmed in the iOS simulator and on a physical iPhone device.

Android devices were not affected as far as I can tell; I could not reproduce on Android.

### Simple Steps to Reproduce

1. Use the attached sample project. Run on either an iOS simulator or iOS device.
2. Click the `Monkeys` tab.
3. Click on `Baboon`
4. Click on the back button in the upper left corner.
5. The app crashes.

### Expected Behavior
The bound command should be executed.

### Actual Behavior
The app crashes with an `InvalidCastException`

### Basic Information

- Version with issue: 4.2 stable and 4.3+
- Last known good version: 4.2.0.673161-pre3
- IDE: VS 2019 on Windows 16.3.8 and Visual Studio for Mac 8.3
- Platform Target Frameworks: 
  - iOS:  Xamarin.iOS 13.6.0.12, XCode 11.2
- Affected Devices: iOS Simulator iPhone 11 iOS 13.2 and iPhone 7 Plus with iOS 12.4.1

### Reproduction Link

[Xaminals.zip](https://github.com/xamarin/Xamarin.Forms/files/3852808/Xaminals.zip)

**Comment by hartez** [comment]
I _think_ the problem is in ShellPageRendererTracker, in the `LeftBarButtonItemHandler` method.

`var command = behavior.GetPropertyIfSet(BackButtonBehavior.CommandProperty, new Command(() => OnMenuButtonPressed(this, EventArgs.Empty)));` 
should either be
'ICommand command = behavior.GetPropertyIfSet(BackButtonBehavior.CommandProperty, new Command(() => OnMenuButtonPressed(this, EventArgs.Empty)));'
or
'var command = behavior.GetPropertyIfSet(BackButtonBehavior.CommandProperty, new Command(() => OnMenuButtonPressed(this, EventArgs.Empty)) as ICommand);'

**Comment by brunck** [comment]
It gets even weirder; the problem doesn't happen unless the `IconOverride` is set on the `BackButtonBehavior.` For whatever reason, the bound command doesn't seem to be invoked otherwise.
