### ISSUE TITLE
Disposed objects are not handled properly in android scrollview renderer

### ISSUE THREAD

**Issue by SubburajPandianV** [xamarin/Xamarin.Forms#8600]
### Issue
Disposed objects are not handled properly in android scrollview renderer.
https://github.com/xamarin/Xamarin.Forms/issues/5820

### Description
It occured due to ScrollViewRenderer is not disposed properly when navigated away from the page i.e., Renderer is not cleared from Xamarin.Forms.ScrollView even if we disposed the native object

This reported issue [5820](https://github.com/xamarin/Xamarin.Forms/issues/5820) has been fixed in this commit [6151](https://github.com/xamarin/Xamarin.Forms/pull/6151)

Fixed in Xamarin.Forms v4.2.0.815419, release notes. 

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.2/4.2.0-sr2 

After upgrading the Xamarin.Forms to v4.2.0.815419, we have encountered the following crash report in the application,

https://github.com/xamarin/Xamarin.Forms/issues/7602 

It is also resolved, now again the mentioned issue [5820](https://github.com/xamarin/Xamarin.Forms/issues/5820) occuring. Kindly check and let us know the details.

**Comment by samhouts** [comment]
@SubburajPandianV  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by jfversluis** [comment]
Hey @SubburajPandianV thanks for the report!

I'm afraid I don't quite understand what is going on. You mention all kinds of issues and fixes and if I read it correctly everything seems fixed?

Could you give some more information and like Samantha mentioned; a reproduction project? Thanks!

**Comment by SubburajPandian** [comment]
Hi @samhouts / @jfversluis,

Sorry for the delay.

I have attached the sample project in which we installed Xamarin.Forms latest stable version 4.4.0.991.  

**Sample:** [ScrollView_Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/3982178/ScrollView_Sample.zip)

**Replication procedure:**

- Run the sample in Android
- Tap the ExpanderSample
- Tap back
- Tap again the ExpanderSample
- Throws ```System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.ScrollViewRenderer```.

**Issue details:**
The reported issue occurs due to ScrollViewRenderer is not disposed properly when navigated away from the page i.e., Renderer is not cleared from Xamarin.Forms.ScrollView even if we disposed the native object. So, that when navigate back to Expander control, we create a new renderer for ScrollView if renderer is null which is loaded in the Content and at this time, disposed renderer for ScrollView is still maintained in Xamarin Forms Android platform which leads to Object disposed exception from ScrollViewRenderer class while accessing the native view in our source in order to layout the native ScrollView.

Since it occurs in the Xamarin framework and we have already logged a defect report, please find the report link below,

https://github.com/xamarin/Xamarin.Forms/issues/5820 
https://github.com/xamarin/Xamarin.Forms/pull/6151 

And it is resolved this issue in Xamarin.Forms version 4.2.0.815419. Please find the release notes below, 

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.2/4.2.0-sr2 

Unfortunately, after upgrading the Xamarin.Forms to v4.2.0.815419, we have encountered the following crash report in the application,

`System.TypeLoadException: Could not load type of field 'Xamarin.Forms.Platform.Android.RendererPool:_freeRenderers' (0) due to: Could not resolve type with token 01000273 from typeref (expected class 'System.Collections.Generic.Stack1' in assembly
`
After further analysis, we found that it is an issue in Xamarin Forms Android platform in this particular version. Please find the bug report link below,

https://github.com/xamarin/Xamarin.Forms/issues/7602 

It is resolved again and now the first issue replicated again in the same scenario. Issue occurs in both 4.2.0.815419 and the latest stable version 4.4.0.991.  

Please let me know if you have any concern

Regards,
Subburaj Pandian V

**Comment by PureWeen** [comment]
@SubburajPandian I feel like there are a few overlapping things here and I don't think anything you are referencing is relevant to your issue.

https://github.com/xamarin/Xamarin.Forms/pull/6151 is just making it so the dispose happen successfully

> System.TypeLoadException: Could not load type of field 'Xamarin.Forms.Platform.Android.RendererPool:_freeRenderers' (0) due to: Could not resolve type with token 01000273 from typeref (expected class 'System.Collections.Generic.Stack1' in assembly

is only related to that particular build of our nuget
https://github.com/xamarin/Xamarin.Forms/issues/7602

> Renderer is not cleared from Xamarin.Forms.ScrollView even if we disposed the native object. 

This is most likely due your control not properly setting up the hierarchy so that our code can navigate the children and detach the renderers. 

All of our controls use a VisualElementPackager and then on dispose it iterates over the children and disposes of the renderers.

I'm not sure how your *SfExpander* is setup but it's on the control to iterate it's children and dispose of the renderers. The forms code can't just descend a hierarchy it doesn't understand
