### ISSUE TITLE
[Bug] [UWP] FontIcons are not aligned correctly

### ISSUE THREAD

**Issue by maexsp** [xamarin/Xamarin.Forms#8606]
### Description
On Xamarin.Forms the Icons from a Fontfile are slightly alligend to the left and top side instead of centered alignment. On Android and iOS is is correctly rendered. On UWP not. 

### Steps to Reproduce

1.  Load the demo application from the attached repo and start it on UWP / Android / iOS and compare the results. Specially on the very first icon of each font the differences are clearly visible (rhomb icon and cogwheel icon). Turn also on the gray background of each icon.

The demo app has two differnt font files included. The materialdesignicons-webfont.ttf from the web and one self extraced icon font fonticonlibrary.ttf extracted via http://fontello.com. 

### Expected Behavior
On UWP the icons should be centered vertically and horizontally sames as on Android and iOS.

### Actual Behavior
UWP font icons are slightly top/left aligned.

### Basic Information

- Version with issue: XF 4.3.0.991211
- Last known good version: 
- IDE: VS2019. latest.
- Platform Target Frameworks: 
  - iOS: Deployment Target 8.0
  - Android: 9.0
  - UWP:  version 1809, build 17763
- Affected Devices: UWP

### Screenshots
<img width="683" alt="Screenshot_UWP" src="https://user-images.githubusercontent.com/15746917/69340080-f7b12280-0c66-11ea-8a00-3ab6fe93d93c.png">

<img width="393" alt="Screenshot_iOS" src="https://user-images.githubusercontent.com/15746917/69340845-a7d35b00-0c68-11ea-9c26-0afa23e6dece.png">

<img width="247" alt="Screenshot_Android" src="https://user-images.githubusercontent.com/15746917/69340852-adc93c00-0c68-11ea-9787-6a96f45d7b99.png">

### Reproduction Link
https://github.com/maexsp/XamarinBase/tree/XamarinFontIcons

**Comment by mgierlasinski** [comment]
@samhouts @maexsp 

It's still present in Xamarin.Forms 5.0.0.1931. Vertical alignment has been fixed in https://github.com/xamarin/Xamarin.Forms/issues/7414. Image is not centered horizontally. Please compare UWP and Android below.

<img src="https://user-images.githubusercontent.com/19707868/107669931-89ed7e00-6c92-11eb-9c2c-290aa50d28a0.png" height="500" /><img src="https://user-images.githubusercontent.com/19707868/107669918-86f28d80-6c92-11eb-948d-738f4470ab7f.jpg" 
height="500" />

Repro project:
[FontImageSourceAlignment.zip](https://github.com/xamarin/Xamarin.Forms/files/5967071/FontImageSourceAlignment.zip)

**Comment by nschoenberg** [comment]
Hi, im on 5.0.0.2012 and facing this issue. I have a icon font that is mono spaced, having a bearing on left and right side. It is working fine on Android and iOS, but not on UWP and I don't know how to resolve it.

Screenshots for your reference:

This is the UWP Version, you can see that the mobile icon in the first row is not centered. All following rows showing the same icons with different implementations / Label Styles. For now I would go with the 2nd row as workarround because that fits best for my scenario. But that means I need a 2nd Label for the text and I cant use spans.

<img width="1101" alt="uwp_iconalignment" src="https://user-images.githubusercontent.com/623690/110462474-0710e500-80d1-11eb-917a-51d87d8c65e6.png">

Same Screen on iOS:
![ios_iconalignment](https://user-images.githubusercontent.com/623690/110462506-15f79780-80d1-11eb-8c29-80c48417bf9f.png)

Same Screen on Android:
![android_iconalignment](https://user-images.githubusercontent.com/623690/110462562-2576e080-80d1-11eb-9f90-15528753094a.png)

**Comment by tonyhallett** [comment]
Change https://github.com/xamarin/Xamarin.Forms/blob/b411491f236c3bf68fe1a07575f3059fb65990ba/Xamarin.Forms.Platform.UAP/FontImageSourceHandler.cs#L45

to `var x = (float)layout.DrawBounds.X - 1;`

This resolves issue although I think for UWP it may be better to just use a TextBlock.  Renderers affected by https://github.com/xamarin/Xamarin.Forms/issues/8293 and https://github.com/xamarin/Xamarin.Forms/issues/14323 can check the type of ImageSource and if FontImageSource can render a TextBlock.

I say may as I have not throughly tested my idea but it appears to work for a ButtonRenderer with a slight adjustment of existing code.

I will add code to mentioned issues shortly.
