### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by susairajs** [xamarin/Xamarin.Forms#8648]
### Description
Hi xamarin team, 
I used Bindable Layout with DataTemplate, inside datatemplate i used Boxview. the boxview height is "HeightRequest=0.5". There are 4 Collection items but all boxview height is not consistent. 

I attached a screenshot with code.
### Steps to Reproduce

`<StackLayout x:Name="PersonList" BindableLayout.ItemsSource="{Binding Persons}"  HorizontalOptions="FillAndExpand">
            <BindableLayout.ItemTemplate>
                <DataTemplate>
                    <Grid RowSpacing="30">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="Auto"/>
                            <RowDefinition Height="0.5"/>
                        </Grid.RowDefinitions>
                        <Label Text="Sample"/>
                        <BoxView Grid.Row="1" HeightRequest="0.5" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" BackgroundColor="Red"/>
                    </Grid>
                </DataTemplate>
            </BindableLayout.ItemTemplate>
        </StackLayout>`

### Expected Behavior
All BoxView height must equal 
### Actual Behavior
Not equal all boxview height
### Basic Information

- IDE: Visual Studio 2019

### Reproduction Link

![bindablelayoutbox issue](https://user-images.githubusercontent.com/22450085/69537894-0a00c880-0fa7-11ea-8809-c63b403e39e3.PNG)

**Comment by jfversluis** [comment]
Hi @susairajs are you referring to the separator lines?

I think what you might be seeing is due to the iOS simulator zoom settings. If you don't set it to 100% you might see some weird visual things with small sizes like that. If you drag the Simulator bigger or smaller this will probably change. If you want to check if it's accurate you can press CMD + 2 with the Simulator active to make it size to "Point Accurate" which should show the right result.

The other thing you could try is run it on a physical device and see how it looks there.

If this is not what you mean, please explain a bit more and a reproduction project would be really helpful with that. Also, please update the issue with a relevant title.

Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by ChristopherStephan** [comment]
This issue is still occurring with Xamarin.Forms 5.0. The HeightRequest with a value of 0,5 for a BoxView is problematic in two ways. Sometimes it does not get rendered at all, sometimes the visual appearance is inconsistent.
