### ISSUE TITLE
top tabbar search handler doesn't change values[Bug] 

### ISSUE THREAD

**Issue by undercabre** [xamarin/Xamarin.Forms#8734]
1. Open xaminals
2. Write in dogs or cats(as you can see, data doesn't change)

- Platform Target Frameworks: 
  - Android: 9.0
- Nuget Packages:Xamarin.Forms(4.2.0.709249)
- Tested in Xiaomi Mi A2

**Comment by PureWeen** [comment]
@undercabre that's not a bug. That's just not how it's been implemented on Xaminals

 Currently Xaminals just pops up what you're typing it doesn't tie the query to the CollectionView

It would just need to be modified so that *OnQuerychanged* from the search handler propagates changes to the CollectionView

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/search
