### ISSUE TITLE
Hot Reload Not working when enabled - No Errors Thrown

### ISSUE THREAD

**Issue by RyanGaudion** [xamarin/Xamarin.Forms#8739]
### Description
I have enabled hot reload in visual studio for xamarin. When I make a change and save, nothing happens. No errors are thrown. If I go to the xamarin logs I get the following:

Xamarin.HotReload|Information|0|2019-12-04 14:15:16.3 Hot Reload IDE Extension Loaded
Xamarin.HotReload|Warning|0|2019-12-04 14:28:19.8 Could not find startup project.

That's all there is for HotReload. This happens to all my projects so I can't show a way to reproduce.

### Basic Information

Visual Studio Version 4.8.03761
Xamarin Version - 16.4.000.305

**Comment by PureWeen** [comment]
@RyanGaudion there's a possibility that your .vs cache is interfering with the ability to find the startup project

Can you try deleting the .vs/obj/bin folders and see if that works?

If you're still having an issue then can you log this issue through the feedback tool on Visual Studio? That will hopefully gather some logs or additional information to help debug

**Comment by drasticactions** [comment]
@RyanGaudion For additional context, judging by that log, Hot Reload couldn't find the startup project for the one you deployed. Since we use the VS APIs for finding that project, most likely it's either using cached data _or_ the project is in a place where we can't find it (such as maybe a fileshare). So, clearing your `.vs` folder in your solution/project should let us find it again. 

If that doesn't work, this is a Xamarin Hot Reload issue and not Xamarin.Forms itself, so if you file this through the feedback tool, we can take a look at it there with additional logs that'll help us debug it.
