### ISSUE TITLE
[Enhancement] Azure DevOps - support for Android App Bundles

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8810]
## Summary
Currently, on Azure DevOps there is no support for Android App Bundles. Task "XamarinAndroid@1" does not support the new publishing format on Google Play (.aab). It's nice that you have added support for AAB in Visual Studio 16.4, but it should be also supported on Azure DevOps.

## Intended Use Case
AAB's have a lot of benefits compared to APK's. It's bad that you cannot build your apps on Azure DevOps using new publishing format on Android.

**Comment by brendanzagaeski** [comment]
Thanks for the report! The best place track this request will be on Visual Studio Developer Community under the Azure DevOps section.

In particular, I believe the following item matches what you're looking for, so when you get a chance, you can upvote and follow it to let the team know you're also interested:

https://developercommunity.visualstudio.com/idea/756675/azure-devops-pipeline-publish-android-bundle-to-go.html

Thanks!

**Comment by dansiegel** [comment]
> Thanks for the report! The best place track this request will be on Visual Studio Developer Community under the Azure DevOps section.

@brendanzagaeski this is not something that should be added to the Developer Community because it's not needed. 

@Mikilll94 Support for AAB vs APK is entirely supported via MSBuild and therefore is up to you to determine when/where you want it. It is something that you can configure in your project by default, by build configuration or simply leave it up to an optional Build Parameter which you can pass in the Azure DevOps task. The following bit is all you need to add to your Android's csproj. 

```xml
<PropertyGroup>
  <AndroidPackageFormat>aab</AndroidPackageFormat>
</PropertyGroup>
```

**Comment by brendanzagaeski** [comment]
Ah ha. Thanks for that additional comment! That made me reread this issue a few more times, and now I think the Developer Community item I linked doesn't quite match the request here.

The existing Developer Community item I linked mentions the Google APIs, but I think this issue is about an earlier step. In particular, the Xamarin.Android task has a dedicated boolean input `createAppPackage`, described as *Passes the target (/t:PackageForAndroid) during build to generate an APK*:

![image](https://user-images.githubusercontent.com/4934473/70964323-42dd0c00-2040-11ea-92d1-2e5cb384d8e1.png)

So I think the question on this issue might be whether it would be best to surface the option for picking APK vs. Android App Bundle in that same way, as a specific option on the Xamarin.Android task, rather than having to add the `AndroidPackageFormat` MSBuild property by hand via the `msbuildArguments` parameter (or in the *.csproj* file).

I noticed that the GitHub repository for the Azure Pipelines tasks allows GitHub issues, so I submitted a corresponding feature request there for further tracking: <https://github.com/microsoft/azure-pipelines-tasks/issues/11985>.
