### ISSUE TITLE
[Bug][iOS][Android] SwipeItems selection on CarouselView incorrect

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#8833]
### Description

I've attached a `SwipeView` to a `CarouselView` and the items in my `TopItems` and `BottomItems` collections aren't rendering correctly. However, the swipe items appear by swiping from the top/bottom of the page, rather than the top/bottom of the `CarouselView` items. Then the swipe items occupy the full page.

My guess is this is because the `CarouselView` occupies the full page, despite the fact that the `CarouselView` items are centered horizontally and vertically.

Note that this occurs on both iOS and Android.

### Steps to Reproduce

1. Run the attached sample (either platform).
2. Browse to the context menu items page (bottom of table).
3. Swipe from the top down, or bottom up to render the swipe items. Note that you have to swipe from the top/bottom of the page, rather than the top/bottom of the item being displayed.

### Expected Behavior

Swipe from top/bottom of the item being displayed, to reveal swipe items that are only rendered where the CarouselView item was.

### Actual Behavior

Swipe from top/bottom of the page, to reveal swipe items that are rendered on the full page.

### Basic Information

- Version with issue: 4.4-pre3
- IDE: VSMac 8.3.10
- Platform Target Frameworks: 
  - iOS: 13.2
  - Android: API 28

### Screenshots

I've only included Android screenshots, as it's problematic to take iOS screenshots.

Swipe top down:

![Screenshot_1575995504](https://user-images.githubusercontent.com/8092460/70549048-7d8c0380-1b6b-11ea-9ee8-3a4a662ce8ce.png)

Eventually the swipe item fills the page:

![Screenshot_1575995498](https://user-images.githubusercontent.com/8092460/70549558-52ee7a80-1b6c-11ea-860b-9be8ddaf4b73.png)

Swipe bottom up:

![Screenshot_1575995510](https://user-images.githubusercontent.com/8092460/70549582-5bdf4c00-1b6c-11ea-9f81-c533b5268f6b.png)

Eventually the swipe item fills the page:

![Screenshot_1575995508](https://user-images.githubusercontent.com/8092460/70549601-639ef080-1b6c-11ea-8989-78b1aae337fc.png)

### Reproduction Link

[CarouselViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3946073/CarouselViewDemos.zip)

**Comment by kingces95** [comment]
It happens but only on the first item. If you swipe left or right then it starts working as expected.

**Comment by jsuarezruiz** [comment]
I have done several tests and I think this issue is the same as https://github.com/xamarin/Xamarin.Forms/issues/8640
We have to decide what to do in this case, how to manage the size of the CarouselView.

Like in #8640, the CarouselView occupies the entire size of the page. For this reason, the behavior for displaying SwipeItems is the following:
![issue8833-1](https://user-images.githubusercontent.com/6755973/81284708-bd91dc80-905e-11ea-9044-cfca55c8ab91.gif)

If we change the size of the Carousel, we see that SwipeItems adjust to its size.
![issue8833-2](https://user-images.githubusercontent.com/6755973/81284711-be2a7300-905e-11ea-8763-a508da31fa41.gif)

I think the expected result was something like:
![issue8833-3](https://user-images.githubusercontent.com/6755973/81284714-bf5ba000-905e-11ea-8408-210887832f71.gif)

This can be achieved using `SwipeItemView` instead of `SwipeItem` because this way you can modify aspects related to the Layout (margins, corner radius etc)
