### ISSUE TITLE
[Bug]  layout gets expanded when the Grid Children has been cleared and added with GridLength as Auto

### ISSUE THREAD

**Issue by RabhiaBehamK** [xamarin/Xamarin.Forms#8932]
### Description

The layout gets expanded when the Grid Children has been cleared and added with GridLength as Auto.

### Steps to Reproduce

1.  Any Custom Control with three different Layouts.
2. Press the Cancel Button in the sample.
3.  The Layout gets expanded in the ReasonforVisit Block.

### Expected Behavior

The Layout should not get expanded.

### Actual Behavior

The Layout gets expanded.

### Basic Information

- Version with issue: 4.4.0.991265
- Platform Target Frameworks:  Xamarin.Forms Android.
                                                        Android: 8.1
- Affected Devices: All devices

### Screenshots

<img width="324" alt="Screenshot 2019-12-17 at 9 19 35 PM" src="https://user-images.githubusercontent.com/39405635/71014274-b30a9100-2117-11ea-90ad-6ce98f5e8a44.png">

<img width="317" alt="Screenshot 2019-12-17 at 9 20 38 PM" src="https://user-images.githubusercontent.com/39405635/71014264-af770a00-2117-11ea-8398-0f56ee494bae.png">

### Reproduction Link

[CustomEntry.zip](https://github.com/xamarin/Xamarin.Forms/files/3974310/CustomEntry.zip)

**Comment by HemalathaMarikuma-syncfusion** [comment]
@samhouts  - Please consider this as a high priority and provide a fix ASAP or if any other workaround to resolve this which is more appreciatable.

**Comment by hartez** [comment]
This issue doesn't appear to have anything to do with GridLength.Auto. The issue is with your CustomEditText control. Notice that if you add a Forms Entry to the last position (instead of your custom control), there is no shifting around when the Grid reloads.

You CustomEditText control appears to be trying to achieve a layout where the EditText is half the height of the control and the TextView is the other half. Right now you're doing this in an OnLayout override with a lot of manual code. I suspect that you're running into some timing and layout pass issues. The first time through, your EditText control is taking up far more than 50% of the height of the control. The second time it's loaded, the EditText and TextView are each taking up 50%, which results in the "shift" you're seeing. 

Anyway, I think you can fix this by:

1. removing your OnLayout override entirely
2. in the Initialize method, between `textView.SetBackgroundColor(Color.Orange);` and `linearLayout.Orientation = Orientation.Vertical;`, add the following code:

```
LinearLayout.LayoutParams param = new LinearLayout.LayoutParams(
	LayoutParams.MatchParent,
	LayoutParams.MatchParent,
	1.0f
);

editText.LayoutParameters = param;
textView.LayoutParameters = param;
```

This will tell your control to give the EditText and TextView controls the same width as the parent LinearLayout, and to divide the height between them evenly (giving each a weight coefficient of 1). 

Do that, and your control will display the same layout before and after you press the Cancel button.

If that doesn't work, let us know and we'll reopen this issue.

**Comment by RabhiaBehamK** [comment]
@hartez , we have considered your solution but since we have a complex layout structure (multiple innner element) we have considered the OnLayout measurement for providing the measured modified height and width of inner element to have a desired view.

Hence without having OnLayout , we can't get proper sizing for child element. Hence any other way to resolve this.

**Comment by hartez** [comment]
Can you tell me why you are trying to build a custom control with an EditText and a TextView? What is the goal? What is the control supposed to do?

**Comment by RabhiaBehamK** [comment]
@hartez, we have a custom ComboBox control layout with 2 children. One for EditText to type letters and another one is a click button to display DropDownItems. 

For this purpose, we only used 2 children in the native. Can you check and let us know the details, please?

**Comment by RabhiaBehamK** [comment]
@hartez , any updates?

**Comment by RabhiaBehamK** [comment]
Please consider this as a high priority and provide a fix ASAP or if any other workaround to resolve this which is more appreciable.
