### ISSUE TITLE
[Bug] [SwipeView] Changing SwipeMode changes the width of the SwipeItem

### ISSUE THREAD

**Issue by czuck** [xamarin/Xamarin.Forms#8941]
### Description
Changing the SwipeMode from Reveal to Execute changes the width of the associated SwipeItem.  This is an issue on both Android and iOS.

### Steps to Reproduce

1. Run the SwipeView Demo.  Choose the Mode and Behavior page. When set to reveal the image looks like this:
![image](https://user-images.githubusercontent.com/1641428/71043271-fb5b8c00-20e2-11ea-8a18-b8ef4d23eda8.png)

2. Shange the SwipeMode to Execute, now it looks like this:
![image](https://user-images.githubusercontent.com/1641428/71043315-28a83a00-20e3-11ea-9d62-f3d82443532e.png)
note - I also had to change the SwipeBehaviorOnInvoked to be able to capture the image, but this does not affect the width of the SwipeItem

3.  This issue is even more evident looking at two items:
![image](https://user-images.githubusercontent.com/1641428/71105545-9b142b00-2172-11ea-80f4-dba9e2faddca.png)
![image](https://user-images.githubusercontent.com/1641428/71105690-d3b40480-2172-11ea-9499-7fa251eaeefa.png)

### Expected Behavior
Changing the mode should not change the item itself.

**Comment by jsuarezruiz** [comment]
Currently the SwipeView applies different sizes to SwipeItems depending on certain conditions.
Using SwipeItem:
- If Mode is Reveal, it will apply a fixed width by default. The SwipeThreshold needed to open the SwipeView is 80% of the width of the SwipeItems.
- If the Mode is Execute, the width of the SwipeView is used. If there are N SwipeItems, the width is divided between each element. That's why in your example, each SwipeItem occupies half the width of the SwipeView in Execute mode.

Then we have SwipeItemView. In this case a View is used and can set a custom width. So, the SwipeThreshold is 80% of the width.

We can avoid this problem in several ways:
- Setting the same behavior using SwipeItems regardless of mode. The _"problem"_ is that in Reveal mode the swipe will be small and this mode is usually used with important actions (delete, etc).
- Allow to define the SwipeThreshold https://github.com/xamarin/Xamarin.Forms/issues/8974. I like this option.

For now, you can use the Execute Mode with SwipeItemView and define the width you need. In this way I am sure you can achieve the desired result.

**Comment by czuck** [comment]
@jsuarezruiz my concern with this design is with a single item, the user has to swipe about 2/5 the way across the screen before there is any indication of what the swipe does.  The first few times I tested this I didn't see the item because I didn't swipe far enough.  Then there is a much smaller distance past the item that the user can move before the action is executed.  When a second item is added, the second item is never visible because the maximum swipe pull, which looks to be about 2/3 the width of the SwipeView, is not enough to reveal the second icon.  To fix this issue I would use the maximum width of the swipe reveal rather than the width of the full SwipeView to determine the width of the SwipeItems.
My personal preference would be to position the SwipeItem at the edge of the SwipeView rather than the center so when the user starts their swipe they see that something is there.  They can fully reveal the item without triggering the action, but swiping a particular distance past the item causes the execution.  If there were two items the items would be stacked together similar to the reveal layout with the extra swipe area following the last item.  Perhaps this could be an optional layout parameter?

Icon is revealed, action is not executed:
![image](https://user-images.githubusercontent.com/1641428/71274453-00018980-2309-11ea-94eb-2b52a5e08736.png)
Swipe continues, now the action is executed (Bold is removed from the title):

![image](https://user-images.githubusercontent.com/1641428/71275050-29221a00-2309-11ea-879f-8f9bb22e79f1.png)
