### ISSUE TITLE
[Bug] ImageSource.FromResource fails in UWP app after update to 4.4.0.991265

### ISSUE THREAD

**Issue by vicocz** [xamarin/Xamarin.Forms#9002]
### Description
There seem to be a recent change in 4.4.0.991265 causing UWP application to fail via call of `ImageSource.FromResource("buwizz_image.png");` which crashes due to the `System.Reflection.TargetException`. Such call used to be working in 4.3. Seems the root cause is  reflection used when `sourceAssembly` parameter is null reference.

Example of the exception:
`System.Reflection.TargetException
  HResult=0x80131603
  Message=Exception of type 'System.Reflection.TargetException' was thrown.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Xamarin.Forms.ImageSource.FromResource(String resource, Assembly sourceAssembly)
   at BrickController2.UI.MarkupExtensions.ImageResourceExtension.ProvideValueInternal()
...`

### Steps to Reproduce
1. Having an UWP application and .NET Standard 2.0 dll library
2. Call `ImageSource.FromResource("buwizz_image.png");` from that dll library

### Expected Behavior
Image is properly loaded for UWP (as it works for Android and iOS)

### Actual Behavior
Exception `System.Reflection.TargetException` is thrown due to reflection is used.

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: 4.3.0.947036
- IDE: Visual Studio 16.4.0
- Platform Target Frameworks: 
  - UWP:  TargetPlatformMinVersion: 10.0.16299.0
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms 4.4.0.991265
- Affected Devices: Windows 10 1803

### Reproduction Link
It's kind a regression #1362
https://github.com/xamarin/Xamarin.Forms/issues/1362

**Comment by samhouts** [comment]
@vicocz Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by 3wiggle** [comment]
This just surfaced for me on 'several' UWP projects... setting up collection of store apps of similar nature.  All using playing card images plus a bit of branding imagery.  WITH multi-platform as well as mult-App.... worked/desire to place all imagery into PCL.   Everything worked/works as advertised UNTIL packaged and tested as 'release' build.  AGAIN: Works fine in DEBUG Android & UWP .... throw said exception in UWP release build ONLY!) ... cannot publish and now late for product release by 2 weeks... PLEASE ADVISE SOONEST!  

PS:  use of parchment.jpg (rather than PNG) is temporary test to clear image format condition.
PSS:
Adopted AbsoluteLayout as UI container, with most all element construction performed in C#....  HOWEVER, the MainPage(PCL) included uses XAML with image source call in cs file as this is a 'barebones' example.   ONLY modification is to a literal string label text value... 
Have test resource load with and without assembly reference... as VAR (shown) and as reflective GetAssembly method call.  
Have tested with images in both PCL and in UWP assemblies... and in UWP assemblies as embedded AND/OR content... NO approach executes on UWP->Release Build only.

REQUESTING... instructions on how to best 'rollback' whatever component will get us back into some  version... where our almost empty main page will function!   

PLEASE: Consider making graphic artifact usage a bit more 'friendly' as well as reliable for this 'graphics orientated development environment'  - been a 'Visual' guy since Visual C++ IDE in the early 1990's... we thought that was complex... (just old bull young bull comment).

HERE is my XAML:
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="GCS.SM.Tricoder.MainPage"
             Title="BackStage">

    <Grid  HorizontalOptions="Center" VerticalOptions="Center">
        <Image Aspect="Fill" x:Name="background"/>
        <StackLayout VerticalOptions="Center">
            <StackLayout Margin="0,20,0,0">
                <Label Text="**APPTITLE" TextColor="Yellow"  HorizontalOptions="Center" VerticalOptions="Start" FontSize="Title" FontAttributes="Italic"  />
                <Label Text="**APPSUBTITLE" TextColor="Yellow"  HorizontalOptions="Center" VerticalOptions="Start" FontSize="Subtitle" FontAttributes="Italic"  />
            </StackLayout>
            <StackLayout Orientation="Horizontal" VerticalOptions="Center"  HorizontalOptions="Center"  Margin="0,25,0,0" HeightRequest="160">
                <Grid HorizontalOptions="Center">
                    <Label Text="Setup"  FontAttributes="Bold" HorizontalOptions="Center" TextColor="Yellow"   />
                    <ImageButton x:Name="btnSettings"  HeightRequest="132" BackgroundColor="Transparent" />
                </Grid>
                <Grid HorizontalOptions="Center">
                    <Label Text="Performance" FontAttributes="Bold" HorizontalOptions="Center" TextColor="Yellow" />
                    <ImageButton x:Name="btnStage" BackgroundColor="Transparent" />
                </Grid>
            </StackLayout>
            <Grid HorizontalOptions="Center" HeightRequest="132" Margin="0,15,0,0">
                <Label Text="Classroom" FontAttributes="Bold" HorizontalOptions="Center" TextColor="Yellow" />
                <ImageButton x:Name="btnSchool" BackgroundColor="Transparent"/>
            </Grid>
        </StackLayout>
    </Grid>
</ContentPage>

  public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
            var assembly = typeof(TriCorder).GetTypeInfo().Assembly;
            //foreach (var res in assembly.GetManifestResourceNames())
            //{
            //  //System.Diagnostics.Debug.WriteLine("found resource: " + res);
            //}

            background.Source = ImageSource.FromResource(Settings.RootPath+"parchment.jpg", assembly);
            background.Source = ImageSource.FromResource(Settings.RootPath + "parchment.jpg");
            btnSchool.Source = ImageSource.FromResource("education.png");
            btnSchool.Clicked += (s, e) => Navigation.PushAsync(new School());
            btnSettings.Source = ImageSource.FromResource(Settings.RootPath + "school.png");
            btnSettings.Clicked += (s, e) => Navigation.PushAsync(new Setup());
            btnStage.Source = ImageSource.FromResource(Settings.RootPath + "Props.png");
            btnStage.Clicked += (s, e) => Navigation.PushAsync(new TriCorder());
        }
    }

Visual Studio About:
Microsoft Visual Studio Community 2019
Version 16.4.2
VisualStudio.16.Release/16.4.2+29613.14
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA689
Microsoft Visual C++ 2019

Arduino IDE for Visual Studio by Visual Micro   19.0
Visual Micro is an Arduino Compatible IDE for Visual Studio 2015-2019. For more information and forum please visit www.visualmicro.com.

ASP.NET and Web Tools 2019   16.4.457.38025
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.4.457.38025
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.4.457.38025
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.4.457.38025
Azure Functions and Web Jobs Tools

C# Tools   3.4.1-beta4-19610-02+c4e5d138903b899477649a17f197abd2bcb22f9e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.10.8.8132
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.21016.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.87+gbb515bf382
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.5.24 (1fafd7e)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Project System Tools   1.0
Tools for working with C#, VisualBasic, and F# projects.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61912.09160
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.7
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

TypeScript Tools   16.0.11031.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.4.1-beta4-19610-02+c4e5d138903b899477649a17f197abd2bcb22f9e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.4.0-beta.19556.5+e7597deb7042710a7142bdccabd6f92b0840d354
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.4.000.307 (d16-4@e031886)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.4.0.464 (remotes/origin/d16-4@4abf337c3)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.4.25 (579ee62)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.1.1.0 (d16-4/f2c9364)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: bef1e63
    Java.Interop: xamarin/java.interop/d16-4@c4e569f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b


Xamarin.iOS and Xamarin.Mac SDK   13.8.3.0 (0d8fe21)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by 3wiggle** [comment]
Reviewing the MainPage.cs I noticed a 'lost brace' after the rem'd section... this is NOT the case with production code...

**Comment by samhouts** [comment]
@3wiggle Any chance you could zip that up into a small project for us? Thanks!

**Comment by hartez** [comment]
@vicocz 
> Call ImageSource.FromResource("buwizz_image.png"); from that dll library

Which overload of `FromResource` are you calling? If you are working with UWP, [you need to be calling the overload which takes an `Assembly` as the second parameter](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=windows#xaml).

**Comment by hartez** [comment]
@3wiggle From the code you pasted, it looks like you also may not be using the correct overload of the method:

>`background.Source = ImageSource.FromResource(Settings.RootPath+"parchment.jpg", assembly);
background.Source = ImageSource.FromResource(Settings.RootPath + "parchment.jpg");
        btnSchool.Source = ImageSource.FromResource("education.png");
        btnSchool.Clicked += (s, e) => Navigation.PushAsync(new School());
        btnSettings.Source = ImageSource.FromResource(Settings.RootPath + "school.png");
        btnSettings.Clicked += (s, e) => Navigation.PushAsync(new Setup());
        btnStage.Source = ImageSource.FromResource(Settings.RootPath + "Props.png");
        btnStage.Clicked += (s, e) => Navigation.PushAsync(new TriCorder());`

You appear to be using it for the first call, but then overwriting the result; subsequent calls don't appear to be using the overload with the assembly parameter.

**Comment by hartez** [comment]
Here's an example app running on 4.4 and using the correct overload; works on UWP in Release mode:
[_9002 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4302185/_9002.Repro.zip)

**Comment by samhouts** [comment]
@vicocz  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by CartBlanche** [comment]
@samhouts, @hartez 

I've just hit this issue where `ImageSource.FromResource` works fine when the **Compile with .Net Native tool chain** flag isn't set and fails because of the lack of the Assembly parameter with**Compile with .Net Native tool chain** is set. This is a very annoying paper cut to hit when you switch to Release mode and this breaks! Then you have to dig around trying to find out why it works in Debug and doesn't in Release. The resource being searched for exists within the current assembly. As I mentioned is works perfectly in Debug mode.

IMO this should Just Work(TM) in Release mode too, but if this is limitation on the compiler side and not how Xamarin.Forms is doing the Resource lookup, then why not just remove(make obsolete) the overload that doesn't have the assembly parameter? That way you write code once and it just works (TM) in both Debug and Release mode! That would mean one less headache when a developer is about to release their app and a better overall user experience with Xamarin.Forms.
