### ISSUE TITLE
[Bug] CarouselView Android Can't Scroll Back when Last Item is Reached

### ISSUE THREAD

**Issue by InnoAhead** [xamarin/Xamarin.Forms#9020]
### Description

On android pie a semicircular blue overlay appears when we try to scroll beyond the last page.

If the last item of the carouselview is reached and we try to swipe back to the previous item, the first time it won't work and we will be bounced back to the last page.

If we reach the last page and we keep trying to swipe beyond the last page let's say N times,
then to swipe back to the previous element we have to swipe  N+1 times and we are bounced back for N times.

### CODE
```
    <CarouselView >
        <CarouselView.ItemTemplate>
            <DataTemplate>
                <ContentView>
                    <Grid>
                        <Label Text="{Binding}"/>
                    </Grid>
                </ContentView>
            </DataTemplate>
        </CarouselView.ItemTemplate>
        
        <CarouselView.ItemsSource>
            <x:Array Type="{x:Type x:String}">
                <x:String>Hello</x:String>
                <x:String>World</x:String>
            </x:Array>
        </CarouselView.ItemsSource>

    </CarouselView>
```
### Expected Behavior

1 swipe to get back to the previous page

### Actual Behavior

N +1 swipes to get back to the previous page if the last page is reached and we try N times to swipe beyond the last page

### Basic Information

- Version with issue: 4.4.0.991265
- IDE: Visual studio 2019
- Platform: Android: MonoAndroid 9.0, API 28, executing on Android Pie

**Comment by timahrentlov** [comment]
I see this as well.

**Comment by heebaek** [comment]
me too

**Comment by InnoAhead** [comment]
Is there any workaround i can use right now?

**Comment by Pemmican-Pete** [comment]
I see it too.

**Comment by jfversluis** [comment]
Confirmed this is happening in last stable and also our nightly. It's a bit hard to spot. Watch the screen recording below.

![Screen Recording 2020-01-10 at 22 03 49](https://user-images.githubusercontent.com/939291/72186533-c991c880-33f5-11ea-8c0c-6e43b4a87435.gif)

Notice how I scroll to the end of 3 items. Then I scroll "past" the last item, spawning the blue Android bubble. Because of the overscroll, when I try to scroll back, it blocks me and shows the last option again. After it flipped back, then I am able to scroll back to the previous item.

From the original issue: if you overscroll N times, it will take you N+1 times to be able to get past the flicker and actual scroll back to the previous item. I have seen that behavior, but not consistently.

I was going to suggest to to set `IsBounceEnabled` to false as a possibility to get past this, but I noticed that this doesn't work too. I will open a new issue for that.
