### ISSUE TITLE
Can't launch app in release mode

### ISSUE THREAD

**Issue by MuziburRahman** [xamarin/Xamarin.Forms#9059]
Even a blank app doesn't launch in release mode.

### Steps to Reproduce

1. Create a blank app with android and UWP,
2. Change the mode to release,
3. now press F5 to build and run the app.

- When the UWP project is set as the start-up project, hitting F5 builds and attemts to launch the app. But the app and the Visual Studio both become unresponsive. There's a small window in Visual Studio that says "Loading symbols for SharedLibrary.dll" and it never finishes.

- When the android project is set as the start-up project, hitting F5 starts building and immediately cancels building. The output window logs these messages:

> 1>------ Build started: Project: TestApp.Android, Configuration: Release Any CPU ------
> Build has been canceled.

- Version with issue: Xamarin.Forms 4.4.0.991265 , Xamarin.Essentials 1.3.1, NetStandard 2.0.3, Microsoft.NETCore.UniversalWindowsPlatform 6.2.9
- IDE: Visual Studio Community 16.4.0
- Platform Target Frameworks: 
  - Android: Compile using: Android 9.0 (Pie)
  - UWP:  Target : 17763

**Comment by hartez** [comment]
@MuziburRahman I can't seem to reproduce your issue with UWP; if I create a blank app, change to Release, and hit F5 to launch, it launches. It _does_ take a few minutes, but it launches.

For Android, I _am_ seeing `Build has been canceled`, but that's because my Android 9.0 emulator is x86 and the default architectures for the project are armeabi-v7a and arm64-v8a. If you look at the `Errors` tab in Visual Studio, is there an error about incompatible architectures? You may need to open the Android project properties, go to the Android Options tab, click Advanced, and add x86 to the "Supported architectures" list.

**Comment by MuziburRahman** [comment]
thanks. The UWP is working today and the android part is exactly what you said. I didn't see any error message yesterday, but it is showing he error today. Strange.
