### ISSUE TITLE
Window.Current.Activate Exception

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9104]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/864884/windowcurrentactivate-exception.html)._

---
In a cross-platform Xamarin UWP app, Window.Current.Activate is encountering an exception which appears to be a {"Object reference not set to an instance of an object."}. See attachments.

---
#### Marc W. George on 12/21/2019, 05:42 AM: 

(private comment, text removed)
#### Visual Studio Feedback System on 12/23/2019, 01:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Marc W. George on 12/31/2019, 04:51 AM: 

See https://github.com/ericsink/SQLitePCL.raw/issues/322 for further details...

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by alaskanrogue** [comment]
Demo attached. Cleaned with bin/obj folders deleted, ready to build and debug. 
[UWP_Error.zip](https://github.com/xamarin/Xamarin.Forms/files/4050089/UWP_Error.zip)

**Comment by rmarinho** [comment]
I think in your `App.xaml.cs`you have something wrong ... You Should navigate the native frame to the UWP MainPage, not the PCL one.

```
    // Establish navigation
            if (rootFrame.Content == null)
            {
                // When the navigation stack isn't restored navigate to the first page,
                // configuring the new page by passing required information as a navigation
                // parameter
                rootFrame.Navigate(typeof(MainPage), e.Arguments);
            }

```

**Comment by alaskanrogue** [comment]
Although I agree that the navigation point should be change, I haven't been able to get to that line because the exception occurs before that call.
![FileNotFoundError](https://user-images.githubusercontent.com/14001196/72286259-c7588580-3612-11ea-8fd0-1f5279bd8131.png)

In Xamarin Forms 4.5.0.142-pre1+sha.5d42b9e3b-azdo.3372978 Init() was working, but I am currently using 4.5.0.142-pre1+sha.5d42b9e3b-azdo.3372978. I just re-debugged with the page name changed, but had the same error results.

**Comment by alaskanrogue** [comment]
As an experiment, I replaced the UWP project of a copy of the current solution version with the UWP project of the solution version which was able to pass the breakpoint, making two slight modifications to the UWP App.xml.cs because of relocation/deletion of called methods. The UWP project retained its Nugget version references. The application failed to pass the breakpoint.

As a second experiment, using the last version of the solution which was able to pass the error point, I created a copy. I then copied the .cs and .xaml files from the current solution PCL. Doing so required the same two slight modifications to the UWP App.xml.cs. The merged version was able to pass the error point.

That experimental project has the older versions of all Nuggets which have changed since they were in use. The version of Xamarin.Forms in use is 4.4.0.936621-pre1 which is dependent on [installed Nugget version]:

UAPVersion=v10.0
Win2D.uwp (>= 1.20.0)
System.ValueTuple (>= 4.5.0) [4.5.0]
NETStandard.Library (>= 2.0.1) [2.0.3]
Microsoft.NETCore.UniversalWindowsPlatform (>= 6.0.15) [6.2.9]
Microsoft.UI.Xaml (>= 2.1.190606001)

What dependencies are used by the Init() method. The experiment can upgrade the Nuggets by each sequential version if necessary to determine the impacts. I am not sure what to do with the dependency components that are not Nuggets.

**Comment by alaskanrogue** [comment]
Continuing with the working project, I was able to upgrade the Xamarin.Forms Nugget to the latest version without the error. Planning on upgrade the NET Nuggets today.

**Comment by rmarinho** [comment]
the SLQ lite issue seems not related with Forms

**Comment by alaskanrogue** [comment]
It is related because the Forms.Init function is at the top of the stack in error.

**Comment by alaskanrogue** [comment]
Having proceeded with going back to the last working version and sequentially reapplying all Nuggets through their versions in both the PCL and UWP projects, including Forms, I have a working version of the UWP project.

**Comment by ChrisProlls** [comment]
The same error occurs in our side with a ASP.NET Core project and the EF Core library.

**Comment by samhouts** [comment]
@alaskanrogue I'm having trouble following the status here. What version of Xamarin.Forms is working? What version is broken? Thanks!

**Comment by DancesWithDingo** [comment]
﻿
The last build in which it worked was 4.3.0.991250. Versions beyond that don’t work.

**Comment by alaskanrogue** [comment]
@samhouts At this moment, given the solution process that I took of going back to the last working version and upgrading version by version all of the Nuggets, the app is operational and working with their latest versions. For me, problem closed.

**Comment by samhouts** [comment]
@alaskanrogue Thanks for the update! Let us know if you experience any other trouble.
