### ISSUE TITLE
[Bug] ListView makes crash while enable HasUnevenRows property

### ISSUE THREAD

**Issue by Sasikumar3595** [xamarin/Xamarin.Forms#9139]
### Description
We are using ListView with item template as SfCalendar(syncfusion calendar) in Xamarin forms iOS, enable the HasUnevenRows property makes application crash. We are validated with SfCalendar source and crash raised on SfCalendar Layout Subviews. Layout subviews called on disposed SfCalendar because of ListView.

Provide suggestion for resolve the issue as soon as possible
### Steps to Reproduce

1. Create the sample with ListView and its itemTemplate as SfCalendar
2. Enable the HasUnevenRows property for list view
3. Run the sample and the crash raised.

### Expected Behavior

- Application Working correctly with out crash

### Actual Behavior

- Application crashed

### Reproduction Link

Sample: [InlineViewSample.zip](https://github.com/xamarin/Xamarin.Forms/files/4040185/InlineViewSample.zip)

**Comment by hartez** [comment]
@Sasikumar3595 I'm trying to reproduce the issue, but when I run the attached sample I'm not seeing the application crash. Which version of iOS are you seeing the problem on? Which devices?

**Comment by Indumathi1195R** [comment]
Hi @hartez ,

**Device details:**
We have checked with the iPhone 8- 12.1 version simulator.

**Stacktrace details:**
We have attached the stack trace for the same. 
![Screenshot (49)](https://user-images.githubusercontent.com/54974849/72126947-fc0ad980-3393-11ea-937f-04b3d8c55e76.png)

**Code Snippet:**
 public MainPage()
        {
            InitializeComponent();
            DateTime dateTime = new DateTime(2015, 03, 05);
            NameCollection = new List<NameModel>();
            for (int i = 0; i < 4; i++)
            {
                var date = dateTime;
                date = date.AddDays(i);
                NameCollection.Add(new NameModel(date) { Name = "Brooklyn" });
                //NameCollection.Add(new NameModel(date) { Name = "James" });
                //NameCollection.Add(new NameModel(date) { Name = "Stehpen" });
                //NameCollection.Add(new NameModel(date) { Name = "Daniel" });
                //NameCollection.Add(new NameModel(date) { Name = "Willams" });
            }
            listView.ItemsSource = NameCollection;
            listView.BindingContext = this;
        }

Due to the virtualization , it was crashed not from the SfCalendar. When set the i<3 it is working fine.

**Crash Video:**
We have attached the crash reproducing video. 
[video.zip](https://github.com/xamarin/Xamarin.Forms/files/4044000/video.zip)

**Sample:**
Once we have attached the sample for reproducing the crash.
[InlineViewSample.zip](https://github.com/xamarin/Xamarin.Forms/files/4044051/InlineViewSample.zip)

**Comment by hartez** [comment]
I've tried this on an iPhone 8 12.4 simulator, and I'm still not seeing a crash. Also, the crash you show in the video appears to be an exception thrown by the SFCalendar control. Perhaps you should open a bug  with Syncfusion.

**Comment by hartez** [comment]
Also, does the error persist if you update to a more recent version of Xamarin.Forms?

**Comment by Indumathi1195R** [comment]
Hi @hartez ,

Thanks for the update. We have updated the Xamarin.Forms version to the latest, now it is working fine.

**Comment by hartez** [comment]
@Indumathi1195R Glad to hear it!
