### ISSUE TITLE
[Bug] ExportFontAttribute has unused properties

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#9255]
### Description

The `ExportFontAttribute` class has three properties. However, the `Alias` and `EmbeddedFontResourceId` properties are unused.

### Basic Information

- Version with issue: 4.5-pre1

**Comment by samhouts** [comment]
@Clancey Are you aware of this?

**Comment by dansiegel** [comment]
I know in talking with @Clancey on this, he noticed that issue while working on a fix for pre-1... funny thing is it all worked during his streams... so something got lost during all of the rebasing before it finally got merged... 

As far as Alias... I know that was something I had originally bugged him about during the live streams... but the whole idea is that if your font file is FontAwesome5Free-Regular.otf and you wanted to just call it FAR you could. Less keystrokes is nice. That said from discussing it with Clancey it should in theory just load the font by the asset filename x-plat which is really the ultimate goal rather than the platform specific nonsense that we have to use now.

Ultimately Alias either needs to be pulled out for pre2 assuming we can just use the file name... or re-implement it.

As for the EmbeddedFontResourceId... I don't really see the point of having the bloat, it should just pick up the file by the name as long as you put it there.

**Comment by samhouts** [comment]
Yeah, it was a gnarly rebase. :/

**Comment by samhouts** [comment]
closed by #9194
