### ISSUE TITLE
[Bug] Frame's shadow in Absolute Layout not hidden when IsVisible="False" on iOS.

### ISSUE THREAD

**Issue by StevenGranados** [xamarin/Xamarin.Forms#9519]
### Description
Frame contents disappear, but leave a frame with a shadow behind.
I think PR #7518 is something to do with it.
Related: #8567
Edit: The frame border does disappear, but only the shadow remains. If HasShadow=false and IsVisible =false, the shadow disappears.
### Expected Behavior
Frame shadow Disappears along with content.
### Actual Behavior
Frame Content and frame disappear but frame's shadow doesn't.
### Basic Information

- Version with issue: 4.5.0-pre1/4.5.0-pre4
- Last known good version:4.4.991640
- IDE: Visual Studio 16.4.4
- Platform Target Frameworks: 
  - iOS:  13.3
  - Android: N/A
  - UWP:  N/A
- Nuget Packages: Essentials
- Affected Devices:iPhone 8

### Screenshots

IsVisible="True"
![2020-02-11_12-59-25-PM](https://user-images.githubusercontent.com/51818199/74238762-5b7b4280-4cce-11ea-97b1-c9e430e310fa.png)
IsVisible="False"
![2020-02-11_12-59-06-PM](https://user-images.githubusercontent.com/51818199/74238775-6209ba00-4cce-11ea-961b-ef8b28b5e1aa.png)

### Reproduction Link
[FrameVisibility.zip](https://github.com/xamarin/Xamarin.Forms/files/4185761/FrameVisibility.zip)
### Workaround
Place Frame in a StackLayout or set HasShadow to false as well.

**Comment by tmijieux** [comment]
Hi, i updated recently to Xamarin.Forms 4.5 (nuget version "4.5.0.356") and I happen to have the same bug.

@StevenGranados 
Contrary to what you said in your "Edit" it seems, in my code, the problem is not only with the shadow:  The background color and border color is drawn as well.


![code](https://user-images.githubusercontent.com/518039/75777658-a2e97180-5d56-11ea-9d74-8efee3984396.png)
If I uncomment le HasShadow = false line, the frame is correctly hidden as it was suggested by the OP.
![IMG_0005](https://user-images.githubusercontent.com/518039/75777659-a3820800-5d56-11ea-9e6f-bad2a1c648ec.PNG)

**Comment by StevenGranados** [comment]
Closed since fixed in nightly.
