### ISSUE TITLE
[Bug] Binding doesn't working in behaviours.

### ISSUE THREAD

**Issue by StevenGranados** [xamarin/Xamarin.Forms#9610]
### Description
Trying to use binding to control a behaviour doesn't work in android and iOS. 
I had it working in android in my project, but the repro doesn't work in both.
Edit:
I've had a bit more of a play, and if the binding is changed from 
```
IsRotating="{Binding Working}"
```
to
```
IsRotating="{Binding BindingContext.Working, Source={x:Reference label}}"
```
Then it works as expected. Is this expected?
Changing the line to 
```
IsRotating="{Binding Working, Source={x:RelativeSource Mode=FindAncestorBindingContext, AncestorType={x:Type local:ViewModel}}}"
```
gives errors of
```
System.InvalidOperationException: 'Operation is not valid due to the current state of the object.'
```
Is this a bug?
My project uses this binding
``` 
IsRotating="{Binding CurrentItem.Working, Source={x:Reference carousel}}"
```
and only fails in iOS. So possibly a bug in the CurrentItem in CarouselView on iOS? Maybe it's null when it shouldn't be? #9500 might help with this.
Apologies for the several bugs in one, but I'm not sure what the correct thing to do is.
### Steps to Reproduce

1. Run repro.
2. Click first button. "Working" label becomes visible to show that binding works.
3. Click second button to see that behaviour works if property is changed manually.

### Expected Behavior
"Xamarin" label spins, when property binding changes.
### Actual Behavior
"Xamarin label does not spin.
### Basic Information

- Version with issue: 4.4.0.991640
- Last known good version: Don't know.
- IDE: Visual Studio 16.4.4
- Platform Target Frameworks: 
  - iOS:  Tried 13.3, 12.4, 11.4
  - Android: Tried API 29
- Nuget Packages: PropertyChanged.Fody 3.2.6
- Affected Devices:Numerous

### Screenshots

![behaviours_issue](https://user-images.githubusercontent.com/51818199/74671353-e2369080-51a2-11ea-8e10-7868641fdc01.gif)

### Reproduction Link
[Behaviours_iOS.zip](https://github.com/xamarin/Xamarin.Forms/files/4214919/Behaviours_iOS.zip)

**Comment by StephaneDelcroix** [comment]
Behaviors and Triggers inherit from BindableObject, but that's was a design mistake. Behavior instances, when applied from Style, can be shared, and so it doesn't make sense to bind to them.

You could expose a property of type BindingBase on your Behavior, and then Clone() and apply the binding when the behavior is applied. that's the closest solution we have

**Comment by IoTFier** [comment]
@StephaneDelcroix - is there a working sample that uses your proposed solution above?

I am wiring an EventToCommandBehavior (via prism mvvm) to the toggled event of a switch used in a DataTemplate serving itemTemplate of a listview.  The binding source of the Command is of type RelativeSource defined using x:Type that points to the viewmodel of the page.
But, getting following exception. 
**System.InvalidOperationException: 'Operation is not valid due to the current state of the object.'**

Do you think this github issue is also applicable in my scenario ?
I would appreciate your thoughts and that working sample.

Thank you.
