### ISSUE TITLE
custom icon for hamburger menu should use svg file

### ISSUE THREAD

**Issue by kssllp** [xamarin/Xamarin.Forms#9622]
I want to replace hamburger menu icon with my custom icon in xamarin.forms shell (android and ios). I want to use svg file of the icon as we are using only **svg** files in our app.

I posted my question on below xamarin forum:
https://forums.xamarin.com/discussion/comment/403438#Comment_403438

Please let me know if it is possible then how I can do it else could you please add this feature in your next release?

Also could you please help me to use svg file in splash screen (Launch screen) and app launcher icon?

**Comment by PureWeen** [comment]
Since we don't support SVG currently the only way to do this would be to create a custom renderer and then set the icon yourself. 

On iOS you can use a ShellPageRendererTracker
On Android you can use a ShellToolbarTracker

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/customrenderers
