### ISSUE TITLE
Picker value cleared when scrolling a CollectionView in iOS

### ISSUE THREAD

**Issue by jrpickett** [xamarin/Xamarin.Forms#9659]
Values selected in a picker are cleared when you scroll down a collection view and then back up.  I found the same issue was logged for the ListView: https://github.com/xamarin/Xamarin.Forms/issues/4250.  I altered the sample from issue 4250 to use a CollectionView and I can reproduce the issue. 

**Steps to Reproduce**

1. Run the sample
2. Scroll down CollectionView items
3. Now scroll the up the CollectionView items and you can see that the picker values cleared.

**Expected Behavior**
Picker values should not clear

**Actual Behavior**
Picker values cleared

**Basic Information**
- Version with issue: Xamarin Forms 4.4.0.991640 and 4.5.0.282-pre4
- IDE: Visual Studio Enterprise 2019 version 16.4.2 on Windows 10
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android: not tested 
  - UWP:  not tested 
- Affected Devices: iPad Air

**Reproduction Link**
[Picker_CollectionView_Issue.zip](https://github.com/xamarin/Xamarin.Forms/files/4233640/Picker_CollectionView_Issue.zip)

**Comment by PureWeen** [comment]
Probably related to this
https://github.com/xamarin/Xamarin.Forms/issues/9200

**Comment by jrpickett** [comment]
I'm using a bindable stacklayout to work around this issue since I don't have very many items in the list. Performance seems to be fine.

**Comment by hartez** [comment]
>I'm using a bindable stacklayout to work around this issue since I don't have very many items in the list. Performance seems to be fine. 

@jrpickett For smaller numbers of items, using a BindableLayout is an excellent choice. The BindableLayout will create instances of all your templated items, rather than using a pool of recycled items like CollectionView does. (See https://github.com/xamarin/Xamarin.Forms/issues/9200#issuecomment-643822589 for a more detailed explanation of what CollectionView is doing.)

If you find later that you need a larger number of items than BindableLayout can handle, you can add a property in your view model for the Picker's selection and bind the Picker to it.

**Comment by programmingworld1** [comment]
Why is this closed? The problem is still not fixed, my picker value gets cleared aswell when scrolling up or down...

**Comment by cmpalmer66** [comment]
Has anyone found a workaround for this one? I just encountered it deep into a redesign and it's killing me. I've basically found the CollectionView to almost unusable on multiple platforms.

**Comment by cmpalmer66** [comment]
Okay, the BindableLayout worked as an alternative. It's a shame that CollectionView has errors on all the platforms, I'm not sure it's usable for anything very complex at this point.

**Comment by programmingworld1** [comment]
> Okay, the BindableLayout worked as an alternative. It's a shame that CollectionView has errors on all the platforms, I'm not sure it's usable for anything very complex at this point.

It's true. BindableLayout works for this. Sorry that I didn't respond faster..

**Comment by abondarenko** [comment]
I don't understand why it's closed actually.
To use BindableLayout is a workaround and it doesn't work fine in all cases.
For example, there is pretty large collection of items in my app and I want tot use ColeectionView instead of BindableLayout because of virtualization and performance improvements. But I can't because of this very, very weird issue.

Any suggections?

**Comment by hartez** [comment]
> Why is this closed? The problem is still not fixed, my picker value gets cleared aswell when scrolling up or down...

@cmpalmer66 @programmingworld1 @abondarenko 

This was closed because it's not a bug. As I suggested [upthread](https://github.com/xamarin/Xamarin.Forms/issues/9659#issuecomment-643825008), you should take a look at the [comments for issue 9200](https://github.com/xamarin/Xamarin.Forms/issues/9200#issuecomment-643822589) for an explanation of why it's not a bug and how to use the CollectionView/CarouselView with data binding to achieve your goal.

**Comment by abondarenko** [comment]
I'm using binding and the thing is binded property is empty after a scrolling.

**Comment by hartez** [comment]
@abondarenko What does your DataTemplate and your Binding look like? Can you post your XAML/code?

**Comment by assanesuzy** [comment]
I am having a problem with this as well in a CarouselView on iOS. we have a picker that get's the SelectedItem cleared when scrolling from the last fragment, the third fragment, to the first, and then back again. The Selected Item is bound to a property using TwoWay binding. Can this be re-opened?

**Comment by Fernando-Braulio** [comment]
March 2022 and the problem still occurs, both for IOS and Android

**Comment by Fernando-Braulio** [comment]
Unfortunately with CollectionView the error occurs, but it is possible to work around using ListView CachingStrategy="RetainElement"

**Comment by Richard-Dufour** [comment]
Dec. 2023 and the problem persists.

**Comment by lightwaver** [comment]
No progress... Very sad...
