### ISSUE TITLE
CollectionView LinearItemsLayout strange behavior on Android[Bug] [CollectionView] [Android]

### ISSUE THREAD

**Issue by dimonovdd** [xamarin/Xamarin.Forms#9681]
### Description
The CollectionView has an unpleasant bug on Android. On UWP and iOS it hasn't been noticed.

When selecting LinearItemsLayout and setting ItemSpacing, the ItemSpacing on Android does not always work

I have created a project to repeat this bug

### Steps to Reproduce

1. Run my test project
2. Open The "Android Bug Page"
3. Click the "add Item" button several times
4. Click the "delete first item" button"

### Reproduction Link

https://github.com/dimonovdd/CollectionViewBug.git

**Comment by jsuarezruiz** [comment]
Thanks for the repro sample. I reproduce the issue, the problem is that the ItemSpacing does not apply well until scrolling.

![issue9681](https://user-images.githubusercontent.com/6755973/75247229-bbdfa900-57d1-11ea-9763-a82cf51306b0.gif)

I have done other tests applying margins, etc. to each item and the same thing happens. The layout is fixed when scrolling, etc.

Seems to be the same issue as https://github.com/xamarin/Xamarin.Forms/issues/9645

**Comment by dimonovdd** [comment]
> Thanks for the repro sample. I reproduce the issue, the problem is that the ItemSpacing does not apply well until scrolling.
> 
> ![issue9681](https://user-images.githubusercontent.com/6755973/75247229-bbdfa900-57d1-11ea-9763-a82cf51306b0.gif)
> 
> I have done other tests applying margins, etc. to each item and the same thing happens. The layout is fixed when scrolling, etc.
> 
> Seems to be the same issue as #9645

As I understood, it is not only connected with scrolling. The ItemSpacing also gets updated when I add several items and then remove the first item (with no scrolling at all).

**Comment by dimonovdd** [comment]
@samhouts  why was this removed from the milestone? this is a very important issue.
