### ISSUE TITLE
[Bug] iOS platform-specific VisualElement Blur is misaligned

### ISSUE THREAD

**Issue by iamlawrencev** [xamarin/Xamarin.Forms#9720]
### Steps to Reproduce

1. Apply VisualElement blur to any view
2. Set that view's VerticalOptions and HorizontalOptions to Center.
3. Observe that the blurred view is rendered as separated from the actual view.

[Gist](https://gist.github.com/iamlawrencev/4052e924f45e254e10ae9fab6a62b7f8)

### Expected Behavior

VisualElement blur should be rendered under the view and should respect its bounds

### Basic Information

- Version with issue: 4.4.0.991640
- Last known good version: N/A
- IDE: Visual Studio Mac 2019
- Platform Target Frameworks: 
  - iOS:  13.2
- Nuget Packages: Xamarin.Forms 4.4.0.991640
- Affected Devices:

### Screenshots

![Simulator Screen Shot - iPhone SE - 2020-02-26 at 14 55 29](https://user-images.githubusercontent.com/14250426/75320046-d042a500-58a8-11ea-847e-269abffb1ac3.png)

### Workaround

Enclose the blurred view using another view (Grid, Stack, etc.) and set the alignment there rather than on the blurred view.

**Comment by jsuarezruiz** [comment]
I attach a sample where the problem is reproduced.

[Issue9720.zip](https://github.com/xamarin/Xamarin.Forms/files/4254425/Issue9720.zip)

<img width="333" alt="Captura de pantalla 2020-02-26 a las 9 49 45" src="https://user-images.githubusercontent.com/6755973/75328035-9f00af80-587d-11ea-909c-8d9638d11977.png">
