### ISSUE TITLE
ListView inside ListView with Grid does not size properly

### ISSUE THREAD

**Issue by PaulSinnema** [xamarin/Xamarin.Forms#9831]
### Description

When you put a ListView inside a ListView it does not size properly on Android and UWP. Furthermore the way the view sizes is different on Android and UWP.

### Steps to Reproduce

1. I've put together a sample project and added it to this bug report.

### Expected Behavior
Difficult to say how it should size. My guess is that Height="*" should take up all the space it can take. 

### Actual Behavior
It does this somewhat on UWP but not at all on Android.

### Basic Information

- Version with issue: 4.5.0.356
- Last known good version: None
- IDE: Visual Studio 2019
- Platform Target Frameworks: Android and UWP (Haven't been able to test on iOS yet).
  - Android: Minimum 5.0 Target 9.0
  - UWP:  16299 
- Affected Devices: Huawei P30 Pro, Emulator pixel_2_pie_9_0_-_api_28_1 (Android 9.0)
[ListViewProblem.zip](https://github.com/xamarin/Xamarin.Forms/files/4285957/ListViewProblem.zip)

**Comment by Robbert-jansen** [comment]
I don't think you're supposed to nest listviews for this exact reason.

What is it you're trying to achieve?

**Comment by hartez** [comment]
> My guess is that Height="*" should take up all the space it can take.
In a vertically scrolling list, "all the space it can take" == "infinity". So I don't think that's really what we're looking for. 

What layout are you trying to achieve? Nested ListViews isn't really a supported scenario, but perhaps you goal can be achieved some other way.

**Comment by PaulSinnema** [comment]
Hmmm we can't nest ListViews? Why not? My model looks like this:

SetList 1 => n Set 1 => n SetItem 1 =>1 Song

I need to display the SetList with all Sets with all Setitems and the Song. Can I achieve this without using nested ListViews?

**Comment by Robbert-jansen** [comment]
I've modified your MainPage, can you see if this is what you wanted?

There is also a scrollable version that you can try out,.

[MainPage.zip](https://github.com/xamarin/Xamarin.Forms/files/4292640/MainPage.zip)

**Comment by PaulSinnema** [comment]
It is a bit counter intuitive but your suggestion works. It this is the way to program nested lists then what is the purpose of the ListView? I'm an ASP.Net MVC developer and the Repeater looks a bit like the ListView and can be nested. I would expect nesting of ListView to be supported.

**Comment by Robbert-jansen** [comment]
I'm not sure, Listview is a little weird at times.
I think It's mostly meant for very simple lists of data, for anything more you should probably use [CollectionView](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/introduction), it's alot much more flexible and powerful, but it isn't fully supported on UWP.
But i think it allows nesting, so  it's probably worth checking out.

**Comment by hartez** [comment]
Yes, CollectionView allows nesting, and nesting is considered a "supported" scenario. 

Nesting with ListView isn't "supported" for a bunch of historical and backward-compatibility reasons. Which basically means that while it might sort of work in some situations, it wasn't originally designed with that in mind; you might well hit a problem we can't fix without breaking things.

Also, keep in mind that ListView and CollectionView are built to support virtualization so that very large sets of items can be displayed efficiently. If you're working with smaller sets of items, a [BindableLayout](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/bindable-layouts) using a StackLayout or FlexLayout might be a better fit. And you can combine these - depending on your requirements, it may make sense for your SetList to be a CollectionView where the ItemTemplate includes Bindable Stacklayout of Sets.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
