### ISSUE TITLE
[Bug] WebView - view model not updated after navigating to another website

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#9846]
### Description
After navigating to another website inside the WebView, the Source property in View Model which is bound to Source property in WebView is not getting updated.

### Steps to Reproduce

1. Run this project.
[WebViewTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4289586/WebViewTest.zip)
2. Click any link in the WebView.
3.  This redirects to another page inside the WebView.
4. The url address at the bottom is not updated.

Everything is shown on the GIF below:
![webview_viewmodel_not-updated](https://user-images.githubusercontent.com/17653648/75921252-1e374a00-5e61-11ea-9562-691b87a53291.gif)

### Expected Behavior
The url address at the bottom of the screen should be updated when navigating to another page.

### Actual Behavior
The url address at the bottom of the screen is not getting updated when navigating to another page.

### Basic Information

- Version with issue: 4.5.0.356
- IDE: 16.4.5
- Platform Target Frameworks: 
  - Android: 9.0

**Comment by hartez** [comment]
The issue here is that the ability to set a string as the `Source` for a `WebView` is a `TypeConverter` convenience; the `Source` property of `WebView` isn't really a string, it's a `WebViewSource`. When you set the string value, under the hood it's converting it to a `WebViewSource` (really a `UrlWebViewSource`). And the `WebViewSource` doesn't know anything about the original string property after that point, so the original string is never updated.

In a perfect world, you could use a `UrlWebViewSource` as your `Source` property, bind your `WebView` to that, and bind your `Label` to the `UrlWebViewSource.Url` property. Unfortunately, the renderers for `WebView` have a bug right now which that prevents that. 

Until that bug is addressed, I'd suggest something like this:

Change you `MainPageViewModel` to 

```
public class MainPageViewModel : INotifyPropertyChanged
{
    private string _url;
    public string Url
    {
        get => _url;
        set
        {
            _url = value;
            OnPropertyChanged(nameof(Url));
        }
    }

    public WebViewSource Source
    {
        get;
    }

    public MainPageViewModel()
    {
        Url = "https://devblogs.microsoft.com/xamarin/";
        Source = new UrlWebViewSource() { Url = Url };
    }

    public event PropertyChangedEventHandler PropertyChanged;
    protected void OnPropertyChanged(string propertyName)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
```

In MainPage.xaml, bind your `Label` to the `Url` property of the viewmodel:
```
<Label Text="{Binding Url}" />
```

And add a handler for `WebView.Navigated` which updates the property on the viewmodel:

```
private void WebView_Navigated(object sender, WebNavigatedEventArgs e)
{
    if (BindingContext is MainPageViewModel vm)
    {
        vm.Url = e.Url;
    }
}
```

It's not ideal, but it works.

**Comment by Mikilll94** [comment]
@hartez 
Thanks for solving my problem.

Maybe in XF, you should change the default binding mode for the WebView source to TwoWay? Because TwoWay mode as the default makes much more sense because you can update the bound value from the UI (by navigating in WebView) like in Entry which has TwoWay as default.

Also, it would be nice if there was a website in Xamarin docs where there will be listed default binding modes for all controls.
