### ISSUE TITLE
[Bug] ListView selected item not change on tap while using custom cell background

### ISSUE THREAD

**Issue by GenPike** [xamarin/Xamarin.Forms#9935]
### Description
On iOS, ListView item tap do not change background color. Issue is closed #7680 and fix done, but doesn't work for repro project.

### Steps to Reproduce
1.  Open "Bad Selection" page, tap any item - background not changed
2.  Open "Good Selection" page, tap any item - background changed

### Expected Behavior
On tap, selected item should turn grey.

### Actual Behavior
The background of the selected item remains white and the bottom border of the selected selected line disappears.

### Basic Information

- Version with issue: 4.3.0.991250
- Last known good version: 4.0...
- IDE: VS 16.4.3 (Windows), VS 8.3.10 (build 2) (Mac), Xcode 11.3.1
- Platform Target Frameworks: 
  - iOS: 13.3 

### Reproduction Link
[iOSHighlightSelected.zip](https://github.com/xamarin/Xamarin.Forms/files/4318431/iOSHighlightSelected.zip)

### Workaround
As mentioned in #7680 set Transparent background color

**Comment by jfversluis** [comment]
Unfortunately this is not something we did. As per the[ release notes](https://developer.apple.com/documentation/ios_ipados_release_notes/ios_13_release_notes) from Apple for iOS 13

> The UITableViewCell class no longer changes the backgroundColor or isOpaque properties of the contentView and any of its subviews when cells become highlighted or selected. If you are setting an opaque backgroundColor on any subviews of the cell inside (and including) the contentView, the appearance when the cell becomes highlighted or selected might be affected. The simplest way to resolve any issues with your subviews is to ensure their backgroundColor is set to nil or clear, and their opaque property is false. However, if needed you can override the setHighlighted(_:animated:) and setSelected(_:animated:) methods to manually change these properties on your subviews when moving to or from the highlighted and selected states. (13955336)

That is why for iOS 13 we default the `ListView` and cells to transparent to make it work again. Because of that I will close this issue. Is the `CollectionView` an option for you to use?

If this is really something you want to see added please open a feature request so we can gauge interest.
