### ISSUE TITLE
Implement WPF Gif support

### ISSUE THREAD

**Issue by Anish-V1073** [xamarin/Xamarin.Forms#9985]
### Steps to Reproduce

1. Add a new Image control and source a GIF file to it's source.
2.  Run the sample project.

### Basic Information

- Version with issue: 4.5.0.396
- Last known good version:
- IDE: Visual studio 2017
- Platform Target Frameworks: 
Xamarin.Froms.WPF 4.5.0.396
- Affected Devices: Windows devices

**Comment by jfversluis** [comment]
Gif support is only implemented on iOS, Android and UWP. I will tag this issue to be an enhancement so we can track interest and progress. Since WPF is a community backed platform this is most likely not something that will be implemented by the team. However, we are happy to see any and all contributions for this!

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
